### ISSUE TITLE
Considering a new project title

### ISSUE THREAD

**Issue by sethladd** [tekartik/sqflite#1]
Hi!

Thanks very much for writing this plugin!

May I ask you to consider a new title for the project? The ".dart" can imply it works wherever Dart works, but this plugin only works with Flutter.

Some ideas, but feel free to use your own title :)

sqflite.flutter
sqflite_flutter

Cheers!

**Comment by alextekartik** [comment]
Ok Let's name it only sqflite! thanks

**Comment by sethladd** [comment]
Cool! FWIW I didn't understand what sqflite meant :) but I guess the f is for Flutter? :)

**Comment by alextekartik** [comment]
Yes the F before the L of lite stands for FLutter. I'm very bad at naming things...
