### ISSUE TITLE
Support for ASC or DESC?

### ISSUE THREAD

**Issue by cornelius-tan** [tekartik/sqflite#10]
Does sqflite support ordering in ascending or descending order?

```sql
SELECT
 *
FROM
 table
ORDER BY
 column_1 ASC,
 column_2 DESC;
```
How would I rewrite the SQL query above in sqflite?

The API provided by the library is 
```dart
  Future<List<Map<String, dynamic>>> query(String table,
      {bool distinct,
      List<String> columns,
      String where,
      List whereArgs,
      String groupBy,
      String having,
      String orderBy,
      int limit,
      int offset})
```

**Comment by alextekartik** [comment]
Yes `ASC`/`DESC` is supported. Also every helper API (`insert`/`query`/`update`/`delete`) has a raw API counterpart (`rawInsert`, `rawQuery`, `rawUpdate`, `rawDelete`) where you enter the SQL statement. In your scenario, you can either used the helper API:
```
db.query(table, orderBy: "column_1 ASC, column_2 DESC");
```
or the raw query when the helper API is not enough
```
db.rawQuery("SELECT * FROM $table ORDER BY column_1 ASC, column_2 DESC");
```

**Comment by cornelius-tan** [comment]
Thanks. It works.
