### ISSUE TITLE
[Question] How to enable debug mode?

### ISSUE THREAD

**Issue by bambinoua** [tekartik/sqflite#1010]
New version of the package deprecates this method
```dart
Sqflite.setDebugModeOn
```
So how can I enable debug mode in the future?

**Comment by alextekartik** [comment]
The easiest would be:

```
databaseFactoryOrNull = databaseFactory.debugQuickLoggerWrapper();
```

It is also deprecated on purpose so that you don't let this in your code in release mode. See information here about the sqflite logger: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#try-the-experimental-logger
