### ISSUE TITLE
UPSERT Statement

### ISSUE THREAD

**Issue by Steelsmasher** [tekartik/sqflite#102]
I noticed using the UPSERT statement doesn't work. I'm guessing it's because sqflite uses a version of [SQLite below 3.24.0.](https://www.sqlite.org/lang_UPSERT.html)

Is there a chance this will be added in the future? As my code is getting very cumbersome without the help of the UPSERT statement.

**Comment by alextekartik** [comment]
UPSERT should definitely work in the future without changes when/if SQLite supports it. I have not tried this command yet (in sqlite it is actually an INSERT with an ON CONFLICT clause). I have to not tried it yet and don’t know what should be the return value (INSERT returns an id and UPDATE a count). Personally I currently use a transaction either optimized for UPDATE (doing the update first, checking the count then doing the insert if needed) or INSERT (doing the insert checking for error then doing the UPDATE if needed) depending of my needs.

I understand your frustration but the way it designed (to work on whatever the platform provides) and if you can to support devices before iOS 13 and Android 10, you might have to maintain your cumbersome code!

Alternatively you can check my response on this thread https://github.com/tekartik/sqflite/issues/59#issuecomment-388292811 where I suggest other solutions using CREATE TABLE and INSERT OR REPLACE.

If you end up with a good alternative, please let us know! thanks

**Comment by Steelsmasher** [comment]
Oh, I see. I assumed sqflite used its own sqlite implementation, didn't realise it uses whatever the platform provides.

INSERT OR REPLACE wouldn't quite work for me as the rowid would change on REPLACE, when I need it to be consistent, which is why I looked at updating instead.

Appreciate the help though. Thanks.
