### ISSUE TITLE
How to get the Database Version

### ISSUE THREAD

**Issue by ehusmann** [tekartik/sqflite#1028]
This question has been asked before, and answered, but that answer is no longer valid. I always used the method getVersion(), but as I upgraded the package to 2.4.5, that no longer works. getVersion is not defined for the class Database. How can I get the version now?

**Comment by alextekartik** [comment]
`getVersion()` is defined as a class extension so I guess that you have to explicitly import 'sqflite.dart' in your source file if you don't import it yet.

**Comment by ehusmann** [comment]
@alextekartik Yes, that did the trick. Perhaps for others, the issue was that my database code was in a library project which was imported into an app project where I tried to use the reference to the database. Importing the sqflite package into the app project solved the issue. Much appreciated!
