### ISSUE TITLE
don't support IOS 12.1

### ISSUE THREAD

**Issue by Seifon** [tekartik/sqflite#103]
My system is IOS 12.1

this version don't support!

I hope you can update!

Thanks!

**Comment by alextekartik** [comment]
Thanks for the report!

I don't have a device on iOS 12.1 yet to test on it. However what I have works fine so far on iOS 12.0. I have not tried Xcode 10 yet as I heard some issues with flutter - and solutions (https://github.com/flutter/flutter/issues/20685) - that I don't want to spend too much time on. Do you have an easy to reproduce the issue you are seeing (maybe as simple as installing xcode 10 and opening the example workspace) so I can take  a look?

I'm not an expert in iOS so community support is welcome! The iOS implementation so far uses fmdb, maybe a version bump could help.

**Comment by alextekartik** [comment]
@Seifon is this still an issue? If yes, can you elaborate on the issue you're facing? thanks
