### ISSUE TITLE
sqlite3.dll included with sqflite_common_ffi is out of date

### ISSUE THREAD

**Issue by k-euser** [tekartik/sqflite#1036]
The included Windows DLL is for SQLite 3.38.2, which is 14 versions out of date.

The current version of SQLite is 3.42.0.  Please update.

**Comment by alextekartik** [comment]
Thanks for the notice. 3.42.0 has been updated in sqflite_common_ffi 2.3.0+2. I added some notes [here](https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/updating_sqlite_dll.md). This is mainly intended for development so sorry if I miss you versions. For release I do recommend to download the latest version available.

**Comment by k-euser** [comment]
Thank you for the extremely fast response.
