### ISSUE TITLE
SqfliteDatabaseException (DatabaseException(Error Domain=FMDatabase Code=6922 "disk I/O error" UserInfo={NSLocalizedDescription=disk I/O error}) sql

### ISSUE THREAD

**Issue by herowws** [tekartik/sqflite#1039]
<img width="1595" alt="image" src="https://github.com/tekartik/sqflite/assets/41428542/4a64d34a-1292-4e2e-932e-e565891fbcdc">

<img width="631" alt="image" src="https://github.com/tekartik/sqflite/assets/41428542/266738e1-9346-4d53-b017-70295facf07f">

closedatabase -> update sqlite to cloud -> open database. 

  After calling this method, any further operations related to the database will result in an IO exception

```
class DbHelper {
  DbHelper._();
  static DbHelper? _instance;
  static DbHelper get instance => _getInstance();
  factory DbHelper() {
    return instance;
  }
  static DbHelper _getInstance() {
    _instance ??= DbHelper._();
    return _instance ?? DbHelper._();
  }

  Future<Database>? _db;

  Future<Database>? get connection {
    _db ??= initDb();
    return _db;
  }

   Future<Database> initDb() async {
    var databasesPath = await getDatabasesPath();
    String path = '$databasesPath/${C.dbName}';
    final db = await openDatabase(
      path, 
      version: 1,
      onCreate: (db, version) async {
      
      },
      onUpgrade: (db, oldV, newV) {
         Console.log('onUpgrade');
      },
    );

    return db;
  }

  Future<void> close() async {
     await _db?.then((value) => value.close());
    _db = null;
  }
}
```
BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /private/var/mobile/Containers/Data/Application/B3AAB538-56D1-433A-B237-748BF060E717/Documents/diary

env:
 
<img width="688" alt="image" src="https://github.com/tekartik/sqflite/assets/41428542/943a6240-a44b-46e4-8ea9-017ae00db330">

**Comment by robinbonnes** [comment]
Same issue here. Seems to happen randomly (only on iOS), also in different queries. Seems like this is happening since version 2.3.0 or it has to do with changes in our codebase. We try if downgrading to version 2.2.8+4 does solve the issue.

**Comment by robinbonnes** [comment]
In our situation, we cleaned up all files in the document directory (https://pub.dev/documentation/path_provider/latest/path_provider/getApplicationDocumentsDirectory.html). For iOS, the database is also stored in this directory, so we accidently deleted it. Stupid ofcourse 🙈. We've excluded the database from deletion.
