### ISSUE TITLE
sqflite_sw.js return 0 bit in production

### ISSUE THREAD

**Issue by toknT** [tekartik/sqflite#1043]
Run `flutter build web` and upload to nginx , `sqflite_sw.js` always get 0 bit error. But if run `flutter run` and debug in local it work fin.
![sqflite_sw_0_b](https://github.com/tekartik/sqflite/assets/15935037/b8114cb0-dbe5-46f1-b5c0-70910e0deb0e)

![sqflite_sw_0_b__2](https://github.com/tekartik/sqflite/assets/15935037/69141ca8-943f-4e78-81fe-25c641a5e250)

**Comment by alextekartik** [comment]
You might look at https://github.com/tekartik/sqflite/issues/1033 with a similar issue (well it was an issue with the .wasm file) but where dealing with the mime type might solve the issue. I only experimented deploying on firebase hosting / github pages and not personal server.

**Comment by toknT** [comment]
https://github.com/tekartik/sqflite/issues/1043#issuecomment-1708391006
