### ISSUE TITLE
fts5 support

### ISSUE THREAD

**Issue by gambhiro** [tekartik/sqflite#105]
I would like to ask about the status or situation with supporting the [FTS5 Extension](https://www.sqlite.org/fts5.html).

Just asking for some context and information.

Is it possible, not possible, requires configuration or a custom build, etc.

Many thanks for the great package!

**Comment by alextekartik** [comment]
Thanks for note. According to this blog post https://android.jlelse.eu/offline-full-text-search-in-android-ios-b4dd5bed3acd FTS5 should be enabled on
* iOS ≥ 10.0
* Android ≥ API 24 (Android 7.0)

I think the safer would be to check what is the actual sqlite binary installed on the device but I have not find a consistent way yet (input welcome).

Since sqflite uses whatever the platform provides, it is not possible to change it. The alternative solution would along the line of what is done in https://github.com/QwilApp/encrypted_sqlite by bundling sqlite binaries for each platform and architecture which is not currently the scope of this package.

**Comment by gambhiro** [comment]
I was running some fts5 match queries in Genymotion, using the Samsung Galaxy S8 (API 26) virtual device. These errored out.

There is [this SO answer](https://stackoverflow.com/a/43293280/195141) which says,

> FTS5 is not available before SQLite 3.9.0, and even then disabled by default, so it is unlikely to be part of any SQLite library shipped with Android.

On the same thread they mention building https://github.com/requery/sqlite-android with FTS5 enabled to make it work.

I've just recently started with Flutter, how does one go about adding this in a project?

**Comment by alextekartik** [comment]
Ok thanks for the precision. Adding a native library (By native here I mean compiled with the NDK) is not an easy process. There is no native extension support so far as defined for the dart VM (https://www.dartlang.org/articles/dart-vm/native-extensions), so you still need a java bridge, build the .so files for all the architecture...as done here: https://github.com/QwilApp/encrypted_sqlite

I have not tried myself. Flutter plugins official support is for Objective C/Swift (iOS) and Java/Kotlin so you are basically on your own to try this (I have not played much with Android NDK so far)

If you go this route, I guess many people (including me) will be interested in being able to use a fixed deterministic sqlite version. plugin into sqflite without adding much dart code could be as easy as using setMockHandler first to try your native plugin...Good luck!

**Comment by gambhiro** [comment]
Thanks for describing an outline.

FTS5 `MATCH` queries with their tokenization and the `snippet()` results are sweet, but it seems that the best one can hope for on the mobile is the `LIKE '%query%'` results.

**Comment by adam7** [comment]
@gambhiro You can use FTS4, I've created a (very) simple [dart package ](https://pub.dev/packages/sqlite_rank) that allows you to rank the matchinfo result.

**Comment by ThinkDigitalSoftware** [comment]
How about now that we have ffi support? Can we interface with the C library?

**Comment by alextekartik** [comment]
ffi is still in preview and does not solve everything for sqlite yet (threading, concurrent access, binary...). There are multiple experiments on it yet but nothing seems production ready yet (but I'm following!)

**Comment by oseiasmribeiro** [comment]
How to use TFS4 or TFS5 virtual tables in flutter?
