### ISSUE TITLE
Sqflite  Long term planning 

### ISSUE THREAD

**Issue by devchenli** [tekartik/sqflite#1050]
The Plan :  
sqflite would provide a solution that works out of the box on all platforms using whatever the platform provides using regular plugin mechanism.

Is there any update on this plan?  
Thank you.

**Comment by alextekartik** [comment]
Good reminder. At this time I don't have a plan to provide such package (basically that will bundle sqflite_common_ffi/web/sqflite into something that works for all platforms).

See [cross-platform-support](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/qa.md#cross-platform-support))

**Comment by devchenli** [comment]
Ok.Thank you
