### ISSUE TITLE
Return Stream from openDatabase

### ISSUE THREAD

**Issue by evan361425** [tekartik/sqflite#1054]
`openDatabase` provides `onUpgrade` which helps provision the new version of database.

The function inside my `onUpgrade` might cause several seconds(depends on user's database rows count) which I like to add some indicator(`CircularProgressIndicator` in my case) to make friendly UX. [Stream](https://dart.dev/tutorials/language/streams) will be the perfect option.

Here might be the new interface of `openDatabase`:

```dart
final db = await openDatabase({
  // ...
  onUpgradeStream: (db, oldVer, newVer) async* {
    for (var ver = oldVer + 1; ver <= newVer; ver++) {
      yield* upgradeActions[ver](db);
    }
  }
});

// Provide the stream by `db` property
showIndicatorBy(db.upgradeStream);
```

The implementation might be:

```dart
if(shouldUpgrade()) {
  if(onUpgradeStream != null) {
    upgradeStream = onUpgradeStream();
  } else {
    onUpgrade();
  }
}
```

**Comment by alextekartik** [comment]
You can create a you stream controller before opening the database and feed your controller from `onUpgrade` (controller.add)
This typically happens only once.

**Comment by evan361425** [comment]
I'll try it and make some comments if I encounter any problems; otherwise, I'll close the issue.

Thanks for the advice!
