### ISSUE TITLE
Apply changeset to sqlite database from sqldiff.exe

### ISSUE THREAD

**Issue by iksivee** [tekartik/sqflite#1056]
Hello,
we would like to sync sqlite database with server, we are able to generate patchset using sqldiff.exe utility from previous version of db.
Can we somehow implement a direct patchset using "Session extensions"?
https://www.sqlite.org/sessionintro.html
Or we need to export diff command and call db.execute(cmd).
Thank you

**Comment by alextekartik** [comment]
sqflite uses the library available on the system and does not control how sqlite is compiled. You might better look at the sqlite3 package for such feature.
