### ISSUE TITLE
Data not persisted to disk on Web

### ISSUE THREAD

**Issue by gadjetnut** [tekartik/sqflite#1057]
I'm using databaseFactory = databaseFactoryFfiWeb;

Running on Web the database is in memory only and not persisted to disk, so I get a new database every run. 

Running on Android, no problems.

**Comment by alextekartik** [comment]
Have you following the setup explained here: https://github.com/tekartik/sqflite/blob/master/packages_web/sqflite_common_ffi_web/README.md#setup

Basically you need to build the worker file and download the wasm file.
