### ISSUE TITLE
Error: DatabaseException(no such function: JSON_OBJECT (code 1 SQLITE_ERROR)) 

### ISSUE THREAD

**Issue by toan88291** [tekartik/sqflite#1061]
I use JSON_OBJECT function show error: "E/flutter (10863): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(no such function: JSON_OBJECT (code 1 SQLITE_ERROR): , while compiling: "...JSON_GROUP_ARRAY(JSON_OBJECT('symbol', r.symbol, 'userId', r.created_by))...;' args []
"
Because version sqlite is 3.22.0, 3.38.0 support json function (https://www.sqlite.org/json1.html#:~:text=The%20JSON%20functions%20and%20operators,2022%2D02%2D22).), how to upgrade sqlite version.

**Comment by alextekartik** [comment]
From [version.md](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/version.md)

Unfortunately the version of SQLite depends on the OS version (I don't know which platform you are using, Android, iOS?) so the json extension might not be present.

You could get a more recent version using [`sqflite_common_ffi`](https://pub.dev/packages/sqflite_common_ffi).

You could then add [`sqlite3_flutter_libs`](https://pub.dev/packages/sqlite3_flutter_libs) for ios/android or include your own sqlite shared library for desktop or mobile (one for each platform).
