### ISSUE TITLE
iOS privacy manifest required

### ISSUE THREAD

**Issue by stuartmorgan** [tekartik/sqflite#1065]
This plugin is listed on https://developer.apple.com/support/third-party-SDK-requirements/ as requiring a privacy manifest. Some action will be required, either to clarify with Apple whether this plugin should be on the list, or to add a privacy manifest.

See https://github.com/flutter/flutter/issues/131940 for context.

**Comment by stuartmorgan** [comment]
We're still collectively working to figure out what is necessary on the data usage front (since it's not currently clear whether Apple considers a plugin like this to be "collecting" data). In the meantime I would encourage checking whether you use any of the Required Reason APIs, since those would definitely require action.

**Comment by stuartmorgan** [comment]
Emailing Apple yourself to request clarification on what they view as the privacy impact of this plugin might help; others have done the same with their plugins, but the more feedback they get that developers are unsure what to do with this list, the more likely they are to provide clearer guidance.

**Comment by alextekartik** [comment]
Published in sqflite 2.3.1

**Comment by rspltestall** [comment]
Hy @alextekartik @stuartmorgan 
PrivacyInfo Issue with SQLite

Problem and Solution:
The PrivacyInfo configuration for SQLite lacks specification for "statfs" API usage, resulting in potential privacy concerns. Updating the PrivacyInfo to include the correct code, E174.1, is necessary to ensure compliance and transparency.

Please review the attached screenshots for further reference.

![Screenshot 2024-04-09 at 3 35 13 PM](https://github.com/tekartik/sqflite/assets/5756687/d8faa07e-bf5e-45a5-80e8-227f499c5773)
![Screenshot 2024-04-09 at 3 44 06 PM](https://github.com/tekartik/sqflite/assets/5756687/d8c5f525-2049-49e9-9b09-66b886e5a89e)

**Comment by stuartmorgan** [comment]
@rspltestall Your screenshot shows a source file from the `sqlite3` Pod, not from this plugin.

**Comment by psatler** [comment]
Hi @stuartmorgan 

I'm updating an app that utilizes `sqflite` and upon submitting the update to the Apple App Store, I received a notification about compliance issues with the build. The message from Apple stated:

```
ITMS-91053: Missing API declaration - Your app’s code in the “Runner” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryDiskSpace.
```
I consulted the [Apple documentation on privacy manifest files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278397) to identify any relevant API usage within the dependencies of my app and I ended up with the same findings of @rspltestall 

Given that _sqlite3_ is a dependency of `sqflite` and it uses APIs that requires declaration in the privacy manifest, does this mean `sqflite` also needs to include these API declarations in its own privacy manifest file?

Thank you for your assistance.

cc: @alextekartik

**Comment by lucygeneric** [comment]
Also struggling with what @psatler mentions

**Comment by stuartmorgan** [comment]
> Given that _sqlite3_ is a dependency of `sqflite` and it uses APIs that requires declaration in the privacy manifest, does this mean `sqflite` also needs to include these API declarations in its own privacy manifest file?

No; if a Pod uses a required reason API then *that Pod* needs to include a privacy manifest describing its required reason APIs.

(Also, where are you seeing `sqflite` depending on the `sqlite3` Pod? There's only one podfile in this repository, and it doesn't reference that pod.)

**Comment by psatler** [comment]
I see, thanks for the clarification @stuartmorgan 

> (Also, where are you seeing sqflite depending on the sqlite3 Pod? There's only one podfile in this repository, and it doesn't reference that pod.)

yeah, I guess I mistakenly assumed this because while searching inside xcode for possible APIs my project uses I was able to find references to that api on a `sqlite3` file, similar to what was shown by @rspltestall above. See it below:

one correction: the project uses `sqflite_sqlcipher` actually

![image](https://github.com/tekartik/sqflite/assets/3421410/51306796-575e-4c98-b7a3-4980fa931c80)

**Comment by stuartmorgan** [comment]
If the `SQLCipher` Pod doesn't have a privacy manifest, then the best option would be to contact the developers of `SQLCipher`.

**Comment by psatler** [comment]
They recently [added it](https://github.com/davidmartos96/sqflite_sqlcipher/blob/master/sqflite/ios/Resources/PrivacyInfo.xcprivacy) and I am already using the most recent version. The `NSPrivacyAccessedAPICategoryDiskSpace` issue I am facing might be due to some other package then. 

Thanks for the attention and time @stuartmorgan .
