### ISSUE TITLE
[Web] Access the database file or read database as bytes

### ISSUE THREAD

**Issue by CBeening** [tekartik/sqflite#1074]
Hi,

is there currently any way in which we can access the actual database file, or alternatively directly read the database as bytes?

The dart.io library is not available on the web, the using File and such are not possible.

The idea would be to make the database "downloadable" when running in web, so its easier to access it for debugging purposes.

Regards

**Comment by alextekartik** [comment]
You cannot access the actual database file since it is not a file. You can read the database as bytes using [`readDatabaseBytes()`](https://pub.dev/documentation/sqflite/latest/sqflite/DatabaseFactory/readDatabaseBytes.html).
