### ISSUE TITLE
Sqflitecommonffi not working in release mode

### ISSUE THREAD

**Issue by himanshuchaurasiya24** [tekartik/sqflite#1077]
Hey there,
Can anyone make a detailed video of how can we make sqflitecommonffi work in release mode I have tried following the steps mentioned here and also from the google but of no use I guess I'm missing something.
If anyone can please make a video and paste the link here it will be a great help for everyone.

**Comment by stan-at-work** [comment]
> Hey there, Can anyone make a detailed video of how can we make sqflitecommonffi work in release mode I have tried following the steps mentioned here and also from the google but of no use I guess I'm missing something. If anyone can please make a video and paste the link here it will be a great help for everyone.

- **Have you tried copying _sqlite3.dll_ to the root of the output folder (after build).**
- When debugging you need to add the folder to your /windows folder

**Comment by himanshuchaurasiya24** [comment]
> > Hey there, Can anyone make a detailed video of how can we make sqflitecommonffi work in release mode I have tried following the steps mentioned here and also from the google but of no use I guess I'm missing something. If anyone can please make a video and paste the link here it will be a great help for everyone.
> 
> * **Have you tried copying _sqlite3.dll_ to the root of the output folder (after build).**
> * When debugging you need to add the _sqlite3.dll_ sqlite file to your /windows folder

Can you please make a video tutorial on that if you have done that

**Comment by himanshuchaurasiya24** [comment]
> > > > Hey there, Can anyone make a detailed video of how can we make sqflitecommonffi work in release mode I have tried following the steps mentioned here and also from the google but of no use I guess I'm missing something. If anyone can please make a video and paste the link here it will be a great help for everyone.
> > > 
> > > 
> > > 
> > > * **Have you tried copying _sqlite3.dll_ to the root of the output folder (after build).**
> > > * When debugging you need to add the _sqlite3.dll_ sqlite file to your /windows folder
> > 
> > 
> > Can you please make a video tutorial on that if you have done that
> > I can't make a video but i can give you this:
> 
> ![image](https://private-user-images.githubusercontent.com/147701137/302225624-001c52b5-b1a4-41c3-9441-cdab9472cc69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjI5MzcsIm5iZiI6MTcwNzEyMjYzNywicGF0aCI6Ii8xNDc3MDExMzcvMzAyMjI1NjI0LTAwMWM1MmI1LWIxYTQtNDFjMy05NDQxLWNkYWI5NDcyY2M2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwODQzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzM0NTgxZjAwZmNhZjk2NGU3YzIwYzk1OGRkN2JkYWNjMGIxOTljZWY3YmU1YTViMjk0ZTNlMjI1Njk2YjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Cx7Ry5mdbNSwqbQXnH0eCa6wRyhUoe14dMK4Sz1-Bw)
> 
> Download the sqlite3.dll file from [HERE](https://github.com/tekartik/sqflite/raw/master/sqflite_common_ffi/lib/src/windows/sqlite3.dll)

Please share your database helper class

**Comment by stan-at-work** [comment]
> > > > > Hey there, Can anyone make a detailed video of how can we make sqflitecommonffi work in release mode I have tried following the steps mentioned here and also from the google but of no use I guess I'm missing something. If anyone can please make a video and paste the link here it will be a great help for everyone.
> > > > 
> > > > 
> > > > 
> > > > * **Have you tried copying _sqlite3.dll_ to the root of the output folder (after build).**
> > > > * When debugging you need to add the _sqlite3.dll_ sqlite file to your /windows folder
> > > 
> > > 
> > > Can you please make a video tutorial on that if you have done that
> > > I can't make a video but i can give you this:
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/147701137/302225624-001c52b5-b1a4-41c3-9441-cdab9472cc69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjI5MzcsIm5iZiI6MTcwNzEyMjYzNywicGF0aCI6Ii8xNDc3MDExMzcvMzAyMjI1NjI0LTAwMWM1MmI1LWIxYTQtNDFjMy05NDQxLWNkYWI5NDcyY2M2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwODQzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzM0NTgxZjAwZmNhZjk2NGU3YzIwYzk1OGRkN2JkYWNjMGIxOTljZWY3YmU1YTViMjk0ZTNlMjI1Njk2YjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Cx7Ry5mdbNSwqbQXnH0eCa6wRyhUoe14dMK4Sz1-Bw)
> > Download the sqlite3.dll file from [HERE](https://github.com/tekartik/sqflite/raw/master/sqflite_common_ffi/lib/src/windows/sqlite3.dll)
> 
> Please share your database helper class

I don't know you mean with a *database helper class*.
+ What does this contribute to the question ?

If this fixed your issue please close the issue, And assign the awnser.

**Comment by himanshuchaurasiya24** [comment]
> > > > > > Hey there, Can anyone make a detailed video of how can we make sqflitecommonffi work in release mode I have tried following the steps mentioned here and also from the google but of no use I guess I'm missing something. If anyone can please make a video and paste the link here it will be a great help for everyone.
> > > > > 
> > > > > 
> > > > > 
> > > > > * **Have you tried copying _sqlite3.dll_ to the root of the output folder (after build).**
> > > > > * When debugging you need to add the _sqlite3.dll_ sqlite file to your /windows folder
> > > > 
> > > > 
> > > > Can you please make a video tutorial on that if you have done that
> > > > I can't make a video but i can give you this:
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/147701137/302225624-001c52b5-b1a4-41c3-9441-cdab9472cc69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjI5MzcsIm5iZiI6MTcwNzEyMjYzNywicGF0aCI6Ii8xNDc3MDExMzcvMzAyMjI1NjI0LTAwMWM1MmI1LWIxYTQtNDFjMy05NDQxLWNkYWI5NDcyY2M2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwODQzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzM0NTgxZjAwZmNhZjk2NGU3YzIwYzk1OGRkN2JkYWNjMGIxOTljZWY3YmU1YTViMjk0ZTNlMjI1Njk2YjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Cx7Ry5mdbNSwqbQXnH0eCa6wRyhUoe14dMK4Sz1-Bw)
> > > Download the sqlite3.dll file from [HERE](https://github.com/tekartik/sqflite/raw/master/sqflite_common_ffi/lib/src/windows/sqlite3.dll)
> > 
> > 
> > Please share your database helper class
> 
> I don't know you mean with a _database helper class_.
> 
> * What does this contribute to the question ?
> 
> If this fixed your issue please close the issue, And assign the answer.

I mean you must have a database logic where you have  initiated the database like db.execute();  , and initDB();
Like these
This will help me to figure out if I'm doing wrong in these methods
You can make a dummy database class if you don't want to share it from your project..

**Comment by stan-at-work** [comment]
> > > > > > > Hey there, Can anyone make a detailed video of how can we make sqflitecommonffi work in release mode I have tried following the steps mentioned here and also from the google but of no use I guess I'm missing something. If anyone can please make a video and paste the link here it will be a great help for everyone.
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > * **Have you tried copying _sqlite3.dll_ to the root of the output folder (after build).**
> > > > > > * When debugging you need to add the _sqlite3.dll_ sqlite file to your /windows folder
> > > > > 
> > > > > 
> > > > > Can you please make a video tutorial on that if you have done that
> > > > > I can't make a video but i can give you this:
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/147701137/302225624-001c52b5-b1a4-41c3-9441-cdab9472cc69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjI5MzcsIm5iZiI6MTcwNzEyMjYzNywicGF0aCI6Ii8xNDc3MDExMzcvMzAyMjI1NjI0LTAwMWM1MmI1LWIxYTQtNDFjMy05NDQxLWNkYWI5NDcyY2M2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwODQzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzM0NTgxZjAwZmNhZjk2NGU3YzIwYzk1OGRkN2JkYWNjMGIxOTljZWY3YmU1YTViMjk0ZTNlMjI1Njk2YjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Cx7Ry5mdbNSwqbQXnH0eCa6wRyhUoe14dMK4Sz1-Bw)
> > > > Download the sqlite3.dll file from [HERE](https://github.com/tekartik/sqflite/raw/master/sqflite_common_ffi/lib/src/windows/sqlite3.dll)
> > > 
> > > 
> > > Please share your database helper class
> > 
> > 
> > I don't know you mean with a _database helper class_.
> > 
> > * What does this contribute to the question ?
> > 
> > If this fixed your issue please close the issue, And assign the answer.
> 
> I mean you must have a database logic where you have initiated the database like db.execute(); , and initDB(); Like these This will help me to figure out if I'm doing wrong in these methods You can make a dummy database class if you don't want to share it from your project..

This has nothing to do with this question:
https://github.com/tekartik/sqflite/issues/1077#issue-2108330683

Currently i don't the time and resources to do that.

Please close the issue if your main issue is fixed

**Comment by stan-at-work** [comment]
@himanshuchaurasiya24 Could you accept the answer, so other people see what helped ?

**Comment by himanshuchaurasiya24** [comment]
Well..
Can you show me how you fetched database path for windows that will help in solving the issue

**Comment by himanshuchaurasiya24** [comment]
> @himanshuchaurasiya24 Could you accept the answer, so other people see what helped ?

Well can you show me how you find the path for the database for windows that may help in solving the issue...

**Comment by stan-at-work** [comment]
> > @himanshuchaurasiya24 Could you accept the answer, so other people see what helped ?
> 
> Well can you show me how you find the path for the database for windows that may help in solving the issue...

In set the path to my database using;

```
    final databaseName = 'database.sqlite';
    final databaseDir = await getApplicationSupportDirectory();
    final databasePath = join(databaseDir.path, databaseName);
    
    ...

    if (Platform.isWindows || Platform.isLinux) {
      sqfliteFfiInit();

      database = await databaseFactoryFfi.openDatabase(
        databasePath,
        options: OpenDatabaseOptions(
          version: LocalDatabase.kVersion,
          onCreate: (Database database, int version) async {
            debugPrint('1: [On Create]: ${database.path}');
            debugPrint('2: Creating tables');
            await _createTables(db: database);
            debugPrint('3: Creating created !');
          },
          onOpen: (Database database) => database.execute('PRAGMA foreign_keys = ON;'),
        ),
      );
    } else if (Platform.isAndroid || Platform.isIOS || Platform.isMacOS) {
      database = await openDatabase(
        databasePath,
        version: LocalDatabase.kVersion,
        onCreate: (Database database, int version) async {
          debugPrint('1: [On Create]: ${database.path}');
          debugPrint('2: Creating tables');
          await _createTables(db: database);
          debugPrint('3: Creating created !');
        },

        //* This allows cascading delete on foreign keys
        onOpen: (Database database) => database.execute('PRAGMA foreign_keys = ON;'),
      );
    }
...
```

If you want the physical location with my configuration it will be saved in; **C:\Users\USER\AppData\Roaming\be.cce.APPNAME\APPNAME**

**Comment by himanshuchaurasiya24** [comment]
I will

> > > @himanshuchaurasiya24 Could you accept the answer, so other people see what helped ?
> > 
> > 
> > Well can you show me how you find the path for the database for windows that may help in solving the issue...
> 
> I set the path to my database using;
> 
> ```
>     final databaseName = 'database.sqlite';
>     final databaseDir = await getApplicationSupportDirectory();
>     final databasePath = join(databaseDir.path, databaseName);
>     
>     ...
> 
>     if (Platform.isWindows || Platform.isLinux) {
>       sqfliteFfiInit();
> 
>       database = await databaseFactoryFfi.openDatabase(
>         databasePath,
>         options: OpenDatabaseOptions(
>           version: LocalDatabase.kVersion,
>           onCreate: (Database database, int version) async {
>             debugPrint('1: [On Create]: ${database.path}');
>             debugPrint('2: Creating tables');
>             await _createTables(db: database);
>             debugPrint('3: Creating created !');
>           },
>           onOpen: (Database database) => database.execute('PRAGMA foreign_keys = ON;'),
>         ),
>       );
>     } else if (Platform.isAndroid || Platform.isIOS || Platform.isMacOS) {
>       database = await openDatabase(
>         databasePath,
>         version: LocalDatabase.kVersion,
>         onCreate: (Database database, int version) async {
>           debugPrint('1: [On Create]: ${database.path}');
>           debugPrint('2: Creating tables');
>           await _createTables(db: database);
>           debugPrint('3: Creating created !');
>         },
> 
>         //* This allows cascading delete on foreign keys
>         onOpen: (Database database) => database.execute('PRAGMA foreign_keys = ON;'),
>       );
>     }
> ...
> ```
> 
> If you want the physical location with my configuration it will be saved in; **C:\Users\USER\AppData\Roaming\APPNAME\APPNAME**

Thank you for this code I'll check if it works for me
