### ISSUE TITLE
Observe database query

### ISSUE THREAD

**Issue by burhanrashid52** [tekartik/sqflite#109]
Thanks for this great library.
Is there any way we can observe the query using Rx or something, so whenever there is data changed in the database then it will notify to all the observer listening to that query.
Since we are moving towards reactive programming this feature will be really helpful.
For reference in Android, Room database provides `LiveData<T>` as a result of that query so whenever the query is updated its notify through this `LiveData`.

**Comment by alextekartik** [comment]
I understant the need (and you're not the first one to ask for that! - see https://github.com/tekartik/sqflite/issues/13)

sqlite itself has not something built-in so supporting this would require parsing SQL queries which could be complex for views or join queries. This is actually not the scope of this library. I (or someone else who has a need and time!) would rather build a library à la lovefield that would add observable feature on top of this library (the goal of sqflite is to remain a thin layer on top of the existing platform implementation)

**Comment by alextekartik** [comment]
I think the best way is to make an API (like I said above an API like lovefield - https://github.com/google/lovefield - should be a good match) to easily track the tables modified and the one queried. Personnally in my apps I always have something I call a provider that does a similar process: it knows when a table a is modified and can notify listeners. I typically use rxdart or raw streams

**Comment by Patte1808** [comment]
I was having the same requirement @burhanrashid52 and found this library, which is fulfilling my current needs:

https://github.com/evant/streamqflite

It's not yet Dart 2 ready, but I already proposed a PR and hope it'll get merged soon.

In the mean time, you can add my fork as a dependency (would not recommend to rely on that for production):

streamqflite:
      git: git://github.com/Patte1808/streamqflite

**Comment by burhanrashid52** [comment]
Thanks man @Patte1808 Let me check

**Comment by fbatschi** [comment]
@Patte1808 do you have an example on how you use streamqflite in connection to sqflite?

**Comment by burhanrashid52** [comment]
Currently not

**Comment by Patte1808** [comment]
Are you having issues setting it up?

I can send you a small example later during the day :)

**Comment by Patte1808** [comment]
Is this example good for you, or to basic? I think it should be good enough to get the idea :) 

https://github.com/Patte1808/reactive_sqflite_example/blob/master/lib

I've used the data structure from the sqflite readme. 

[This method ](https://github.com/Patte1808/reactive_sqflite_example/blob/master/lib/todo_provider.dart#L72) exposes a Stream which you can then observe. In this small example, [I'm using a StreamBuilder to react to new emissions from the stream](https://github.com/Patte1808/reactive_sqflite_example/blob/master/lib/main.dart#L52) 

Using it with SQFlite is quite simple. [Once the database is created, you can just pass the database object to the `StreamDatabase` constructor.](https://github.com/Patte1808/reactive_sqflite_example/blob/master/lib/todo_provider.dart#L55)

However, I'm not sure whether the maintainer wants to continue working on that project as he didn't respond yet to my PR.

**Comment by fbatschi** [comment]
:+1: thanks - i had a problem in using the StreamBuilder Widget. Your example helped.
