### ISSUE TITLE
[sqflite_common_ffi_web 0.4.3] - db is not accessible in Android Chrome

### ISSUE THREAD

**Issue by DDSrivatsan** [tekartik/sqflite#1095]
I have already have an android app, created using sqflite plugin. So now im implementing to web also. As per documentation i have used this code to implement web support also.

`if (kIsWeb) {
      // Change default factory on the web
      sql.databaseFactory = databaseFactoryFfiWeb;
      dbPath = 'ultimate.db';
    }
`
Now this is working fine for app running on laptop/pc. But the db is not loading or accessible in Android Chrome.

I think previously it was working... I don't know... Currently I couldn't see any operations on Android Chrome.

But works fine on Chrome on PC

**Comment by alextekartik** [comment]
Sorry it seems I messed up basic web workers. Can you try to update to sqflite_common_ffi_web 0.4.3+1 just published?

Need to re-run:

```bash
$ dart run sqflite_common_ffi_web:setup --force
```

https://tk-demo-sqflite.web.app/

**Comment by DDSrivatsan** [comment]
@alextekartik Thank you for Updating... Will update the package and  let within a day or two..

**Comment by DDSrivatsan** [comment]
@alextekartik Thanks for updating the package now its working fine in both android and windows. One more thing need to clarify how to overcome this error in console.

```
*** sqflite warning ***

You are changing sqflite default factory.
Be aware of the potential side effects. Any library using sqflite
will have this factory as the default for all operations.

*** sqflite warning ***
```

```
if (kIsWeb) { 
// Change default factory on the web 
sql.databaseFactory = databaseFactoryFfiWeb; 
databaseFactoryOrNull = databaseFactoryFfiWeb; // Should I Add like this how to do it ?
dbPath = 'ultimate.db'; 
} 
```
Kindly clarify, thank you in advance,

**Comment by DDSrivatsan** [comment]
@alextekartik 

im using like this is the correct  ? Kindly let me know 

```
import 'package:sqflite_common_ffi_web/sqflite_ffi_web.dart';
import 'package:sqflite/sqflite.dart' as sql;

if (kIsWeb) {
      // Change default factory on the web
      sql.databaseFactoryOrNull=null;
      sql.databaseFactory = databaseFactoryFfiWeb;
      dbPath = 'ultimate.db';
    }
```

**Comment by DDSrivatsan** [comment]
thank you @alextekartik . Opened issue is also fixed can i close the issue ?

**Comment by alextekartik** [comment]
@DDSrivatsan Yes typically I let the person that created the issue closing it (otherwise I'll do it later). Thank you !
