### ISSUE TITLE
Error on build Android Related to Android Manifest MinSDK

### ISSUE THREAD

**Issue by datvtwkm** [tekartik/sqflite#110]
I meet this error while building a project which has sqflite, following this guide https://flutter.io/android-release/
"The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file."

**Comment by alextekartik** [comment]
Can you tell me which version of sqflite you are using? (I thought this was solved in 0.12.2+1 (https://github.com/tekartik/sqflite/issues/106)

**Comment by pulyaevskiy** [comment]
This happened to me as well. Definitely fixed by upgrading to `^0.12.0`.

**Comment by alextekartik** [comment]
Thanks for the note. I'm marking this as resolved.
