### ISSUE TITLE
power function not supported

### ISSUE THREAD

**Issue by bishal-rumba007** [tekartik/sqflite#1100]
I am getting this error saying no such function: power

E/flutter (11236): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(no such function: POWER (code 1 SQLITE_ERROR): , while compiling: insert into

While executing complex query imported from .sql file, is there any work around for this? I also tried to use EXP and LN for which is also not available.

**Comment by alextekartik** [comment]
I guess it depends on the native implementation. You might want to try using sqflite_common_ffi and sqlite flutter libs https://pub.dev/packages/sqflite_common_ffi
