### ISSUE TITLE
How to close the database from the StatefulWidget class

### ISSUE THREAD

**Issue by dark-chocolate** [tekartik/sqflite#111]
I am using following to close the database. But in the logcat I can see an error. 

**Code:**

```
// StatefulWidget class
@override
  void dispose() async {
    await helper.closeDb();
    super.dispose();
  }
```

And in the database model class, the `closeDb()` method looks like:

```
// Database model
Future closeDb() async {
    await _db.close();
}
```

**Error:** 
An error occurred in closing a resource.

**Comment by alextekartik** [comment]
As a first note (not sqflite related), dispose is not an async method for a widget and you must call `super.dispose()` without 'awaiting'

```dart
@override
void dispose() {
  helper.closeDb();
  super.dispose();
}
```

So basically you cannot really wait for the helper to finish. If you open/close a database, which is not recommended (common usage is to keep it open forever) unless needed, you need to be carefull about it, especially if you use a singleInstance

**Comment by dark-chocolate** [comment]
Thanks @alextekartik for the basic type (don't use async in dispose()) and the solution (it's okay to keep the database open forever unless you need something special).
