### ISSUE TITLE
sqlflite web db not persistent

### ISSUE THREAD

**Issue by bsutton** [tekartik/sqflite#1112]
I'm using sqflite and its working fine on android and desktop.

On web its working (able to create tables and insert/update rows). 

The problem is that on web the db isn't persisted. Each time I restart the flutter web app the db is empty.

![image](https://github.com/tekartik/sqflite/assets/900408/d02eeac0-bc4c-4680-abad-426778bc7bdf)

```dart 

  static Future<void> initDatabase() async {
    if (kIsWeb) {
      databaseFactory = databaseFactoryFfiWeb;
    } else {
      if (Platform.isLinux || Platform.isMacOS || Platform.isWindows) {
        /// required for non-mobile platforms.
        sqfliteFfiInit();
        databaseFactory = databaseFactoryFfi;
      } else if (Platform.isAndroid || Platform.isIOS) {
        /// uses the default factory.
      }
    }
```

```yaml
 sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3+1
```

Any hints as to what might be causing this?

**Comment by alextekartik** [comment]
So its seems to be there according to your image, right ? 
You might want to run the setup again (https://pub.dev/packages/sqflite_common_ffi_web#setup)

I have a basic (persistent) example here:
- live demo: https://tk-demo-sqflite.web.app/
- source code: https://github.com/alextekartik/flutter_app_example/tree/master/demo_sqflite

Also make sure when you start your app that you are on the same web port.

**Comment by bsutton** [comment]
So it looks like the port number was the issue, once I change the debug launch config to use a consistent port the database was preserved.

For the record my .vscode/launch.json now contains

```
 "configurations": [
        {
            "name": "handyman-chrome",
            "request": "launch",
            "type": "dart",
            "args": ["-d", "chrome","--web-port", "8000"],

        },
```

Thanks for the help.

P.S. it might be worth updating the web doco with a note about the port needing to be stable when debugging.
