### ISSUE TITLE
Execute initialization operation with script (available on Windows and web platforms, not available on Android)

### ISSUE THREAD

**Issue by 244916896** [tekartik/sqflite#1120]
void onDBCreate(Database db, int version) async {
    MyLogger.info("onDBCreate-db:${db.path},version:$version");
    // 创建标记表
    // await db.execute('''
    //   CREATE TABLE IF NOT EXISTS initialization (
    //     initialized INTEGER
    //   )
    // ''');
    await db.execute(
        'CREATE TABLE IF NOT EXISTS initialization ( initialized INTEGER )');
    // 检查是否已经初始化
    var result = await db.query('initialization');
    if (result.isEmpty) {
      // 用脚本实行初始化操作（Windows、Web平台可用，Android不可用）
      String sql = await AssetsMgr().loadDBScripts();
      await db.execute(sql);

      // 标记为已初始化
      await db.execute('INSERT INTO initialization (initialized) VALUES (1)');
      print("------------------------onDBCreate");
    } else {
      print("++++++++++++++++++++++++onDBCreate");
    }
  }

![image](https://github.com/user-attachments/assets/5bebbec6-8378-4162-b999-9e44ce662411)

**Comment by alextekartik** [comment]
Indeed, native Android implementation supports one operation at a time. You can try to use sqflite_common_ffi on Android as well or you can use batch and split your script in multiple commands
