### ISSUE TITLE
LIKE Query with Non-ASCII Character

### ISSUE THREAD

**Issue by pratamarama** [tekartik/sqflite#1123]
I have query that contains Non-ASCII characters, the query like:

`WHERE books.value LIKE '%Société%'`

Where the actual data is "SOCIÉTÉ".

The result is nothing, even though the data is there. I've tried with `LOWER()` function and various `COLLATE <Collation>`, but the result is still the same.

When there is no Non-ASCII character, everything is normal.

Is there any way to solve this issue?

**Comment by alextekartik** [comment]
You should use parameters: 
* https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#parameters
* https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#using-like

```
WHERE books.value LIKE ?
```

with parameters `['%Société%']`

**Comment by pratamarama** [comment]
Thank you for your suggestion.

I've used `await db.query('books', columns: ['value'], where: 'value LIKE ?', whereArgs: ['%Société%']);` and the result is still the same.

but is it possible to query with case insensitive Non-ASCII character with this plugin?

**Comment by alextekartik** [comment]
`COLLATE NOCASE` should be the solution but unfortunately it does not seem consistent on the various implementation and sqflite uses whatever the platform provides. One safe solution I see is to add another column where you manually convert the string (lowercase, removing diacritics). see https://github.com/tekartik/sqflite/issues/231 for a similar bug and proposed solution.

You might also try with `sqflite_common_ffi` along with `sqlite3_flutter_libs` to see if it provides a more consistent implementation.
