### ISSUE TITLE
ITMS-91065: Missing signature - Your app includes “Frameworks/sqflite.framework/sqflite”, which includes sqflite, an SDK that was identified in the documentation as a privacy-impacting third-party SDK.

### ISSUE THREAD

**Issue by swaraj-raw** [tekartik/sqflite#1129]
Getting below mentioned issue while uploading the app on app store.
![image](https://github.com/user-attachments/assets/b84bb845-694c-4e0d-819d-b19ea836c70c)
I have updated the library to latest version, still i am facing the issue. One thing I noticed that the sqflite.xcframework is unsigned. What could be the fix for this? As I have a upcoming release scheduled being blocked by this issue, which is an critical thing for the Client.

**Comment by alextekartik** [comment]
I don't know much about iOS build but was able to publish on the app store (about a month ago) without issue. Is your ios/Xcode project old? You might have to re-create it if no solution works...(yes I know it is a pain). Personally I don't have such sqflite.framework in XCode, I only have Pods.

You can try to:
- delete ios/Podfile
- delete ios/Podfile.lock
- delete ios/Pods folder
- run `flutter build ios`
- run `pod install --repo-update` in ios folder
- and in the worst case, try to re-create your ios project...

**Comment by swaraj-raw** [comment]
hi @alextekartik, no my Xcode project is not old one. Basically my project is a SwiftUI application which has a game module made using Flutter. In that game module, I am using **cached_network_image** library which is using the sqflite library inside. So while generating the xcFrameworks of flutter for my project, sqflite.xcFramework is generated. Also, i have already tried your below mentioned steps, but no luck.

**Comment by alextekartik** [comment]
I'm not sure but I think that for now you can't use frameworks, you have to use cocapods: https://docs.flutter.dev/add-to-app/ios/project-setup

I would gladly help if I knew what I could do, I followed all the steps to match what other plugins do - see https://github.com/tekartik/sqflite/issues/1065

If someone listening here has some ios build knowledge...

**Comment by alextekartik** [comment]
You should check here for a similar issue (and a solution): https://github.com/flutter/flutter/issues/148300

**Comment by swaraj-raw** [comment]
hi @alextekartik , I did the manual code signing for the xcFramework, but my application is not archiving now with that XC. Any other solution that may help here is most welcomed.

**Comment by swaraj-raw** [comment]
Finally fixed the issue by manually signing the xcFramework. Thanks for the help. @alextekartik

**Comment by alextekartik** [comment]
@swaraj-raw I'm glad you managed. If you could describe the steps needed, I would gladly generate some doc from it for the next developer having a similar issue. Thanks!

**Comment by swaraj-raw** [comment]
Sure, @alextekartik !
So first we need to manually sign the xcFramework using the below command:
`codesign --timestamp -v -f --sign "<Identity> (**********)" sqflite.xcframework`

That's it.

use command: `codesign -dv sqflite.xcframework` to check the signature details of the xcFramework.

then use command: `codesign -vv sqflite.xcframework`to check the integrity of the xcFramework, like to find if any error is there in the signature or not. 
If all is okay then you'll see this message after using `-vv` command.
<img width="521" alt="image" src="https://github.com/user-attachments/assets/64ffe64e-d78c-4cc9-9b45-fd5f13ca6441">

All set, you're good to go with archiving your iOS app.

**Note: There is a .dSYM file associated with the xcFramework Signature, make your .gitignore file is ignoring that .dSYM file.**

**Comment by alextekartik** [comment]
Thank you @swaraj-raw I have added your notes here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#missing-signature
