### ISSUE TITLE
SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database

### ISSUE THREAD

**Issue by v7lin** [tekartik/sqflite#113]
E/SQLiteDatabase( 2043): Failed to open database '/data/user/0/com.xxx.xxx/databases/1881_3c07bbc431e70f53929daa89c69e057e_im.db'.
E/SQLiteDatabase( 2043): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:211)
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:195)
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:766)
E/SQLiteDatabase( 2043): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
E/SQLiteDatabase( 2043): 	at com.tekartik.sqflite.SqflitePlugin$Database.openReadOnly(SqflitePlugin.java:775)
E/SQLiteDatabase( 2043): 	at com.tekartik.sqflite.SqflitePlugin$Database.access$800(SqflitePlugin.java:762)
E/SQLiteDatabase( 2043): 	at com.tekartik.sqflite.SqflitePlugin.onOpenDatabaseCall(SqflitePlugin.java:642)
E/SQLiteDatabase( 2043): 	at com.tekartik.sqflite.SqflitePlugin.onMethodCall(SqflitePlugin.java:741)
E/SQLiteDatabase( 2043): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/SQLiteDatabase( 2043): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/SQLiteDatabase( 2043): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/SQLiteDatabase( 2043): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/SQLiteDatabase( 2043): 	at android.os.Looper.loop(Looper.java:160)
E/SQLiteDatabase( 2043): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/SQLiteDatabase( 2043): 	at java.lang.reflect.Method.invoke(Native Method)
E/SQLiteDatabase( 2043): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/SQLiteDatabase( 2043): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 2043): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 2043): DatabaseException(open_failed /data/user/0/com.xxx.xxx/databases/1881_3c07bbc431e70f53929daa89c69e057e_im.db)
E/flutter ( 2043): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter ( 2043): <asynchronous suspension>
E/flutter ( 2043): #1      SqfliteDatabase._openDatabase (package:sqflite/src/database.dart:471:12)
E/flutter ( 2043): #2      SqfliteDatabase.doOpen (package:sqflite/src/database.dart:504:28)
E/flutter ( 2043): <asynchronous suspension>
E/flutter ( 2043): #3      SqfliteDatabaseOpenHelper.openDatabase.<anonymous closure> (package:sqflite/src/database.dart:166:26)
E/flutter ( 2043): <asynchronous suspension>
E/flutter ( 2043): #4      Lock._runTask (package:synchronized/src/synchronized_impl.dart:149:27)
E/flutter ( 2043): #5      LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:64:14)
E/flutter ( 2043): #6      LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:74:17)
E/flutter ( 2043): #7      Lock.synchronized (package:synchronized/src/synchronized_impl.dart:142:12)
E/flutter ( 2043): #8      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:163:25)
E/flutter ( 2043): <asynchronous suspension>
E/flutter ( 2043): #9      SqfliteDatabaseFactory.openDatabase (package:sqflite/src/database_factory.dart:134:41)
E/flutter ( 2043): <asynchronous suspension>
E/flutter ( 2043): #10     openDatabase (package:sqflite/sqflite.dart:338:26)
E/flutter ( 2043): #11     SQLiteOpenHelper.getDatabase (package:fake_os/src/sqlite_open_helper.dart:23:18)
E/flutter ( 2043): <asynchronous suspension>
E/flutter ( 2043): #12     SQLiteOpenHelper.getReadableDatabase (package:fake_os/src/sqlite_open_helper.dart:44:12)
E/flutter ( 2043): #13     IMDBHelper.getMessages (package:star_repository/src/im/im_db_helper.dart:98:25)
E/flutter ( 2043): <asynchronous suspension>
E/flutter ( 2043): #14     IMRepository.getLocalMessageHistory (package:star_repository/src/im/im_repository.dart:43:29)
E/flutter ( 2043): <asynchronous suspension>
E/flutter ( 2043): #15     _MessagePresenterImpl.loadMixedMessageHistory (package:star_im/src/ui/message/message_contract.dart:62:10)
E/flutter ( 2043): #16     _MessageComponentState._initMessage (package:star_im/src/ui/message/message_component.dart:76:31)
E/flutter ( 2043): <asynchronous suspension>
E/flutter ( 2043): #17     _MessageComponentState.build (package:star_im/src/ui/message/message_component.dart:91:9)
E/flutter ( 2043): #18     StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
E/flutter ( 2043): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
E/flutter ( 2043): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
E/flutter ( 2043): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
E/flutter ( 2043): #22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
E/flutter ( 2043): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
E/flutter ( 2043): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
E/flutter ( 2043): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
E/flutter ( 2043): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
E/flutter ( 2043): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
E/flutter ( 2043): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
E/flutter ( 2043): #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
E/flutter ( 2043): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
E/flutter ( 2043): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
E/flutter ( 2043): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
E/flutter ( 2043): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
E/flutter ( 2043): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
E/flutter ( 2043): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
E/flutter ( 2043): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
E/flutter ( 2043): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
E/flutter ( 2043): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
E/flutter ( 2043): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
E/flutter ( 2043): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
E/flutter ( 2043): #41     Element.rebuild (package:flutter/src/widg

**Comment by alextekartik** [comment]
It seems to be an IO access issue. Are you able to read/write a file is the same folder? (might require permission or root access).

**Comment by v7lin** [comment]
在项目里，仅打开一个数据库。还未进行读写等函数的调用。
--- translate ---
In the project, only one database is opened. No calls for functions such as read and write have yet been made.

--- code ---
`abstract class SQLiteOpenHelper {
  @protected
  final String name;
  @protected
  final int version;

  SQLiteOpenHelper(
    this.name,
    this.version,
  );

  @protected
  Future<Database> getDatabase({
    bool readOnly: false,
  }) async {
    String path = join(await getDatabasesPath(), name);
    return await openDatabase(
      path,
      version: version,
      onConfigure: onConfigure,
      onCreate: onCreate,
      onUpgrade: onUpgrade,
      onDowngrade: onDowngrade,
      onOpen: onOpen,
      readOnly: readOnly,
    );
  }

  @protected
  Future<Database> getWritableDatabase() {
    return getDatabase(
      readOnly: false,
    );
  }

  @protected
  Future<Database> getReadableDatabase() {
    return getDatabase(
      readOnly: true,
    );
  }

  @protected
  Future<void> onConfigure(Database db);

  @protected
  Future<void> onCreate(Database db, int version);

  @protected
  Future<void> onUpgrade(Database db, int oldVersion, int newVersion);

  @protected
  Future<void> onDowngrade(Database db, int oldVersion, int newVersion);

  @protected
  Future<void> onOpen(Database db);

  @protected
  String selectionPlaceholder(List<String> selectionArgs) {
    StringBuffer buffer = new StringBuffer();
    for (int i = 0; i < selectionArgs.length; i++) {
      buffer.write(i != 0 ? ',' : '');
      buffer.write('?');
    }
    return buffer.toString();
  }
}`

`abstract class SimpleSQLiteOpenHelper extends SQLiteOpenHelper {
  SimpleSQLiteOpenHelper(String name, int version) : super(name, version);

  @override
  Future<void> onConfigure(Database db) async {}

  @override
  Future<void> onOpen(Database db) async {}

  @override
  Future<void> onDowngrade(Database db, int oldVersion, int newVersion) async {}
}`

`class MessageTable {
  static const String TABLE_NAME = 'message';

  static const List<String> COLUMNS = [
    MessageData.KEY_SENDER,
    MessageData.KEY_TYPE,
    MessageData.KEY_URL,
    MessageData.KEY_UNREAD,
    MessageData.KEY_MSG,
    MessageData.KEY_DATE,
  ];

  static const int COLUMN_SENDER = 0;
  static const int COLUMN_TYPE = 1;
  static const int COLUMN_URL = 2;
  static const int COLUMN_UNREAD = 3;
  static const int COLUMN_MSG = 4;
  static const int COLUMN_DATE = 5;

  MessageTable._();

  static String initTableScript() {
    StringBuffer buffer = new StringBuffer();
    buffer.write('create table if not exists ');
    buffer.write(TABLE_NAME);
    buffer.write(' ');
    buffer.write('(');
    buffer.write('${COLUMNS[COLUMN_SENDER]} text primary key,');
    buffer.write('${COLUMNS[COLUMN_TYPE]} integer,');
    buffer.write('${COLUMNS[COLUMN_URL]} text,');
    buffer.write('${COLUMNS[COLUMN_UNREAD]} integer,');
    buffer.write('${COLUMNS[COLUMN_MSG]} text,');
    buffer.write('${COLUMNS[COLUMN_DATE]} integer');
    buffer.write(')');
    return buffer.toString();
  }
}

class ProfileTable {
  static const String TABLE_NAME = 'profile';

  static const List<String> COLUMNS = [
    ProfileData.KEY_SENDER,
    ProfileData.KEY_URL,
    ProfileData.KEY_NAME,
    ProfileData.KEY_AVATAR,
  ];

  static const int COLUMN_SENDER = 0;
  static const int COLUMN_URL = 1;
  static const int COLUMN_NAME = 2;
  static const int COLUMN_AVATAR = 3;

  ProfileTable._();

  static String initTableScript() {
    StringBuffer buffer = new StringBuffer();
    buffer.write('create table if not exists ');
    buffer.write(TABLE_NAME);
    buffer.write(' ');
    buffer.write('(');
    buffer.write('${COLUMNS[COLUMN_SENDER]} text primary key,');
    buffer.write('${COLUMNS[COLUMN_URL]} text,');
    buffer.write('${COLUMNS[COLUMN_NAME]} text,');
    buffer.write('${COLUMNS[COLUMN_AVATAR]} text');
    buffer.write(')');
    return buffer.toString();
  }
}

class IMDBHelper extends SimpleSQLiteOpenHelper {
  static const int VERSION_1 = 1;

  IMDBHelper(String userId, String flag)
      : super('${userId}_${flag}_im.db', VERSION_1);

  @protected
  @override
  Future<void> onCreate(Database db, int version) async {
    await db.execute(MessageTable.initTableScript());
    await db.execute(ProfileTable.initTableScript());
  }
...
}`

**Comment by alextekartik** [comment]
It seems you are trying to open the database in read-only mode. Indeed if the database does not exist, it will fail. Can you try to remove the readOnly flag?

**Comment by v7lin** [comment]
谢谢。但是我觉得仍觉得这是一个BUG。这部分代码仿Android的SQLiteOpenHelper，Android上SQLiteOpenHelper能正常工作。Flutter也应该能正常工作，这样更方便Android程序员开发Flutter。

--- translate ---

Thank you. But I still think it's a BUG. This part of the code is modeled on Android's SQLiteOpenHelper, and SQLiteOpenHelper works on Android. Flutter should also work properly, making it easier for Android programmers to develop Flutter.

**Comment by alextekartik** [comment]
I understand the issue. Android does indeed try to open in read-only first then read-write. The API is actually largely based on Android. The difference here is that opening in read mode fails if the database does not exist. I'd rather not change that as some existing code relies on that (for example when opening an asset database on iOS).

**Comment by v7lin** [comment]
嗯，考虑到iOS兼容问题，倒是可以理解不做修改。非常感谢你的回答，我想这个问题可以关闭了。

--- translate ---

Well, considering iOS compatibility, it is understandable that no modification is made. Thank you very much for your answer. I think this question can be closed.

**Comment by v7lin** [comment]
-.-||| 又发现一个问题。

--- translate ---

Find another problem.

--- code ---

abstract class SQLiteOpenHelper {
...
  @protected
  Future<Database> getDatabase({
    bool readOnly: false,
  }) async {
    String path = join(await getDatabasesPath(), name);
    if (readOnly && !new File(path).existsSync()) {
      await openDatabase(
        path,
        version: version,
        onConfigure: onConfigure,
        onCreate: onCreate,
        onUpgrade: onUpgrade,
        onDowngrade: onDowngrade,
        onOpen: onOpen,
        readOnly: false,
      );
    }
    return await openDatabase(
      path,
      version: version,
      onConfigure: onConfigure,
      onCreate: onCreate,
      onUpgrade: onUpgrade,
      onDowngrade: onDowngrade,
      onOpen: onOpen,
      readOnly: readOnly,
    );
  }
...
}

class IMDBHelper extends SQLiteOpenHelper {
  Future<List<MessageData>> getMessages() async {
    Database db = await getReadableDatabase();
    List<Map<String, dynamic>> maps = await db.query(
      MessageTable.TABLE_NAME,
      columns: MessageTable.COLUMNS,
      orderBy: '${MessageTable.COLUMNS[MessageTable.COLUMN_DATE]} desc',
    );
    return maps != null
        ? maps.map((Map<String, dynamic> map) {
            return new MessageData(map);
          }).toList()
        : null;
  }
}

--- logs ---

E/flutter ( 6102): DatabaseException(attempt to write a readonly database (code 8 SQLITE_READONLY))
E/flutter ( 6102): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #1      SqfliteDatabase.invokeExecute (package:sqflite/src/database.dart:306:12)
E/flutter ( 6102): #2      SqfliteDatabase.txnExecute.<anonymous closure> (package:sqflite/src/database.dart:301:14)
E/flutter ( 6102): #3      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:264:26)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #4      SqfliteDatabase.txnWriteSynchronized (package:sqflite/src/database.dart:295:7)
E/flutter ( 6102): #5      SqfliteDatabase.txnExecute (package:sqflite/src/database.dart:300:12)
E/flutter ( 6102): #6      SqfliteDatabaseExecutor.execute (package:sqflite/src/database.dart:22:10)
E/flutter ( 6102): #7      SqfliteDatabase.setVersion (package:sqflite/src/database.dart:451:11)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #8      SqfliteDatabase.doOpen.<anonymous closure> (package:sqflite/src/database.dart:581:17)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #9      SqfliteDatabase._runTransaction (package:sqflite/src/database.dart:417:28)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #10     SqfliteDatabase.transaction.<anonymous closure> (package:sqflite/src/database.dart:432:14)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #11     SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:264:26)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #12     SqfliteDatabase.txnWriteSynchronized (package:sqflite/src/database.dart:295:7)
E/flutter ( 6102): #13     SqfliteDatabase.transaction (package:sqflite/src/database.dart:431:12)
E/flutter ( 6102): #14     SqfliteDatabase.doOpen (package:sqflite/src/database.dart:560:15)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #15     SqfliteDatabaseOpenHelper.openDatabase.<anonymous closure> (package:sqflite/src/database.dart:166:26)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #16     Lock._runTask (package:synchronized/src/synchronized_impl.dart:149:27)
E/flutter ( 6102): #17     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:64:14)
E/flutter ( 6102): #18     LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:74:17)
E/flutter ( 6102): #19     Lock.synchronized (package:synchronized/src/synchronized_impl.dart:142:12)
E/flutter ( 6102): #20     SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:163:25)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #21     SqfliteDatabaseFactory.openDatabase (package:sqflite/src/database_factory.dart:134:41)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #22     openDatabase (package:sqflite/sqflite.dart:338:26)
E/flutter ( 6102): #23     SQLiteOpenHelper.getDatabase (package:fake_os/src/sqlite_open_helper.dart:37:18)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #24     SQLiteOpenHelper.getReadableDatabase (package:fake_os/src/sqlite_open_helper.dart:58:12)
E/flutter ( 6102): #25     IMDBHelper.getMessages (package:star_repository/src/im/im_db_helper.dart:98:25)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #26     IMRepository.getLocalMessageHistory (package:star_repository/src/im/im_repository.dart:43:29)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #27     _MessagePresenterImpl.loadMixedMessageHistory (package:star_im/src/ui/message/message_contract.dart:62:10)
E/flutter ( 6102): #28     _MessageComponentState._initMessage (package:star_im/src/ui/message/message_component.dart:77:31)
E/flutter ( 6102): <asynchronous suspension>
E/flutter ( 6102): #29     _MessageComponentState.build (package:star_im/src/ui/message/message_component.dart:92:9)
E/flutter ( 6102): #30     StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
E/flutter ( 6102): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
E/flutter ( 6102): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
E/flutter ( 6102): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
E/flutter ( 6102): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
E/flutter ( 6102): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
E/flutter ( 6102): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
E/flutter ( 6102): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
E/flutter ( 6102): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
E/flutter ( 6102): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
E/flutter ( 6102): #40     C

**Comment by alextekartik** [comment]
It seems you are still opening the database in readOnly mode. Writing fails as expected. Can you make getReadbleDatabase just returns getWritableDatabase as a simple fix, or remove the readOnly flag everywhere

**Comment by v7lin** [comment]
我仅仅只是执行了查询数据库，并没有将数据写入到数据库中。

--- translate ---

I just executed the query database and did not write the data to the database.

**Comment by alextekartik** [comment]
The readOnly flag is exclusif, you should not set a onCreate/onConfigure/onUpdate method as it will create a transaction and then fails. I will add some check to prevent that (i.e. it should have failed before). As I said readOnly support is limited and in your case you should not use it

**Comment by v7lin** [comment]
^_^ thanks
