### ISSUE TITLE
Some better Initializationof db create and all sql query like crud 

### ISSUE THREAD

**Issue by jhonbatler99** [tekartik/sqflite#1131]
[db.txt](https://github.com/user-attachments/files/17193861/db.txt)
[getData.txt](https://github.com/user-attachments/files/17198764/getData.txt)
[model.txt](http
[addToDb.txt](https://github.com/user-attachments/files/17198767/addToDb.txt)
s://github.com/user-attachments/files/17198765/model.txt)
[model.txt](https://github.com/user-attachments/files/17198825/model.txt)
https://github.com/jhonbatler99/futures/tree/main/lib/Databasedemo%20LIb/lib

**Comment by alextekartik** [comment]
That does not sound like an issue...

**Comment by jhonbatler99** [comment]
ohh yeah bro

but i think you not read heading first what i menstion

**Comment by alextekartik** [comment]
Sorry if I did not understand your issue but the description has no text but links to some code without any description of what it is supposed to report. Many developers complain that I have too many open issues so it is hard for me to keep such issue open forever without any description about what is wrong and what I'm supposed to do to fix it. Sorry again

**Comment by jhonbatler99** [comment]
Thanks for your explanation.
