### ISSUE TITLE
Framework 'sqflite' not found

### ISSUE THREAD

**Issue by antonengelhardt** [tekartik/sqflite#1134]
When running `flutter run` i get the following message.

```
Launching lib/main.dart on iPhone 16 Pro in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,757ms
Xcode build done.                                           27.0s
Failed to build iOS app
Error (Xcode): Framework 'sqflite' not found


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.
```

We never imported `sqflite` as a pub into our project. It was in our `Podfile.lock`(maybe as a sub-dependency`. 3 days ago we got this message for the first time.

I tried

- cleaning Flutter, Pod and XCode Caches and Build Caches (did not help)
- creating a new Flutter App with sqflite as a pub (which worked)
- changing the minimum deployment version of iOS to 15 (did not help)

I was wondering if there was anything that we could do to debug this further or to find missing/incorrect configuration on our end. Maybe someone has had this issue already.

**Versions**

Xcode 16.0
Flutter v3.24.3
Dart 3.5.3
Cocoapods 1.15.0

**Comment by alextekartik** [comment]
I'm assuming you're using the latest version of sqflite (2.4.0) and you performed a pub upgrade
sqflite has change to a federated plugin recently (last week), so the iOS/MacOS implementation is now in sqflite_darwin.
You might have a some remaining sqflite framework in your project that you should simply remove (not sure how to do though...)

**Comment by antonengelhardt** [comment]
Yes, we did `pub upgrade` and also upgraded all major versions.

We solved it now by removing all `OTHER_LDFLAGS` in the `project.pbxproj` file. One day lost but maybe this helps someone :)
