### ISSUE TITLE
In a short period of time, many times the database was opened and closed, and the following two random exceptions occurred.

### ISSUE THREAD

**Issue by v7lin** [tekartik/sqflite#114]
短时间内，多次打开关、闭数据库，随机出现以下两个异常

--- translate ---

In a short period of time, many times the database was opened and closed, and the following two random exceptions occurred.

--- log 1 ---

E/flutter (10186): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (10186): DatabaseException(attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.xrj.edu.admin/databases/1881_3c07bbc431e70f53929daa89c69e057e_im.db)
E/flutter (10186): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #1      SqfliteDatabase.invokeExecute (package:sqflite/src/database.dart:306:12)
E/flutter (10186): #2      SqfliteDatabase.txnExecute.<anonymous closure> (package:sqflite/src/database.dart:301:14)
E/flutter (10186): #3      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:264:26)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #4      SqfliteDatabase.txnWriteSynchronized (package:sqflite/src/database.dart:295:7)
E/flutter (10186): #5      SqfliteDatabase.txnExecute (package:sqflite/src/database.dart:300:12)
E/flutter (10186): #6      SqfliteDatabase.beginTransaction (package:sqflite/src/database.dart:391:15)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #7      SqfliteDatabase._runTransaction (package:sqflite/src/database.dart:413:19)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #8      SqfliteDatabase.transaction.<anonymous closure> (package:sqflite/src/database.dart:432:14)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #9      SqfliteDatabase.txnSynchronized.<anonymous closure> (package:sqflite/src/database.dart:279:22)
E/flutter (10186): #10     Lock._runTask (package:synchronized/src/synchronized_impl.dart:149:27)
E/flutter (10186): #11     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:64:14)
E/flutter (10186): #12     LockBase._createAndRunTask.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:96:17)
E/flutter (10186): #13     _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (10186): #14     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (10186): #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (10186): #16     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (10186): #17     Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (10186): #18     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (10186): #19     LockBase.cleanUpTask (package:synchronized/src/synchronized_impl.dart:121:20)
E/flutter (10186): #20     LockBase._createAndRunTask.run.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:67:9)
E/flutter (10186): #21     _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter (10186): #22     _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter (10186): #23     Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter (10186): #24     Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter (10186): #25     Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (10186): #26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (10186): #27     _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (10186): #28     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (10186): #29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (10186): #30     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (10186): #31     Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (10186): #32     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (10186): #33     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (10186): #34     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
E/flutter (10186): #35     SqfliteDatabase._runTransaction (package:sqflite/src/database.dart)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #36     SqfliteDatabase.transaction.<anonymous closure> (package:sqflite/src/database.dart:432:14)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #37     SqfliteDatabase.txnSynchronized.<anonymous closure> (package:sqflite/src/database.dart:279:22)
E/flutter (10186): #38     Lock._runTask (package:synchronized/src/synchronized_impl.dart:149:27)
E/flutter (10186): #39     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:64:14)
E/flutter (10186): #40     LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:74:17)
E/flutter (10186): #41     Lock.synchronized (package:synchronized/src/synchronized_impl.dart:142:12)
E/flutter (10186): #42     SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:275:37)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #43     SqfliteDatabase.txnWriteSynchronized (package:sqflite/src/database.dart:295:7)
E/flutter (10186): #4

--- log 2 ---

I/SQLiteConnectionPool(10186): The connection pool for /data/user/0/com.xrj.edu.admin/databases/1881_3c07bbc431e70f53929daa89c69e057e_im.db has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.
E/flutter (10186): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (10186): DatabaseException(database_closed 2)
E/flutter (10186): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #1      SqfliteDatabase.invokeExecute (package:sqflite/src/database.dart:306:12)
E/flutter (10186): #2      SqfliteDatabase.txnExecute.<anonymous closure> (package:sqflite/src/database.dart:301:14)
E/flutter (10186): #3      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:264:26)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #4      SqfliteDatabase.txnWriteSynchronized (package:sqflite/src/database.dart:295:7)
E/flutter (10186): #5      SqfliteDatabase.txnExecute (package:sqflite/src/database.dart:300:12)
E/flutter (10186): #6      SqfliteDatabase.endTransaction (package:sqflite/src/database.dart:403:15)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #7      SqfliteDatabase._runTransaction (package:sqflite/src/database.dart:422:15)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #8      SqfliteDatabase.transaction.<anonymous closure> (package:sqflite/src/database.dart:432:14)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #9      SqfliteDatabase.txnSynchronized.<anonymous closure> (package:sqflite/src/database.dart:279:22)
E/flutter (10186): #10     Lock._runTask (package:synchronized/src/synchronized_impl.dart:149:27)
E/flutter (10186): #11     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:64:14)
E/flutter (10186): #12     LockBase._createAndRunTask.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:96:17)
E/flutter (10186): #13     _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (10186): #14     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (10186): #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (10186): #16     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (10186): #17     Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (10186): #18     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (10186): #19     LockBase.cleanUpTask (package:synchronized/src/synchronized_impl.dart:121:20)
E/flutter (10186): #20     LockBase._createAndRunTask.run.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:67:9)
E/flutter (10186): #21     _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter (10186): #22     _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter (10186): #23     Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter (10186): #24     Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter (10186): #25     Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (10186): #26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (10186): #27     _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (10186): #28     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (10186): #29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (10186): #30     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (10186): #31     Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (10186): #32     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (10186): #33     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (10186): #34     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
E/flutter (10186): #35     SqfliteDatabase._runTransaction (package:sqflite/src/database.dart)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #36     SqfliteDatabase.transaction.<anonymous closure> (package:sqflite/src/database.dart:432:14)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #37     SqfliteDatabase.txnSynchronized.<anonymous closure> (package:sqflite/src/database.dart:279:22)
E/flutter (10186): #38     Lock._runTask (package:synchronized/src/synchronized_impl.dart:149:27)
E/flutter (10186): #39     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:64:14)
E/flutter (10186): #40     LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:74:17)
E/flutter (10186): #41     Lock.synchronized (package:synchronized/src/synchronized_impl.dart:142:12)
E/flutter (10186): #42     SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:275:37)
E/flutter (10186): <asynchronous suspension>
E/flutter (10186): #43     SqfliteDatabase.txnWriteSynchronized (package:sqflite/src/database.dart:295:7)
E/flutter (10186): #44     SqfliteDatabase.transaction (package:sqflite/src/database.dart:431:12)
E/flutter (10186): #45     IMDBHelper.replaceMessages (package:star_repo

**Comment by alextekartik** [comment]
It seems that you are trying to access an already closed database (i.e. you might have reopened it but the current call is using the old one database reference). In general, I recommend to keep the database open (like a standard SQLite content provider on Android) unless you specifically need to close it.

**Comment by v7lin** [comment]
好的，谢谢。
我建议给 Database 添加一个 readOnly 方法，以便使用者区分不同场景下的 Database，我在 SqfliteDatabase 里找到了这个方法，不知道为何不开放给 Database。

--- translate ---

Okay, thank you.
I recommend adding a readOnly method to the database so that users can distinguish between different scenarios. I found this method in SqfliteDatabase, and I don't know why it's not open to the database.
