### ISSUE TITLE
Bad parameter or other API misuse, bad parameter or other API misuse (code 21)

### ISSUE THREAD

**Issue by Srimathi622** [tekartik/sqflite#1140]
I have millions of records to insert in windows machine. The insert operation is running in an isolate thread. I encountered the error below when trying to retrieve data immediately after the insert was completed. However, once the app is restarted, it works as expected. I ensured the database was closed after the transaction was finished.I checked the path and parameters. All are right. Here is my insert and fetch code. Could someone help identify what might be going wrong? 

Future<String?> getAppDataPath() async {
  String? appPath;

  // print('getApplicationSupportPath()  ${getApplicationSupportPath()}');
    final Directory directory =
        await path_provider.getApplicationSupportDirectory();

    appPath = directory.path;

    //   print('path $AppPath');
    
  return appPath;
}

**Insert Statement:**

Future insertFndColumns(
    {required String sqlXmlColumnData,
    required String folderName,
    required String fileName}) async {
  try {
    // showCircularProgressIndicator(context: ctx);
    String? appPath = await getAppDataPath();
    // sqfliteFfiInit();
    var databaseFactory = databaseFactoryFfi;
    //
  

    var path = normalize(join(appPath!, 'data', folderName, fileName));
    await Directory(dirname(path)).create(recursive: true);

    var db = await databaseFactory.openDatabase(path,
        options: OpenDatabaseOptions(
          version: gDbObjectBrowserVersion,
        ));

    // Optimize database settings
    await db.execute('PRAGMA synchronous = OFF');
    await db.execute('PRAGMA journal_mode = WAL');

    await db.execute('DELETE FROM XXC_COLUMNS');

    debugPrint('xml parsing started ${DateTime.now()}');

    final document = xml.XmlDocument.parse(sqlXmlColumnData);
    debugPrint('xml parsed ${DateTime.now()}');
    //final columnRows = document.findAllElements('ROW');

    List<xml.XmlElement> columnxmlList =
        document.findAllElements('ROW').toList();

    debugPrint('Got Row Elements ${DateTime.now()}');

    // print('columnxmlList created ${DateTime.now()}');
    // Batch insertion configuration
    const batchSize = 1000;
    // You can adjust the batch size as needed
    final totalRecords = columnxmlList.length;

    // print('totalRecords ${totalRecords} ${DateTime.now()}');

    for (int i = 0; i < totalRecords; i += batchSize) {
      List<xml.XmlElement> chunk = [];
      if (i + batchSize <= totalRecords) {
        chunk = columnxmlList.sublist(i, i + batchSize);
        //print('chunk ${chunk.length} ${DateTime.now()}');
      } else {
        chunk = columnxmlList.sublist(i, totalRecords);
        // print('chunk less than 1000 ${chunk.length} ${DateTime.now()}');
      }

      await db.transaction((txn) async {
        var batch = txn.batch();
        for (xml.XmlElement column in chunk) {
          // print(' table id ${column.findElements('TABLE_ID').first.innerText}');
          var value = {
            'TABLE_ID': column.findElements('TABLE_ID').first.innerText,
            'COLUMN_ID': column.findElements('COLUMN_ID').first.innerText,
            'COLUMN_NAME': column.findElements('COLUMN_NAME').first.innerText,
            'COLUMN_TYPE': column.findElements('COLUMN_TYPE').first.innerText,
            'WIDTH': column.findElements('WIDTH').first.innerText,
            'PRECISION': column.findElements('PRECISION').first.innerText,
            'NULL_ALLOWED_FLAG':
                column.findElements('NULL_ALLOWED_FLAG').first.innerText,
            'DESCRIPTION': column.findElements('DESCRIPTION').first.innerText,
            'CREATION_DATE': DateTime.now().toString()
          };
          batch.insert('XXC_COLUMNS', value);
        }
        await batch.commit(noResult: true);

        //print('Inserted into the table XX_COLUMNS');
      });
      // Trigger garbage collection
      //Garbage Collection: Added a small delay after each batch to help with memory cleanup
      await Future.delayed(const Duration(milliseconds: 100));
      SystemNavigator.pop(); // Ensures memory cleanup
    }

    await db.close();
    // Navigator.of(ctx).pop();
  } catch (error, stacktrace) {
    throw Exception(
        'Error occured while inserting XX_COLUMNS $error at $stacktrace');
  }
}

**Get columns code :**
Future<List<Map<String, dynamic>>> getFndColumns(
    {required String tableId,
    required String folderName,
    required String fileName}) async {
  final ColumnsBGProcessController fndColumnController = Get.find();

  // Init ffi loader if needed.

  String? appPath;

  appPath = await getAppDataPath();

  var databaseFactory = databaseFactoryFfi;
  // Pick a path on your file system
  
  var path = normalize(join(appPath!, 'data', folderName, fileName));
  // Create parent directory

  // deleteDatabase(path);
  await Directory(dirname(path)).create(recursive: true);

  //print('path $path');
  var db = await databaseFactory.openDatabase(
    path,
    options: OpenDatabaseOptions(
      version: gDbObjectBrowserVersion,
    ),
  );
  var result = await db.rawQuery('''
      SELECT "COLUMN_NAME",
             "COLUMN_TYPE",
             "PRECISION",
             "NULL_ALLOWED_FLAG",
             "DESCRIPTION"
        FROM XXC_COLUMNS 
       WHERE TABLE_ID =?
    ORDER BY COLUMN_NAME
    ''', [tableId]);

  debugPrint('table id is $tableId');
  // print('result $result');

  //print('decryptedData $decryptedData');

  await db.close();

  return result;
}

**Error :**
Unexpected error occurred while adding addColumnSugesstionRelatedPrompts SqfliteFfiException(sqlite_error: 21, , SqliteException(21): while preparing statement, bad parameter or other API misuse, bad parameter or other API misuse (code 21)
  Causing statement:       SELECT "COLUMN_NAME",
             "COLUMN_TYPE",
             "PRECISION",
             "NULL_ALLOWED_FLAG",
             "DESCRIPTION"
        FROM XXC_COLUMNS 
       WHERE TABLE_ID =?
    ORDER BY COLUMN_NAME
    }) DatabaseException(SqliteException(21): while preparing statement, bad parameter or other API misuse, bad parameter or other API misuse (code 21)
  Causing statement:       SELECT "COLUMN_NAME",
             "COLUMN_TYPE",
             "PRECISION",
             "NULL_ALLOWED_FLAG",
             "DESCRIPTION"
        FROM XX_COLUMNS 
       WHERE TABLE_ID =?
    ORDER BY COLUMN_NAME
    ) sql '      SELECT "COLUMN_NAME",
             "COLUMN_TYPE",
             "PRECISION",
             "NULL_ALLOWED_FLAG",
             "DESCRIPTION"
        FROM XX_COLUMNS 
       WHERE TABLE_ID =?
    ORDER BY COLUMN_NAME
    ' args [7287] {details: {database: {path: C:\Users\SR\AppData\Roaming\SX\sql\data\database_browser\fnd_columns.db, id: 6, readOnly: false, singleInstance: true}}} at #0      responseToResultOrThrow (package:sqflite_common_ffi/src/method_call.dart:125:9)
#1      SqfliteIsolate.handle (package:sqflite_common_ffi/src/isolate.dart:35:12)

**Comment by nilkanthp-interpay** [comment]
I also face same 
I try to run build in windows in debug mode then it's showing sqlite_error:21

when build app and install in windows it's working fine

`SqfliteFfiException(sqlite_error: 21, , SqliteException(21): while preparing statement, bad parameter or other API misuse, bad parameter or other API misuse (code 21)`

@alextekartik can you please let me know why this happened or guide me how to fixed this

Thanks

**Comment by alextekartik** [comment]
@nilkanthp-interpay You can add more logs to find out which query is failing as I cannot analyse much with this info. You can use the experimental logger: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#try-the-experimental-logger and and some code of what your doing.

@Srimathi622 Code without code block (triple ticks) is hard to read, can you improve the formatting of your issue? Dealing with multiple isolate is not something I'm really confident with. Since sqlite itself runs in a seperate isolate, I would recommend doing your insert in the main isolate if that is possible.

**Comment by Srimathi622** [comment]
Since it's a large insertion, I need to handle it in a separate isolate. The issues arise only when I query the records with a parameter in the main thread immediately after the isolated insertion completes. Queries without parameters work fine. Does this additional detail help in identifying any potential cause?

**Comment by alextekartik** [comment]
@Srimathi622 Weird indeed. I notice that you open the database with `singleInstance = true` which could be the issue as closing the database in isolate will close it for both the instances. You can try with `singleInstance = false` in the isolate. See https://github.com/tekartik/sqflite/blob/master/sqflite/doc/usage_recommendations.md#isolates

**Comment by Srimathi622** [comment]
Thanks so much for pointing that out! @alextekartik Changing singleInstance to false in the isolate solved the issue perfectly, and I’m really happy!

**Comment by nilkanthp-interpay** [comment]
Thanks @alextekartik After changing **singleInstance** is **false** it's working.
