### ISSUE TITLE
Could not resolve all files for configuration ':sqflite_android:androidJdkImage'.

### ISSUE THREAD

**Issue by Wilfried02** [tekartik/sqflite#1141]
> Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\lenovo\AppData\Local\Android\sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\lenovo\.gradle\caches\transforms-3\4a46fc89ed5f9adfe3afebf74eb8bfeb\transformed\output\temp\jmod --add-modules java.base --output C:\Users\lenovo\.gradle\caches\transforms-3\4a46fc89ed5f9adfe3afebf74eb8bfeb\transformed\output\jdkImage --disable-plugin system-modules}
![image](https://github.com/user-attachments/assets/9a7ed0cf-07f5-49d0-895b-b5763e30bb96)

**Comment by alextekartik** [comment]
Do you have more info on how to reproduce the issue ? Does it happen if you try the example app here: https://github.com/tekartik/sqflite/tree/master/sqflite_android/example

**Comment by Moh541hhg** [comment]
im having the same issues, The moment i add the sqflite to the dependencies file, then i try to run the project it crashes , the problem is its happening even ith a brand new project.

here is the error:

FAILURE: Build failed with an exception.
* What went wrong:
```
Execution failed for task ':sqflite_android:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':sqflite_android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\hhh25\AppData\Local\Android\Sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\hhh25\.gradle\caches\8.8\transforms\428cdd4ac2909cc0d7a3a93021ebbb38-ebe3650e-b053-417c-a345-b502e216d9d9\transformed\output\temp\jmod --add-modules java.base --output C:\Users\hhh25\.gradle\caches\8.8\transforms\428cdd4ac2909cc0d7a3a93021ebbb38-ebe3650e-b053-417c-a345-b502e216d9d9\transformed\output\jdkImage --disable-plugin system-modules}
```

**Comment by alextekartik** [comment]
I cannot reproduce on a fresh project (flutter 3.5.4, Intellij on Ubuntu). It could be related to the jdk used. See similar issues here:
- https://github.com/flutter-stripe/flutter_stripe/issues/1951
- https://github.com/flutter/flutter/issues/156558

**Comment by ziedrebhi** [comment]
Same issue :
Jdk 23
Gradle 8.10

**Comment by alextekartik** [comment]
Ok I was able to reproduce on latest Android Studio. I'm on it

**Comment by alextekartik** [comment]
I found out the same happens using path_provider: https://github.com/flutter/flutter/issues/156558#issuecomment-2446956094

solution summary:

`gradle-wrapper.properties`:
```
# distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip
# Updated to 8.9
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip
```

`settings.gradle`:
```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    /// id "com.android.application" version "8.1.0" apply false
    /// Updated to 8.7.1
    id "com.android.application" version "8.7.1" apply false
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}
```

Notes added here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#could-not-resolve-all-files-for-configuration-sqflite_androidandroidjdkimage

**Comment by Moh541hhg** [comment]
I fixed it by:
downloading Java JDK 17 and then specifying the path with the following command: flutter config --jdk-dir 'C:\Program Files\Java\jdk-17'

im still not sure why newer jdk didnt work though, i tried 23 and 21 both of which produced the same issue
