### ISSUE TITLE
app crashes on databaseopen

### ISSUE THREAD

**Issue by skrizanovic** [tekartik/sqflite#118]
When I call openDatabase, on first install and load, everything works fine. But when I load the app again the second time (in the emulator) it immeditatly crashed when the opendatabase method is called.

#35 pc 00669538  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
#36 pc 0066b678  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
#37 pc 0001afa7  /system/lib/libutils.so (android::Looper::pollInner(int)+439)
#38 pc 0001b307  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+53)
#39 pc 0000b675  /system/lib/libandroid.so (ALooper_pollOnce+96)
#40 pc 0066b77b  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
#41 pc 00667d5e  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
#42 pc 00669e53  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
#43 pc 00080ab3  /system/lib/libc.so (__pthread_start(void*)+56)
#44 pc 00021952  /system/lib/libc.so (__start_thread+25)
#45 pc 000170b6  /system/lib/libc.so (__bionic_clone+70)
Tombstone written to: /data/tombstones/tombstone_01
Lost connection to device.
Exited (sigterm)

**Comment by alextekartik** [comment]
Thanks for the report. Hard to tell at this point without more information on how you use it. Do you have a simple project to share that reproduces the issue (and on which Emulator API version)?
