### ISSUE TITLE
Json1 extension

### ISSUE THREAD

**Issue by JssDWt** [tekartik/sqflite#119]
Is it possible to enable sqlite's json1 extension through sqflite somehow? I'm currently getting 'no such function: json_extract'. So I guess it is not implicitly enabled.

**Comment by alextekartik** [comment]
As far as I know: no
See my answer here: https://github.com/tekartik/sqflite/issues/70

**Comment by JssDWt** [comment]
Thanks for the quick reply. That would indeed be a lot of work.
