### ISSUE TITLE
flutter packages get busy wait

### ISSUE THREAD

**Issue by YASSERRMD** [tekartik/sqflite#12]
After adding
`dependencies:`
`  flutter:`
`      sdk: flutter`
`   sqflite: any`
flutter packages get busy wait and need to stop by deleting .lockfile in the flutter/bin
how can use this package in my project

**Comment by alextekartik** [comment]
Sorry you get into troubles. Which version of Flutter are you using? In my latest test, it works with
version Dart 1.25.0-dev.11.0
I use Intellij with plugin flutter 0.17 version
Also what happens if you remove sqflite depency? or if you try to upgrade the packages?

**Comment by YASSERRMD** [comment]
At last i found myself what is the issue,
Our ISP blocks the https://pub.dartlang.org
So i used another ISP from my mobile to connect and it is working fine

Thank you for your response

Note: I resolved by making dummy pubspec.yaml and tried to pub get the Resolve dependencies took so long then i found it is not getting any dependencies coz of not having access to this URL
