### ISSUE TITLE
WITH statement throwing syntax error

### ISSUE THREAD

**Issue by waltermaldonado** [tekartik/sqflite#120]
I am not being able to execute a recursive query with the WITH ... AS () command, is it expected? If not, how should I proceed?

**Comment by alextekartik** [comment]
I have not tried any statement with a WITH clause. sqflite itself does not parse the statement so it should not add (theoretically) any incompatibility on top of the existing SQLite implementation

Is it a statement that you have ever tried on SQLite? If yes, let me know how I can reproduce the issue to check on my side. If not, I recommend you to try the command line sqlite client to make more experiment and check the WITH documentation <https://www.sqlite.org/lang_with.html>

**Comment by waltermaldonado** [comment]
I've already tried with sqlite3. To be specific, I tried in the exact same version as the Android device and it worked. The command is below:

`WITH groups AS (
                  SELECT b.*, ROW_NUMBER() OVER (PARTITION BY breeding_season_id ORDER BY date DESC) AS rn
                  FROM bds b
                  where a_id = ?
                )
                SELECT bg.id,
                        bg.date, 
                        bg.b_season_id, 
                        bg.a_id,
                        bs.desc as b_season, 
                        s.desc as sm, 
                        a.id as b_id, 
                        a.code as a_code FROM groups bg
                    inner join b_seasons bs on bs.id = bg.b_season_id
                    left join sms s on bg.s_id = s.id
                    left join bths br on br.b_id = bg.id
                    left join a on a.bth_id = br.id
                where rn = 1`

**Comment by alextekartik** [comment]
Ok thanks. I assume you have tried with `rawQuery` with the proper number of parameters. I don't have your schema so will try tomorrow with another `with` statement. If you have more information (schema or database, detail of the error you get), let me know. Thanks for the report

**Comment by alextekartik** [comment]
I have tried a WITH query with success: https://github.com/tekartik/sqflite_more/blob/a4afb1002e9f89c3475a2a1155ef9a7d207b9702/sqflite_test/test/statement_test.dart#L17-L53

If i try your statement in sqlite3 command line tool, I do get a syntax error as well. Can you confirm the statement your provide works in sqlite3 command line tool and even better a list of command that works in sqlite3 and fails in sqflite. Thanks!

**Comment by waltermaldonado** [comment]
After some testing I found out the error lies on the part ... OVER (PARTITION BY... That's the parenthesis it is referring to in the exception.
