### ISSUE TITLE
Allow ignoring errors when running batch

### ISSUE THREAD

**Issue by alextekartik** [tekartik/sqflite#121]
(This follows a discussion I had on gitter with janniklind)
The need: "I create a batch with all update statements in a sync process and I actually want as many as possible to be added to the database even though one of them fails"

One solution is to try/catch around every command. One other solution:
"Possibility to commit a batch with the option to ignore errors, currently is fails on first error."
This solution would involve adding an extra `continueOnError` parameter when running the batch

**Comment by Steelsmasher** [comment]
I would really appreciate the second option.

At the minute I'm forced to make individual transactions for multiple updates to prevent errors stopping the whole process, which is a lot slower than simply batching them all at once.

**Comment by alextekartik** [comment]
Thanks for the note, it is always good to here the needs. As a side note, in the mean-time, you could have a single transaction and surround each insert/update/delete calls with try/catch to ignore failing commands. That should already greatly improves speed.

**Comment by alextekartik** [comment]
Hi @Steelsmasher I published a version `0.13.0-dev.1` (i.e. you have to force `>=0.13.0-dev.1` in your pubspec) that implements the `continueOnError` when commiting a batch. Since I don't have the need myself in my apps, I would appreciate to know if it fits your need.
