### ISSUE TITLE
Is it possible to interact with this db from ios or android native side  ?

### ISSUE THREAD

**Issue by eshiett1995** [tekartik/sqflite#123]
i am trying to perform platform specific code from the android and ios side and interact with the database...is this possible ?

**Comment by alextekartik** [comment]
Not sure if you're talking about native or dart code. On the dart side, indeed can do `if (Platform.isIOS)` or `if (Platform.isAndroid)` and implement a different behavior; but that is not really related to sqflite so maybe you meant something different...
