### ISSUE TITLE
SqfliteDatabaseException (DatabaseException(database_closed))

### ISSUE THREAD

**Issue by rajeshzmoke** [tekartik/sqflite#127]
Whenever i do a **Hot Restart** i get this exception

> wrapDatabaseException (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/sqflite-0.12.2+1/lib/src/exception.dart:125)
> <asynchronous gap> (Unknown Source:0)
> SqfliteDatabase.txnRawQuery.<anonymous closure> (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/sqflite-0.12.2+1/lib/src/database.dart:330)
> _Closure.call (dart:core/runtime/libfunction.dart:0)
> SqfliteDatabase.txnSynchronized.<anonymous closure> (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/sqflite-0.12.2+1/lib/src/database.dart:279)
> _Closure.call (dart:core/runtime/libfunction.dart:0)
> Lock._runTask (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/synchronized-1.5.3/lib/src/synchronized_impl.dart:149)
> LockBase._createAndRunTask.run (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/synchronized-1.5.3/lib/src/synchronized_impl.dart:64)
> _Closure.call (dart:core/runtime/libfunction.dart:0)
> LockBase._createAndRunTask (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/synchronized-1.5.3/lib/src/synchronized_impl.dart:74)
> Lock.synchronized (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/synchronized-1.5.3/lib/src/synchronized_impl.dart:142)
> SqfliteDatabase.txnSynchronized (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/sqflite-0.12.2+1/lib/src/database.dart:275)
> <asynchronous gap> (Unknown Source:0)
> SqfliteDatabase.txnRawQuery (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/sqflite-0.12.2+1/lib/src/database.dart:329)
> SqfliteDatabaseExecutor.rawQuery (/Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/sqflite-0.12.2+1/lib/src/database.dart:92)
> ChatDatabase.fetchChat (/Users/rajeshkumar/Desktop/flutter_splash/lib/database/database.dart:117)
> <asynchronous gap> (Unknown Source:0)
> _ChatScreenState.getDatabaseMessages (/Users/rajeshkumar/Desktop/flutter_splash/lib/screens/chat_screen.dart:745)
> <asynchronous gap> (Unknown Source:0)
> _ChatScreenState.onlineService (/Users/rajeshkumar/Desktop/flutter_splash/lib/screens/chat_screen.dart:203)
> _ChatScreenState.initConnectivity (/Users/rajeshkumar/Desktop/flutter_splash/lib/screens/chat_screen.dart:269)
> <asynchronous gap> (Unknown Source:0)
> _ChatScreenState.initState (/Users/rajeshkumar/Desktop/flutter_splash/lib/screens/chat_screen.dart:112)
> StatefulElement._firstBuild (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/widgets/framework.dart:3830)
> ComponentElement.mount (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/widgets/framework.dart:3696)
> Element.inflateWidget (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/widgets/framework.dart:2950)
> Element.updateChild (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/widgets/framework.dart:2753)
> ComponentElement.performRebuild (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/widgets/framework.dart:3732)
> Element.rebuild (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/widgets/framework.dart:3547)
> BuildOwner.buildScope (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/widgets/framework.dart:2286)
> _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart:676)
> _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/rendering/binding.dart:219)
> _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/rendering/binding.dart:0)
> _Closure.call (dart:core/runtime/libfunction.dart:0)
> _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/scheduler/binding.dart:990)
> _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/scheduler/binding.dart:930)
> _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/scheduler/binding.dart:842)
> _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (/Users/rajeshkumar/Desktop/flutter/packages/flutter/lib/src/scheduler/binding.dart:0)
> _invoke (dart:ui/hooks.dart:154)
> _drawFrame (dart:ui/hooks.dart:143)

My database class

````
import 'package:flutter_splash/chat_message/chat_message.dart';
import 'package:flutter_splash/model/chatHistoryModel.dart';
import 'package:flutter_splash/model/profileDataModel.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';
import 'package:synchronized/synchronized.dart';

import 'dart:async';
import 'dart:io';

class ChatDatabase {
  static final ChatDatabase _instance = ChatDatabase.internal();
  factory ChatDatabase() => _instance;

  static Database _db;
  final _lock = new Lock();

  Future<Database> get db async {
    if (_db == null) {
      await _lock.synchronized(() async {
        if (_db == null) {
          _db = await initDB();
        }
      });
    }
    return _db;
  }

  ChatDatabase.internal();

  Future<Database> initDB() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, 'chat.db');
    var thDB = await openDatabase(path, version: 1, onCreate: _create);
    return thDB;
  }

  void _create(Database db, int version) async {
    var sql1 = '''CREATE TABLE Chat(
         id INTEGER PRIMARY KEY NOT NULL,
         message TEXT,
         timestamp NUMERIC,
         email STRING,
         bot BOOLEAN
         )''';
    var sql2 = '''CREATE TABLE User(
         id INTEGER PRIMARY KEY NOT NULL,
         userName TEXT,
         email TEXT,
         gender TEXT,
         birthDateAndTime NUMERIC,
         latitude NUMERIC,
         longitude NUMERIC,
         offset NUMERIC,
         pob TEXT,
         profilePic STRING
         )''';
    var sql3 = '''CREATE TABLE Charms(
         id INTEGER PRIMARY KEY NOT NULL,
         luckyNumber TEXT,
         luckyDirection TEXT,
         luckyGem TEXT,
         luckyDays STRING,
         luckyColors STRING
         )''';

    await db.execute(sql1);
    print("Table Chat was Created!");
    await db.execute(sql2);
    print("Table User was Created!");
    await db.execute(sql3);
    print("Table Charms was Created!");
  }

  addUser(ProfileData profileData) async {
    print(profileData);
    var dbClient = await db;
    int res = await dbClient.insert("User", profileData.toJson());
    print('User profile added $res');
    printUser();
    // return res;
  }

  Future fetchUser(String email) async {
    var dbClient = await db;
    var res = await dbClient.rawQuery(
        'SELECT * FROM User WHERE email = ?', ['$email']); //fetch with email
    print('user profile $res');
    return res;
  }

  Future<int> addChatHistory(ChatHistory chat) async {
    var dbClient = await db;
    int res = await dbClient.insert("Chat", chat.toMap());
    // print('ChatHistory updated $res');
    // printChatRows();
    return res;
  }

  Future<int> deleteUser() async {
    var dbClient = await db;
    int res = await dbClient.delete("User");
    print('User profile deleted $res');
    return res;
  }

  Future<int> deleteChat() async {
    var dbClient = await db;
    int res = await dbClient.delete("Chat");
    print('Chat Table deleted $res');
    return res;
  }

  Future fetchChat() async {
    var dbClient = await db;
    var res = await dbClient.rawQuery('SELECT * FROM Chat');
    return res;
  }

  Future getChat() async {
    var dbClient = await db;
    List<Map> res = await dbClient.rawQuery('SELECT * FROM Chat');

    return res;
  }

  Future<List<ChatMessage>> fetchChatFromDatabase() async {
    List<Map> chatMessagesDB = await getChat();
    List<ChatMessage> chatmessage = List();

    for (int i = 0; i < chatMessagesDB.length; i++) {
      ChatMessage message = ChatMessage(
        user: chatMessagesDB[i]['bot'] == 1 ? true : false,
        text: chatMessagesDB[i]['message'],
      );

      chatmessage.insert(0, message);
    }

    return chatmessage;
  }

  printUser() async {
    var dbClient = await db;
    var res = await dbClient.rawQuery('SELECT * FROM User');
    print('User prof res $res');
  }

  printChatRows() async {
    var dbClient = await db;
    var res = await dbClient.rawQuery('SELECT * FROM Chat');
    print("Chat res $res");
  }

  Future closeDb() async {
    var dbClient = await db;
    dbClient.close();
  }
}
`
```

**Comment by alextekartik** [comment]
Thanks for the report. Good if you can format your code a little better.
Hard to debug without the full app. According to your report the database is closed. In general I recommend to keep the database open and never close it. Can you try to remove you `closeDb` method (or make sure/confirm nothing is calling it)?

**Comment by rajeshzmoke** [comment]
even after removing it, i still get the same error

**Comment by alextekartik** [comment]
Nothing looks wrong to me so I'm not sure how I can help. If you could make a small app that reproduces the issue that you could share, that would be the best, but I know that is not always feasible.

**Comment by TurkiWalid** [comment]
I have the same problem with almost the same code, does anyone found a solution ?

**Comment by alextekartik** [comment]
Which version are you using? Hot-restart behavior should be better in the latest version (1.1.5) for singleInstance databases. I personnally also close the databases (WillPopScope) when exiting the app (for Android) to handle potential transaction issues when the database was closed. But I might have missed some scenarios.

**Comment by TurkiWalid** [comment]
As version i just put any to fit with cached_image_network pub, Exception happent when i use cached_image network asynchronously with retreiving data from the sqflite mostly on hot-restart

**Comment by alextekartik** [comment]
Can you try with ```sqflite: "^1.1.5"``` dependencies to see if it improves things? thanks
