### ISSUE TITLE
Is a Room like API possible?

### ISSUE THREAD

**Issue by LouisCAD** [tekartik/sqflite#13]
Hi,

[Room](https://developer.android.com/topic/libraries/architecture/room.html) provides a really nice API to use SQLite on Android. Since iOS also supports SQLite, is there a way to bring an API similar to Room in this library for Flutter?

**Comment by alextekartik** [comment]
`sqflite` provides a raw SQL API and a lightweight API similar to ContentProvider on Android. The main benefit is that it provides an API with the same behavior on iOS and Android.

Room is based on Java reflection so I guess something similar could be built on top of sqflite, maybe using Annotation and `source_gen`. I'd rather keep sqfilte lightweight and not provide a feature for those who only need raw sqlite access (that was my original need). One package = one feature

Having something like Room could definitely be a good idea. It is a big amount of work that could live in a separate package and take benefit of the sqlite API provided by sqflite.

**Comment by alextekartik** [comment]
I'm closing the issue as a room like API won't be part of this library but could be built on top of it
