### ISSUE TITLE
how to rollback the transaction？

### ISSUE THREAD

**Issue by Xantolee** [tekartik/sqflite#136]
Sorry, I can not find any function to rollback in a transaction. Could you tell me how to implement this？

**Comment by alextekartik** [comment]
I would say that it is always better to avoid it if you can, although I have no argument for that. In general I tend to avoid this case.

A transaction is committed if the callback does not throw an error. If an error is thrown, the transaction is cancelled. So to rollback a transaction one way is to throw an exception.

**Comment by Xantolee** [comment]
Thanks for you reply.
