### ISSUE TITLE
Version number not clear

### ISSUE THREAD

**Issue by suragch** [tekartik/sqflite#138]
Rather than using `any` for they version number, I would feel better about using it if the documentation used the current version. 

```
dependencies:
  ...
  sqflite: ^0.13.0+1
```

I assume this plugin uses [semantic versioning](https://semver.org/). Since this plugin is being heavily used, it would also be good to start versioning it with 1.0.0.

**Comment by alextekartik** [comment]
Yes I should update the documentation for each release. However the installing tab in pub already specify it the correct way: <https://pub.dartlang.org/packages/sqflite#-installing-tab->

Yes I guess it could become 1.0.0. Many flutter official plusing are not 1.0.0 yet too though.
One of my main concern before jumping to 1.0.0 is whether I should use `Map<String, dynamic>` vs `Map<String, Object>` everywhere which could be a painful breaking change. I remember reading a post from a google enginneer about that but I have seen clear statement which one should be used.

I personally try to avoid upper bound dependencies which for the sake of ensuring compatibility, many times enforce using `dependency_overrides` if one of any component was not updated.

**Comment by suragch** [comment]
I see. I guess using the 0.x.x versioning communicates that you feel that the plugin is still in beta and that breaking changes are likely. I can understand that, though I hope to see it out of beta in the near future.

I didn't really understand your comment about [`dependency_overrides`](https://www.dartlang.org/tools/pub/dependencies#dependency-overrides).

**Comment by suragch** [comment]
Thanks a lot! I actually didn't expect you to listen to me. I'm a little new to interacting with other people's repositories.

And I wouldn't worry to much about the  `Map<String, dynamic>` vs `Map<String, Object>` change. If the time comes that you feel you need to make that change, then just increment the major version number to 2.0.0. A major version number increment is by definition a breaking change so you aren't going to surprise anyone (except for the people who are still using `any`). The `^` caret notation will keep it from breaking anyone's current projects and developers can decide to update when they are ready.
