### ISSUE TITLE
Could not load source 'dart:core/runtime/libobject_patch.dart': <source not available>. When call execute()

### ISSUE THREAD

**Issue by TercyoStorck** [tekartik/sqflite#143]
I got an issue that says "Could not load source 'dart:core/runtime/libobject_patch.dart': <source not available>." when I call Database.execute(query); and the app suddenly freezes.

**Comment by alextekartik** [comment]
Hard to say without much context (iOS?, Android?), device OS version and model, flutter sdk, sqflite version.. Does the example application crashes also on your device?
