### ISSUE TITLE
A little help on understanding the code

### ISSUE THREAD

**Issue by michaelhoeller** [tekartik/sqflite#148]
Dear Mr. tekartik ,

I am currently trying to learn Dart/Flutter with the help of this project, since it seems to be a good example on how to reuse widgets and of course a database.

The thing I still don't understand is the following methode:
```
  void _onTap() {
    widget.onTap(widget.item);
  }
```
in the ItemWidget class. As far as I understand it, the ItemWidgets field 'onTap' is set  to (Item item) in the _itemBuilder.

```
Widget _itemBuilder(BuildContext context, int index) {
    Item item = getItem(index);
    return ItemWidget(item, (Item item) {
```

This is exactly the point I can't get my head around. A new Item  is set as the onTap function in the ItemWidget but doesn't have anything remotly simmilar to a function itself.

During my debug-endeavours  I stumbled upon this:

onTap = {_Closure} Closure: (Item) => Null //See bottom right of the attached screenshot.

![2019-01-17 11_24_14-](https://user-images.githubusercontent.com/34237008/51311970-79825f00-1a4a-11e9-9436-8063254f4832.png)

The big question: How does this sorcery work? (In the sense that the item-object becomes a function that does reload itself and executes it's related test on tap).

If you could spare some time and point me in the right direction I would be very thankful. :)
Kind regards

Michi

Edit: I finally got it and realized im stupid ^^

**Comment by alextekartik** [comment]
Hi, not sure i'm the best person to help. This project is about sqflite. For generic Flutter usage and question, you could consider using StackOverflow instead of a github issue
