### ISSUE TITLE
replace into

### ISSUE THREAD

**Issue by fsobanski** [tekartik/sqflite#155]
Does this plugin support sqlite `REPLACE INTO` statements?

**Comment by Gorbas** [comment]
It would be grate if you could add a "replace" function that performs REPLACE INTO in a similar way as "insert" function

**Comment by alextekartik** [comment]
Sorry it seems I missed this issue. I have not used this command but as far as I know, REPLACE INTO is just an alias for INSERT OR REPLACE (<https://www.sqlite.org/lang_replace.html>)

So you should be able to do it this way

```dart
await db.insert(table, map, conflictAlgorithm: ConflictAlgorithm.replace);
```

**Comment by fsobanski** [comment]
Thanks for your suggestion. I will try it out on the weekend and update you if it worked, afterwards.

**Comment by fsobanski** [comment]
Seems to work.
