### ISSUE TITLE
allow sqflite to run in console app

### ISSUE THREAD

**Issue by freemant2000** [tekartik/sqflite#160]
it's a pity that we can't run sqflite in standalone unit tests because it is currently dependent on some flutter platform services. It would be great if it is decoupled. That will make testing much easier.

**Comment by alextekartik** [comment]
I could not agree more! That's actually the case for any flutter plugin where there is no easy io implementation. You can follow this thread https://github.com/tekartik/sqflite/issues/83 for some test utilities suggestion.

**Comment by alextekartik** [comment]
sqflite_common_ffi v1.0.0 has been published allowing using ffi on the desktop. It is based on moor_ffi (!) that provides a nice wrapper around sqlite libraries. It has no dependency on flutter
