### ISSUE TITLE
NULL SQL values are returned as empty Strings 

### ISSUE THREAD

**Issue by dev-horacebg** [tekartik/sqflite#163]
When using an asset database with tables created with the following script, values that have been specified as `null` in the database are returned as an empty `String` `""`.

```
CREATE TABLE "bands" ( `year` INTEGER, `percentage` NUMERIC, `start` NUMERIC, `end` NUMERIC)
```

I update one of the values to `null` using the following command and view it in [DB Browser for SQLite](https://sqlitebrowser.org/)

```
UPDATE `bands` SET `end`=? WHERE _rowid_='6';
```
This works and the changes I expect to see are made to the table and the value is now `null`.

![image](https://user-images.githubusercontent.com/40957572/52849770-be60ea80-3109-11e9-9387-67e57376a580.png)

The issue appears to be when trying to get the value out of the `map` provided by calling `client.query(…queryParams)` where the null value is stored as an empty `String ("")` even when specified as `NUMERIC` in the database creation script. I've also noticed that non `null` numbers are all stored as integers regardless of the type used to create them when making the database (even when created as a `String`!).

**Comment by alextekartik** [comment]
Thansk for the report. Are you on Android or iOS?
I know that NUMERIC is not a real type in SQLite <https://www.sqlite.org/datatype3.html>

> A column with NUMERIC affinity may contain values using all five storage classes. When text data is inserted into a NUMERIC column, the storage class of the text is converted to INTEGER or REAL (in order of preference) if such conversion is lossless and reversible. For conversions between TEXT and REAL storage classes, SQLite considers the conversion to be lossless and reversible if the first 15 significant decimal digits of the number are preserved. If the lossless conversion of TEXT to INTEGER or REAL is not possible then the value is stored using the TEXT storage class. No attempt is made to convert NULL or BLOB values.

I will do some testing on my side but in the mean time, I would suggest using only the following types:
* TEXT
* INTEGER
* REAL
* BLOB

so likely REAL in your case. Does it happen when using REAL?

**Comment by dev-horacebg** [comment]
Hi, should have specified initially - iOS.

The same happens when I use a REAL - value comes back as an int.

**Comment by alextekartik** [comment]
Ok good. According to SQLite it seems that REAL might be stored but this should be transparent.

> A column with REAL affinity behaves like a column with NUMERIC affinity except that it forces integer values into floating point representation. (As an internal optimization, **small floating point values with no fractional component and stored in columns with REAL affinity are written to disk as integers** in order to take up less space and are automatically converted back into floating point as the value is read out. This optimization is completely invisible at the SQL level and can only be detected by examining the raw bits of the database file.)

I'll try to add some notes about NUMERIC vs REAL in the documentation

**Comment by dev-horacebg** [comment]
Perfect, thanks. Not sure whether or not I should have closed the bug as it was mainly about `null`

**Comment by alextekartik** [comment]
Not a problem, keeping it open will keep on reminding me doing tests on NUMERIC. Ideally NUMERIC should map to `num`. As a side note, I sometimes handle on the application side any bad format (i.e. doing `is num` and `num.tryParse` if it is a String)

**Comment by alextekartik** [comment]
I made some tests using the NUMERIC type and did not notice any issue. Unless you explicitely put a string (that cannot be parsed as a number, so it includes the empty string), you should get values as num (int or double). null are stored as null.

**Comment by dev-horacebg** [comment]
Yes, this is consistent with my latest testing. Thanks for following up.

**Comment by mertkokusen** [comment]
Hi, I read the comments but didn't see any solution for "nulls being returned as an empty string". Currently we are experiencing the same problem.

**Comment by alextekartik** [comment]
@mertkokusen Do you have a way to reproduce the problem or some explanation when it happens (table schema, insertion done, usage of temp table or views, iOS/Android), thanks.

**Comment by mertkokusen** [comment]
It turned out to be our mistake, sorry for taking your time.

**Comment by michael-spf** [comment]
Maybe this thread is out of date, but I think the problem with the empty string for NULL values still exists.
I have a table with a REAL column (named PRICE). Some records contain NULL values.

With this query I would expect that I only get records with values greater than 60:
`IFNULL(price, 0) > 60.0`

But I get NULL values also.

This query gives the expected results:
`IFNULL(price, 0) > 60.0 AND price != ''`

(Android)
