### ISSUE TITLE
Help on Catching DatabaseException

### ISSUE THREAD

**Issue by danbarejr** [tekartik/sqflite#17]
I've been unsuccessful at catching a sqflite SQL error that thows a DatabaseException.

For example, this code:

```
Future<String> getData() async {
Directory documentsDirectory = await getApplicationDocumentsDirectory();
String path = join(documentsDirectory.path, globals.databaseName);
Database db = await openDatabase(path);
List results = await db.rawQuery("mal formed sql on purpose");
}
```

throws the following error.. The console shows:

`E/SQLiteLog( 7908): (1) near "mal": syntax error`

What I want to do is be able to catch SQL errors and handle them.

I did try this:

```
try {
  List results = await db.rawQuery("mal formed sql on purpose");
} catch (e) {
  print(e);
}
```
but it results in the same error.

`E/SQLiteLog( 3148): (1) near "mal": syntax error`

And I've tried **.then** and **.catchError** - but not getting that to work either.

Thanks in advance for the help!

**Comment by alextekartik** [comment]
Thanks for reporting. I'll take a look as indeed there should be an exception to catch here. For my information, was it on Android or iOS (or both)?

**Comment by danbarejr** [comment]
Android.

**Comment by alextekartik** [comment]
I could not reproduce the issue. See my test here: https://github.com/tekartik/sqflite/blob/master/example/lib/exception_test_page.dart#L89-L94

If you don't get an exception, what is the returned value you get in 'results'. However I remember having similar issue, I updated the package (3.0.1) to use gradle 4.1, however that is a breaking change as you might have to update your gradle file. Can you tell me (print is fine) what happened before, after, in the catch (print("exception $e"))

**Comment by danbarejr** [comment]
Upgraded the project to gradle 4.1... and it's now working.  Thanks!!

**Comment by mado-bohsali** [comment]
Any updates?
