### ISSUE TITLE
onUpgrade always getting called

### ISSUE THREAD

**Issue by dark-chocolate** [tekartik/sqflite#170]
I wanna upgrade my database but whenever I use
```
Database database = await openDatabase(path, version: versionCode, onCreate: _onCreate, onUpgrade: _onUpgrade);
```
my `_onUpgrade()` method gets called. It should be called just once when `newVersion` is greater than `oldVersion`. So, what should I do in `_onUpgrade()` method so that my `newVersion` gets saved there and next time I try to open database, neither `_onCreate()` nor `_onUpgrade()` gets called.

**Comment by dark-chocolate** [comment]
I didn't notice there is `setVersion()`. Here we go:
``` 
   database.setVersion(newVersion);
```

**Comment by alextekartik** [comment]
To note that you should not need to call setVersion. It is automatically called after onUpgrade. As you stated onCreate and onUpgrade should be called only once so actually I'm interested in the behavior you are seeing

**Comment by dark-chocolate** [comment]
I'm sorry @alextekartik , actually in `onUpgrade()` my app was crashing in one of the cases, which is why onUpgrade wasn't able to run successfully and I thought it was not saving new version code, but once I remove the crash, I don't have to use `setVersion()` explicitly anymore. 

I appreciate your work.
