### ISSUE TITLE
rawQuery hangs when null is supplied as a field value

### ISSUE THREAD

**Issue by jasonlewicki** [tekartik/sqflite#173]
How is one supposed to go about setting a field to NULL?

```dart
    await Sqflite.setDebugModeOn();
    Map accountMap = account.toMap();
    print(accountMap);
    await _db.rawQuery("""
      INSERT OR REPLACE INTO  account (id, email_address, username)
      VALUES                  (?,?,?) """,
      [accountMap["id"], accountMap["email_address"], accountMap["username"]]);

    print("this is never reached");
```

`print(accountMap);` evaluates to:
```json
{
        "id": 1, 
        "email_address": "test+admin@example.com", 
        "username": null,
}
```

Create table code:
```dart
await db.execute(
      "CREATE TABLE account (id INTEGER PRIMARY KEY, email_address TEXT, username TEXT)");
```

**Comment by alextekartik** [comment]
It looks correct (if your are not in a transaction). You can set a null value (if your database schema allows it - can you share it?). Maybe an exception is thrown (check the raw logs, or try to catch any exception)

**Comment by jasonlewicki** [comment]
This is all I'm doing to initialize the database. the table's create code is above ^
```dart
_database = await openDatabase(path, version: 1, onCreate: _onCreate, onUpgrade: _onUpgrade);
```
You're right about the try/catch. It caught an error:
```
DatabaseException(the bind value at index 2 is null) sql '      INSERT OR REPLACE INTO  account (id, email_address, username)
I/flutter (32227):       VALUES                  (?,?,?) ' args [1, test+admin@example.com, null]}   
```

**Comment by alextekartik** [comment]
Yeap I forget you cannot bind NULL value (you might wonder why but the root cause is that null are used differently in values and where clause and sqflite does not parse SQL ans SQLite does not support binding null values). You have to explicitely put NULL in the raw SQL:

https://github.com/tekartik/sqflite/blob/94b1d8509554cedac7a3ef68de91c259bb134c09/sqflite/test/sql_builder_test.dart#L55-L57

**Comment by jasonlewicki** [comment]
bummer. thanks
