### ISSUE TITLE
Using databaseExists with asset db?

### ISSUE THREAD

**Issue by hgl** [tekartik/sqflite#180]
I wonder why the doc recommends opening the db to test if it exists, why not use databaseExists?

Also, it seems databaseExists only exists in the factory, wonder why it's not exported as a function?

**Comment by alextekartik** [comment]
Good point. I'll look at it.

**Comment by hhtokpinar** [comment]
Yes, i solved this..
Look at https://github.com/hhtokpinar/sqfEntity

**Comment by hhtokpinar** [comment]
> I wonder why the doc recommends opening the db to test if it exists, why not use databaseExists?
> 
> Also, it seems databaseExists only exists in the factory, wonder why it's not exported as a function?

Yes, i solved this..
Please look at https://github.com/hhtokpinar/sqfEntity

**Comment by hgl** [comment]
@hhtokpinar Thanks a lot. No offense,  but this seems way overkill. I just need to check if the db file exists.

**Comment by alextekartik** [comment]
@hgl I published 1.1.5-dev.1 that exports databaseExists as top level function. That should be the function to use indeed to test if a database exists

**Comment by hhtokpinar** [comment]
> @hhtokpinar Thanks a lot. No offense, but this seems way overkill. I just need to check if the db file exists.

no problem. I also thought it might be useful if you want to use ORM.
