### ISSUE TITLE
How to properly open preloaded db file with Sqflite?

### ISSUE THREAD

**Issue by bremington** [tekartik/sqflite#181]
Hi, I have successfully loaded a preloaded db file with 3 tables, and had initialized this with a procedure using the Bloc pattern I found online. Since it takes a few seconds to initially load the file, I need to initilize the database for the first time while the users are going through onboarding pages. I have tried many variations of your instructions on Opening the DB during the intro screens, but cannot get it to work. Here is my model:

class Finance {
  int id, value, future, year, flag;
  String icon, name, cat;

  Finance({
    this.id,
    this.year,
    this.name,
    this.cat,
    this.value,
    this.future,
    this.icon,
    this.flag});

  Finance.update({this.id,
    this.year,
    this.name,
    this.cat,
    this.value,
    this.future,
    this.icon,
    this.flag
  });

  Finance.fromMap(Map<String, dynamic> map) {
    id = map[id];
    year = map[year];
    name = map[name];
    cat = map[cat];
    value = map[value];
    future = map[future];
    icon = map[icon];
    flag = map[flag];
  }

  Finance.fromMapValue(Map<String, dynamic> map) {
    future = map[future];
  }

  Map<String, dynamic> toMap() {
    var map = Map<String, dynamic>();
    map['id'] = id;
    map['year'] = year;
    map['name'] = name;
    map['cat'] = cat;
    map['value'] = value;
    map['future'] = future;
    map['icon'] = icon;
    map['flag'] = flag;
    return map;
  }
}

Here is my App DB to load the DB file

import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path_provider/path_provider.dart';

/// This is the singleton database class which handlers all database transactions
/// All the task raw queries is handle here and return a Future<T> with result
class AppDatabase {
  static final AppDatabase _appDatabase = AppDatabase._internal();

  //private internal constructor to make it singleton
  AppDatabase._internal();

  Database _database;

  static AppDatabase get() {
    return _appDatabase;
  }

  bool didInit = false;

  /// Use this method to access the database which will provide you future of [Database],
  /// because initialization of the database (it has to go through the method channel)
  Future<Database> getDb() async {
    if (!didInit) await _init();
    return _database;
  }

  Future _init() async {

    // Get a location using path_provider
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, "finance.db");
    ByteData data = await rootBundle.load(join("assets", "seed.db"));
    List<int> bytes =
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    await new File(path).writeAsBytes(bytes);
    print("loaded seed.db");
    print(path);
    _database = await openDatabase(path, readOnly: false);
    print ("opened DB");
    didInit = true;
  }

}

Here is the model for one of the tables within the Database

import 'package:seed/db/app_db.dart';
import 'package:seed/models/datamodel.dart';
import 'package:sqflite/sqflite.dart';

class FinanceDB {
  static final FinanceDB _financeDB = FinanceDB._internal(AppDatabase.get());

  AppDatabase _appDatabase;

  //private internal constructor to make it singleton
  FinanceDB._internal(this._appDatabase);

  static FinanceDB get() {
    return _financeDB;
  }

  updateFinanceValue(int id, int value) async {
    // Get a reference to the database
    var db = await _appDatabase.getDb();
    await db.transaction((Transaction txn) async {
      await txn.rawUpdate(
          "UPDATE Finance SET value = $value WHERE id = $id");
    });
  }

  Future<Finance> getFinanceByID(int id) async {
    var db = await _appDatabase.getDb();
    var res = await db.query("Finance", where: "id = ?", whereArgs: [id]);
    return res.isNotEmpty ? Finance.fromMap(res.first) : null;
  }
}

Here is my repository

import 'package:flutter/widgets.dart';
import 'package:seed/db/finance_db.dart';
import 'package:seed/models/datamodel.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

class FinanceBloc extends StatesRebuilder {

  FinanceDB _financeDB;
  List<Finance> financeList;
  int id;
  Finance item;
  

  loadFinances(State state) async {
    financeList = await _financeDB.getAll();
    rebuildStates(states : [state]);
  }

  loadValueById(State state, int id) async {
   await  _financeDB.getFinanceByID(id);
   rebuildStates(states : [state]);
  }

  loadValueByName(State state, String name) async {
    await  _financeDB.getByName(name);
    rebuildStates(states : [state]);
  }
  void updateValue(State state, int id, int value) {
    _financeDB.updateFinanceValue(id, value);
    rebuildStates(states : [state]);
  }

}

FinanceBloc financeBloc = FinanceBloc();

This is what I was trying to use in my intro page

startDB() async {
    AppDatabase _appDatabase;
    var db = await _appDatabase.getDb();
    print(db.isOpen);
  }

  @override
  void initState() {
    startDB();
    super.initState();
  }

Any help would be appreciated!

**Comment by hhtokpinar** [comment]
try this Flutter/Dart ORM and Class Generator for manage your database model (many of tables, add new columns to an exiting table and CRUD operations .. etc) and more easily and quickly with the help of fluent methods. go to: https://github.com/hhtokpinar/sqfEntity

**Comment by bremington** [comment]
Hi, This program is amazing, but I am not sure I can use this. I have over 4000 prebuilt records to load, and as there is no easy way to preload a DB instead of your methods to create tables. If I go your route and create the tables, I cannot use the addProducts (to add the 4000 records) because the Model is not already built prior to the initial run. So I cannot create this function until the Model is built.

**Comment by hhtokpinar** [comment]
Hi, Do you create your tables for each user-specific in runtime?
you can't do already that create and use an unbuilt classes in runtime.
If your tables are standard, then you create and compile the classes of your tables at a time, so tables (not models/classes) are created automatically in the first installation and ready to add records

**Comment by bremington** [comment]
I have created an sql database, with tables (4) and 4000 records. The bundle is then copied (per Sqflite documentation). It is done just once. 

So I was looking to use your methodology, but add to the initializeDB to copy over the existing file 

 Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, "finance.db");
    ByteData data = await rootBundle.load(join("assets", "seed.db"));
    List<int> bytes =
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    await new File(path).writeAsBytes(bytes);

This file would match the model I updated in MyDbModel, including the added field for 'isDeleted'

**Comment by hhtokpinar** [comment]
if there is different connection method for existing database connection, I can solve this problem  if you share with me your sample db together with the method.

**Comment by bremington** [comment]
I have the bundled file loading now and initialized...and I set a bool at the end of my on boarding slides (seen).  This was my main issue. Now I will look to use your code, and overwrite the file your program creates.


void main() {
  SharedPreferences.getInstance().then((prefs) {
    runApp(MyApp(prefs: prefs));
    getDb();
  });
}


Database _database;

Future<Database> getDb() async {
  SharedPreferences prefs = await SharedPreferences.getInstance();
  bool seen = (prefs.getBool('seen') ?? false);
  if (!seen) {
    return await _init();
  } else {
    return _database;
  }
}

Future _init() async {
  // Get a location using path_provider
  Directory documentsDirectory = await getApplicationDocumentsDirectory();
  String path = join(documentsDirectory.path, "finance.db");
// delete existing if any
await deleteDatabase(path);
  ByteData data = await rootBundle.load(join("assets", "seed.db"));
  List<int> bytes =
  data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  await new File(path).writeAsBytes(bytes);
  print("loaded seed.db");
  print(path);
  _database = await openDatabase(path, readOnly: false);
  print("opened DB");

}

**Comment by hhtokpinar** [comment]
Ok. I solved this.
get full package for testing.

I have added a new const for asset path into MyDbModel 
     `static const String bundledDatabasePath = "assets/sample.db";`
if this const is not empty then copy database from asset when initializing db and then start immediately sql queries.. good luck..

**Comment by bremington** [comment]
Wow, this is fantastic.

**Comment by hhtokpinar** [comment]
Hi, i changed architecture a bit and added multiple database support
You may get clone again and test it
