### ISSUE TITLE
Support to prevent cloud backup

### ISSUE THREAD

**Issue by kmusham** [tekartik/sqflite#193]
I’m using sqlite flutter libraries for the database storage. 
Do you have a way to prevent OS taking the database backup? 

One of our clients reported that he was using same Apple ID on two different iOS devices and one of the devices has got a restored data from the cloud backup. Unfortunately that backup was old and messed up lot of other things.

So, if you have a flag that prevents from system backup would help a lot. 
Please let me know if you have any plans to implement.

**Comment by alextekartik** [comment]
(sorry i missed this issue). I'm not aware of such flag. A database is just a regular file so sqflite cannot do much here.
