### ISSUE TITLE
After copying Map from query still getting error changing Map value (#140).

### ISSUE THREAD

**Issue by brianoh** [tekartik/sqflite#195]
Hi Alex,

Thanks for providing sqflite which is obviously very necessary for developers.

Running on Android using Flutter 1.2.1 • channel stable and using sqflite v 1.1.5, I attempted to change Map data from a query which resulted in an error. I then read the solution to issue #140 which solved the problem of changing data that results from an sqflite query. Then I thought that I implemented that in my program, however the result was still an error as follows:

1. Screen showing Error and related message:

```
I/flutter (28591): NotesList: _selectDataFromDb: copying data from SqFlite Query


I/flutter (28591): NotesList: _updateNoteCompleted. Setting Map completed value to 0
E/flutter (28591): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unsupported operation: read-only
E/flutter (28591): #0      QueryRow.[]= (package:sqflite/src/collection_utils.dart:140)
E/flutter (28591): #1      NotesListPageState._updateNoteCompleted (package:notes08/NotesList.dart:449)
E/flutter (28591): <asynchronous suspension>
```

2. Code where the error occurs:

```
  Future<bool> _updateNoteCompleted(Map mapRec, int iNdx) async {
    int iCompleted = mapRec[sColCompleted] < 1 ? 1 : 0;

    debugPrint(
        "NotesList: _updateNoteCompleted. Setting Map completed value to $iCompleted");

    _lsMapNotes[_iTabNumber][iNdx][sColCompleted] = iCompleted;

    debugPrint(
        "NotesList - _updateNoteCompleted - Map completed value has been set");
    NoteRec noteRec = NoteRec.fromMap(_lsMapNotes[_iTabNumber][iNdx]);
    int iResult = await _dbHelper.updateNoteRec(noteRec);
```

3. Code where the data is created:

```

List<List<Map<String, dynamic>>> _lsMapNotes = [null, null, null, null, null];


if (tfDataHasChanged) /* ONLY SELECT IF DATA HAS CHANGED */ {
      debugPrint(
          "NotesList SelectDataFromDb ($_iSelectRequests) : Data has changed, so selecting data");
      if (iNewTabNumber == 0) {
        lsMapItems =
            await _dbHelper.selectNoteRecsForTodayAndPrior(_viCategory);
      } else if (iNewTabNumber == 1) {
        lsMapItems = await _dbHelper.selectNoteRecsAllByDateDue(_viCategory);
      } else if (iNewTabNumber == 2) {
        lsMapItems = await _dbHelper.selectNoteRecsByPriority(_viCategory);
      } else if (iNewTabNumber == 3) {
        lsMapItems = await _dbHelper.selectNoteRecsByDateDue(_viCategory);
      } else if (iNewTabNumber == 4) {
        lsMapItems = await _dbHelper.selectNoteRecsNoDueDate(_viCategory);
      }
      _iFetched++;
      //_lsMapNotes[iNewTabNumber] = lsMapItems;
      debugPrint(
          "NotesList: _selectDataFromDb: copying data from SqFlite Query");

      _lsMapNotes[iNewTabNumber] = List<Map<String, dynamic>>.from(lsMapItems);

      _lsDataHasChanged[iNewTabNumber] = false;
    }
```
What I am attempting to achieve is to make my program more efficient. If I can change the value in the list then I can just do setState to update the screen, alternatively I have to reselect the table. It would be even more efficient if I could alter the original list created by the query.

Q1. Have I implemented your solution correctly, and if not, what should I do to make the List editable?

Q2. Would it be feasible for you to optionally make the query List editable?

**Comment by alextekartik** [comment]
The `List<Map<String, dynamic>>` results is a special list that avoids parsing results data (which can be huge if you list has 10000 items). You could wrap the result in a lazy generated list that would allow what you need. Each user might have a different need (some might want to add a row, some to change a value in a map) where optimization would be different.

A brute force way to make the results editable would be to convert them after your query using something like:

```dart
/// Generate a modifiable result set
List<Map<String, dynamic>> makeModifiableResults(
    List<Map<String, dynamic>> results) {
  // Generate modifiable
  return List<Map<String, dynamic>>.generate(
      results.length, (index) => Map<String, dynamic>.from(results[index]),
      growable: true);
}
```

You can then modify the list and each item in the list depending on your needs
