### ISSUE TITLE
Support sqlite3_update_hook auto callback the data change

### ISSUE THREAD

**Issue by crossle** [tekartik/sqflite#197]
How about support sqlite3_update_hook for auto notify the data change.

**Comment by alextekartik** [comment]
Hi. I'm not aware of this and I'm not sure Android exposes these callbacks in their Java API. If you have a solution, I'm all hears!

**Comment by haarts** [comment]
[moor](https://pub.dev/packages/moor) must be doing something like this. I just can't figure out how. They provide a `watch()` method and it re-triggers queries when a (registered) table changed. I lose track where that's supposed to happen.

**Comment by haarts** [comment]
I figured it out. They're 'just' keeping an internal record of which tables are hit and fire callbacks based on that. Unfortunately.

**Comment by alextekartik** [comment]
sqflite won't likely implement that, you have to track changes at the application level

**Comment by t1ooo** [comment]
@alextekartik, How about listening for updates from another isolate launched from WorkManager/AlarmManager? sqlite3_update_hook may be very useful.
