### ISSUE TITLE
Transaction inserts are slower than without transaction

### ISSUE THREAD

**Issue by lepicekmichal** [tekartik/sqflite#198]
Is there something wrong with my code below? Cause transaction takes 5x to 10x more time than without transaction. If I compare to Kotlin, the no transaction time is much closer to what it should be. I use --profile, of course.

    final db = await DBProvider.instance.database;

    final Random random = Random();
    final HashMap<int, List<double>> mapa = HashMap();

    // 1 million of random temperature measures
    for (var i = 0; i < 1000000; ++i) {
      final year = 1700 + random.nextInt(2018 - 1700);
      final month = 1 + random.nextInt(12 - 1);
      final temperature = random.nextDouble();
      mapa
          .putIfAbsent(year * 100 + month, () => List<double>()) // unique key for grouping by unique month
          .add(temperature);
    }

    Stopwatch time = Stopwatch()..start();
    await db.transaction((txn) async {
      mapa.forEach((key, temperatures) async {
        await txn.rawInsert(
            "INSERT INTO temp (year, month, measureCount) VALUES (?, ?, ?)",
            [
              (key / 100).truncate(),
              key % 100,
              temperatures.length
            ]);
      });
    });
    var el = time.elapsedMicroseconds;
    print("with transaction: ${el}μs");

    time = Stopwatch()..start();
    mapa.forEach((key, temperatures) async {
      await db.rawInsert(
          "INSERT INTO temp (year, month, measureCount) VALUES (?, ?, ?)",
          [
            (key / 100).truncate(),
            key % 100,
            temperatures.length
          ]);
    });
    el = time.elapsedMicroseconds;
    print("without transaction: ${el}μs");

**Console prints:**

    with transaction:    2612712μs  
    without transaction:  492418μs

P.S.: It's usually 3498 inserts.

**Comment by alextekartik** [comment]
Actually it should not even work here. You should not use `map.forEach` which is not an async function that you cannot "await" for. So here the transaction terminates before any insert happens. Try to use regular loop and make sure you await all operations or even better use a batch: <https://github.com/tekartik/sqflite/blob/master/sqflite/README.md#batch-support>

**Comment by lepicekmichal** [comment]
@alextekartik You are right, how stupid of me. 
I have changed the code accordingly:

    Stopwatch time = Stopwatch()..start();
    await db.transaction((txn) async {
      for (var entry in mapa.entries) {
        await txn.rawInsert(
            "INSERT INTO temp (year, month, measureCount) VALUES (?, ?, ?)",
            [
              (entry.key / 100).truncate(),
              entry.key % 100,
              entry.value.length
            ]);
      }
    });

And now transactions are faster. 15 seconds no transaction, 7 seconds within transaction. BUT it's hell of a lot! Is there still something wrong with my code? Why is Kotlin having the same insertion in 0.1 seconds?

**Comment by alextekartik** [comment]
You should look at batches as I said before:
https://github.com/tekartik/sqflite/blob/master/sqflite/README.md#batch-support

Pseudo untested-code:
```dart
var batch = db.batch();
for (var entry in mapa.entries) {
  batch.rawInsert(
      "INSERT INTO temp (year, month, measureCount) VALUES (?, ?, ?)", [
    (entry.key / 100).truncate(),
    entry.key % 100,
    entry.value.length
  ]);
}
await batch.commit(noResult: true);
``

**Comment by lepicekmichal** [comment]
Oh, so what you are saying is: Kotlin/Java transaction is implicitly batched, but SQFLite is not. Gotcha.
I implemented it and I am getting just 0.8 second now. For comparison, Kotlin is 0.1s and NDK is actually 0.03s.
So is that the end of performance? Nothing else to be done? Seems still a little bit slower than it should be. What is the reason for such performance?

```dart
Stopwatch time = Stopwatch()..start();
await db.transaction((txn) async {
  var batch = txn.batch();
  for (var entry in mapa.entries) {
    batch.rawInsert(
        "INSERT INTO temperatures (year, month, measureCount) VALUES (?, ?, ?)",
        [
          (entry.key / 100).truncate(),
          entry.key % 100,
          entry.value.length
        ]);
  }
  await batch.commit();
});
var el = time.elapsedMicroseconds;
print("with transaction:    $elμs");
```

**Comment by alextekartik** [comment]
Flutter plugins for now imposes using Flutter services to exchange with native world so I guess that is one reason here. Anyway until we get access to native libraries, there will always be an extra layer. I guess some things could be improved but I'm not sure how much (and compatible with Android and iOS) so if someone has some performance enhancements I welcome PR.

(And no, Kotlin/Java are not implicit "batched" whatever that means; here the goal of the batch is to avoid too many ping-pong between the dart and native world by sending all requests at once)

**Comment by lepicekmichal** [comment]
Alright, understood. Batch in SQFLite has different meaning than in Kotlin/Java.
