### ISSUE TITLE
order by int does not seem to work unless rawQuery

### ISSUE THREAD

**Issue by neiljaywarner** [tekartik/sqflite#199]
I apologize if i should have put this on SO or gathered more details first - i haven't tested on iPhone yet.

this doesn't work (order correctly)
    List<Map<String, dynamic>> records = await db.query(tableName, orderBy: "intColumnName");
but this does
    List<Map<String, dynamic>> records = await db.rawQuery("select * from $tableName order by intColumnName");

and this does
    List<Map<String, dynamic>> records = await db.query(tableName, orderBy: "textColumn");

**Comment by alextekartik** [comment]
Hard to tell. In the sample you give you use once intColumn and once intColumnName so don't know which on is correct. Can you print the output?

**Comment by neiljaywarner** [comment]
My apologies; what i mean is i simply used the exact same names and no errors, just the behaviour didn't work.  I tested several times so i don't think it's EBKAC, but it could be.

**Comment by alextekartik** [comment]
Hard to investigate without more info (data you inserted and output). Since you tested several times you might have some output displayed?
