### ISSUE TITLE
BLOB doesn't work to store image

### ISSUE THREAD

**Issue by qeude** [tekartik/sqflite#204]
Hi everyone,

I would like to store an image in a sqflite database but I am facing an issue. I am storing the Uint8List element get from my ImagePicker but when I am querying my DB to get my image i've got this following error message : 
`CursorWindow( 7290): Window is full: requested allocation 4685824 bytes, free space 2096620 bytes, window size 2097152 bytes`
` exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT * FROM Event ORDER BY date`

Am I doing it in a wrong way or is there an issue about that ? 
Thanks in advance for answering. :)

**Comment by alextekartik** [comment]
I have not used BLOB enough to have a strong answer however there seems to be a limitation in the cursor windows size, see: <https://stackoverflow.com/questions/35766836/cursorwindow-window-is-full>. So I'm not sure there is a solution to your issue.

I recommend storing binary files as...files and save the reference (path) on sqlite.
