### ISSUE TITLE
matchinfo returns 8 bit array when 32 bit array is expected

### ISSUE THREAD

**Issue by adam7** [tekartik/sqflite#206]
I have a FTS4 table created like this:

`CREATE VIRTUAL TABLE Food using fts4(description TEXT)`

I then query it using a rawQuery:

`await db.rawQuery("SELECT description, matchinfo(Food) as matchinfo FROM Food WHERE Food MATCH ?", ["$searchText*"]);`

Based on the SQLite documentation for [matchinfo](https://www.sqlite.org/fts3.html#matchinfo) I would expect each row in the result to contain a matchinfo key with a 32bit array of some kind but instead I get a _Uint8ArrayView. Is there a way for me to get the expected array type?

**Comment by alextekartik** [comment]
Thanks for the report. I have not tried this at all yet so can only make speculation at this point. I try to make as little data conversion but flutter services add another conversion so it is likely that any unknown types other than the one supported (String, int, double, UInt8List) get converted to binay blob.

Have you tried to look at the content? You might try to convert the UInt8List to UInt32List. If you have some sample SQL I can try (create table + insert + query) , that would be great. Thanks!

**Comment by adam7** [comment]
Yes if I look at the content it's basically a little endian 8 bit array representation of a 32 bit array, so I end up with an array with four times more elements than it should contain. So I could probably fold the values up and get the correct representation but I'd like to avoid that if possible. 

This sample SQL will create a table populate it and query it:

```
CREATE VIRTUAL TABLE Food using fts4(description TEXT)

INSERT Into Food (description) VALUES ('banana')
INSERT Into Food (description) VALUES ('apple')

SELECT description, matchinfo(Food) as matchinfo FROM Food WHERE Food MATCH 'ban*'
```

**Comment by alextekartik** [comment]
Thanks. So I made some experiments. Indeed the matchinfo is returned as a byte array on the native android side so there is not much I can do. So for now, matchinfo will be returned a Uint8List array and you will have to convert it yourself. Sorry!

**Comment by adam7** [comment]
OK, guess I'll work around it for now. Do you know if the same is true for iOS?

**Comment by alextekartik** [comment]
I will try and let you know

**Comment by alextekartik** [comment]
Ok so I tried on iOS and it gives the same result for the following test: https://github.com/tekartik/sqflite/blob/fbeea9f70fc1a2dbc6bc309aac3621269997822d/sqflite/example/lib/exp_test_page.dart#L434-L470

I can only confirm the behavior on the latests OS though.

**Comment by adam7** [comment]
Great, thanks for investigating, I'll go with converting to a Uint32List like you do in the test. 👍

**Comment by alextekartik** [comment]
Don't know if the conversion and results are correct but at least I can tell it is consistent on iOS and Android...
