### ISSUE TITLE
onConfigure

### ISSUE THREAD

**Issue by GRouslan** [tekartik/sqflite#21]
Need onConfigure support to enable foreign keys and execute other pragmas:

> onConfigure
> added in API level 16
> void onConfigure (SQLiteDatabase db)
> Called when the database connection is being configured, to enable features such as write-ahead logging or foreign key support.
> 
> This method is called before onCreate(SQLiteDatabase), onUpgrade(SQLiteDatabase, int, int), onDowngrade(SQLiteDatabase, int, int), or onOpen(SQLiteDatabase) are called. It should not modify the database except to configure the database connection as required.
> 
> This method should only call methods that configure the parameters of the database connection, such as enableWriteAheadLogging() setForeignKeyConstraintsEnabled(boolean), setLocale(Locale), setMaximumSize(long), or executing PRAGMA statements.

[docs](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html#onConfigure%28android.database.sqlite.SQLiteDatabase%29)

**Comment by alextekartik** [comment]
Thanks for the report. I will look into adding it

**Comment by alextekartik** [comment]
Implemented in 0.6.0, pusblished

**Comment by alextekartik** [comment]
Let me know if the implementation suits your needs, otherwise re-open the bug!

**Comment by GRouslan** [comment]
Thank you, it works
