### ISSUE TITLE
Look into use the new Dart / Flutter FFI under development

### ISSUE THREAD

**Issue by sachaarbonel** [tekartik/sqflite#210]
Hi @alextekartik thank's for your great project I use it in all my apps and it is awesome. I realised that it would be great to have support for other platforms ([desktop](https://github.com/go-flutter-desktop), [web](https://github.com/flutter/flutter_web)) with a same package thus the native extension approach. It's not production ready yet but they provided a guide for sqlite on [android](https://github.com/dart-lang/sdk/blob/master/samples/ffi/sqlite/docs/android.md). Ios and tooling for pub doesn't exist yet but it is worth considering it IMHO.

**Comment by alextekartik** [comment]
Yes I'm following that. I'd like first to have a desktop solution but I'm waiting for good samples desktop flutter pluging sample from the flutter team first. For web, websql is not implemented everywhere (missing in firefox) so I'm not sure we can find a decent solution here with a similar interface. Maybe an API at a greater level (something like lovefield but I have never used it) with a good abstraction to tackle all the targets could be an alternative solution.

**Comment by alextekartik** [comment]
sqflite_common_ffi v1.0.0 has been published allowing using ffi on the desktop. It is based on moor_ffi (!) that provides a nice wrapper around sqlite libraries
