### ISSUE TITLE
Delete database not working

### ISSUE THREAD

**Issue by x4080** [tekartik/sqflite#213]
Hi, i just realized that database delete is not working, is there any permission to storage needed in Android or ios? 

I remember that it used to work but niw it seems its not (in emulator)

Thanks

**Comment by alextekartik** [comment]
> Hi, i just realized that database delete is not working

Maybe it is not working in your scenario. Are you sure the database is closed before deleting it? sqflite keep a cache of the opened databases. Maybe I should add some check in deleteDatabase to throw an exception if the database is not closed.

**Comment by x4080** [comment]
Hi @alextekartik , I use it in the start of the application, in main.dart, so I think its not opened yet, like in your example, 
```
await deleteDatabase(path); 
_database = await openDatabase(path, version: 1,
          onCreate: (Database db, int version) async {
...
```
And I know it didnt delete it because the onCreate is not called (I restructure the table) - its in android emulator not yet tested in device or ios

**Comment by alextekartik** [comment]
If the database has been opened yet, it should work. However this won't work with hot reload as the database is still open. As a workaround you try the following (in debug mode only):

```dart
await ((await openDatabase(path)).close());
await deleteDatabase(path); 
```

Thinking more about it, I don't think it would be a breaking change to force closing all database connections before deleting so I will look into it. I'll let you know.

**Comment by x4080** [comment]
@alextekartik , it works ! The key then is should openDatabase first

**Comment by AstroDecoder2511** [comment]
Would you guys mind sharing the Delete Database() function and Close Database() function cause i cannot find anywhere where it shows how to this

**Comment by mathieurousseau** [comment]
> Would you guys mind sharing the Delete Database() function and Close Database() function cause i cannot find anywhere where it shows how to this

@AstroDecoder2511 
```
import 'package:sqflite/sqflite.dart' as sqflite;
Future<void> main() async {
  await sqflite.deleteDatabase('database.db');
}
```

or:

```
import 'package:sqflite/sqflite.dart';
Future<void> main() async {
await sqflite.deleteDatabase('database.db');
```

**Comment by AstroDecoder2511** [comment]
Thanks!
Just one last question, where do you place the statement because I don't have a main method for my Database, I have like a database getter and an InitDb, etc. 
Depending on where I place my deleteDatabase function it gives me different errors, such as it says the database is a readOnly database and I can't write or insert into it and many other errors.
Also is the closeDatabase needed because I also sometimes get an error that the database must be closed when it is done and as a result of this it says it 'leaks'.

Thanks
- Matt

**Comment by mathieurousseau** [comment]
> Thanks!
> Just one last question, where do you place the statement because I don't have a main method for my Database, I have like a database getter and an InitDb, etc.
> Depending on where I place my deleteDatabase function it gives me different errors, such as it says the database is a readOnly database and I can't write or insert into it and many other errors.
> Also is the closeDatabase needed because I also sometimes get an error that the database must be closed when it is done and as a result of this it says it 'leaks'.
> 
> Thanks
> 
> * Matt

I put it first thing os my main main().
I ran into issue with android emulator when it did not close it on hot restart. So now I open, close then delete.

**Comment by alextekartik** [comment]
As of sqflite 1.1.8, the behavior of deleteDatabase has slightly change, for the better hopefully as I don't consider this a breaking change.

It now supports Android restart and hot restart in general. If the database was opened previously as a single instance, the database is closed first, then deleted.

This means that the trick of opening the database before deletion is no longer needed.

**Comment by x4080** [comment]
So we can remove
```
await ((await openDatabase(path)).close());
```

and just call 
```
await deleteDatabase(path); 
```

? Is it work also in ios ? Thanks

**Comment by alextekartik** [comment]
That's correct. Works on Android/iOS/MacOS

**Comment by x4080** [comment]
cool

**Comment by ladybug4o4** [comment]
I use `sqflite` version 2.0.1. After the command `await deleteDatabase(path)` my database in not `null` as expected, but it contains (randomly!) an empty table named `android_metadata` which makes the following code fail:

```
if (_database != null) {
      return _database;
    }else {
      _database = await createDatabase();
    }
```

Is there any solution (except of manual dropping the table) or what am I doing wrong?
