### ISSUE TITLE
Are whereArgs sanitized?

### ISSUE THREAD

**Issue by stevenspiel** [tekartik/sqflite#214]
Do I need to sanitize my whereArgs, or is that handled in plugin's android/ios code?

**Comment by alextekartik** [comment]
whereArgs items can be of type num (int/double) or String

**Comment by stevenspiel** [comment]
Are the strings sanitized to avoid SQL injection?

**Comment by alextekartik** [comment]
Sorry I misunderstood your question. There is no sanitization done. I think that is the purpose of using parameters instead of a raw sql where here you can do sql injection.
