### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by AndersonDan** [tekartik/sqflite#215]
Because app depends on sqflite >=0.2.0 <=0.11.0+1 which requires SDK version <2.0.0 or >=2.0.0-dev <2.0.0, version solving failed.

Running "flutter packages get" in app...      

The current Dart SDK version is 2.3.0-dev.0.5.flutter-a1668566e5.

Because app depends on sqflite >=0.2.0 <=0.11.0+1 which requires SDK version <2.0.0 or >=2.0.0-dev <2.0.0, version solving failed.
pub get failed (1)
Process finished with exit code 1

**Comment by alextekartik** [comment]
You need to check your dependencies (i.e. maybe your package or a dependency depends on sqflite <0.11.0. Try to force the dependency in your app). See <https://github.com/tekartik/sqflite/blob/master/sqflite/README.md#getting-started>

```yml
dependencies:
  ...
  sqflite: ^1.1.5
```
