### ISSUE TITLE
Upsert would be nice...

### ISSUE THREAD

**Issue by kevin-haynie** [tekartik/sqflite#217]
Having the 'upsert' functionality at the Database class level would be convenient.  It's great to have insert, delete, etc at the Database level but we're missing the Upsert method.  I know we can just issue an execute() statement but it would be nice to have a simple way to do this.

**Comment by alextekartik** [comment]
It is actually possible doing insert with some upsert feature based on sqlite conflict. See https://github.com/tekartik/sqflite/issues/59.

**Comment by kevin-haynie** [comment]
Thank you.  You are correct.  We can use the conflictAlgorithm option on the INSERT method by setting it to REPLACE.
