### ISSUE TITLE
Issue with not using tic symbols for field names in a query

### ISSUE THREAD

**Issue by patrioticcow** [tekartik/sqflite#22]
Hello

I get thrown some errors if I don't use ` in the query fields . For example:

this works:

    db.execute("CREATE TABLE IF NOT EXISTS quiz (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `group` INTEGER, `name` TEXT)")

this doesn't work:

    db.execute("CREATE TABLE IF NOT EXISTS quiz (id INTEGER PRIMARY KEY AUTOINCREMENT, group INTEGER, name TEXT)")

This wouldn't be a huge issue, because I could just wrap the field names in `. The issue comes if I do:

    await _db.insert("quiz", quiz.toMap())
 
in this case I get:

    DatabaseException(near "group": syntax error (Sqlite code 1): , while compiling: INSERT INTO quiz (group, name) VALUES (?, ?), (OS error - 2:No such file or directory))

If I write the raw query, then the insert works, but that defies using the sugar method, like `_db.insert(...`

    await _db.rawInsert('INSERT INTO quiz (`group`, `name`) VALUES(?, ?)', [data['group'], data['name']]);

Basically the field names don't get wrapped in ` symbols.

Any ideas?

Here is the full error trace:

```
E/flutter (26309): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (26309): DatabaseException(near "group": syntax error (Sqlite code 1): , while compiling: INSERT INTO quiz (group, name) VALUES (?, ?), (OS error - 2:No such file or directory))
E/flutter (26309): #0      wrapDatabaseException (package:sqflite/src/exception.dart:52:7)
E/flutter (26309): <asynchronous suspension>
E/flutter (26309): #1      Database.rawInsert.<anonymous closure> (package:sqflite/sqflite.dart:106:14)
E/flutter (26309): #2      SynchronizedLock._run.<anonymous closure>.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:86:29)
E/flutter (26309): #3      _rootRun (dart:async/zone.dart:1126)
E/flutter (26309): #4      _CustomZone.run (dart:async/zone.dart:1023)
E/flutter (26309): #5      runZoned (dart:async/zone.dart:1501)
E/flutter (26309): #6      SynchronizedLock._run.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:84:14)
E/flutter (26309): #7      new Future.sync (dart:async/future.dart:222)
E/flutter (26309): #8      SynchronizedLock._run (package:synchronized/src/synchronized_impl.dart:83:16)
E/flutter (26309): #9      SynchronizedLock.synchronized.run (package:synchronized/src/synchronized_impl.dart:147:14)
E/flutter (26309): #10     SynchronizedLock.synchronized (package:synchronized/src/synchronized_impl.dart:157:17)
E/flutter (26309): #11     Database.writeSynchronized (package:sqflite/sqflite.dart:288:23)
E/flutter (26309): #12     Database.rawInsert (package:sqflite/sqflite.dart:105:12)
E/flutter (26309): #13     Database.insert (package:sqflite/sqflite.dart:124:12)
E/flutter (26309): #14     DatabaseClient.insertIntoQuiz (package:myapp/models/databaseClient.dart:27:25)
```

**Comment by alextekartik** [comment]
Thanks for the detail report. Indeed name like `group`, `table`... need to be escaped.For now I only escape a list of given words (most of them are sqlite keywords) and I use " (double-quote), \` (backtick) not being SQL standard.

To note that in the `where`, `orderBy`... and raw queryies, it is still a manual operation so it's still better to avoid SQL keywords as column name.

Fixed in 0.5.0 published. Let me know if that works for you

**Comment by patrioticcow** [comment]
`_db.insert("quiz", quiz.toMap())` seems to work with no errors in 0.5.0. As I build the app, if I run in any related issues Ill post them.

```
To note that in the where, orderBy... and raw queryies, it is still a manual operation so it's still better to avoid SQL keywords as column name.
```
Not sure if u want to add the this to the `README.md`. Maybe will be useful for others to know about this. 

Thank you

**Comment by alextekartik** [comment]
Yeap will do (the documenting)! Thanks again for the reporting and good analysis and let me know if you ran into issues

**Comment by alextekartik** [comment]
I added a note in the README.md
