### ISSUE TITLE
Sqflite error (no transaction active)

### ISSUE THREAD

**Issue by Tolga-GA** [tekartik/sqflite#220]
When executing a CRUD operation and changing from pages on Flutter, I get to see this error popping up:

```
Error calling sqlite3_step (1: cannot rollback - no transaction is active) SQLITE_ERROR
DB Query: ROLLBACK
Unknown error finalizing or resetting statement (1: cannot rollback - no transaction is active)
DB Query: ROLLBACK
```

So the method that I am using is this one:

```
Future<int> getCount( String table ) async {
    Database db = await this.database;
    List<Map<String, dynamic>> x = await db.rawQuery( 'SELECT COUNT (*) from $table' );
    return Sqflite.firstIntValue(x);
  }
```

And this is how I check count and navigate to another page:

```
  _navigateWhenUserExists() async {
    DatabaseHelper dbHelper = DatabaseHelper();
    var val = await dbHelper.getCount( User.table );
    Navigator.pushReplacementNamed(context, val == 0 ? 'sign' : 'dashboard');
  }

  SplashState() {
    UIHelper.loadCryptoStyle();
    Future.delayed( const Duration(milliseconds: 1500), () => _navigateWhenUserExists() );
  }
```

Is there anything that I should know or is this a bug? I have seriously no idea right now.

**Comment by alextekartik** [comment]
Hard to tell without seeing more and yes sometimes sqlite issues are hard to track. I'm not aware of such issue. There are some tricks to support hot reload that can trigger some rollback but the error is caught (i.e. the warning can be ignored). It is unlikely that your getCount method is the one triggering this since there seems to be a transaction in progress....

**Comment by Tolga-GA** [comment]
> Hard to tell without seeing more and yes sometimes sqlite issues are hard to track. I'm not aware of such issue. There are some tricks to support hot reload that can trigger some rollback but the error is caught (i.e. the warning can be ignored). It is unlikely that your getCount method is the one triggering this since there seems to be a transaction in progress....

Please see the code below and let me know if there is something fishy going on. The warning occurs only on the iOS emulator. 

```
class DatabaseHelper {
  
  static final String _databaseName = 'myDatabase.db';
  static final int _databaseVersion = 1;

  static DatabaseHelper _databaseHelper = DatabaseHelper._internal();
  static Database _database;

  DatabaseHelper._createInstance();

  factory DatabaseHelper() {
    return _databaseHelper;
  }

  DatabaseHelper._internal() {
    _databaseHelper = DatabaseHelper._createInstance();
  }

  Future<Database> get database async {
    if( _database == null )
      _database = await initializeDatabase();
    
    return _database;
  }

  Future<Database> initializeDatabase() async {
    Directory directory = await getApplicationDocumentsDirectory();
    String path = '${directory.path}/$_databaseName';

    return openDatabase(path, version: _databaseVersion, onCreate: _createDb);
  }

  static void deleteDb() async {
    Directory directory = await getApplicationDocumentsDirectory();
    String path = '${directory.path}/$_databaseName';
    
    deleteDatabase(path);
  }

  static void _createDb( Database db, int version ) async {
    await db.execute( User.initDB() );
    await db.execute( HDWallet.initDB() );
    await db.execute( Crypto.initDB() );
    await db.execute( CryptoTransaction.initDB() );
  }

  static void emptyAllTables() {
    _databaseHelper.clearTableContent( User.table );
    _databaseHelper.clearTableContent( HDWallet.table );
    _databaseHelper.clearTableContent( Crypto.table );
    _databaseHelper.clearTableContent( CryptoTransaction.table );
  }

  Future<int> clearTableContent( String table ) async {
    Database db = await this.database;
    var result = await db.rawDelete( 'DELETE FROM $table' );

    return result;
  }

  Future<List<dynamic>> getList( String table, {String where, int limit, String orderBy} ) async {
    Database db = await this.database;
    var result = await db.query( table, where:where, limit: limit, orderBy: orderBy );
    
    return result;
  }

  Future<int> insert( String table, dynamic model ) async {
    Database db = await this.database;
    var result = await db.insert( table, model.toMap() );

    return result;
  }

  Future<int> update( String table, dynamic model ) async {
    Database db = await this.database;
    var result = await db.update( table, model.toMap(), where: 'id = ?', whereArgs: [model.id] );

    return result;
  }

  Future<int> delete( String table, int id ) async {
    Database db = await this.database;
    var result = await db.rawDelete( 'DELETE FROM $table WHERE id = $id' );

    return result;
  }

  Future<int> getCount( String table ) async {
    Database db = await this.database;
    List<Map<String, dynamic>> x = await db.rawQuery( 'SELECT COUNT (*) from $table' );
    return Sqflite.firstIntValue(x);
  }
}
```

**Comment by alextekartik** [comment]
At first glance, I don't see anything wrong (didn't even know BOOL type was supported although it does not exist) and interesting to see that it happens only on iOS. Are you getting an exception thrown? It would be good to try to catch the exception to see where it was thrown from. Sorry but it is hard to help you more on this without being able to reproduce the issue.

**Comment by Tolga-GA** [comment]
> At first glance, I don't see anything wrong (didn't even know BOOL type was supported although it does not exist) and interesting to see that it happens only on iOS. Are you getting an exception thrown? It would be good to try to catch the exception to see where it was thrown from. Sorry but it is hard to help you more on this without being able to reproduce the issue.

I made a simple app with my DBHelper included. :) Please take a look and let me know if we should change something.. :)
https://github.com/Tolga-GA/todoapp-simple

**Comment by alextekartik** [comment]
Thanks for taking the time to write a sample app (i know it is a pain to extract code from an app). I had to remove the dependency on FMDB 2.7.5 from your podfile (Only FMDB 2.7.2 can target ios 8 for now so I'm not sure yet whether sqflite should remove this target). I was able to run the app on iOS and Android Emulator without issue. What are the steps to reproduce the issue?

You should use `getDatabasesPath` instead of get `getApplicationDocumentsDirectory` although that is not a strong requirement.

**Comment by kayrules** [comment]
I also had similar error on ios simulator.. 

```
Error calling sqlite3_step (1: cannot rollback - no transaction is active) SQLITE_ERROR
DB Query: ROLLBACK
Unknown error finalizing or resetting statement (1: cannot rollback - no transaction is active)
DB Query: ROLLBACK
Unknown error calling sqlite3_step (10: disk I/O error) eu
DB Query: BEGIN EXCLUSIVE
Unknown error finalizing or resetting statement (10: disk I/O error)
DB Query: BEGIN EXCLUSIVE
flutter: error DatabaseException(Error Domain=FMDatabase Code=10 "disk I/O error" UserInfo={NSLocalizedDescription=disk I/O error}) sql 'BEGIN EXCLUSIVE' args []} during open, closing...
Error calling sqlite3_step (1: cannot rollback - no transaction is active) SQLITE_ERROR
DB Query: ROLLBACK
Unknown error finalizing or resetting statement (1: cannot rollback - no transaction is active)
DB Query: ROLLBACK
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=10 "disk I/O error" UserInfo={NSLocalizedDescription=disk I/O error}) sql 'BEGIN EXCLUSIVE' args []}
```

**Comment by jimgreer** [comment]
FWIW, I get the same issue when using the flutter_cache_manager package, but when doing a hot restart. A normal restart doesn't trigger it.

**Comment by gireeshp** [comment]
Even I'm facing the same issue. Did an entry in the collection (Cloud firestore) from backend and refreshed the page (using RefreshIndicator widget) to reload the data. It is appearing correctly upon restart. But when the app is running and a DB entry is made from BE, getting this error. Using IOS simulator.
