### ISSUE TITLE
type 'BatchResults' is not a subtype of type 'List<int>'

### ISSUE THREAD

**Issue by thomas-bartleet** [tekartik/sqflite#221]
Hi!

Great support plugin for SQLite on Flutter. Thanks for writing it!

I have encountered a problem while trying to do some `batch.commit()`s. I keep getting the following exception:

```
type 'BatchResults' is not a subtype of type 'List<int>'
```

This seems to occur only when doing a `batch.commit()`. I can provide the last bit of code that failed for me as an example:

```dart
/// updates all the rows in the [table].
///
/// [table] The table names to compile the query against.
/// [List<t>] The list of rows to update.
Future<List<int>> updateAll(
  String table,
  List<T> list, {
  ConflictAlgorithm conflictAlgorithm = ConflictAlgorithm.ignore,
}) async {
  final db = await database;
  final batch = db.batch();
  list.forEach((t) async {
    batch.update(
      table,
      t.toMap(),
      where: 'id = ?',
      whereArgs: [t.id],
      conflictAlgorithm: conflictAlgorithm,
    );
  });
  final results = await batch.commit(continueOnError: true); // FAILS HERE
  return results;
}
```

The `.commit()` says it returns a `List<int>`, so it's not like I can use (for example):
```dart
final results = (await batch.commit())?.rawList;
```

Has this been raised before? How do I get around this?

I'm using `Flutter (Channel stable, v1.5.4-hotfix.2)`, `sqflite ^1.1.5`, and my `flutter doctor` shows no issues. This occurs on both device and emulator/simulator.

**Comment by alextekartik** [comment]
commit returns a `List<dynamic>` not a `List<int>` since it can return results from update/delete but also insert and queries. In your case, since indeed all the results are int, you should cast the result:

```dart
final results = (await batch.commit(continueOnError: true)).cast<int>();
```

**Comment by thomas-bartleet** [comment]
Such a simple solution I should have seen it. I'm almost embarrassed to have asked the question! Thanks @alextekartik !
