### ISSUE TITLE
How to get fresh database after uninstall

### ISSUE THREAD

**Issue by shariful2011** [tekartik/sqflite#224]
I am having some problem after uninstall my app and re-install I got the same data on my app. Is there a way that I can get fresh database on a new install? I am using the same code as [https://github.com/tekartik/sqflite/issues/223](url)

**Comment by alextekartik** [comment]
I recommend using `getDatabasePath` to set the correct location of the database. This directory should get deleted when the application is uninstalled. If you enable backup you might indeed get your data back and I know some developers explicitely set `android:allowBackup="false"` in their manifest (Personnally I don't) so you might try that.

**Comment by shariful2011** [comment]
Thanks, it worked.
