### ISSUE TITLE
Cannot find symbol

### ISSUE THREAD

**Issue by VB10** [tekartik/sqflite#225]
Hello guys
Update this lib 1.1.5 and its throw error: "cannot find symbol"
(Now use 1.1.1 it's doesn't have an error.)
How to resolve?
`
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:3: error: cannot find symbol
import com.tekartik.sqflite.SqlCommand;                                 
                           ^                                            
  symbol:   class SqlCommand                                            
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:7: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_CONTINUE_OR_ERROR;    
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:7: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_CONTINUE_OR_ERROR;    
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:8: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_NO_RESULT;            
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:8: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_NO_RESULT;            
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:9: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_SQL;                  
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:9: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_SQL;                  
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:10: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_SQL_ARGUMENTS;        
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:10: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_SQL_ARGUMENTS;        
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/Operation.java:3: error: cannot find symbol
import com.tekartik.sqflite.SqlCommand;                                 
                           ^                                            
  symbol:   class SqlCommand                                            
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BaseReadOperation.java:25: error: cannot find symbol
    public SqlCommand getSqlCommand() {                                 
           ^                                                            
  symbol:   class SqlCommand                                            
  location: class BaseReadOperation                                     
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/Operation.java:15: error: cannot find symbol
    SqlCommand getSqlCommand();                                         
    ^                                                                   
  symbol:   class SqlCommand                                            
  location: interface Operation                                         
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/SqlErrorInfo.java:3: error: cannot find symbol
import com.tekartik.sqflite.SqlCommand;                                 
                           ^                                            
  symbol:   class SqlCommand                                            
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/SqlErrorInfo.java:8: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_SQL;                  
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/SqlErrorInfo.java:8: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_SQL;                  
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/SqlErrorInfo.java:9: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_SQL_ARGUMENTS;        
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/SqlErrorInfo.java:9: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_SQL_ARGUMENTS;        
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:9: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_ERROR;                
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:9: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_ERROR;                
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:10: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_ERROR_CODE;           
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:10: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_ERROR_CODE;           
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:11: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_ERROR_DATA;           
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:11: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_ERROR_DATA;           
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:12: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_ERROR_MESSAGE;        
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:12: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_ERROR_MESSAGE;        
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:13: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_METHOD;               
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:13: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_METHOD;               
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:14: error: cannot find symbol
import static com.tekartik.sqflite.Constant.PARAM_RESULT;               
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/BatchOperation.java:14: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.PARAM_RESULT;               
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/ExecuteOperation.java:3: error: cannot find symbol
import com.tekartik.sqflite.SqlCommand;                                 
                           ^                                            
  symbol:   class SqlCommand                                            
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/ExecuteOperation.java:16: error: cannot find symbol
    final SqlCommand command;                                           
          ^                                                             
  symbol:   class SqlCommand                                            
  location: class ExecuteOperation                                      
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/operation/ExecuteOperation.java:19: error: cannot find symbol
    public ExecuteOperation(MethodChannel.Result result, SqlCommand command) {
                                                         ^              
  symbol:   class SqlCommand                                            
  location: class ExecuteOperation                                      
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/SqlCommand.java:11: error: cannot find symbol
import static com.tekartik.sqflite.Constant.TAG;                        
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/SqlCommand.java:11: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.TAG;                        
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/SqflitePlugin.java:34: error: cannot find symbol
import static com.tekartik.sqflite.Constant.ERROR_BAD_PARAM;            
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/SqflitePlugin.java:34: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.ERROR_BAD_PARAM;            
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/SqflitePlugin.java:35: error: cannot find symbol
import static com.tekartik.sqflite.Constant.MEMORY_DATABASE_PATH;       
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/SqflitePlugin.java:35: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.MEMORY_DATABASE_PATH;       
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/SqflitePlugin.java:36: error: cannot find symbol
import static com.tekartik.sqflite.Constant.METHOD_BATCH;               
                                  ^                                     
  symbol:   class Constant                                              
  location: package com.tekartik.sqflite                                
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/SqflitePlugin.java:36: error: static import only from classes and interfaces
import static com.tekartik.sqflite.Constant.METHOD_BATCH;               
^                                                                       
/Users/vb/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.5/android/src/main/java/learnigo/tekartik/sqflite/SqflitePlugin.java:37: error: cannot find symbol
import static com.tekartik.sqflite.Constant.METHOD_CLOSE_DATABASE;     `

Doctor : 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.7.3, on Mac OS X 10.14.5 18F132, locale en-TR)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[!] iOS tools - develop for iOS devices
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
[✓] Android Studio
[!] IntelliJ IDEA Community Edition (version 2017.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)

**Comment by alextekartik** [comment]
Have you checked the troubleshooting section https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#troubleshooting to try the various clean/update build tricks?
