### ISSUE TITLE
Storing Custom Object type not supported?

### ISSUE THREAD

**Issue by basnetjiten** [tekartik/sqflite#226]
How do I store this NetworkList type in Sqflite database ? I don't know what should be the exact type in the table Column?

@JsonSerializable()
class NetworkResponseData {
  @JsonKey(name: "status")
  String status;
  @JsonKey(name: "language")
  Map<String, String> language;
  @JsonKey(name: "networks")
  NetworkList networkList;
  @JsonKey(name: "site_urls")
  Map<String, String> siteUrlMap;

  NetworkResponseData(this.status, this.language, this.networkList,
      this.siteUrlMap);

  factory NetworkResponseData.fromJson(Map<String, dynamic> json) => _$NetworkResponseDataFromJson(json);
  Map<String, dynamic> toJson() => _$NetworkResponseDataToJson(this);

}

@JsonSerializable()
class NetworkList {
  @JsonKey(name: "en")
  List<Map<String, String>> en;
  @JsonKey(name: "fr")
  List<Map<String, String>> fr;
  @JsonKey(name: "ge")
  List<Map<String, String>> ge;
  @JsonKey(name: "sp")
  List<Map<String, String>> sp;

  NetworkList(this.en, this.fr, this.ge, this.sp);

  factory NetworkList.fromJson(Map<String, dynamic> json) => _$NetworkListFromJson(json);
  Map<String, dynamic> toJson() => _$NetworkListToJson(this);

}

**Comment by basnetjiten** [comment]
Please don't be confused with the json_serialiazable here. In android SqLite we can store Object which is a property of another Class using Converter. I am asking is there any way I could save Map value or the NetworkList(as in my case) in the sqlite table format. There are scenarios where we need to save these kind of relation. Please help me with other solution if there are any. I am really in Trouble.

**Comment by basnetjiten** [comment]
I am concerned with storing these value
 NetworkList networkList;  and Map<String, String> siteUrlMap; like any other Text or Int type in database Column

**Comment by alextekartik** [comment]
I guess Android is doing some serialization at some point, sqlite simply does not support that. One solution is to json convert your maps and lists as a string.

**Comment by basnetjiten** [comment]
Ok I understand it. Here NetworkList networkList is a Object. It's just my naming Convention. That means I should convert this Object to String or json encoded value to store in the database. right ?

**Comment by alextekartik** [comment]
correct

**Comment by basnetjiten** [comment]
okay I will soon answer it in the stackoverflow if I got it working :) Thank you for your time :)
