### ISSUE TITLE
case-insensitive search has different results for not English letters on iOS and Android

### ISSUE THREAD

**Issue by moonvader** [tekartik/sqflite#231]
I see different search results on iOS and Android
search is made over cyrrylic TEXT field, on iOS it is case-sensitive and on Android it is case-insensitive

I expect it to be case-insensitive on both iOS and Android, this is query example

`db.rawQuery('SELECT * FROM contactsTable WHERE name LIKE \'%$search%\' LIMIT 10 OFFSET $offset');`

**Comment by robospot** [comment]
Thank god I'm not alone! I already thought that I was starting to go crazy.
I confirm, request 
 var res = await db
        .rawQuery("SELECT * FROM $table WHERE rusname  LIKE  '%$name%'");
returns wrong results on iOS for the cyrrylic symbols.  For Android everything is ok.

**Comment by TNorbury** [comment]
Have you tried using "COLLATE NOCASE" in your query? I was having an issue with case-sensitive sorting, and this fixed it (though this was for the English alphabet).
You would use it like this: `db.rawQuery('SELECT * FROM contactsTable WHERE name LIKE \'%$search%\' LIMIT 10 OFFSET $offset ORDER BY name COLLATE NOCASE');`

**Comment by maciogg** [comment]
Hi there

I check platform and use below code:
var collateString = Platform.isAndroid ? " COLLATE LOCALIZED " :" COLLATE NOCASE " ;
 return await db.rawQuery("SELECT * FROM " + tableName +" ORDER BY " + sortedBy + collateString + order); 

Problem I have is only with iOS.
Using COLLATE NOCASE records starting with polish letters are at the end :)

Any suggestions about iOS sorting?

**Comment by alextekartik** [comment]
One safe solution I see (and I use) is to add another column, storing a lower case ascii representation for safe sorting (or whatever make sense for sorting polish letters at the proper place). See https://stackoverflow.com/questions/16282083/how-to-ignore-accent-in-sqlite-query-android

**Comment by maciogg** [comment]
Finally I added additional column with duplicated data (but with removeDiacritics(string) function from 'diacritic' plugin/flutter). 
I spend few hours for googling :)
In my opinion sorting with national characters should be obvious function for SQLite

**Comment by alextekartik** [comment]
Thanks for the info about the diacritic plugin.

> In my opinion sorting with national characters should be obvious function for SQLite

Unfortunately we don't control how sqlite is compiled for all the supported platforms.

**Comment by ChandramaniPatel** [comment]
I had the sililer issue on one my App . where my iOS code failed to search for special character. my serach keyword always become case senstive once I entered the special character.
I do change the search word is **uppercase** ans well as **lowercase**  and then I just use OR statement with lowercase also.

before fixing the code (SQL query on )was like this below.
**SELECT * FROM PLACE WHERE Address LIKE '%mãe%'**
After Fix.
**SELECT * FROM PLACE WHERE (Address LIKE '%mãe%' OR Address LIKE ‘%MÃE%’ )**
