### ISSUE TITLE
Question: Is there a global Pragma foreign_keys = ON option or an onOpen functionality?

### ISSUE THREAD

**Issue by schachdavid** [tekartik/sqflite#238]
Because I use foreign keys with contraints in my tables I always need to excecute "PRAGMA foreign_keys = ON;".

For example:

```dart
await db.execute("PRAGMA foreign_keys = ON;");
var res = await db.delete("Notes", where: "id = ?", whereArgs: [id]);
```

Is there some way to always excecute this automatically before accessing the database?
In `SQLiteOpenHelper` for example you can put into `onOpen`. Is there something similiar for sqflite?

**Comment by alextekartik** [comment]
Yes there is an `onOpen` (last callback called) option during openDatabase. Personally I use `onConfigure` for the exact same purpose which is the first callback called: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_db.md#configuration

**Comment by schachdavid** [comment]
That is what I was looking for. Thank you and keep up the great work!
