### ISSUE TITLE
Create Index is impossible 

### ISSUE THREAD

**Issue by dblokhin** [tekartik/sqflite#242]
All attemps to create an index for a table fail. It doesnt work even db is pretty simple.
For example, this statement executes ok:
```dart
await db.execute('''
      CREATE TABLE test (
    f1 TEXT PRIMARY KEY NOT NULL,
    f2 INTEGER NOT NULL); 
      ''');
```
But:
```dart
await db.execute('CREATE INDEX test_index ON test(f2);');
```
Creating an index returns error:
```
E/SQLiteLog(17416): (1) near ">": syntax error
```
Does the plugin support work with indexes?

**Comment by alextekartik** [comment]
I was able to run your commands without issue. Are you sure the exception comes from this call (i.e. if you wrap with a try/catch, are your observing and catching such error?) From the example folder, you can add a unit test in the test_driver folder and run `flutter driver test_driver/main.dart`. Can you try to reproduce the error your are seeing in such a unit test?

**Comment by dblokhin** [comment]
Sorry for bothering you, it's really true the exception comes from another place.
Thank you for quick response!
