### ISSUE TITLE
Cannot read data from existing Database (.sqlite file)

### ISSUE THREAD

**Issue by kamalpreetus** [tekartik/sqflite#246]
I have an existing .sqlite database file that I'm trying to make read only queries against but I get no such table exception, here my code that tries to open the database + read from a table called sources (the table already exists in the db).

```
final String DB_NAME = "dbName.sqlite";

void runQuery() async {
    // Get a location using getDatabasesPath
    var databasesPath = await getDatabasesPath();
    String path = join(databasesPath, DB_NAME);

    // Check if the database exists
    var exists = await databaseExists(path);

    if (!exists) {
      // Should happen only the first time you launch your application
      print("Creating new copy from asset");

      // Make sure the parent directory exists
      try {
        await Directory(dirname(path)).create(recursive: true);
      } catch (_) {}
        
      // Copy from asset
      ByteData data = await rootBundle.load(path);
      List<int> bytes =
      data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      
      // Write and flush the bytes written
      await File(path).writeAsBytes(bytes, flush: true);

    } else {
      print("Opening existing database");
    }
    // open the database
    Database db = await openDatabase(path, readOnly: true);
    print(db.toString()); 

    **// THIS IS WHERE IT FAILS - IT CANNOT FIND THE TABLE SOURCES**
    var list = await db.rawQuery('SELECT * FROM sources');
    print(list.toList().toString());
    
    // Close the database
    await db.close();
  }
```

**Comment by alextekartik** [comment]
Can you try to run: `print(await db.query('sqlite_master', columns: ['name']));` to confirm that the table exists?

**Comment by kamalpreetus** [comment]
Looks like the problem was the the database file not correctly being added to the assests in `pubspec.yaml`.
I switched from vs code to android studio and started seeing `FlutterError: Unable to load asset` but I don't why this error didn't get caught before. I updated the code above to what worked for me. Thanks for your help.

**Comment by kamalpreetus** [comment]
You may also see this error after you correctly add the database asset: no such table exception. You need uninstall the application and reinstall it. Source: https://stackoverflow.com/questions/6554269/no-such-table-error-found-in-sqlite-android
