### ISSUE TITLE
0.6.0 Fails to Build for Dart Docs

### ISSUE THREAD

**Issue by Mohammed90** [tekartik/sqflite#25]
The docs for the current version 0.6.0 is not available and presented as HTTP 404 on DartDocs due to build failure which can be found here: [https://www.dartdocs.org/documentation/sqflite/0.6.0/log.txt](https://www.dartdocs.org/documentation/sqflite/0.6.0/log.txt). It complains about `Incompatible version constraints on async`.

**Comment by alextekartik** [comment]
Thanks. I will look into it. Maybe adding version constraints...

**Comment by alextekartik** [comment]
The issue is that dartdoc is using dartdoc from the regular sdk (1.24.2) and not from flutter. Can't figure out how to change that. In the mean time, you can get the doc here: https://www.dartdocs.org/documentation/sqflite/0.5.0 until I figure out how to fix that

**Comment by Mohammed90** [comment]
Interesting. I don't understand why it cares which version `pub` itself uses. Shouldn't it be independent from the project's implementation? Odd.

**Comment by Mohammed90** [comment]
The docs are correctly generated and served now.
