### ISSUE TITLE
is there any way to check the table exist?

### ISSUE THREAD

**Issue by zhancheng** [tekartik/sqflite#251]
cause i met the error 
```dart
DatabaseException(no such table: msgsssssList (code 1): , while compiling: SELECT * FROM msgsssssList WHERE uid = ?) sql 'SELECT * FROM msgsssssList WHERE uid = ?' args [2DZSK4YGTB7C]}
```

**Comment by alextekartik** [comment]
There is no helper API for that but you can query the sqlite_master table. More information here: https://www.sqlite.org/faq.html#q7

**Comment by zhancheng** [comment]
@alextekartik  thanks

**Comment by isjain35** [comment]
### **Yes**, there is a way to check if a table exists in database of sqflite in flutter:
You can do it by using query in this way:

**var result = await db.query('sqlite_master', where: 'name = ?', whereArgs: ['MyTable']);**

_Assuming: db has the path to database._
_Note: The value of 'result' will be [ ] (i.e. empty list) if the table does not exist and [ { Details of table } ] if it does._
