### ISSUE TITLE
Prepared Statement support

### ISSUE THREAD

**Issue by mertkokusen** [tekartik/sqflite#253]
Hello,

Thanks for this great package.
Is it possible to support prepared statements, or is it too much work with the current api structure? In the past I've benefited great performance gains with prepared statements while inserting huge amounts of data.

**Comment by alextekartik** [comment]
I have not used prepared statement much to have a strong opinion on it. Looking quickly into fmdb (the base of the iOS native implementation), I don't see any reference to prepared statement so I don't see yet how we could have a common dart implementation.

Now if inserting a lot of records are slow (have you tried a batch with `noResult: true`?) maybe we could consider having an 'insertAll' method to insert multiple records that could be optimized for Android. but I'm not sure what the benefit would be.
