### ISSUE TITLE
List Arguments Not Handled Properly

### ISSUE THREAD

**Issue by Pante** [tekartik/sqflite#254]
From my understanding , the following will not be converted properly which IMO is a defect.

```dart
database.rawQuery('''
SELECT * FROM WHERE a IN (?) AND b IN (?);
''', [['a', 'b', 'c'], [1, 2, 3]]);
```

**Comment by alextekartik** [comment]
Unfortunately that is not how it works on the native side (sqflite not involved here), you need to specify each argument in the lists:

```dart
database.rawQuery('''
SELECT * FROM WHERE a IN (?, ?, ?) AND b IN (?, ?; ?);
''', ['a', 'b', 'c', 1, 2, 3]);
```

**Comment by Pante** [comment]
That's a pity, in this case IMO it should then be documented.

**Comment by akx** [comment]
Just bumped into this too.

**Comment by alextekartik** [comment]
I added a section about this here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#parameters
