### ISSUE TITLE
Opening database android 9.0

### ISSUE THREAD

**Issue by brun0xon** [tekartik/sqflite#255]
The problem is in next situation: on first run (after install or deleting user data) my app checks if database is downloaded. If it's not downloaded then trying to download it using http get. After downloading (file was downloaded, I did check it), app again tries to read db, but it reads old db file(incorrect, because it throws DatabaseException "no such table") although it was replaced by new db file. After restarting, app loads correct db file and works fine. I tried both to close and not to close db instance, reinitiate db instance (using openDatabase() method) in between downloading and reading the file, nothing helped me. This app was tested on many os versions (Android 5.0, 5.1, 6.0, 8.1) and it was working fine but on Android 9.0 I watch problem described above . I think the problem is in implemented in Android 9.0 algorithm which works with app data in another place. Any ideas how to solve this problem?

**Comment by brun0xon** [comment]
Found a problem in linking in SQLite. 
`W/SQLiteLog(29640): (28) file unlinked while open: /data/user/0/...`
Before downloading new file, just remove old db file.

**Comment by JoseGeorges8** [comment]
Hey @brun0xon I'm trying to replicate a similar situation to yours were I update the db by downloading a zip file and replacing the db, I was wondering if you were using the assets folder for this

Thanks in advance!


>
