### ISSUE TITLE
Problem running Sqflite in Isolate.

### ISSUE THREAD

**Issue by brianoh** [tekartik/sqflite#258]
I'm getting the following error (below) when attempting to access Sqflite in an Isolate.

I had thought the problem may be caused by Singleton and db being already open. However, I think that I disabled that code in an attempt to temporarily overcome the problem, and the error still occurred. This is just the latest example of my attempts.

Code is below. Any help or suggestions welcome.
```
E/FlutterIsolate(28389): NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
E/FlutterIsolate(28389): It is possible the default GeneratedPluginRegistrant is attempting to register
E/FlutterIsolate(28389): a plugin that uses registrar.activity() or a similar method. Flutter Isolates have no
E/FlutterIsolate(28389): access to the activity() from the registrant. If the activity is being use to register
E/FlutterIsolate(28389): a method or event channel, have the plugin use registrar.context() instead. Alternatively
E/FlutterIsolate(28389): use a custom registrant for isolates, that only registers plugins that the isolate needs
E/FlutterIsolate(28389): to use.
I/flutter (28389): fnSelectDataFromDb: Error = MissingPluginException(No implementation found for method openDatabase on channel com.tekartik.sqflite)
```

```
import 'package:flutter_isolate/flutter_isolate.dart';
import 'dart:async';
import 'dart:isolate';
import 'package:sqflite/sqflite.dart';

Future<FlutterIsolate> fnCreateIsolate1() async {
  ReceivePort receivePort = ReceivePort();

  FlutterIsolate isolate = await FlutterIsolate.spawn(
    fnIsolateEntry,
    receivePort.sendPort,
  );
  receivePort.listen((result) {
    print('Result from Isolate = $result');
  });
  return isolate;
}

fnIsolateEntry(SendPort sendPort) async {
  Database db;
  List<Map<String, dynamic>> lsMapRecs;
  String sDbPath =
      "/data/user/0/com.example.timesheet01/app_flutter/Timesheets.db";
  String sSql = "Select * from clients";
  try {
    db = await openReadOnlyDatabase(sDbPath);
    if (db == null) throw ("Unable to open db");
    lsMapRecs = await db.rawQuery(sSql);
  } catch (vError) {
    print("fnSelectDataFromDb: Error = $vError");
  } finally {
    if (db != null) db.close();
  }
  await Future.delayed(Duration(seconds: 5));
  sendPort.send(lsMapRecs);
}
```

**Comment by alextekartik** [comment]
If it is still possible (the setup was a pain), this was discussed and solved here: https://github.com/tekartik/sqflite/issues/186. However I still recommend not using an isolate (sqflite already has its own threading) and I even thought this was not possible anymore...

**Comment by brianoh** [comment]
@alextekartik Thanks for getting back to me. I was able to run the @vishna example without any problems (issue 169). I gather that from what @rmawatson has stated in that issue, that the use of "custom registrant" can solve some problems. I would like to get experience using an Isolate, and Sqflite is really the only place that I can use it.  Do you think that by using a "custom registrant" that this would overcome the problem?

**Comment by alextekartik** [comment]
It seems so. However I don't want to add anything specific about isolate now in sqflite compared to other plugins. If it can work with flutter_isolate, let's use this!

**Comment by brianoh** [comment]
Perhaps my post was unclear. I did change the code in my app to use flutter_isolate and emulate what @vishna had done, and I couldn't get it to work (fatal error). I presumed that the reason that my code resulted in a fatal error was that there are many more imports than @vishna's. However, I will revisit the code and have another look. It's not critical to anything so I'm not trying to hassle you, just trying to understand the current situation. If it won't work I'll look for something else to try it on (flutter_isolate). Thanks for your work on Sqflite.

**Comment by alextekartik** [comment]
My other issue with using any isolate solution is that the current transaction mechanism in sqflite is not cross isolate safe so I'm unsure about concurrent writes behavior. I won't try isolate in the near future to be of good help unless supporting isolate is critical. I don't know how the official flutter plugins behave from an isolate neither.

**Comment by brianoh** [comment]
Ok, I don't need isolates to work with Sqflite, so I'll look for something else to try isolates on.
