### ISSUE TITLE
Unnamed columns causes problem with `print()`

### ISSUE THREAD

**Issue by dnfield** [tekartik/sqflite#26]
If you do, for example, a `GROUP BY` query without aliasing aggregated columns, `rawQuery` returns null.  For example,

```
await db.rawQuery('''
      select t.one, GROUP_CONCAT(t.another)
      from tbl t
      GROUP BY t.one''')
```

gives no way to access that unaliased column (?) - I initially thought it didn't return anything at all because `print` outputs nothing for it, but that doesn't seem to be the case now...

```
await db.rawQuery('''
      select t.one, GROUP_CONCAT(t.another) as anothers
      from tag t
      GROUP BY t.one''')
```

works as expected.  Thinking through the API (even without looking at the code), this makes some sense but should probably be documented and either handled or thrown.

I should add that I've tested this on iOS but not Android yet - I've had issues with gradle versions on Android I haven't sorted through just yet.

**Comment by dnfield** [comment]
So on more testing I'm no longer sure what the issue actually is.

In my first snippet above, `print()`ing the result gives no output (nor does `print(result.first)`), but `print(result.first['GROUP_CONCAT(t.another)'])` does give expected output for that column. I'm not sure why the print is failing...

**Comment by alextekartik** [comment]
Thanks for the report. I created an example from report here: https://github.com/tekartik/sqflite/blob/master/example/lib/exp_test_page.dart#L139-L182
Actually I managed to print result...and the behavior is as expected on Android (not tried on iOS yet). Can you manage to isolate a test?

**Comment by dnfield** [comment]
So I'm pretty convinced at this point that there's no problem with your code, but rather with the framework.  The keys/values are present, but calling `print()` or `toString()` on the map entry does nothing.  For example, in my testing on iOS, https://github.com/tekartik/sqflite/blob/master/example/lib/exp_test_page.dart#L164 prints nothing (nor does printing `$result.first.toString()`).  The value is there (so the `assert`s are good), but there's something up with `toString()` on the map.

**Comment by alextekartik** [comment]
indeed I tested on iOS simulator and I have the same issue, I can print before and after line 164, but the result does not appear...weird...don't known what to do here...

**Comment by dnfield** [comment]
This is definitely a dart or perhaps flutter bug.  The following code reproduces it independently of your library:
```
var map = [{
    'id': 123,
    'i)d': 'Foo,bar',
  }];
  print(map); // prints nothing, nor does map.first, nor does map.first.toString()
```

I'm thinking there's a bug with something in one of the `Map` implementations `toString()` when there's a `)` in the key.

**Comment by dnfield** [comment]
It's not `toString()`, it's print:

```
Map<String, dynamic> map = {
    'id': 123,
    'id)': 'Foo,bar',
  };
  print(map.toString() == '{id: 123, id): Foo,bar}'); // prints true
  print(map.toString()); // doesn't print
  ```
