### ISSUE TITLE
Add insertAll to Database

### ISSUE THREAD

**Issue by patroclos** [tekartik/sqflite#262]
sqlite supports inserting multiple rows at a time, so it would be nice to have a convenience method that would take an `Iterable<Map<String, dynamic>>` instead of the `Map<String, dynamic>`.

When building the SQL, values would have to be of the format `VALUES (...)[, (...)]` instead of `VALUES (...)`

**Comment by alextekartik** [comment]
I don't know what you would expect in terms of return values (the inserted row ids?) and how to read the results in a portable way (and whether that is supported in all shipping SQLite implementation). A batch with mutliple inserts - https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg68113.html - should be fast enough in most scenario. Maybe it would be worth comparing to a raw statement (which has its own flaws and performance issue if the maps have different fields).
