### ISSUE TITLE
Multiple DB query

### ISSUE THREAD

**Issue by hsombini** [tekartik/sqflite#263]
Hello Tekartik, first of all I would like to thank you for this great piece of software! It's really amazing and it works pretty flawless.

I'm working on a project that has multiple DBs, one is kinda of read only, it has alot of data and it gets fully removed and replaced by a new one every month, the other one is used for keeping some references based on the the big DB, I'm doing relational things between the DBs on the code right now but is getting messy, searching on Google I came across this:

"If ATTACH is activated in your build of Sqlite (it should be in most builds), you can attach another database file to the current connection using the ATTACH keyword."

```
attach 'database1.db' as db1;
attach 'database2.db' as db2;

select
  *
from
  db1.SomeTable a
    inner join 
  db2.SomeTable b on b.SomeColumn = a.SomeColumn;
```

There's any possibility to add this feature or should I take another approach to solve this problem?

**Comment by davidmartos96** [comment]
You can do that already. You just need to attach it after opening one of the databases.

```
var db = await openDatabase(db1Path);
db.execute('ATTACH db2 ... ');
```
