### ISSUE TITLE
Cannot copy sqflite to external directory (Android)

### ISSUE THREAD

**Issue by StephanCassel** [tekartik/sqflite#264]
Hi

I would like to copy a populated database file (sqflite) from my Flutter app to an external data directory (i.e Android/data/files) for examination via a SQL tool. Also it is very handy when you for example trying more complicated joins between tables.

The copy is not the problem but the content of the db file is a bit odd: "SQLite format 3....." and reset of the 4Kb is 0 (byte). In other words it seems that the database is empty but the db has plenty of data when it is used by the app. I probably grabbing wrong file, see code snippet below.

Anyone out there who has done this, **or any smarter approach**, I would be very happy for any help. 
Thanks in advanced.

// Source file
final databasePath = await getDatabasesPath();
final sourcePath = join(databasePath, 'mydb.db');
File sourceFile = File(sourcePath);
List<int> content = await sourceFile.readAsBytes();

// target file
final targetDir = await getExternalStorageDirectory();
final targetPath = join(targetDir.path, 'mydb.db');
File targetFile = File(targetPath);
await targetFile.writeAsBytes(content, flush: true);

**Comment by Sach97** [comment]
You should open your database file with a sqlite client like [sqlitebrowser](https://sqlitebrowser.org/)

**Comment by StephanCassel** [comment]
Thanks for your answer.
Yes I do that on daily basis from a native Android app. The user knocks 7 times on a particular screen and the sqlite DB is copied to an external folder and then sent via mail to me. Then I can monitor the content via tool you mentioned, or similar.
The problem is that the file seems to be empty. In other words: it is not correct file I get from the code above. 
Do you know how to "drag" a db file from a Flutter app?

**Comment by hyperpanthera** [comment]
You have to close the database connection and then copy. I requested an official Sqlite .backup feature, so we could copy it during runtime.

**Comment by StephanCassel** [comment]
Aha. Stupid me. I was sure it was flushed.
Thanks a ton

Den mån 9 sep. 2019 15:59hyperpanthera <notifications@github.com> skrev:

**Comment by hyperpanthera** [comment]
No problem.

**Comment by davidmartos96** [comment]
I think another option you have is to `await db.execute("VACUUM")` and then copy.

**Comment by StephanCassel** [comment]
Excellent. I will test that.
Thanks

Den mån 9 sep. 2019 16:03David Martos <notifications@github.com> skrev:

**Comment by hyperpanthera** [comment]
@davidmartos96 What does that do? Would love to know as well.

**Comment by davidmartos96** [comment]
I don't know how to answer you accurately, but basically, sqlite uses multiple files to persist the data, not only the .db/.sqlite Vacuum will merge those extra files into the main one. It's been a while since I tried it and I don't remember if the command "PRAGMA wal_checkpoint" needs to be executed before the VACUUM as well

**Comment by StephanCassel** [comment]
Closing the database did the trick.
(Still irritated over my self not trying this first)
Thanks

**Comment by pearlmaknun** [comment]
i close the database already but still can not

**Comment by sohelakhtar23** [comment]
Check out this article on medium for your issue.
[https://sohelakhtar23.medium.com/flutter-sqflite-database-backup-restore-import-export-db-18cf7377bdca](https://sohelakhtar23.medium.com/flutter-sqflite-database-backup-restore-import-export-db-18cf7377bdca)

**Comment by gputhige** [comment]
Hi
I have tried the above process with Android 11 (and with Manage External Storage Permissions), but there is no content in the copied file. 

 Future<File> _getLocalFile() async {
    final dbFolder = await getDatabasesPath();
    final sourcepath = join(dbFolder, 'Database.db');
    final sourcefile = File(sourcepath);
    content = await sourcefile.readAsBytes();

    return sourcefile;
  }

  Future<int> _copyFile(source1, copyTo, newpath, content) async {
    try {
      if ((await copyTo.exists())) {
        var status = await Permission.manageExternalStorage.status;
        print(status);

        if (await Permission.manageExternalStorage.request().isGranted) {
          print('Exists: Permission for External Storage Granted');
        }
      } else {
        print("not exist");
        if (await Permission.manageExternalStorage.request().isGranted) {
          print('Permission for External Storage Granted');
          await copyTo.create();
        } else {
          print('Please give permission');
        }
      }
    
      var newfile = await source1.writeAsBytes(content, flush: true);

    } catch (e) {
      print(e);
    }
    return 0;

Wondering what could be the issue here.
