### ISSUE TITLE
Unhandled Exception: FileSystemException: Cannot open file, path

### ISSUE THREAD

**Issue by kitet** [tekartik/sqflite#269]
the function getDatabasesPath causes error on Android 6.0

error:
`E/flutter ( 4424): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
E/flutter ( 4424): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 4424): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 4424): #3      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter ( 4424): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter ( 4424): #5      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter ( 4424): #6      Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter ( 4424): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
E/flutter ( 4424): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 4424): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 4424): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 4424): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 4424): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 4424): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)`

**Comment by hyperpanthera** [comment]
Post code.

**Comment by kitet** [comment]
`downloadFile() async {
    var dbDir = await getDatabasesPath();
    var dbFilepath = join(dbDir, 'motivational.db'); //using path package's join to concatenate
    var exists = await databaseExists(dbFilepath);
    exists ? _loadData() : _checkConnection();
  }`

**Comment by alextekartik** [comment]
Can you wrap your code in a try/catch to validate that it comes from this function? (getDatabasesPath does not call File.open)
