### ISSUE TITLE
Row too big to fit into CursorWindow 

### ISSUE THREAD

**Issue by Abalioglu** [tekartik/sqflite#270]
When I Upgrade my db following code

```
static Future<void> upgrade(Database db,int currentVersion,int newVersion) async{
    if(currentVersion<newVersion){
      
      await db.execute("ALTER TABLE konular ADD COLUMN ks INTEGER");
  
    }
  }
```

and I try to fetch table I get the error

> Exception has occurred. SqfliteDatabaseException (DatabaseException(Row too big to fit into CursorWindow requiredPos=0, totalRows=404) sql 'SELECT * FROM konular' args []})

**Comment by alextekartik** [comment]
That's the proper way (you can even drop the `COLUMN` keyword). I'm not sure what you mean by 'I think it didn't work', did you get an exception?

SQLite does not support dropping a column. You can see workaround here: https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite

**Comment by Abalioglu** [comment]
When I upgrade my current db i get the following error
`Exception has occurred.
SqfliteDatabaseException (DatabaseException(Row too big to fit into CursorWindow requiredPos=0, totalRows=404) sql 'SELECT * FROM konular' args []})`

I guess that's why I get the error.

**Comment by alextekartik** [comment]
I think there is 1MB limit on Cursor row (no proof of what I said though). If you have a big blob, I suggest saving it as a file instead (and store a pointer in the db)
