### ISSUE TITLE
Flutter DB insert issue.

### ISSUE THREAD

**Issue by Rajeshkannan1609** [tekartik/sqflite#271]
I try insert bulk(41K objects) data in flutter sqlite db it takes 8 mints more.I want to decrease the data insert time on the flutter sqlite.Is there any method available for insert bulk data with short period Kindly help me for shot out this issue.
Code:
  String url = 'https://www.*****.com/companyList';
  Map<String, String> headers = {"Content-type": "application/json","token":"$token"};
  var response =await http.get(url, headers: headers);
  print("response=$response");
  int statusCode = response.statusCode;
  var result = jsonDecode(response.body);
  var user = new User.fromJson(result);
User student = new User.fromJson(result);
 // var users = result['CompanyList'].map((result));
print('users*******************');
  // result = await databaseHelper.insertNote(result['CompanyList'].toString()); 
      String path = await initDeleteDb("batch.db");
      Database db = await openDatabase(path);
      Batch batch = db.batch();
 for (var j=0;j<user.shippingAddresses.length;j++) { 
         note.title = user.shippingAddresses[j].profileStatus;
   note.description = user.shippingAddresses[j].profileStatus;
     inserting(note); 
    } 

Future <String> inserting(Note note) async {
var result = await databaseHelper.insertNote(note);
print('result${result}');
//Loadingvalue = result.toString();
// _makeLoading();
}
Future <String> endingcall() async {
moveToLastScreen();
this.setState(() {
this._loading = false;
_progressHUD.state.dismiss();
});

}

Batch = db.batch(); batch.insert('Test', {'name': 'item'}); batch.update('Test', {'name': 'new_item'}, where: 'name = ?', whereArgs: ['item']); batch.delete('Test', where: 'name = ?', whereArgs: ['item']); results = await batch.commit();

**Comment by alextekartik** [comment]
In you loop, you should call `batch.insert()`. After exiting your loop, call `batch.commit()`. If needed, split in multiple batcesh (for example 1000 operations per batch). Example here: https://github.com/tekartik/sqflite/blob/091c998cdb92d681dde6cec80cca39a9b24cb632/sqflite/example/lib/slow_test_page.dart#L59-L64

**Comment by Rajeshkannan1609** [comment]
Dear @alextekartik  sir thanks for your reference above mentioned code works successfully.
