### ISSUE TITLE
Remove Flutter dependency

### ISSUE THREAD

**Issue by gisborne** [tekartik/sqflite#274]
It’s not obvious why this needs the flutter dependency.

Consider making this so it can be used in back-end code or other platforms. There is no just-dart sqlite package and frankly that’s a major hole in Dart’s capabilities.

Thanks for this, though. It’s great!

**Comment by alextekartik** [comment]
The implementation uses Flutter services so it can only be used on flutter (mobile). The subjective API itself and some dart code could be extracted to a non-flutter lib though. We'll see whether this is needed once we get a dart vm sqlite implementation (likely through ffi).
