### ISSUE TITLE
Unexpected type casting on result set ???

### ISSUE THREAD

**Issue by cornsauce** [tekartik/sqflite#282]
I have a table, like
```SQL
CREATE TABLE `${accountTable}` (
  account_id STRING,
  name STRING,
  properties STRING,
  created_at REAL,
  updated_at REAL
);
```

I have inserted and fetched one, use
```dart
var batch = database.batch();
batch.rawQuery('SELECT * FROM `${accountTable}` WHERE account_id = ?', [id]);
batch.rawQuery('SELECT * FROM `${accountProfileTable}` WHERE account_id = ?', [id]);
batch.rawQuery('SELECT * FROM `${accountConfigTable}` WHERE account_id = ?', [id]);
var rs = await batch.commit();
var accountRow = rs[0][0];
var accountProfileRow = rs[1][0];
var accountConfigRow = rs[2][0];
```
When I read the result by ```accountRow['account_id']```, I got an ` (int) 0 `, but a ` (String) 0 ` is expected.

How to prevent this case that type auto casting ???

**Comment by cornsauce** [comment]
Ohh Sorry... This is my wrong because the data type has wrong, shouldn't ` STRING `, but ` TEXT `.

I have resolved this problem, thx u : )

**Comment by alextekartik** [comment]
Unfortunately I'm not sure that there is much to do but adding a `?.toString()` to convert to a string. Sqlite seems very lazy about types. If the data was inserted as an int, it will likely be read as an int. I would have thought that text types should be fine though...
