### ISSUE TITLE
how to upgrade SQLITE version from 3.22 to 3.25 so i can use row_number()?

### ISSUE THREAD

**Issue by JoaoSaran** [tekartik/sqflite#284]

**Comment by alextekartik** [comment]
Since sqflite uses whatever sqlite the platform provides natively, it is not possible to change it. Bundling sqlite binaries for each platform and architecture is not currently the scope of this package.

**Comment by stevesmithworks** [comment]
This another reason @flutter should take on native SQLite support. Our apps that use SQLite should ship with the version of SQLite that we want not the one that the OS has.

**Comment by alextekartik** [comment]
Bundling a compiled version of sqlite has a serious impact on binary size, not everybody wants that. Most of the native Android and iOS app use the available sqlite implementation (event through CoreData or Room).

There is no way as I am aware of to have a package that supports both scenario (custom or existing sqlite)

**Comment by PiN73** [comment]
Now it's possible, thanks to @alextekartik: https://stackoverflow.com/a/70490593/6131611
