### ISSUE TITLE
Some wierd type returned by the rawQuery method

### ISSUE THREAD

**Issue by omar-bz** [tekartik/sqflite#286]
I am experiencing a weird behavior when using rawQuery method:
```
final q = await db.rawQuery(
        '''select *
         from table1, table2
         where table1.name = '$name' and table1.id = table2.owner 
         order by name;''');
print("List type: ${q.toList().map((e) {
          print("Element Type: ${e.runtimeType.toString()}");
          return e;
        }).toList().runtimeType.toString()}");
```
now the above code produces these output:
```
Element Type: QueryRow                          (<======= one time because i have only one match)
List type: List<Map<String, dynamic>>
```
as you can see the type of the list is what I need, but when I try to get the items their type is changed, is this a bug or I made a mistake???

**Comment by alextekartik** [comment]
Internally QueryRow is a Map<String, dynamic> so you should be fine. It is just an implementation detail

**Comment by omar-bz** [comment]
but it throws an error:
![image](https://user-images.githubusercontent.com/20848841/67111806-af1cca00-f1cd-11e9-95d3-55366ec35ddd.png)

**Comment by omar-bz** [comment]
I used HashMap instead of Map, closing....
