### ISSUE TITLE
DatabaseException ocurring on Ios (works on Android) when opening database from assets

### ISSUE THREAD

**Issue by Sach97** [tekartik/sqflite#289]
Hi @alextekartik I just revived my macbook to see if I could compile my app on ios and I was surprised to see this exception occurs on Ios : SqfliteDatabaseException (DatabaseException(Error Domain=FMDatabase Code=14 "unable to open database file" UserInfo={NSLocalizedDescription=unable to open database file}). 
I'm using the iphone 11 pro max emulator ios 13 on mojave 10.14.6. Any idea what is happening here ? Thank's for your great work. Here is my code on which the exception occurs

My DatabaseHelper code : 
```dart
class DatabaseHelper {
  static final DatabaseHelper _instance = DatabaseHelper.internal();

  factory DatabaseHelper() => _instance;

  static Database _db;

  Future<Database> get db async {
    if (_db != null) {
      return _db;
    }
    _db = await initDB();
    return _db;
  }

  DatabaseHelper.internal();
  //Creating a database with content.db in your directory
  initDB() async {
    Directory appDocDir = await getApplicationDocumentsDirectory();
    String path = join(appDocDir.path, 'content.db');
    // Check if the database exists
    final exists = await databaseExists(path);

    if (!exists) {
      // Should happen only the first time you launch your application
      print("Creating new copy from asset");

      // Copy from asset
      final data = await rootBundle.load(join('assets', 'content.db'));
      final bytes =
          data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      await File(path).writeAsBytes(bytes);
    } else {
      print("Opening existing database");
    }
    // open the database
    return await openDatabase(path);
  }

  Future<MydData> getMyData() async {
    final dbClient = await db;
    final List<Map<String, dynamic>> listResult = await dbClient
        .rawQuery(...);
  }}
```

**Comment by Sach97** [comment]
Nevermind I found the issue. I have an async main and I needed to ensure everything was loaded properly with `WidgetsFlutterBinding.ensureInitialized()`: 

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final db = DatabaseHelper();
```

**Comment by nvquangth** [comment]
I have same issue, althought I called  WidgetsFlutterBinding.ensureInitialized(); first

**Comment by zhuwei** [comment]
> Nevermind I found the issue. I have an async main and I needed to ensure everything was loaded properly with `WidgetsFlutterBinding.ensureInitialized()`:
> 
> ```dart
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   final db = DatabaseHelper();
> ```

It doesn't seem to work.
