### ISSUE TITLE
batch.insert

### ISSUE THREAD

**Issue by taihangg** [tekartik/sqflite#291]
thank you for the lib!

i got a failure when i am using Batch.insert, the step:

### **1.create table**

String _columnDate = "date";
String _columnID = "id";
String _columnDailyDone = "done";

CREATE TABLE ${tableDaily} (
${_columnDate} INTEGER,
${_columnID} INTEGER,
${_columnDailyDone} INTEGER,
primary key (${_columnDate}, ${_columnID})
);

### **2.insert**
Batch.insert(tableDaily, {
        _columnDate: date, _columnID: ID, _columnDailyDone: done});

it always cause a "UNIQUE constraint failed" exception with the right data,such like ( 20190829,1,1) and (20190830,1,1);

when i use Database.insert, it works well.
i am using v1.1.6+5

thank you!

---

my data is :
ID=1;
// Map<date,done>
dailyData=Map<int,int>{
20190829:1,
20190830:1,
20190831:1,
20190902:1,
20190903:1,
20190904:1,
20190905:1,
20190906:1,
20190913:1,
20190914:1,
20190915:1,
20190917:1,
20190918:1,
20190919:1,
20190920:1,
20190921:1,
20190922:1,
20190923:1,
20190924:1,
20190925:1,
20190926:1,
20190927:1,
20190928:1,
20190929:1,
20190930:1,
20191001:1,
20191002:1,
20191003:1,
20191004:1,
20191005:1,
20191006:1,
20191007:1,
20191008:1,
20191009:1,
20191010:1,
20191011:1,
20191012:1,
20191013:1,
20191014:1,
20191015:1,
20191016:1,
20191017:1,
20191018:1,
20191019:1,
20191020:1,
20191021:1,
20191022:1,
20191023:1,
20191024:1,
}

**Comment by taihangg** [comment]
and use batch.update data in a table which some word with unique constrant, the commit failed too.

**Comment by alextekartik** [comment]
Hard to help you sorry. Unique constraint are enforced at the sqlite level. (good if you can print the content on the table before the insert/update to see if there is any duplicated primary key).
