### ISSUE TITLE
Calling databaseExists() throws an error if ran from an manually installed .APK

### ISSUE THREAD

**Issue by k00na** [tekartik/sqflite#292]
Hello! 

**Description**
I am doing a rewrite of an existing native Android app with Flutter. I must gather the data from the previous native Android DB and import it into the new Flutter DB. **All works as expected, when I launch the Flutter app from the terminal. But when I export the APK and install it by hand on an Android device, I get an error when databaseExists() gets called**: 

**Error log**
_Error DatabaseException(database is locked (code 5), while 
compiling PRAGMA journal_mode…. 
Error code 5 - SQLITE_BUSY
Caused by “The database file is locked”_ 

**My sequence of commands**
This is the sequence on apps first launch, inside **initDB()**:
- check if platform is Android... if it is, call databaseExists() to check if the old native DB is present, 
- if it is present, load data from it and prepare it to be inserted into newly created DB of the Flutter app, 
- proceede to run openDatabase() on the Flutter DB   

The problem is that the whole thing crashes when databaseExists() gets called. 

**Workaround**
The workaround to avoid this error is to just try to open the database, without checking if it exists. But still one would expect that databaseExists() would do it's job, therefor I'm submitting this as an issue.

**Comment by alextekartik** [comment]
>  I get an error when databaseExists() gets called:

Weird as this method is just checking for the file to be present and not actually doing any sqlite database. Can you post the stacktrace?
