### ISSUE TITLE
is there any sample code for opening an existing data base?

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [tekartik/sqflite#293]
hi
im trying to make a quiz app and the questions and answers are in a sql database. but have no idea how to work with it. i would be appreciate if you show me some relate source codes.
thanks

**Comment by alextekartik** [comment]
Is this a question about how to bundle an existing sql database? If yes, it should be an asset that you can open like described here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_asset_db.md

If it is just a question about how to design a SQL database for your needs, you might want to try StackOverflow as this "issues" section is about well...reporting issues about sqflite.

Thanks!

**Comment by MojtabaTavakkoli** [comment]
yes i want to bundle an existing database. thanks for the tutorial but I wonder how can I bundle it in a List<>. Actually Im looking for the syntax to see how its going to be done.

What you mentioned there is just for opening the database but I want to read it into a List and use it somewhere in the app. something like this repo (https://github.com/lohanidamodar/flutter_opentrivia) but using sqflite instead of json.

**Comment by alextekartik** [comment]
Ok I guess StackOverflow will be a better place to ask such questions to get help from the community (including myself).
