### ISSUE TITLE
sqflite requires SDK version >=2.5.0 <3.0.0

### ISSUE THREAD

**Issue by VNAPNIC** [tekartik/sqflite#294]
I can't integrate this library

The current Dart SDK version is 2.4.0.
Because health_check depends on sqflite >=1.1.7-dev.1 which requires SDK version >=2.5.0 <3.0.0, version solving failed.

**Comment by alextekartik** [comment]
You can try to update your flutter sdk (stable uses dart 2.5) or lower you sqflite dependency (sqflite: any).
