### ISSUE TITLE
Create, upgrade and downgrade cannot change pragma foreign_keys

### ISSUE THREAD

**Issue by JamesMcIntosh** [tekartik/sqflite#297]
I've had to move away from the in-build upgrade mechanism because you cannot change the state of foreign key enforcement on the database if it has been set in `onConfigure`. This makes it impossible to make structural changes to tables using the suggested 12-step method in the SQLite docs as the first step is to disable foreign keys.
https://www.sqlite.org/draft/lang_altertable.html#otheralter

The source of the problem is the create/upgrade/downgrade procedure is wrapped in a transaction, see https://github.com/tekartik/sqflite/blob/master/sqflite/lib/src/database_mixin.dart#L677

From the docs https://sqlite.org/foreignkeys.html#fk_enable
"_It is not possible to enable or disable foreign key constraints in the middle of a multi-statement transaction (when SQLite is not in autocommit mode). Attempting to do so does not return an error; it simply has no effect._"

Pulling out this procedure into a method and adding an option to choose whether you wrap it in a transaction would be a way to allow the functionality.

**Comment by alextekartik** [comment]
It seems that you want an option like `dontCreateTransactionDuringOpen`.
Not having a transaction could have an edge case misbehavior if 2 processes open the database at the same time (could happen in the future) so I'm not sure it should be added.

I understand. That is indeed the limitation of the implementation. As it is hard to find the right settings for everyone, I think of 2 altenatives.

1) What I do usually during testing is to have my own versioning system implemented in the app, opening the database without any parameter and handling creation/migration manually through user version.

```dart
// Custom version handling
var db = await openDatabase('notes.db');

// We want version 2
var oldVersion = await db.getVersion();
var newVersion = 2;

if (oldVersion == 0) {
  // Create...
} else if (oldVersion == 1) {
  // Update...
}
if (oldVersion < newVersion) {
  // We are at version 2 now
  await db.setVersion(newVersion);
}
```

2) Maybe you could turn foreign keys off in onConfigure and turn it on later in onOpen (this is called after the transaction is closed)

**Comment by JamesMcIntosh** [comment]
Hi @alextekartik,

Thanks for the suggestions, I cannot do suggestion 2 as I want keys enabled in some of the upgrade steps and not others.

I've done something close to what you are suggesting in 1 by moving the upgrade code into `onOpen()` so I can control the transaction boundaries and turn off/on the keys for only the specific steps which modify the schema and increase the version number as I go.

From what you are saying though I would assume that suggestion 1 is fraught with the same danger as you are saying about the edge case of 2 processes opening the database at the same time. Is there something in the library to stop multiple executions of the upgrade onOpen code at the same time?

Would using your synchronized library around the database create / upgrade / downgrade code be enough to stop it running simultaneously?

James

**Comment by alextekartik** [comment]
> From what you are saying though I would assume that suggestion 1 is fraught with the same danger as you are saying about the edge case of 2 processes opening the database at the same time

Correct

> Is there something in the library to stop multiple executions of the upgrade onOpen code at the same time?

Inside our process, we are fine, yes, as there is already a lock to prevent this. I'm just speculating about the future, for desktop support if we have 2 processes. as of today, solution 1 (or what you are doing in onOpen) is safe on Android and iOS.
