### ISSUE TITLE
Using sqflite with Dart -- Error: Not found: 'dart:ui'

### ISSUE THREAD

**Issue by ali80** [tekartik/sqflite#298]
Hi, I am learning Dart, Flutter and SQL Database
I was wondering if it is possible to run sqflite directly from dart without dependency on "dart:ui" or flutter.
I am using windows and if I could have direct access to the database file it would be great.
Currently this is possible with hive, sembast and objectdb.

**Comment by alextekartik** [comment]
Unfortunately that is not possible for now. Sqflite only supports iOS and Android. There is no easy mocking.
