### ISSUE TITLE
Support Dart 2.0

### ISSUE THREAD

**Issue by rfuhrer** [tekartik/sqflite#30]
Looks like the strong typing in 2.0 stops the library from running:
```
E/flutter ( 5976): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 5976): type '_Future' is not a subtype of type 'Future<int>' where
E/flutter ( 5976):   _Future is from dart:async
E/flutter ( 5976):   Future is from dart:async
E/flutter ( 5976):   int is from dart:core
E/flutter ( 5976):
E/flutter ( 5976): #0      _openDatabase (package:sqflite/sqflite.dart:365:10)
E/flutter ( 5976): #1      openDatabase (package:sqflite/sqflite.dart:407:26)
```

Looks like the issue is that you have this method `Future wrapDatabaseException(action()) async {` which gets used in most calls like this:
```
Future<int> _openDatabase(String path) {
  return wrapDatabaseException(() {
```
so you're casting the `Future<dynamic>` to `Future<int>` which causes the new type checking to blow up.  I tried a couple things to see if I could fix it and maybe give you a pull request, but I've been using dart for about 3 days now and have no idea how you can cast these (just ramming `as Future<int>` in there also blows up) in some way that won't require rewriting a bunch of it.  The only thing that worked was basically changing all of these methods to return `Future<dynamic>` which sucks.

Great work on sqflite library! Made it super easy to screw around with sqlite in my project.  Thanks and let me know if there's some way I can help

**Comment by alextekartik** [comment]
Thanks for the note. I use channel alpha and master for testing so far. What is the way to reproduce the issue (i.e. special run command?)

**Comment by VeryVito** [comment]
I'll chime in, as I'm seeing the same issue. To run using Dart 2, ensure you've got the flutter SDK and use `run --preview-dart-2.` Full details can be found

**Comment by rfuhrer** [comment]
Once you run flutter in dart 2.0 mode it should fail for you as soon as you try to open a database. If you fix that command it'll then fail on running some raw SQL, and so on :)

I'm not sure if there's some way to make it do the check at compile time instead of runtime, but that would give you a full list of what's wrong

**Comment by alextekartik** [comment]
I was able to reproduce and make progress. I was only able to see the issue at runtime...The biggest issue seems to be the way the plugins Map/List returned values are encoded. For example I can no longer directly returned a `List<Map<String, dynamic>` object from a query. I created a `preview-dart-2` branch where I put the ugliest workarounds (basically wrapping List/Map returned from the plugin) and added some type annotations where needed (and where not needed too since it is hard to guess which one were really necessary).

The example work on `preview-dart-2` but I'd rather wait to see and understand what changes in plugins for Dart2. It might fails in many cases since I put some changes that I really don't understand why there are needed (for example when I need to re-implement first in a ListMixin...). I don't know whether the other plugins work on Dart2 too...

**Comment by VeryVito** [comment]
Thanks for the quick response, @alextekartik. I too would love to jump in, but my comfort level with Dart's type and async schemes is still shaky at best. Hoping that changes quickly, but for now I'll leave it to someone who knows what they're doing.

**Comment by alextekartik** [comment]
Well I tried the flutter shared_preferences plugin and it has similar issue. I filled an issue here on that: https://github.com/flutter/flutter/issues/14921

My guess at this point is that something changed regarding plugins. I will follow up on that

**Comment by rfuhrer** [comment]
Good stuff.  I was just poking around the dartlang reddit and gitter and didn't see anything about how to update libraries (other than them talking about how to do versioning so you don't force dart 2.0 changes on dart 1.0 users).  Hopefully the flutter team fixing their own plugin will give you a guide as to how to fix this one

**Comment by alextekartik** [comment]
I published a version 0.7.0 that work with `--preview-dart-2` (and without). Let me know if that works for you

**Comment by rfuhrer** [comment]
@alextekartik Works great! I had to do a `flutter clean` before it stopped using the old sqflite version, but I think that might have been since I was screwing with the library myself and it had a local copy with my changes.

So, to get it running all I did was: `flutter upgrade` and then `flutter clean` and then `flutter run --preview-dart-2`

Great work! I was looking forward to trying Dart 2 with the new syntax for building widgets, seemed a little less verbose but then when this plugin died I had to revert as my "Stat tracking" app is useless without a database 😃

**Comment by rfuhrer** [comment]
Well, almost able to use dart 2.0.0 haha: https://github.com/Dart-Code/Dart-Code/issues/625
It works well if I run the commandline flutter so I'm still good.  Feel free to close this issue unless there's some more testing you want to do or something

**Comment by mfahy** [comment]
Perfect! Thanks!
