### ISSUE TITLE
Question: is there a way to create SQLite user-defined functions.

### ISSUE THREAD

**Issue by moovida** [tekartik/sqflite#304]
I am coming from the java world and with the xerial jdbc drivers I would be able to add user defined functions like this:

```
     Function.create(conn, "myFunc", new Function() {
          protected void xFunc() {
              System.out.println("myFunc called!");
          }
      });
```

Is there any similar way to create user defined functions in sqflite?

And sure thank you for this great project!

**Comment by alextekartik** [comment]
Currently there is no way to create a C/C++ callback (as I think that is how they are implemented in sqlite). Using the flutter plugin mechnanism, hooking this would be super slow. Maybe an ffi implementation could allow that but currently sqflite is not using ffi (It is under consideration but no work planned so far and it would likely be a separate non-flutter project)

**Comment by moovida** [comment]
Thanks for the feedback @alextekartik

**Comment by moovida** [comment]
Please allow me to come back to this question @alextekartik 

I have seen that there is a part related to ffi in the project. Does this open a possibility for functions?

**Comment by alextekartik** [comment]
the ffi implementation in https://pub.dev/packages/sqflite_common_ffi uses https://pub.dev/packages/moor_ffi. I don't think it supports custom functions but I think it should be possible (so you might ask). sqflite package itself is not using ffi.
