### ISSUE TITLE
FlutterJNI was detached from native C++. Could not send. Channel: flutter_branch_io/event. Response ID: 0

### ISSUE THREAD

**Issue by nirav-patel-logical** [tekartik/sqflite#313]
Hi,
I am facing issue in the flutter. 
I am using "flutter_branch_io_plugin 1.0.1" for branch.io integrate with my flutter application.
When I tried to get deep linking data from FlutterBranchIoPlugin using below method

 FlutterBranchIoPlugin.listenToDeepLinkStream().listen((string) {
      print("DEEPLINK $string");
      print("DEEPLINK $string");
      // PROCESS DEEPLINK HERE
    });
In android studio print below message.
Error "Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter_branch_io/event. Response ID: 0"

**Comment by alextekartik** [comment]
This repository is about sqflite not about flutter_branch_io_plugin. I cannot really help. Please submit your issue here: https://github.com/blackmenthor/flutter-branch-io/issues
