### ISSUE TITLE
cannot run example on iPhone

### ISSUE THREAD

**Issue by hellowtisch** [tekartik/sqflite#314]
Hi,

I am trying to get the example to run on my iPhone 7 running iOS 13.2.3

In XCode I get the following errors directly in  main.m:
2019-11-22 14:38:33.133831+0100 Runner[654:105737] Metal API Validation Enabled
2019-11-22 14:38:33.260569+0100 Runner[654:105992] flutter: Observatory listening on http://127.0.0.1:55365/-TXx0RvZhDY=/
2019-11-22 14:38:33.706054+0100 Runner[654:105737] -[AppDelegate applicationDidBecomeActive:]: unrecognized selector sent to instance 0x2823dce60
2019-11-22 14:38:33.706320+0100 Runner[654:105737] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate applicationDidBecomeActive:]: unrecognized selector sent to instance 0x2823dce60'
*** First throw call stack:
(0x1c071980c 0x1c0441fa4 0x1c061d36c 0x1c47b0710 0x1c071da00 0x1c071fa6c 0x104665fe8 0x1c4777a70 0x1c3f4f2a8 0x1c3f4f5f0 0x1c3f4eeac 0x1c3f533c8 0x1c43166a4 0x1c43fd5b0 0x1c3f53100 0x1c43fd4ac 0x1c3f52f6c 0x1c3dc4ba4 0x1c3dc370c 0x1c3dc48dc 0x1c433750c 0x1c581f2f8 0x1c5843dd8 0x1c5828fb4 0x1c5843d0c 0x10686ebd8 0x106871ffc 0x1c58684c8 0x1c5868194 0x1c58686bc 0x1c06977c4 0x1c069771c 0x1c0696eb4 0x1c0692000 0x1c06918a0 0x1ca5e9328 0x1c4782768 0x1046661ec 0x1c051c360)
libc++abi.dylib: terminating with uncaught exception of type NSException

my flutter doctor output is:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!

On Android everything works well...

Thanks for any hint

**Comment by alextekartik** [comment]
Thanks for the report, I will look into it (iOS build remains a pain...)

**Comment by hellowtisch** [comment]
Update: the error occurred after I removed the errors related to missing development team etc... I added a screenshot from XCode
<img width="876" alt="error" src="https://user-images.githubusercontent.com/5956873/69448590-290a1b00-0d59-11ea-88cf-4dea5548abd3.png">

**Comment by alextekartik** [comment]
The example ios project was really outdated. I try to follow some changes they were doing in the flutter/plugins repository. I did get the same error (unfortunately I don't have any ios 13 device to test yet, only simulator and ios 12 device) that I fixed in the master branch. Can you try again?

**Comment by hellowtisch** [comment]
yes, it does work again on iOS!


Thank you

**Comment by tedhenry100** [comment]
@hellowtisch Can this issue be closed?

**Comment by hellowtisch** [comment]
yes thanks
