### ISSUE TITLE
Asset database copy wont update

### ISSUE THREAD

**Issue by PramodJoshi** [tekartik/sqflite#318]
Hi, I followed [https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_asset_db.md](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_asset_db.md) instructions to create a copy of asset database and all the read functions are working fine. However, i am unable to update any data. 

I am opening the copy by turning off read-only and singleInstance mode as,

`await openDatabase(path, singleInstance: false);`

I can include a runnable if needed but this is a long process so first I wanted to see if i missed anything obvious or if this is even supported.

**Comment by alextekartik** [comment]
I would recommand using `singleInstance: true`. using multiple instance has the risk of having the database blocked in another connection (hot/reload causes that)
