### ISSUE TITLE
Cascade delete?

### ISSUE THREAD

**Issue by vysotsky** [tekartik/sqflite#319]
Hi, I wonder how to implement cascade delete? I've added `ON DELETE CASCADE ` but seems that it's even not used for database creation as Sqlite Viewer shows me that schemas don't have such line.

**Comment by alextekartik** [comment]
Foreign keys are off by default, this can be configured using the following onConfigure during open:

```dart
/// Let's use FOREIGN KEY constraints
Future onConfigure(Database db) async {
  await db.execute('PRAGMA foreign_keys = ON');
}
```

The [migration example](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/migration_example.md) uses `ON DELETE CASCADE` if that can help

**Comment by vysotsky** [comment]
@alextekartik thanks. Yep, I had enabled `PRAGMA foreign_keys = ON ` when I created this ticket. Anyway, it seems that I was doing something in a wrong way if you say that `ON DELETE CASCADE` should work. I'll figure it out by myself and let you know if it still doesn't work. Again, thanks!

**Comment by rgb1380** [comment]
@vysotsky  did you manage to solve your issue?
I have enabled 'PRAGMA foreign_keys = ON' in both onConfigure and onOpen but still no joy with ON DELETE CASCADE.
