### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by qwilbird** [tekartik/sqflite#32]
Hi,

thank you for making sqlite available for Flutter - I need to use sqlite with encryption - do you know how the normal way to use encryption with sqlite could be implemented?

https://www.sqlite.org/see/doc/trunk/www/readme.wiki

Thanks!

**Comment by alextekartik** [comment]
Thanks for the note. According to my knowledge, you might need to build your own sqlite native library first, interface to it, bundle the various binaries... There is currently no portable way to support encryption on both iOS and Android as we use whatever version the platform provide. I don't know the feasibility at this point for such thing but it is not in the scope of this library (at least yet)

**Comment by long1eu** [comment]
https://github.com/long1eu/encrypted_sqlite It is build on top if this library

**Comment by g123k** [comment]
@long1eu Will you publish your plugin on pub?

**Comment by long1eu** [comment]
Not sure how to go with this, because only the underlaying sqlite has
changed, the dart part it's mostly the same. So unless there is a big
difference in the implementation of the dart part, I don't find a reason to
publish it on pub.

**Comment by henrysachs** [comment]
Hi is this still out of Scope and if so @long1eu could you say a few words about your Solution.

**Comment by zimmi** [comment]
Would you consider a pull request for this @alextekartik ?
If @long1eu agrees, I'd like to pull his changes (or a variation of them) back into sqflite.
Looking through the changes, they don't seem overly intrusive to me:

iOS
1. Switch dependency from `FMDB` to `FMDB/SQLCipher`
1. [use the password if provided](https://github.com/tekartik/sqflite/commit/d3da8b2ebdf2588580d756a43e060005322abde9#diff-15b4e2fd626c13eebb1ce66b1f032d8fR494)

Android
1. Add dependency on `net.zetetic:android-database-sqlcipher:3.5.9@aar`
   (@long1eu you seem to have unpacked the aar manually, do you remember why?)
1. Replace package `android.database` with `net.sqlcipher.database`
1. [use the password if provided](https://github.com/tekartik/sqflite/commit/c9fc65ec6a72e26a4ae4e6824f787ada326db900#diff-41d742e3f7b8cbb2ede894b7b4dafd2fR168)

Flutter
1. Add optional named parameter `password` to `openDatabase`
1. Add tests

Of course, this change will package sqlite (SQLCipher) with the plugin, increasing the app size. On the other hand, this will make versions consistent across platforms, helping predictability.

Additional use cases to implement later:
- changing passwords
- encrypting previously unencrypted database
- unencrypting previously encrypted database

**Comment by jaumard** [comment]
That functionality would be nice indeed :)

> Of course, this change will package sqlite (SQLCipher) with the plugin, increasing the app size. On the other hand, this will make versions consistent across platforms, helping predictability.

Helping predictability is a huge advantage as at least you'll know which version of sqlite you have and which keywords are available. Because for now we can't easily know which version we'll have and so maybe some request will not work on older version of sqlite. I start working on Jaguar ORM (https://github.com/Jaguar-dart/jaguar_orm) to make a sqflite adapter and have an ORM in flutter so having predictable version of SQLite would be awesome ^^

**Comment by alextekartik** [comment]
Thanks of the details on how to use SQLCiipher
Indeed maintaining a cipher and non-cipher version of about the same code on the native side could be a pain. However I'd like if we can keep having this current light weight version. For many basic database scenario, it works. Most of the code (dart and native) could be shared so maybe building a `sqflite_cipher` on top of the existing one could be one solution. Maybe having a `sqflite_common` package that both could reuse could be another one. I look into that. I need first to play a little bit with the encrypted version. Not having an easy ability to run unit tests with plugins is still a pain.

**Comment by henrysachs** [comment]
Any updates on this? :)

**Comment by alextekartik** [comment]
No new sorry @henrysachs ! Since I don't have a need for myself (I always started an open source project when I had a need for my job), at this point I'm not sure I can devote my free time on creating/maintaining such sqflite_cipher component that would require some significant work although @long1eu tackled most of the hard duties. 

https://github.com/long1eu/encrypted_sqlite  is currently the best solution. Have you tried it?

**Comment by artob** [comment]
For those interested in SQLite database encryption: I'm actively working on [flutter_sqlcipher](https://pub.dartlang.org/packages/flutter_sqlcipher), a Flutter plugin that bundles and wraps SQLCipher. At present, it is not as featureful and convenient as the sqflite plugin, and it doesn't have iOS support as yet, but for those developing primarily for Android it is already quite usable. Find the project at [drydart/flutter_sqlcipher](https://github.com/drydart/flutter_sqlcipher).

**Comment by alextekartik** [comment]
@jlcool you should ask directly to project owner in the repo you pointed. Currently encryption is not supported in sqflite. A sqflite_cipher project could share most of the dart code with sqflite but unless I get dedicated time and project for it, I won't tackle it soon.

**Comment by jlcool** [comment]
I don't seem to be able to ask questions there. I just said that here. I hope you have time to add encryption. Thank you.

**Comment by jlcool** [comment]
My problem is that the sqlcipher used by IOS is the latest 4.1. However, 4.1 can not open the previous database. The project @long1eu provided can be used. It seems that the modification is not complicated. I don't know why sqflite does not provide it.

**Comment by davidmartos96** [comment]
I recently forked this library to include SQLCipher for my own project. It includes the latest version of SQLCIpher, 4.10 and it works for Android and iOS.

https://github.com/davidmartos96/sqflite_sqlcipher

To include it in your project you can put this in your pubspec.yaml

```
sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
```
It has minimal differences with this library, so I am guessing it will not be hard to keep it updated.

**Comment by binodlohani** [comment]
> No new sorry @henrysachs ! Since I don't have a need for myself (I always started an open source project when I had a need for my job), at this point I'm not sure I can devote my free time on creating/maintaining such sqflite_cipher component that would require some significant work although @long1eu tackled most of the hard duties.
> 
> https://github.com/long1eu/encrypted_sqlite is currently the best solution. Have you tried it?

Works well in Android .
In case of Ios, produce error while opening database (I guess). Exception is 
------------------
SqfliteDatabaseException (DatabaseException(Error Domain=FMDatabase Code=26 "file is not a database" UserInfo={NSLocalizedDescription=file is not a database}) sql 'BEGIN EXCLUSIVE' args []})
------------------

Any idea What to do ??

**Comment by davidmartos96** [comment]
@binodlohani Maybe it is due to the SqlCipher version you are using and the one in the library. That library uses SqlCipher 3.x 
You can try my fork (linked in a previous comment) which handles databases in SqlCipher 4.x and automatically migrates the ones using version 3.x

**Comment by jlcool** [comment]
@binodlohani
Modification of file
 /ios/sqflite.podspec   
s.dependency 'FMDB/SQLCipher'
s.dependency 'SQLCipher', '~>3.4.2'

**Comment by JoseGeorges8** [comment]
Just from experience, I had a similar scenario and what I did was use https://pub.dev/packages/encrypt to encrypt strings with a public key, and then decrypt them when retrieving the data with a private key

**Comment by omidraha** [comment]
It seems separate solutions are out of date.

https://github.com/QwilApp/encrypted_sqlite (2 years ago)
https://github.com/drydart/flutter_sqlcipher (14 months ago )
https://github.com/davidmartos96/sqflite_sqlcipher (2 months ago)

**Comment by ahzmie** [comment]
Is there any simple way to just set a password for the sqlite DB ?

**Comment by alextekartik** [comment]
@ahzmie https://pub.dev/packages/sqflite_sqlcipher from @davidmartos96 allows using a password (it shares most of its dart code with sqflite).

**Comment by alextekartik** [comment]
I have added some docs on this topic:
* [Notes about Encryption support](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/encryption_support.md)

that I copy here for quick reference:

# Encryption support

Encryption is supported on Android, iOS and MacOS support using [`sqflite_sqlcipher`](https://pub.dev/packages/sqflite_sqlcipher)
by David Martos which has some shared code through `sqflite_common` package.

On desktop, encryption is provided by [`sqflite_common_ffi`](https://pub.dev/packages/sqflite_common_ffi).
Since support is provided both on flutter and on DartVM on MacOS/Linux/Windows, it is not a flutter plugin.
See [here](https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/encryption_support.md) for more information
of how encryption is supported on Desktop.
