### ISSUE TITLE
why Unsupported operation: read-only？

### ISSUE THREAD

**Issue by GanZhiXiong** [tekartik/sqflite#326]
The result after query is List<Map<String, dynamic>> maps
I return an error when I execute the following code
```
      for (var item in maps) {
        item['name'] = 'new name';
      }
```
An error is as follows
`flutter: Unsupported operation: read-only`

**Comment by alextekartik** [comment]
Indeed the maps are read-only for permance as its data come from the native world and cannot be modify easily without cloing the data first. See the comment here: https://github.com/tekartik/sqflite/issues/140#issuecomment-451881301
