### ISSUE TITLE
Multiple data cannot be deleted

### ISSUE THREAD

**Issue by GanZhiXiong** [tekartik/sqflite#328]
`db.delete(name, where: 'id = ?', whereArgs: [1, 2, 3])`
The above code cannot delete data whose id are 1, 2, or 3
**just delete data with id 1**

Is my code wrong?  or does the delete method only support deleting one piece of data? What if I want to delete multiple pieces of data?

**Comment by alextekartik** [comment]
See https://github.com/tekartik/sqflite/issues/15
Basically you have to do something like:

```dart
db.delete(name, where: 'id IN (?, ?, ?)', whereArgs: [1, 2, 3])
```

May I suggest checking the regular SQLite documentation first (ok I admit it is not the simplest to browser) or asking Stackoverflow, this package cannot give all the help needed on SQLite and you could get answer from the community.

**Comment by GanZhiXiong** [comment]
Very quick response, Thanks！😀
