### ISSUE TITLE
My failing attempts to return Streams rather than Futures of Lists

### ISSUE THREAD

**Issue by hicnar** [tekartik/sqflite#329]
Hi folks,

I have a question regarding the results returned by the ```Database.query(...)``` method.
So, I am trying to convert the ```Future<List<Map<String, dynamic>>>``` returned by the ```Database.query(...)``` into ```Stream<Map<String, dynamic>>``` but I am getting somewhat unexpected results.

My confused mind could do with the fact that I am relatively new to Dart, so if you find some obvious mistakes I will be grateful if you point them out

In the test scenario the database table is populated with two records both matching the query, so as a result both records should be returned.

In the screenshot below, the first function -> ```Stream<Map<String, dynamic>> get _getDocumentMapStream async*``` attempts to return the ```Stream```. 
Now, if the source ```List``` is the ```testDocuments``` the resulting stream will emit two entries. If hovewer the source is set to ```testDocuments2``` (returned from the database) the resulting stream will emit only one result (and the ```List.length returns``` ```1``` too).

Below that, there is another function: ```Future<List<Map<String, dynamic>>> get _getDocumentMapList async ```  that executes exactly the same query and in the same test scenario every time returns a list with two elements as expected.

I am aware of the streamqflite wrapper plugin, but it produces exactly the same results.
Again, if there is something obviously wrong with my approach let me know.

![Streamzzz](https://user-images.githubusercontent.com/1816194/70805282-73a71200-1db0-11ea-810b-a19566789567.png)

**Comment by alextekartik** [comment]
>  If hovewer the source is set to testDocuments2 (returned from the database) the resulting stream will emit only one result (and the List.length returns 1 too)

Indeed if the list if of length 1, the stream will emit only once.

Other than that, indeed that's puzzling and it don't see any obvious mistake.
