### ISSUE TITLE
Should ConflictAlgorithm be expose?

### ISSUE THREAD

**Issue by yathit** [tekartik/sqflite#33]
To avoid requiring `import 'package:sqflite/src/sql_builder.dart' show ConflictAlgorithm;` in which, dart analyzer complain about not to import from `src` folder.

**Comment by alextekartik** [comment]
Yeah I'm not sure about the export yet.In the current version, you can use the following public import:
````dart
import 'package:sqflite/sql.dart';
````
I have not done much testing on it so scenario with this option are welcomed for my own testing

**Comment by yathit** [comment]
Sorry, I did not know to import `sq.dart`. I just taken as suggested by IDE. May be you could export all in `sqflite.dart`.

**Comment by alextekartik** [comment]
`sql.dart` could become part of a separate package in the future (we can build sql commands without sqflite) so I'd rather not export it yet (although ConflitAlgorithm is used in an API in sqflite.dart so we'd better define it...so I might decide to only export this class soon! - sorry still thiking out loud). Thanks for the report
