### ISSUE TITLE
Request In memory database

### ISSUE THREAD

**Issue by LeTadas** [tekartik/sqflite#332]

**Comment by LeTadas** [comment]
Please add in memory database support

**Comment by alextekartik** [comment]
Although not documented, you can use `inMemoryDatabasePath` as the path argument in `openDatabase` to open a database in memory.

**Comment by LeTadas** [comment]
When using inMemoryDatabasePath it throws error in unit test:

> ERROR: MissingPluginException(No implementation found for method openDatabase on channel com.tekartik.sqflite)

**Comment by alextekartik** [comment]
That's a different issue. Testing code with plugin remains a pain. See doc here:
https://github.com/tekartik/sqflite/blob/master/sqflite/doc/testing.md

And the following issue:
https://github.com/tekartik/sqflite/issues/49
