### ISSUE TITLE
Readme CAP typo?

### ISSUE THREAD

**Issue by jdeltoft** [tekartik/sqflite#336]
Not sure if it matters since I can't test right now.  But reading this confused me.  The VALUE I think should be lowercase.

> // Update some record
int count = await database.rawUpdate(
    'UPDATE Test SET name = ?, VALUE = ? WHERE name = ?',
    ['updated name', '9876', 'some name']);
print('updated: $count');

**Comment by alextekartik** [comment]
Thanks for spotting this. Indeed, I tend to use UpperCamelCase for table name, lowerCamelCase for column name and UPPERCASE for SQLite keywords. Not always following this (subjective and personal) rule for the doc can make this confusing as you noticed. I fixed it although it might not be in pub until the next version is published.
