### ISSUE TITLE
Store and Query on nested json object

### ISSUE THREAD

**Issue by rizwan-dev** [tekartik/sqflite#340]
In my application, I need to store nested json objects. Then I need to perform query on those stored json objects. I have approx 50000 records to store. I don't want to use traditional rdbms approach because of performance issue due to join on 5 tables in my case. Because of this I want to store json object directly and want to query on that.
Is Sqflite will support my requirements? Is there any performance issue with storing and quering json objects in Sqflite.

**Comment by alextekartik** [comment]
Assuming you store a json text in a string column, there is no way to efficiently perform queries on the json data. Each field that you want to filter on (>=, <=, LIKE) must be extracted in its own column.
