### ISSUE TITLE
execute

### ISSUE THREAD

**Issue by blondie63** [tekartik/sqflite#345]
Hi, on your doc https://pub.dev/documentation/sqflite/latest/sqlite_api/DatabaseExecutor/execute.html
i don't understand how reference to DB..
this my example
``` 
void addIndexesToLocalDb (path) async {
    logger.d("DatabaseManager addIndexesToLocalDb");
    Database db = await openDatabase(path);
    db.execute("CREATE INDEX IF NOT EXISTS resources_idx ON resources(element_id, element_type, file_name);");
    //Future<void> execute("CREATE INDEX IF NOT EXISTS resources_idx ON resources(element_id, element_type, file_name);");

  }
```
commented row copyed from your doc does'nt works..

whats wrong ?

**Comment by alextekartik** [comment]
The doc you pointed at is generated, I don't control that, it is just an interface definition not an example. You should use it like you did (but you'd better await it):

```dart
await db.execute("CREATE INDEX IF NOT EXISTS resources_idx ON resources(element_id, element_type, file_name);");
```

See usage doc here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#execute

**Comment by blondie63** [comment]
thanks
