### ISSUE TITLE
can't execute in background

### ISSUE THREAD

**Issue by AmjadKhan2k18** [tekartik/sqflite#346]
I am trying to execute insert query in background

for background service i am using workmanager plugin latest version & sqflite version is latest too
when i run code using onPress it work fine and new value is inserted but when code execute in background it doesn't work

do i need to add anything extra for background execution ? 

workmanager work fine it execute in every 15 minutes and i see the debug it execute insert function from DatabaseHelper class but it doesn't execute successfully 
`
dbHelper.insert({DatabaseHelper.catTitle: "$now"},
      DatabaseHelper.categoryTable).catchError((onError) {
    print(onError.toString());
  }).then((value) {
    print('$value');
  });
`

**Comment by alextekartik** [comment]
This is not supported at the moment. Sqflite already execute data access in a background thread.

See https://github.com/tekartik/sqflite/issues/258.
