### ISSUE TITLE
Failed to change locale for db to 'ru_RU'.

### ISSUE THREAD

**Issue by ctac1287** [tekartik/sqflite#35]
When i try insert record in db on Russian language, i have exception: Failed to change locale for db '...' to 'ru_RU'.
How i can change locale ?

**Comment by alextekartik** [comment]
Thanks for the report. It would be great if i could reproduce it.
* is it on Android?
* do you open an existing db copied from the asset folder? If yes where was this db created and can you share it?
* could it be related to that: https://stackoverflow.com/questions/19491675/failed-to-change-locale-for-db-data-data-my-easymedi-controller-databases-easy

I have to admit that I did know that there was any locale support on sqlite...I will take a look but any information is welcome!

**Comment by ctac1287** [comment]
I was wrong. The error did not arise from the write text in the Russian language in db. And because of reading\writing\creating the database simultaneously from two objects. Apparently I was confused in await\then calls. Sorry, but I did not have the source code.  If the error is repeated again, I will give the code. And sorry for my english. Thank you!
