### ISSUE TITLE
AUTO_INCREMENT cause wrong

### ISSUE THREAD

**Issue by huhuang03** [tekartik/sqflite#350]
I tried change the example's `Open onCreate` test.  The sql `CREATE TABLE Test2 (id INTEGER PRIMARY KEY)` to CREATE TABLE Test2 (id INTEGER PRIMARY KEY **AUTO_INCREMENT**).  And it let the test fails.

So how can I define a `AUTO_INCREMENT` field?

**Comment by alextekartik** [comment]
SQLite has it own (lighter) SQL syntax and does not support all SQL commands. See https://www.sqlite.org/index.html for more information. For example AUTOINCREMENT is one word, no underline space in the middle.

**Comment by huhuang03** [comment]
My fault, I forget it's sqlite, and I'm not familiar with sqlite or mysql..
