### ISSUE TITLE
db.insert

### ISSUE THREAD

**Issue by blondie63** [tekartik/sqflite#355]
i've a json object with many fields and i've to insert it on a table
I'm using db.insert but i've an error because on json there are more field then on db table

Can i use conflictAlgorithm to skip this fields and insert record ?
Or are there another right way ?

ps. for sure deleting unnecessary vales from json is a way but maybe there's a better way to do :)
Thanks for help

**Comment by alextekartik** [comment]
No you have to sanitize your map before.
