### ISSUE TITLE
sqflite does not work with firebase_messaging

### ISSUE THREAD

**Issue by mnesarco** [tekartik/sqflite#357]
I am trying to save some data into the database using sqflite when I receive a push message. The problem is that apparently firebase_messaging manages incoming push messages in an isolate. Any attempt that i made to call openDatabase inside the message handler is silently ignored, no error no info just nothing.

Versions:
 sqflite: ^1.2.0
 firebase_messaging: ^6.0.9

**Comment by alextekartik** [comment]
I have some apps already working correctly with firebase_messaging and sqflite and it did not get into this issue. I was only using onMessage and onLaunch. After reading some docs, my guess is that you are using onBackgroundMessage. sqflite won't work in a separate isolate so you'd better find a workaround for that (maybe just save temporarily in a plain file).

**Comment by mnesarco** [comment]
Thank you @alextekartik , yes, I am using onBackgroundMessage, so I am looking for a workaround... My problem is that I have to read some data from the DB when the push arrives and then save new data. Using alternative storage like a file is not possible, the database has a very complex structure.

**Comment by alextekartik** [comment]
According to the doc (https://developer.android.com/about/versions/oreo/background) you have to be very quick on such service and I'm pretty you won't be able to interract with any flutter plugin in this case. Have you tried using onMessage instead?

**Comment by mnesarco** [comment]
I am using onMessage AND onBackgroundMessage in order to support silent data updates without user attention. But archiving that is a pain in the ###.

**Comment by alextekartik** [comment]
You might try the following upgrade (allowing plugin registration without activity):
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
