### ISSUE TITLE
SqfliteDatabaseException (DatabaseException(incomplete input (code 1 SQLITE_ERROR)

### ISSUE THREAD

**Issue by TMaxedCode** [tekartik/sqflite#360]
Hello guys. I am new in using sqflite and was able to follow a tutorial online. I tried the sample code in my app and it gave me the error:  
```
Exception has occurred.
SqfliteDatabaseException (DatabaseException(incomplete input (code 1 SQLITE_ERROR): , while compiling: CREATE TABLE rooms(id INTEGER PRIMARY KEY AUTOINCREMENT, room TEXT) sql 'CREATE TABLE rooms(id INTEGER PRIMARY KEY AUTOINCREMENT, room TEXT' args []})
```

How can I fix it? Here is the code:
```
  Future<Database> initializeDatabase() async {
    Directory directory = await getApplicationDocumentsDirectory();
    String path = join(directory.path, 'rooms.db');
    var database = await openDatabase(path, version: 1, onCreate: _createDB);
    return database;
  }
```
```

  void _createDB(Database db, int version) async {
    await db.execute(
        'CREATE TABLE $table($colID INTEGER PRIMARY KEY AUTOINCREMENT, $colRoom TEXT NOT NULL)');
  }
```

Thanks guys

**Comment by alextekartik** [comment]
This sounds like a SQL error. Your SQL is wrong in the reported exception (and slightly different from the one in _createDB):

```
CREATE TABLE rooms(id INTEGER PRIMARY KEY AUTOINCREMENT, room TEXT
```

a trailing `)` is missing.

**Comment by TMaxedCode** [comment]
@alextekartik Thank you so much for your reply. I've wrote the trailing `)` in the code: `await db.execute(
'CREATE TABLE $table($colID INTEGER PRIMARY KEY AUTOINCREMENT, $colRoom TEXT NOT NULL)');
}` How would I be able to solve this problem? Thanks.

**Comment by alextekartik** [comment]
Are you still getting the same Exception? Do you have some logs again?

**Comment by TMaxedCode** [comment]
@alextekartik I still have the same logs again. I don't know why. I will try to run flutter clean and update you about this.

**Comment by TMaxedCode** [comment]
@alextekartik Thanks, it seems like the code is just not updating I checked all the logs again and saw it. Its not a problem with your plugin. It just won't update the program even after running `flutter clean`. Thanks for helping me.
