### ISSUE TITLE
Sqflite Unit test 

### ISSUE THREAD

**Issue by Kobreizhyashi** [tekartik/sqflite#363]
Hi, 

Is there any way to test our databases with transactions instead of plain old database object  (as advised in documentation) ? 

I'm trying to test like if it was the database object and I always have : 

`ERROR: NoSuchMethodError: The method 'transaction' was called on null.`

Any idea ? :-)

**Comment by alextekartik** [comment]
I'm not sure I understand the issue. After you open the database, you can create transaction using `db.transaction`. If `db` is null it means the database was not open properly.

**Comment by Kobreizhyashi** [comment]
I'm sorry I should link more code to make you understand it but .. In fact, I think you gave me the answer. This is not an issue, this is a mistake from me. I never call the database in my test and you're right, that's why it's null and the test is not passing. My bad, thanks for your answer ;)
