### ISSUE TITLE
iOS getDatabasesPath returned everytime another path

### ISSUE THREAD

**Issue by maerlynflagg** [tekartik/sqflite#364]
Hello,

not excatly sure, but it looks wrong.

**Android**
there is no problem.  always the same database is open.

**iOS**

i debugging my flutter app on an iPad. everytime i start debugging, the function returned another path. 

`/var/mobile/Containers/Data/Application/someID/Documents/__myDB`
 
the part "someID" changed everytime.

looks like a bug.

**Comment by alextekartik** [comment]
No sure why. Does it differ from the path returned using `path_provider`?

**Comment by maerlynflagg** [comment]
> No sure why. Does it differ from the path returned using `path_provider`?

oh, i tried the path_provider. both "getDatabasespath" of sqlite plugin and "getApplicationDocumentsDirectory" of path_provider returned the same path.

i'm using the current stable: flutter_macos_v1.12.13+hotfix.7-stable

**Comment by maerlynflagg** [comment]
so i searched for path_provider and found out, the is similar issue: https://github.com/flutter/flutter/issues/23957

it is also not an bug, it is a feature, if this answer correct:

https://github.com/flutter/flutter/issues/23957#issuecomment-460812527

**Comment by maerlynflagg** [comment]
Thank you for repsonse. it is not a bug. :)
