### ISSUE TITLE
MacOS openDatabase() fails to assemble path

### ISSUE THREAD

**Issue by smokytheangel0** [tekartik/sqflite#365]
Flutter 1.14.7-pre.112 • channel master • https://github.com/flutter/flutter.git
Framework • revision 52d5744ea2 (21 hours ago) • 2020-02-04 15:02:55 -0800
Engine • revision 81dffd1241
Tools • Dart 2.8.0 (build 2.8.0-dev.7.0 c8ed304e97)

macOS Catalina
version: 10.15.3 (19D76)

During a flutter test run, when running openDatabase('relative_path', ...) on MacOS, it gives the error MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite). I checked in https://github.com/tekartik/sqflite/commit/04623e1f409faec9a1ac0a9610816e749196dca5 and there didn't seem to be any tests added for MacOS which utilize the path finding stuff so that I could copy the steps to open a desktop database, however in the issue about desktop support https://github.com/tekartik/sqflite/issues/194, several users mentioned that the had tested db creation and connection and it worked. I'm sorry if this issue is duplicitous but I did not find any information on whether there is a different way to openDatabase on MacOS or whether this error is related to a bad setup.

**Comment by alextekartik** [comment]
A `MissingPluginException` is more likely a setup issue. https://github.com/tekartik/sqflite/blob/16a51216cd8e496b8487d29ff06c31daaabe3aa7/sqflite/doc/troubleshooting.md#missingpluginexception

**Comment by smokytheangel0** [comment]
I looked at that and it doesn't seem to have advanced checks for MacOS, would they be the same as the iOS instructions?

**Comment by alextekartik** [comment]
Yes MacOS should be mostly about the same as iOS

**Comment by smokytheangel0** [comment]
Thank you
