### ISSUE TITLE
Cannot work with db HONOR 10 first install

### ISSUE THREAD

**Issue by neestell** [tekartik/sqflite#366]
`wrapDatabaseException (package:sqflite/src/exception_impl.dart:12)
    <asynchronous suspension>
    #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25)
    #2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:188)
    #3      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite/src/database_mixin.dart:374)
    #4      SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite/src/database_mixin.dart:307)
    #5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32)
    #6      SqfliteDatabaseMixin.txnSynchronized (package:sqflite/src/database_mixin.dart:303)
    #7      SqfliteDatabaseMixin.txnRawQuery (package:sqflite/src/database_mixin.dart:373)
    #8      SqfliteDatabaseExecutorMixin.rawQuery (package:sqflite/src/database_mixin.dart:119)
    #9      SqfliteDatabaseExecutorMixin.query (package:sqflite/src/database_mixin.dart:109)`

If I clear all device data all works properly

**Comment by alextekartik** [comment]
There seems to be an error with your query but the stack trace is cut. Hard to tell without knowing how you open the database, handle versioning and without seeing your query

**Comment by neestell** [comment]
Open db
` Future<Database> openDb() async {
    var db = await openDatabase(DB_NAME,
        singleInstance: true,
        version: 1,
        onCreate: _createDb,
        onConfigure: _onConfigureDb);
    return db; }`

Configure DB

`  Future _onConfigureDb(Database db) async {
    await db.execute('PRAGMA foreign_keys = ON');
  }
`

Create one table in onCreate

`createSettingsTable(Batch db) {
    db.execute('CREATE TABLE  ${SettingsRaw.table} ( '
        '${SettingsRaw.columnId} INTEGER PRIMARY KEY NOT NULL, '
        '${SettingsRaw.column1} INTEGER DEFAULT 0, '
        '${SettingsRaw.column2} INTEGER DEFAULT 0, '
        '${SettingsRaw.column3} INTEGER DEFAULT 1, '
        '${SettingsRaw.column4} INTEGER DEFAULT 0, '
        '${SettingsRaw.column5} INTEGER DEFAULT 1, '
        '${SettingsRaw.column6} INTEGER DEFAULT 0, '
        '${SettingsRaw.column7} INTEGER DEFAULT 1)');
  }`

Query
``
` await _dbHelper.openDb().then((db) =>
        db.query(
          SettingsRaw.table,
          columns: [
            SettingsRaw.columnId,
            SettingsRaw.column1,
            SettingsRaw.column2,
            SettingsRaw.column3,
            SettingsRaw.column4,
            SettingsRaw.column5,
            SettingsRaw.column6,
            SettingsRaw.column7,
          ],
          )).catchError((error, stackTrace) {
      print("inner: $error");
      print("Error: " + stackTrace.toString());
      return Future.error("");
    });`

Please note, I cannot access to db for a release build with a proguard file.
`-keep class com.tekartik.sqflite.** { *; }
`
Build command:
`flutter build apk --release --flavor dev --target-platform android-arm64 --split-per-abi`

**Comment by alextekartik** [comment]
Maybe you can try some [dev tips](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#debugging) to display more logs and dump the structure of your data as it is hard to guess what is causing the issue (is just a SQL issue?)

**Comment by neestell** [comment]
Ok, I applied your suggestion. Here is a result
` [1,Sqflite(55575)] SELECT * FROM sqlite_master
2020-02-07 14:56:44.065 15497-15526/? I/flutter: [{type: table, name: android_metadata, tbl_name: android_metadata, rootpage: 3, sql: CREATE TABLE android_metadata (locale TEXT)}, {type: table, name: MatchReminder, tbl_name: MatchReminder, rootpage: 4, sql: CREATE TABLE MatchReminder ( fixtureId INTEGER PRIMARY KEY NOT NULL, timestamp INTEGER NOT NULL, game TEXT NOT NULL, venue TEXT, url TEXT NOT NULL, team1Name TEXT NOT NULL, team2Name TEXT NOT NULL, team1Logo TEXT, team2Logo TEXT)}, {type: table, name: Reminder, tbl_name: Reminder, rootpage: 5, sql: CREATE TABLE Reminder ( id INTEGER PRIMARY KEY, matchId INTEGER, local INTEGER, calendar  INTEGER DEFAULT 0, timestamp  INTEGER NOT NULL, FOREIGN KEY (matchId) REFERENCES MatchReminder(fixtureId) ON DELETE CASCADE)}]
2020-02-07 14:56:44.066 15497-15615/? D/Sqflite: [1,Sqflite(55575)] SELECT * FROM MatchSettings`

There is no Android side logs from the library or Database.
I checked one more time. If I build an app by command
`flutter run --release --flavor dev `
All works as expected
but for production build the command 
`flutter build apk --release --flavor dev --target-platform android-arm64 --split-per-abi
`
break all queries to the library until I clear all device data in app settings

**Comment by neestell** [comment]
Also I turned off app optimisations
 `shrinkResources false
            minifyEnabled false
            useProguard false`


`android.enableR8=false
`
nothing is changed

**Comment by alextekartik** [comment]
Try to post your logs with multiple lines. I don't see any exception in the logs here

**Comment by neestell** [comment]
No exceptions are printed. Except one I posted above 
`wrapDatabaseException (package:sqflite/src/exception_impl.dart:12) <asynchronous suspension> #1 SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25) #2 SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:188) #3 SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite/src/database_mixin.dart:374) #4 SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite/src/database_mixin.dart:307) #5 BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32) #6 SqfliteDatabaseMixin.txnSynchronized (package:sqflite/src/database_mixin.dart:303) #7 SqfliteDatabaseMixin.txnRawQuery (package:sqflite/src/database_mixin.dart:373) #8 SqfliteDatabaseExecutorMixin.rawQuery (package:sqflite/src/database_mixin.dart:119) #9 SqfliteDatabaseExecutorMixin.query (package:sqflite/src/database_mixin.dart:109)`

**Comment by neestell** [comment]
The issue is resolved. If `allowBackup` is true in the AndroidManifest file a new database will not be created and, possibly, an old db scheme may conflict with current code.
