### ISSUE TITLE
Flutter No implementation found for method getDatabasesPath 

### ISSUE THREAD

**Issue by billymahmood** [tekartik/sqflite#368]
Hi,

I am using the plugin version `sqflite: ^1.2.0`, with a Flutter App. The plugin seems to work fine when the app is running in the foreground, however when I try to use the plugin on background process in a headless task (to sync database from API with app while the app is closed) I get the following error: `[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)`

Any suggestions please?

Here is my code
```dart
Future<void> initDatabase() async {
    final path = await getDatabasePath('dbname.db');
    db = await openDatabase(
      path,
      version: _version,
      onCreate: onCreate,
      onUpgrade: onUpgrade,
    );
  }
```

Flutter Doctor 
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
`

**Comment by alextekartik** [comment]
You might look at this section for the new embedding system for android plugin (allowing registration without flutter activity): https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by AlecDr** [comment]
Hello @alextekartik,

I tried to read the upgrading pre 1.12 android projects link you mentioned, and after some days reasearching about it, i really cant get it to work. Can you tell me if sqflite can run in a headless task?

**Comment by alextekartik** [comment]
@AlecDr I'm not sure how a headless task work but sqflite itself is not cross isolate safe (transaction wise) and should be used from the main isolate. It spawns its own native thread

**Comment by AlecDr** [comment]
Theoretically it should start normally without a UI, but injecting the necessary plugins, but I keep having that error (MissingPluginException (No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)), even manually loading the plugin in MainActivity.kt or using another class like this one.

```
package com.example.flutter_example

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import com.tekartik.sqflite.SqflitePlugin

class MyApp : FlutterApplication(), PluginRegistrantCallback {

    override fun registerWith(registry: PluginRegistry) {
        com.tekartik.sqflite.SqflitePlugin.registerWith(
                registry.registrarFor("com.tekartik.sqflite.SqflitePlugin"))
    }
}
```

I think that my problem is something like #446, where the code should run in the background, without the app being open.

**Comment by hyouuu** [comment]
@AlecDr did you figure out a way to use it in headless execution?

**Comment by AlecDr** [comment]
Hey @hyouuu,

Yes, i actually got it working, basically i created a blank flutter project to test it without any other package. I defined a headless task with [this](https://pub.dev/packages/background_fetch) package, then in the headless task i created a database, then i created a record in a dummy table to test, and it worked.

It turns out the problem was another package i was using. I'm actually not using this sqflite package directly, but it worked in a headless task. I'm currently using [moor](https://pub.dev/packages/moor_flutter), which i believe uses this  sqflite package.

**Comment by hyouuu** [comment]
Thanks for the reply @AlecDr ! When the headless task runs, `await getDatabasesPath()` never returns, did you have a custom database path or something to make it work?

**Comment by AlecDr** [comment]
Hey @hyouuu

I created a blank project for you to test. I used the default examples from sqflite and background fetch packages, take a look [here](https://github.com/AlecDr/sqflitetest).

I launched this app in a real device to register a headless task, closed the app and launched the logcat to see logs. With that, you can force the headless task to run with this command -> adb shell cmd jobscheduler run -f com.example.sqflitetest 999.

I got something similar to the bellow image.

![image](https://user-images.githubusercontent.com/13920428/119581616-48906280-bd99-11eb-8a51-8c61c0edb8d9.png)

Test this out, if you can't get it to work, you may be facing something similiar to the problem i described above. Sorry for the bad english.

Cheers.

**Comment by hyouuu** [comment]
@AlecDr thank you so much for taking the time to make the test example! Will look into it tonight!

**Comment by hyouuu** [comment]
Indeed the test example works fine - thanks again and I'll see what's the problem with my project
