### ISSUE TITLE
The error using openDatabase is as follows:MissingPluginException(No implementation found for method openDatabase on channel com.tekartik.sqflite)

### ISSUE THREAD

**Issue by xiechunyan** [tekartik/sqflite#37]
The error using openDatabase is as follows:MissingPluginException(No implementation found for method openDatabase on channel com.tekartik.sqflite).How should I solve it?

**Comment by alextekartik** [comment]
Well it seems the build failed somehow to include the native part...Does it happen on iOS or Android? Does it happen with the sample app?

**Comment by xiechunyan** [comment]
I'm using an ios simulator.

**Comment by alextekartik** [comment]
ok. hard for me to help here as it is likely a build issue. Does it happen with the sample app? Can try a f clean of your app?

**Comment by xiechunyan** [comment]
Ok, I'll try. Thank you.

**Comment by DeckeDeng** [comment]
> Well it seems the build failed somehow to include the native part...Does it happen on iOS or Android? Does it happen with the sample app?

hi, i use android and encountered this problem, so，how can i solve it?

**Comment by DeckeDeng** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
    <asynchronous suspension>
    #1      invokeMethod (package:sqflite/src/sqflite_impl.dart:18:34)
    <asynchronous suspension>
    #2      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:33:7)
    #3      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite/src/factory_mixin.dart:22:35)
    #4      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:34)
    <asynchronous suspension>
    #5      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29:7)
    #6      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite/src/factory_mixin.dart:22:7)
    #7      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite/src/factory_mixin.dart:136:17)
    <asynchronous suspension>
    #8      getDatabasesPath (package:sqflite/sqflite.dart:162:54)
    #9      Provider.init (package:flutter_go/utils/provider.dart:62:34)
    <asynchronous suspension>
    #10     main (package:flutter_go/main.dart:66:18)
    <asynchronous suspension>
    #11     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
    #12     _rootRun (dart:async/zone.dart:1124:13)
    #13     _CustomZone.run (dart:async/zone.dart:1021:19)
    #14     _runZoned (dart:async/zone.dart:1516:10)
    #15     runZoned (dart:async/zone.dart:1500:12)
    #16     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
    #17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
    #18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by alextekartik** [comment]
@DeckeDeng it looks like a setup issue. Have you tried a clean and other troubleshooting options <https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md> ?

**Comment by yshahak** [comment]
@DeckeDeng Do you try to create database from a Spawn? In my case this was the issue.

**Comment by JessieNet** [comment]
> Ok, I'll try. Thank you.

hello, how to solve this issues?

**Comment by rtessler** [comment]
Im having the same problem in IOS on both simulator and device. calling any function in sqflite produces MissingPluginException. Im seeing the same thing in when I call functions in the FirebaseAuth plugin as well. The projects builds without error, its a runtime problem. Im not calling many functions in a short period of time

**Comment by alextekartik** [comment]
I have added a section on this. https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#missingpluginexception

If you manage to fix the issue on your side, please add the notes on what you did so that I can add more information (many people ask this question when they get the issue but never take the time to tell what they did to fix it)

**Comment by rtessler** [comment]
Hi Alexandre

I had trouble making a comment in the git hub page
anyway I have a fix:

To avoid the missingPluginException make sure your IOS AppDelegate.m is correct:

#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
@import UIKit;
@import Firebase;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [FIRApp configure];
  [GeneratedPluginRegistrant registerWithRegistry:self];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
  //return YES;
}

The code given by default in the firebase IOS app setup does not handle plugins. You need the  [GeneratedPluginRegistrant registerWithRegistry:self]; command

thanks

Robert

**Comment by alextekartik** [comment]
Thanks @rtessler I'll populate my troubleshooting section

**Comment by alextekartik** [comment]
More info added here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#missingpluginexception

**Comment by Angeloem** [comment]
I've found out that during development, the problem may be due to change of branches.
When i changed branches, i got the error.. 
to resolve, simply delete the app and get back up

**Comment by Akshay0701** [comment]
> Ok, I'll try. Thank you.
dude its just happen with me also ,its clear issue with build just delete your pervious build files ..thanks @alextekartik  it worked

**Comment by emouawad** [comment]
Hi, tried the troubleshooting guide but still nothing works.

Anyone got it working in a background isolate on Android.
I am trying to use it with Moor and Workmanager - tried to register the plugin inside a custom Application and made sure it's in the GeneratedPluginRegistrant

Please any guidelines? or code sample - thanks

flutter 1.20.4
sqflite 1.3.1+1

**Comment by Fayiz-A** [comment]
This issue happened with me too. This was happening because I was doing hot restart. Instead, press the **stop button** and **then** click on **run**.  This fixed my problem.

**Comment by diogocsc** [comment]
I noted this only appeared after adding package screenshot_share_image. I removed it and error disappeared.

**Comment by Faiizii** [comment]
I am generating a release android apk and facing the error ``` MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite) ``` I am using `sqflite: ^1.3.2+2`. The error does not appear in any mode of app (debug,profile,release) but it does in release apk.

Ouput of `flutter --version`
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (6 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4 ```

**Comment by rishirizz** [comment]
Error: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
    at Object.throw_ [as throw] (http://localhost:40163/dart_sdk.js:4348:11)
    at MethodChannel._invokeMethod (http://localhost:40163/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:40163/dart_sdk.js:37956:33
    at _RootZone.runUnary (http://localhost:40163/dart_sdk.js:37810:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:40163/dart_sdk.js:32771:29)
    at handleValueCallback (http://localhost:40163/dart_sdk.js:33319:49)
    at Function._propagateToListeners (http://localhost:40163/dart_sdk.js:33357:17)
    at _Future.new.[_completeWithValue] (http://localhost:40163/dart_sdk.js:33199:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:40163/dart_sdk.js:33222:35)
    at Object._microtaskLoop (http://localhost:40163/dart_sdk.js:38071:13)
    at _startMicrotaskLoop (http://localhost:40163/dart_sdk.js:38077:13)
    at http://localhost:40163/dart_sdk.js:33574:9


Can anyone help ?

**Comment by alextekartik** [comment]
@Faiizii This issue can also happen if any plugin you have fails to register (depending on the order). Unfortunately this is sometimes hard to guess, unless looking at the log. One solution on Android (to find what is causing the issue) is to override configureFlutterEngine and catch exception and display the stacktrace

@rishirizz the log are showing js related files. sqflite is not supported on flutter web

**Comment by vanessabin** [comment]
@alextekartik will the sqflite plugin be available for flutter web? Been building the database for my project all day and then found out through this issue that it doesn't work at all for flutter web :(. For the rest of my app I also use sqlflite so maybe I need to change the whole thing.

**Comment by alextekartik** [comment]
Support for the web is not planned as there is no decent persistent solution at this time. There is an advanced project here https://github.com/deakjahn/sqflite_web that uses sql.js that you can try.

**Comment by abelardolg** [comment]
Hi @alextekartik , 

Is Linux supported? I am checking my Flutter app into this environment and it gives me this error, too.

Best regards.

**Comment by alextekartik** [comment]
@abelardolg  see: https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md
