### ISSUE TITLE
V2 plugin

### ISSUE THREAD

**Issue by yyt231** [tekartik/sqflite#375]
The plugin `sqflite` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

**Comment by alextekartik** [comment]
Thanks for the report. I tried to follow the steps and publish a new version `1.2.1-dev.3`. I will make more tests and any feedback is welcome.

**Comment by yyt231** [comment]
@alextekartik Thanks.But I have a new issue.

 Because flutter_waybill_detail depends on sqflite ^1.2.1 which doesn't match any versions, version solving failed.
pub get failed (1; Because flutter_waybill_detail depends on sqflite ^1.2.1 which doesn't match any versions, version solving failed.)

**Comment by alextekartik** [comment]
1.2.1 was not published when I responded (1.2.1-dev.3 only). 1.2.1 should be available now
