### ISSUE TITLE
_CastError (type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast)

### ISSUE THREAD

**Issue by rakafajar** [tekartik/sqflite#379]
Want to ask again ... try implementing the data API stored in a local database ... the form of the JSON API The object in which there is a JSON Array ... there was an error when wanting to load data from the API to Local ... roughly this is an error because of "the wrong model or what

Api Service

```
class MealApiProvider {
  Future<List<Categories>> getAllMeal() async {
    var url = "https://www.themealdb.com/api/json/v1/1/categories.php";
    Response response = await Dio().get(url);
    print("Hasil Respon ${response.data}");
    return (response.data as List).map((employee) {
      print('Inserting $employee');
      DBProvider.db.insertMeals(Categories.fromJson(employee));
    }).toList();
  }
}
```
Model

```
class DataMeal {
  final List<Categories> categories;

  DataMeal({this.categories});

  @override
  String toString() {
    return 'DataMeal{categories: $categories}';
  }

  factory DataMeal.fromJson(Map<String, dynamic> json) {
    return DataMeal(
      categories: List<Categories>.from(
        json["categories"].map(
          (categories) {
            return Categories.fromJson(categories);
          },
        ),
      ),
    );
  }

  Map<String, dynamic> toJson() => {
        "categories": List<dynamic>.from(
          categories.map(
            (x) => x.toJson(),
          ),
        ),
      };
}
```
Error

> return (response.data as List).map((employee)

**Comment by alextekartik** [comment]
It seems that somewhere in your code you have a map where a list is expected. Is this correct: `response.data as List`? what is response.data content?

**Comment by alextekartik** [comment]
Thanks for using Stackoverflow instead (where you seem to have a valie response):https://stackoverflow.com/questions/60294025/casterror-type-internallinkedhashmapstring-dynamic-is-not-a-subtype-of-t/60296396#60296396
