### ISSUE TITLE
Need example for transactions

### ISSUE THREAD

**Issue by GRouslan** [tekartik/sqflite#38]
How to use nested transactions? I get deadlocks.

**Comment by alextekartik** [comment]
yes i started deprecating `inTransaction` which supports nested transaction so I understand your concern. The fact is that `inTransaction` uses Zone which, according to some flutter talk at Dartconf does not play well with setState (I don't have much info why). I think you can manage to organize your code to avoid nested transactions, using `Database.transaction` and using the transaction object for all the calls (`DatabaseExecutor` is also a shared interface to have common code that run on with or without a transaction). Batch is also the best alternative for performance. If you want to share some code, I could try to help you

**Comment by GRouslan** [comment]
This is the essence, this is how I handle it now, but keeping transaction in the class member to reuse it in inner transaction is definitely not safe:

```
class DB {
  static DB _instance;

  

  factory DB() {
    if (_instance != null) return _instance;
    _instance = new DB._internal();
    return _instance;
  }

  DB._internal();

  Future<Database> open() async {
    if (db != null) return db;
    String path = 'assets/database.db';
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    path = join(documentsDirectory.path, 'database.db');

    db = await openDatabase(
      path,
      version: 1,
      onConfigure: (db) async {
        await db.execute('PRAGMA foreign_keys = ON;');
        await db.execute('PRAGMA recursive_triggers = ON;');
      },
      onCreate: (Database db, int version) async {/*...*/},
    );
    return db;
  }

  final _lock = new Lock();
  Database db;
  Transaction txn;
  DatabaseExecutor get ex => txn ?? db;

  Future<T> inTransaction<T>(Future<T> action()) async {
    return await _lock.synchronized<T>(() async {
      if (txn != null) throw 'txn is not null';
      return await db.transaction<T>((txn) async {
        this.txn = txn;
        final result = await action();
        this.txn = null;
        return result;
      });
    });
  }

  Future<T> innerTransaction<T>(Future<T> action(Transaction txn)) async {
    final localTxn = txn;
    if (localTxn != null) {
      return await action(localTxn);
    } else {
      return await _lock.synchronized<T>(() async {
        return await db.transaction<T>(action);
      });
    }
  }

  Future deleteRecord(Record record) async {
    await ex.delete(/*...*/);
  }

  Future<RecordText> insertRecordText(
    String content,
  ) async {
    int record;
    await innerTransaction((txn) async {
      record = await txn.insert(/*...*/);
      /*...*/
    });
    return new RecordText(id: record, content: content);
  }
}

class Client {
  
  
  Future doSomething() async {
    final db = new DB();
    await db.inTransaction(() async {
      await db.deleteRecord(/**/);
      await db.insertRecordText('some text');
    });
  }
}
```

**Comment by alextekartik** [comment]
Ok I see, you are basically trying to put back the re-entrant feature (funny as I did the same in one project). The only mistake I see is that you are creating a lock which is not reentrant

```dart
final _lock = new Lock();
```
should be

```dart
final _lock = new Lock(reentrant: true);
```

And you should be able to get rid of `innerTransaction`and use `inTransaction` everywhere you want to and I think actually you should wrap all your calls with it (or with _lock.synchronized) deleteRecord behavior calls from another method not in a transaction might have unpredictable behavior (it uses the transaction object which will no longer be valid when the call will actually be performed)

**Comment by GRouslan** [comment]
Thank you, I tried your advice. Seems working. But the behavior of app changed, everything is now synchronous, waiting previous operation is done.

```
  final _lock = new Lock(reentrant: true);
  Transaction txn;
  DatabaseExecutor get ex => txn ?? db;

  Future<T> inTransaction<T>(Future<T> action()) async {
    return await _lock.synchronized<T>(() async {
      if (txn != null)
        return await action(); // case of reentrant: performs inside root action, txn is valid throughout life of this action
      return await db.transaction<T>((txn) async {
        this.txn = txn;
        final result = await action();
        this.txn = null;
        return result;
      });
    });
  }


  Future deleteRecord(Record record) async {
    await _lock.synchronized(() async {
       await ex.delete(/*...*/);
    });
  }

  Future<RecordText> insertRecordText(
    String content,
  ) async {
    int record;
    await inTransaction(() async {
      record = await txn.insert(/*...*/);
      /*...*/
    });
    return new RecordText(id: record, content: content);
  }
}
```

**Comment by alextekartik** [comment]
Yes, anyway sqflite does not allow for concurrent read write so adding an external lock won't change much in the overall performance (it actually matches the current deprecated `Database.inTransaction`). In your previous code calling deleteRecord from another block could have an unexpected behavior (if there was currently a transaction)

**Comment by GRouslan** [comment]
Yes, I meant "await" parts of simultaneous complicated actions were shaffled. It was more pleasant ui experience, but with potential errors as you said. And I missed zones in dart docs, should read it and probably get an idea how to organize my code.
