### ISSUE TITLE
how to access on sql in background mode

### ISSUE THREAD

**Issue by niypoo** [tekartik/sqflite#381]
I'm using Sqflite with background headless mode when I terminated app and I executed job when app is open it's work great but when I terminated app it's give me this issue only on android

> MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

i'm work on flutter < 1.2
this is MainActivity.kt file

    package xxx.xxx.xxx
    
    import androidx.annotation.NonNull;
    import io.flutter.embedding.android.FlutterActivity
    import io.flutter.embedding.engine.FlutterEngine
    import io.flutter.plugins.GeneratedPluginRegistrant
    
    import android.os.Build
    import android.view.ViewTreeObserver
    import android.view.WindowManager
    class MainActivity: FlutterActivity() {
        override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
            GeneratedPluginRegistrant.registerWith(flutterEngine);
        }
    }

**Comment by alextekartik** [comment]
Response in stackoverflow (thanks for using Stackoverflow instead):  https://stackoverflow.com/questions/60366435/how-to-access-on-sql-in-background-mode
