### ISSUE TITLE
MissingPluginException conflict with other plugin

### ISSUE THREAD

**Issue by niypoo** [tekartik/sqflite#382]
My app access on database in backend mode after user terminated app, after update that issue show up to me

> MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

I tested all solutions I know and I found in internet but I found nothing so I have disabled plugin one by one until speech_to_text : 0.8.0 after that database work great and issue has disappear .

i'm work on flutter 1.2

I have edit on GeneratedPluginRegistrant.java
from

```
com.csdcorp.speech_to_text.SpeechToTextPlugin.registerWith(shimPluginRegistry.registrarFor("com.csdcorp.speech_to_text.SpeechToTextPlugin"));
 flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
```

to

```
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
com.csdcorp.speech_to_text.SpeechToTextPlugin.registerWith(shimPluginRegistry.registrarFor("com.csdcorp.speech_to_text.SpeechToTextPlugin"));
```

and it's working but every build flutter reset older to old one and I have to move speech register to last one.

I don't know why nut I did that to help you about where is this issue , thanks

I have posted also in speech_to_text issue 
https://github.com/csdcorp/speech_to_text/issues/39

**Comment by alextekartik** [comment]
duplication of #368 I think. You might look at this section for the new embedding system for android plugin (allowing registration without flutter activity): https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by niypoo** [comment]
> duplication of #368 I think. You might look at this section for the new embedding system for android plugin (allowing registration without flutter activity): https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

I'm already on embedding 2 and I have created new project and have same error

**Comment by alextekartik** [comment]
It seems SpeechToText is not supporting embedding v2 yet (SpeechToText requires an activity upon registration hence the crash).

**Comment by niypoo** [comment]
@alextekartik  thanks I will inform author of SpeechToText
