### ISSUE TITLE
Batch.commit exception is not catched!

### ISSUE THREAD

**Issue by bambinoua** [tekartik/sqflite#384]
There is a simple code for initializing database table. Just execute many `insert` SQL queries. 
```
try {
  final db = await database;
  for (var obj in obj) {
    await db.batch.insert(table, obj.toJson()); 
  }
  await db.commit(exclusive: true); // crash is here!
} on DatabaseException (e) {
  print('error: $e');
}
```
Some of INSERTs contains error - there is no unique value in field and of couse exception must be occurred on commint. It is occurred but it is not catched! The exception is happend in `wrapDatabaseException` in a row `12` where there is a statement:
```
throw SqfliteDatabaseException(e.message, e.details);
```
It seems there is a bug somewhere here. It looks like exception is throwing in `non async/await` code and that is why the exception is not catched.

Trace is:
```
wrapDatabaseException, line: 12, file: exception_impl.dart
<asynchronous gap>
wrapDatabaseException, line: 25, file: factory_impl.dart
safeInvokeMethod, line: 188, file: database_mixin.dart
tnxAppyBatch, line: 410, file: database_mixin.dart
tnxSynchzonized, line: 292, file: database_mixin.dart
tnxWriteSynchronized, line: 325, file: database_mixin.dart
tnxApplyBatch, line: 399, file: database_mixin.dart
commit, line: 128, file: batch.dart
_runTransaction, line: 456, file: database_mixin.dart
<asynchronous gap>
```
Maybe call of method `wrapDatabaseException` must be also wrapped with `try/catch` which `rethrow` the exception?

**Comment by alextekartik** [comment]
I would not get your code to compile, so I'm not sure you are using batch the correct way. I took the time to write a unit test. The behavior is what is expected:

https://github.com/tekartik/sqflite_more/blob/0df3abd5275ec9e9de571834c95789e1552586e8/sqflite_test_app/test/more_ffi_test.dart#L10-L30

Indeed a batch is just a list of commands. Commit will run all commands so exception will only be thrown from here.

Best is to write a unit test like I did to show the issue you are seeeing.

**Comment by bambinoua** [comment]
Ok. I will try to create a unit test. Please not not close this case.

**Comment by bambinoua** [comment]
Well, I created not a test but code in app to show what happens.
```
import 'package:sqflite/sqflite.dart';

class TestBloc {
  ///
  Future<void> run() async {
    try {
      final db = await openDatabase(inMemoryDatabasePath, version: 1,
          onCreate: (db, version) {
        db.execute('''
          CREATE TABLE test (
            guid TEXT PRIMARY KEY,
            name TEXT NOT NULL
          )''');
      });
      final batch = db.batch();
      batch.insert('test', {'guid': 'abcd', 'name': 'abcd'});
      batch.insert('test', {'guid': 'abcd', 'name': 'abcd'});
      await batch.commit(exclusive: true);
      print('success');
    } on DatabaseException catch (e) {
      print('error: $e');
    }
  }
}
```
In principle it looks like yours.

I expect that I will see the `error` print **only**. But VS Code debugger stops on exception like on uncaught one and this I don't like. It looks like exception is uncaught. After break point I click `continue` button few times, then exception is happends again and only after 2-3 stops I see the `error` message.

![sqflite_exception](https://user-images.githubusercontent.com/45417992/75625843-86b8c980-5bca-11ea-88df-53e36d26d6d2.jpg)

**Comment by alextekartik** [comment]
I don't use VS code but I guess that is just a debugger issue (since error got display any way) that might be set to pause on all exception. When you run the behavior is correct, right?

**Comment by bambinoua** [comment]
Unfortunately I can test this. :( So let's consider this is a debugger issue.
Thanks for trying to help.
