### ISSUE TITLE
Database security

### ISSUE THREAD

**Issue by uc-apa** [tekartik/sqflite#386]
Is the database/table created using this package are safe? I am concerned about the security of our database to use in the app specially if it a large scale app being used in production. Kindly guide me in the right direction. Also is it possible to browser the database using any db browser, so that it may show the database file saved in the app's document like realm does in react native.

**Comment by alextekartik** [comment]
Not sure what you mean by safe. It uses whatever sqlite the platform provide so any features that you were able to do using native sqlite on iOS and Android are available. You can extract the db and use any db browser. I know some people are browsing the database on the database using 3rd party tools but I have not tried this.

Regarding security, the database is not encrypted so here as well it is as secure as native sqlite database.
