### ISSUE TITLE
Windowing function support

### ISSUE THREAD

**Issue by Milchdealer** [tekartik/sqflite#387]
Hello,

right now, windowing functions are not supported yet. They were added in SQLite 3.25.0 on 2018-09-15. (https://www.sqlite.org/changes.html)
Is there any plan to add these?

Best

**Comment by Milchdealer** [comment]
Just checked and SQLite on Android supports 3.4 since API1 and with API27 3.19. (https://developer.android.com/reference/android/database/sqlite/package-summary)

**Comment by alextekartik** [comment]
`sqflite` uses the SQLite available on the platform. It does not ship/bundle any additional SQLite library. See https://github.com/tekartik/sqflite/blob/master/sqflite/doc/version.md
