### ISSUE TITLE
Speed optimization

### ISSUE THREAD

**Issue by Kobreizhyashi** [tekartik/sqflite#388]
Hi, 

I'm actually working on a flutter app because we currently compare KMP / Flutter techs for the future and I have to show a HUGE form (with 1000 fields & checkboxes in each 7 tabs). The problem is I'm currently using sqflite and I try to fetch datas with transaction but the form needs 20 seconds to show itself because of data providing. How can I Improve my database calls and the tables are built with classic CREATE TABLE etc.. ? I use BLoC between repositories (which call datasources where my transactions are stored) and Views. 

Thanks a lot,
KBZH

**Comment by alextekartik** [comment]
Indeed SQLite performance can be optimized a lot using indecies and optimizing queries as you would do on native Android and iOS app. This question is more about SQL and SQLite than `sqflite` itself so you might get better help on StackOverflow once you expose with details you schema and you queries. 

In general, I try to avoid too many queries (better to write 1 query to ready 10k records then 10 queries), limit the amount of data by specifying only the column I need, and make sure the fields used in `JOIN`s are indexed. I like `VIEW`s personally but I use SQLite with basic queries almost like a NoSQL database and taking advantage of queries and join when needed. Transactions won't help for reading performance. Even 10K small records should not take more than a second to be read.

**Comment by Kobreizhyashi** [comment]
Thanks for your answer. I've hesitate ATM I was writing this post between here & stackOverflow you're right. But In order I didn't get the problem with Android (and room), I chose to talk about it with you. I'll add few indexes in order to increase performance. Finger crossed :-)
