### ISSUE TITLE
Open database in read-only mode

### ISSUE THREAD

**Issue by kliron** [tekartik/sqflite#39]
Is this possible?

**Comment by alextekartik** [comment]
I started supporting that on Android at the beginning but did not spend enough time to make it work. I guess we could add a flag during open mode for that. Currently the workaround is to copy the read-only database.

So yes, it could be possible (FMDB - the native iOS implementation I use - and Android support that). I guess I should consider this a feature request?

**Comment by kliron** [comment]
@alextekartik It would be nice to have it. It would enable opening the database directly from the bundle in iOS without the need to copy to the Documents folder. I'm not sure if android permits this as well. This would reduce startup time a little if the bundled database is large and maybe (I'm just speculating here) make asynchronous reads faster.

**Comment by alextekartik** [comment]
Read-only support has been added in 0.8.4. I was not able to test in the scenario you proposed however `openReadOnlyDatabase` open the database file in read-only mode on both iOS and Android. It would be nice if you could validate in the scenario you mentionned (iOS bundled database)

**Comment by kliron** [comment]
@alextekartik Great, it works nicely. 

I looked into creating a test case for opening the db directly from the asset bundle. Unfortunately at this time there doesn't seem to be a way to get the _path_ of a resource in the Flutter asset API. See issue [#11892](https://github.com/flutter/flutter/issues/11892). 

In other words there is no equivalent to doing (in iOS)
`let path = Bundle.main.path(forResource: <...>, ofType: <...>)` in Flutter. All you can do is `rootBundle.load(...)` which returns a ByteData object of an asset. 

On Android it is impossible to do random reads on assets in the APK without first copying to documents folder - unless you use hacks like [this](https://bitbucket.org/kiwidrew/android-staticdb). 

Regardless, I think the option to open read-only is nice to have. At the very least SQLite will omit creating a journal file when opening the database.

**Comment by alextekartik** [comment]
Yeap, that was my issue: how to get a path from an asset. We'll see how Flutter goes on this...at least sqflite should be ready!
