### ISSUE TITLE
Warning shown in Xcode

### ISSUE THREAD

**Issue by pvegh** [tekartik/sqflite#391]
I think the warning says it all:

.pub-cache/hosted/pub.dartlang.org/sqflite-1.2.1/ios/Classes/SqflitePlugin.m:2:9: non-portable path to file '<fmdb/FMDB.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
293 [12:14:49]: ▸ #import <FMDB/FMDB.h>
294 [12:14:49]: ▸         ^~~~~~~~~~~~~

**Comment by alextekartik** [comment]
Thanks for reporting this. I think I made a 1.2.1 version only for a change on this and i did it wrong...Will fix

**Comment by alextekartik** [comment]
I published 1.2.2 that should fix the issue. Somehow I need to import fmdb/FMDB.h on iOS but FMDB/FMDB.h on MacOS and I try to maintain a single source for both platform. Let me know if that works for you. Thanks again for the report!

**Comment by pvegh** [comment]
Looks good so far, thanks!

**Comment by LDXu** [comment]
why  I need to import FMDB/FMDB.h on iOS?
