### ISSUE TITLE
Want to run onUpgrade the first time the app is launched.

### ISSUE THREAD

**Issue by sh-ogawa** [tekartik/sqflite#397]
In the current guidelines
- Re-setup so that onCreate has the table configuration after version upgrade.
- In onUpgrade, execute SQL so that the table will be up-to-date with the application installed before that.

It is troublesome to register the difference every time,
I want to run onUpgrade every time when I first start it.

This can be achieved by changing the following part from else if to if.

https://github.com/tekartik/sqflite/blob/master/sqflite/lib/src/database_mixin.dart#L702

**Comment by alextekartik** [comment]
This will be a major breaking change. Existing app expect either onCreate or onUpdate to be called. Any change in that will likely break most implementation. It matchs Android SqliteDatabase api [SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper).

You can easily have your own _onCreate and _onUpgrade and have onCreate call both.

**Comment by sh-ogawa** [comment]
Hi @alextekartik 

In Android and Flutter, I understand that the database version is not matched in the life cycle method at initialization.

Follow this approach, because you can simply catch up to the database version from within onCreate.

Thank you!!
