### ISSUE TITLE
Save json data to database

### ISSUE THREAD

**Issue by matejik** [tekartik/sqflite#404]
Hi cannot save json data to database, column type text with  Future<int> update(String table, Map<String, dynamic> values,   {String where,    List<dynamic> whereArgs,   ConflictAlgorithm conflictAlgorithm}); Does not return an error. if I use rawUpdate everything is fine.

structure table: CREATE TABLE "site" (id int primary key not null , prices text )

examples update code: 

var _db = DatabaseHelper.instance;
Map<String, dynamic> _m = new Map();
 _m["prices"] = '[{"price":44.44,"id":1,"currencyid":1,"updatedat":1583881200},{"price":33.9,"id":6,"currencyid":1,"updatedat":1584054000}]';
 _db.update("site", _m, "id = ?", ["1"]);

The problem will probably be with the escape sequence? 

Thank you for answer

Jiri

**Comment by alextekartik** [comment]
Hard to tell without seeing the error you get and stack trace. I strongly suggest first to use strong mode and pedantic 1.9 as it catches a lot of error at compile time (for example your code would not compile - don't use `new Map()` but `<String, dynamic>{}` to ensure the root map has the proper type).

**Comment by matejik** [comment]
Hi,
after clearing the cache the problem disappeared. 
I do not understand. 
Thank you and sorry.
