### ISSUE TITLE
does it suport like query ?  it gives an error  when i was trying to query tables  with  'where name  like ?% '

### ISSUE THREAD

**Issue by mlbao** [tekartik/sqflite#407]

**Comment by mlbao** [comment]
I/flutter (18424): Exception: DatabaseException(incomplete input (code 1 SQLITE_ERROR): , while compiling: SELECT name, sex, title, nation, nativePlace, birthDate, joinDate, eduLevel, jobRank, curentJobDate, orgId, orgIdfull FROM personInfo WHERE name like ?%) sql 'SELECT name, sex, title, nation, nativePlace, birthDate, joinDate, eduLevel, jobRank, curentJobDate, orgId, orgIdfull FROM personInfo WHERE name like ?%' args [vv]}

**Comment by alextekartik** [comment]
`?%` is not supported in SQLite, you have to use `?` only and `vv%` in the arguments instead.

```dart
// Example name containing the text 'item'
await db.query('Test', where: 'name LIKE ?', whereArgs: ['%item%']);
```

**Comment by mlbao** [comment]
> `?%` is not supported in SQLite, you have to use `?` only and `vv%` in the arguments instead.
> 
> ```dart
> // Example name containing the text 'item'
> await db.query('Test', where: 'name LIKE ?', whereArgs: ['%item%']);
> ```

Thanks！ It works now ,  i used to write it like below.
await db.query('Test', where: 'name LIKE %?%', whereArgs: ['item']);
