### ISSUE TITLE
Is there a better way to Query things?

### ISSUE THREAD

**Issue by goldcoders** [tekartik/sqflite#408]
Is there any package that has An Abstractiont that utilize for example
laravel eloquent... Where in The database can easily be migrated Up and Down
Easily Seed Inital Data. And Easily Query things 
For example User::all(); , User::find(1); 

Sorry i came from laravel world, and it is just a convenience using those fluent api...
without having to write raw query...

**Comment by alextekartik** [comment]
Unfortunately sqflite provides only basic helpers. You might look for external packages like https://pub.dev/packages/sqlcool but I have not tried any as I tend to write and optimize SQL queries manually.
