### ISSUE TITLE
Database .query using LIKE

### ISSUE THREAD

**Issue by briosheje** [tekartik/sqflite#409]
I'm trying to play around and I need to perform a `LIKE` search depending on a filter parameter, which might lead to searching for startsWith, contains or endsWith.

Ther relevant code is this:

```dart
String searchExpression = '';
    if (filters.description != null && filters.description != '') {
      switch (filters.searchFilterMode) {
        case TodoSearchFilterMode.Contains:
          searchExpression = 'AND description like \'%?%\'';
          break;
        case TodoSearchFilterMode.EndsWith:
          searchExpression = 'AND description like \'%?\'';
          break;
        case TodoSearchFilterMode.StartsWith:
          searchExpression = 'AND description like \'?%\'';
          break;
      }
    }
    
    String archivedWhere = filters.showArchived ? '(0,1)' : '(0)';
    
    final List<Map<String, dynamic>> todos = await this.db.query(
      this.tableName,
      where: 'archived IN $archivedWhere $searchExpression',
      whereArgs: [
        if (filters.description != null && filters.description != '') (filters.description != null) ? filters.description : ''
      ]
    );
```

However, I'm getting a runtime error mentioning that 0 parameters were found:
```
Exception has occurred.
SqfliteDatabaseException (DatabaseException(Cannot bind argument at index 1 because the index is out of range.  The statement has 0 parameters.) sql 'SELECT * FROM todos WHERE archived IN (0) AND description like '%?%'' args [est]})
```

Am I losing something or there should be one positional argument? I didn't find any example.

**Comment by alextekartik** [comment]
instead of doing `like %?%`, args `['est']`, can you try `like ?`, args `['%est%']`, instead? Sorry for the lack of documentation but basically it is similar to Android, see example stackoverflow question https://stackoverflow.com/questions/9076561/android-sqlitedatabase-query-with-like

**Comment by briosheje** [comment]
> instead of doing `like %?%`, args `['est']`, can you try `like ?`, args `['%est%']`, instead? Sorry for the lack of documentation but basically it is similar to Android, see example stackoverflow question https://stackoverflow.com/questions/9076561/android-sqlitedatabase-query-with-like

Thanks, it worked.

Perhaps it might be worth mentioning that somewhere for future readers.

Also, thanks for the immediate support.

**Comment by alextekartik** [comment]
> Perhaps it might be worth mentioning that somewhere for future readers.

Yeap you're right since you are not the first one to ask for this. I added an exemple here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#using-like
