### ISSUE TITLE
'fmdb/FMDB.h' file not found

### ISSUE THREAD

**Issue by yuhaocan** [tekartik/sqflite#411]
I dont know why cant find 'fmdb/FMDB.h'  . 
So I rewrite this code 
```
#if TARGET_OS_IPHONE
#import <fmdb/FMDB.h>
#else
#import <FMDB/FMDB.h>
#endif
```
I write this can run success , I use 13.2 iOS with simulator 
```
#if TARGET_OS_IPHONE
#import <FMDB/FMDB.h>
#else
#import <FMDB/FMDB.h>
#endif
```

sqflite version 1.3.0

**Comment by alextekartik** [comment]
Thanks for the report. I made the change regarding this bug: https://github.com/tekartik/sqflite/issues/391

Can you confirm that the example projet in sqflite works for you and are you overriding the FMDB version used?

Maybe I should update the FMDB being used (2.7.5 instead o 2.7.2 meaning dropping iOS 8 support) or use direct sqlite native code. I'm not an iOS expert I'd rather get some advices on the best path to choose.

**Comment by yuhaocan** [comment]
> Thanks for the report. I made the change regarding this bug: #391
> 
> Can you confirm that the example projet in sqflite works for you and are you overriding the FMDB version used?
> 
> Maybe I should update the FMDB being used (2.7.5 instead o 2.7.2 meaning dropping iOS 8 support) or use direct sqlite native code. I'm not an iOS expert I'd rather get some advices on the best path to choose.

I not direct use sqflite plugin.  I use cached_network_image: 2.0.0 plugin and it depend sqflite.
I can see it use sqflite version 1.3.0 and I am  not an iOS developer so not sure which version of FMDB.

**Comment by yuhaocan** [comment]
I find it !!
![image](https://user-images.githubusercontent.com/12983937/78240917-36f35800-7512-11ea-8b05-4744535b2ef1.png)

**Comment by alextekartik** [comment]
According to https://github.com/ccgus/fmdb/pull/774, `fmdb/FMDB.h` seems to be the correct usage which is what sqflite does. 

As test I create a new project (XCode 11.4 installed) on flutter stable with just `cached_network_image` as dependency and it builds fine. Event in XCode in builds without warning.

Can you try the same and see whether you still have the issue? Then maybe you can try recreating your iOS project (I had to this sometimes).

**Comment by yuhaocan** [comment]
> ccgus/fmdb#774

I see. I am not sure what problem make it.Maybe project pod version not latest or else. 
Now I temporarily simple and rude use "import FMDB/FMDB.h" . 
If I find right way ,i will reply in here.

**Comment by Guang1234567** [comment]
https://github.com/tekartik/sqflite/issues/411#issuecomment-608191844

@yuhaocan

because your macOS and my macOS is **case sensitive**, 😭

so need temporarily simple and rude use "import FMDB/FMDB.h"  in a **case sensitive** macOS !!!

**Comment by Guang1234567** [comment]
![image](https://user-images.githubusercontent.com/8240718/114979770-0cc2cd00-9ebe-11eb-87c5-d92dcd075b9a.png)

**Comment by erlangzhang** [comment]
> case

i also have the problem, my macos is **case sensitive**, so will build error, need to import use #import <FMDB/FMDB.h>
