### ISSUE TITLE
Can we cancel a running command

### ISSUE THREAD

**Issue by pmaAdvensyn** [tekartik/sqflite#419]
Is it planned to have a cancel command like that https://stackoverflow.com/questions/24738417/canceling-sql-server-query-with-cancellationtoken ?

**Comment by alextekartik** [comment]
I have not tried this yet but I think you can "raise" errors using triggers: https://sqlite.org/lang_createtrigger.html

sqlite is definitely not as complete as sql server (hence the lite name). sqflite does nothing specific on that.
