### ISSUE TITLE
'_InternalLinkedHashMap' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by the4thfloor** [tekartik/sqflite#42]
```
2018-03-27 17:01:47.649310+0200 Runner[557:230228] [VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type '_InternalLinkedHashMap' is not a subtype of type 'Map<String, dynamic>' where
  _InternalLinkedHashMap is from dart:collection
  Map is from dart:core
  String is from dart:core
```

I get this error message when I run my Flutter app with Flutter channel dev. When I use Flutter channel beta it works

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.4, on Mac OS X 10.13.3 17D102, locale de-DE)
    • Flutter version 0.2.4 at /Users/ralphbergmann/Downloads/flutter
    • Framework revision 3352a3fb48 (7 days ago), 2018-03-20 19:30:06 +0100
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985
```

**Comment by VadyaVL** [comment]
Hello.
I have this trouble.
Do you have any solution?

If I will do it then I post it here.

**Comment by WonderProgrammer** [comment]
Hello guys, 
I do have the same problem. It would be great if someone could post a solution.

**Comment by alextekartik** [comment]
What version of sqflite are you using? I recommend using the latest version (`sqflite: '>=0.8.4'` in `pubspec.yaml`)

**Comment by alextekartik** [comment]
Indeed there seems to be an issue with the latest dev version (cast method has been removed from List/Map). I'll take a look tomorrow....

**Comment by alextekartik** [comment]
I was not able to reproduce using the lastest flutter dev/beta version and I update the package with deprecation warning fix. Can you try again (and check my troubleshoot section here: https://github.com/tekartik/sqflite/blob/master/doc/troubleshooting.md)

**Comment by the4thfloor** [comment]
Okay, I found my mistake:

I forgot the `<String, dynamic>` at the `toMap()` method (`Map<String, dynamic> toMap()`)

**Comment by alextekartik** [comment]
yes indeed. That's definitely a must for dart 2; I had many crashes with that have required some fixes in the library itself (that's why I recommend the `implicit-casts: false` which sounds noisy at first but helps catching such issues. Good that you found it!

**Comment by alextekartik** [comment]
I added a note in the troubleshooting section on this specific common issue: https://github.com/tekartik/sqflite/blob/master/doc/troubleshooting.md#cast-error
