### ISSUE TITLE
Feature request: INSERT OR REPLACE

### ISSUE THREAD

**Issue by philipdolenko** [tekartik/sqflite#426]
for now this 
> db.execute("INSERT OR REPLACE INTO $table ($keys) VALUES ($values)");

is working fine but maybe there is reason to add it to prebuild functions like db.insert();

Also, are there plans to add Windows (maybe Linux) support?

Ps. Thanks for the package, awesome work!

**Comment by alextekartik** [comment]
> maybe there is reason to add it to prebuild functions like db.insert()

It actually exists. For insert/update helper however, there is a [conflictAlgorithm](https://pub.dev/documentation/sqflite_common/latest/sql/ConflictAlgorithm-class.html) parameter which in your case would be `ConflictAlgorithm.replace`

> Also, are there plans to add Windows (maybe Linux) support?

Windows and Linux support is currently supported using [`sqflite_common_ffi`](https://pub.dev/packages/sqflite_common_ffi). Basically you use `databaseFactory` on mobile and `databaseFactoryFfi` on windows and Linux

**Comment by philipdolenko** [comment]
Wow, thanks a lot again 👍
Have a nice day
