### ISSUE TITLE
how to return results after an insert used batch.commit

### ISSUE THREAD

**Issue by Dn-a** [tekartik/sqflite#429]
Hi @alextekartik , congratulations for this fantastic plug-in.
The guide mentions `await batch.commit (noResult: true);` to avoid results.Instead to get the results how can I do it? I noticed that the methods of the Batch object return a void type
Example
```
final List<int> ids = [];
    await database.transaction((db) async {
      Batch btc = db.batch();
      values.forEach((value) async {
//problem
          final int id = await btc
              .insert(tableName, value);
          ids.add(id);
      });
        await btc.commit(noResult: noResult);
    });
    return ids;
```
thanks

**Comment by alextekartik** [comment]
commits returns a list of result, matching all the commands added. In you case, since you do only insert, each item is the inserted id.

```dart
// only keep ids as int, set other result to null
ids = (await btc.commit())
    .map((result) => result is int ? result : null)
    .cast<int>();
```

**Comment by Dn-a** [comment]
it was so simple, how did I not think about it? thanks
