### ISSUE TITLE
Please support DateTime 

### ISSUE THREAD

**Issue by escamoteur** [tekartik/sqflite#43]
For a Database DateTime is an essential type especially with sorting please support DateTime.
I know that SQLite doesn't support a special Datetype but the Dart interface should do it

**Comment by alextekartik** [comment]
Indeed SQLite does not support storing Date, see the note here: https://www.sqlite.org/datatype3.html
Personally I store them as int (millisSinceEpoch) or string (iso8601) that I convert to/from a DateTime in the toMap/fromMap fonction I typically used for object to/from record conversion. When reading a record (as a map) there is no information that the field is a Date so it is up to the reader to convert it. I understand your need but the purpose of sqflite is to provider a thin layer around SQLite provider by iOS and Android. Providing extra conversion feature could be built on top of it.

Even JSON does not support DateTime conversion...
