### ISSUE TITLE
onUpgrade problem

### ISSUE THREAD

**Issue by SebAubin** [tekartik/sqflite#430]
Hi, I have an issue with the onUpgrade function and the version of the database. If I upgrade the version to 17 instead of 16, there is no change. The version is still 16. Therefore the onUpgrade function is not called. Here's my code:

```
var database = openDatabase(p.join(await getDatabasesPath(), 'database.db'),
        onCreate: (Database db, int version) async {
      await db.execute(
          'CREATE TABLE Users(userId INTEGER, givenName TEXT, familyName TEXT, email TEXT, username TEXT)');
    }, onUpgrade: (Database db, int oldVersion, int newVersion) async {
      print("$oldVersion - $newVersion");
}, version: 17);
```

**Comment by alextekartik** [comment]
Once you open it with a given version, onUpgrade will be called once and won't be called again so you can only test this once. Even if you do nothing in your `onUpgrade` method, the version will be upgraded. Can you confirm that the version is still 16 after opening the database? (db.getVersion()).

**Comment by SebAubin** [comment]
Yes it is still 16 even if I open the databse and make a few requests on it (multiple selects)

**Comment by alextekartik** [comment]
That is weird indeed. I assume the database is not opened yet and you are not opening the same database with different version while running.

If you can, can you try to reproduce the issue in a unit test: See example here: https://github.com/tekartik/sqflite_more/tree/d71dc29be35727bf70c0d703e21bb89c6e0dd9c2/sqflite_common_test_app#simple-test

Thanks!

**Comment by SebAubin** [comment]
Thanks for the answers. I figured it out. I was my mistake.

**Comment by hhgz9527** [comment]
> Thanks for the answers. I figured it out. I was my mistake.

Hi, i have same problem, how did you solve it?

Thanks

**Comment by SebAubin** [comment]
If I remember correctly, I wasn't editing the right file (database.db).

**Comment by hhgz9527** [comment]
> If I remember correctly, I wasn't editing the right file (database.db).

Ok, It doesn't seem to solve my problem. Thank you

https://github.com/tekartik/sqflite/issues/548
