### ISSUE TITLE
IOS  delete() API

### ISSUE THREAD

**Issue by huangsir0** [tekartik/sqflite#431]
ios 执行 delete方法清除数据后，db文件所占大小并没有减小。

**Comment by alextekartik** [comment]
Please use English (even if I'm not english native neither):
Google translate:
> After the delete method is used to clear the data, the size of the db file has not decreased.

Yes that is a known fact of SQLite (sqflite does nothing specific here). [`VACUUM`](https://www.sqlite.org/lang_vacuum.html) can be used if needed
