### ISSUE TITLE
Password Protect a SQFLite DB. 

### ISSUE THREAD

**Issue by raghavan-mookiah** [tekartik/sqflite#432]
There is no API to protect the database with a password. 

But as an SQLLite standard feature, you can protect the data with a password.

Could you please add that feature? 

References: https://stackoverflow.com/questions/1381264/password-protect-a-sqlite-db-is-it-possible

**Comment by davidmartos96** [comment]
@raghavan-mookiah I'm not sure that is a standard feature. I think the link you provided is a wrapper for SqlCipher. 
In Flutter you can use the package sqflite_sqlcipher which has the same API as Sqflite. It includes an optional password parameter to the openDatabase method.

**Comment by alextekartik** [comment]
As @davidmartos96 stated please use https://pub.dev/packages/sqflite_sqlcipher
