### ISSUE TITLE
No Such Table

### ISSUE THREAD

**Issue by yudaprama** [tekartik/sqflite#433]
I have sqlite3 asset named `person_db.sqlite` with table `person`. I copied asset with:

```dart
const _tableName = 'person';
const _personDB = 'person_db.sqlite';

Future<Database> openDB(String dbName) async {
  var databasesPath = await getDatabasesPath();
  var path = join(databasesPath, dbName);
  var exists = await databaseExists(path);

  if (!exists) {
    // Should happen only the first time you launch your application
    print("Creating new copy from asset");
    // Make sure the parent directory exists
    await Directory(dirname(path)).create(recursive: true);
    // Copy from asset
    ByteData data = await rootBundle.load(join("lib", "database", dbName));
    List<int> bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    // Write and flush the bytes written
    await File(path).writeAsBytes(bytes, flush: true);
    print('database $dbName is copied to $path');
  } else {
    print("Opening existing database");
  }
  // open the database
  return await openDatabase(
    path,
    version: 1,
    onCreate: (Database db, int version) async {
      var execute = await db.rawQuery('SELECT * FROM sqlite_master');
      print(execute);
    },
  );
}
```

I checked Device File Explorer, `person_db.sqlite` is already being copied. And I open it, there are `person` table with all it's data. But I get error `no such table: person` and method `onCreate` not being called

![2020-05-10_10-22](https://user-images.githubusercontent.com/33281225/81490118-2cae4180-92a8-11ea-8740-714cff097fe6.png)

Also:
```dart
  await ((await openDatabase(path)).close());
  await deleteDatabase(path);
```
Not working, I should delete manually from Device File Explorer

**Comment by yudaprama** [comment]
wipe emulator data and everything fine

**Comment by OzzyTheGiant** [comment]
Can confirm with @yudaprama. If you get this weird error and you double checked that the database and table exist, then just run `flutter clean` and run the app again as a clean install. Be sure that if you're testing data, don't put so many entries so as not to have to reenter them every time this happens. I've also checked, on iOS at least, that if you double click Home button to view the list of apps and close it from there, and then if you reopen the app directly, you should be able to see your previously saved entries.

**Comment by mohamadkenway** [comment]
Hi 
I found the solution and error cause,
if u first time with certain table name create a table with incorrect syntax , that table name doesn't responding any more and u should try other names or remove it's file in directory of phone
