### ISSUE TITLE
GeneratedPluginRegistrant.java fails to register com.tekartik.sqflite.SqflitePlugin());

### ISSUE THREAD

**Issue by MaatlaBird** [tekartik/sqflite#438]
```
C:\Users\Maatla\Downloads\Code\flutter_backend\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:18: error: cannot find symbol
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
                                                           ^
  symbol:   class SqflitePlugin
  location: package com.tekartik.sqflite
1 error

FAILURE: Build failed with an exception.
```

Added latest 1.3.0+1 to pubsec.yaml and plugin fails to registered by GeneratedPluginRegistrant.java

```
`package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
  }
}
```

- re-installed flutter sdk, switched to stable flutter channel, created new project and still facing same issue.
- flutter doctor -v output is all green ticks
- failing to build sqflite usage examples
- Cannot seem to find any problems with code; database helper class followed from @suragch below:

```
`import 'dart:io';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';

// database table and column names
final String tableScans = 'scans';
final String columnId = '_id';
final String columnFirstName = 'firstName';
final String columnLastName = 'lastName';
final String columnPersonalNumber = 'personalNumber'; 

// data model class
class Scan {
  int id;
  String firstName;
  String lastName;
  String personalNumber;

  Scan();

  // convenience constructor to create a Word object
  Scan.fromMap(Map<String, dynamic> map) {
    id = map[columnId];
    firstName = map[columnFirstName];
    lastName = map[columnLastName];
    personalNumber = map[columnPersonalNumber];
  }

  // convenience method to create a Map from this Word object
  Map<String, dynamic> toMap() {
    var map = <String, dynamic>{
      columnFirstName: firstName,
      columnLastName: lastName,
      columnPersonalNumber: personalNumber,

    };
    if (id != null) {
      map[columnId] = id;
    }
    return map;
  }
}

// singleton class to manage the database
class DatabaseHelper {
  // This is the actual database filename that is saved in the docs directory.
  static final _databaseName = "ScanDatabase.db";
  // Increment this version when you need to change the schema.
  static final _databaseVersion = 1;

  // Make this a singleton class.
  DatabaseHelper._privateConstructor();
  static final DatabaseHelper instance = DatabaseHelper._privateConstructor();

  // Only allow a single open connection to the database.
  static Database _database;

  Future<Database> get database async {
    if (_database != null) return _database;
    _database = await _initDatabase();
    return _database;
  }

  // open the database
  _initDatabase() async {
    // The path_provider plugin gets the right directory for Android or iOS.
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, _databaseName);
    // Open the database. Can also add an onUpdate callback parameter.
    return await openDatabase(path,
        version: _databaseVersion, onCreate: _onCreate);
  }

  // SQL string to create the database
  Future _onCreate(Database db, int version) async {
    await db.execute('''
              CREATE TABLE $tableScans (
                $columnId INTEGER PRIMARY KEY AUTOINCREMENT,
                $columnFirstName TEXT NOT NULL,
                $columnLastName TEXT NOT NULL,
                $columnPersonalNumber TEXT NOT NULL,
              );
              ''');
  }

  // Database helper methods:

  Future<int> insert(Scan scan) async {
    Database db = await database;
    int id = await db.insert(tableScans, scan.toMap());
    return id;
  }

  Future<List<Scan>> queryAllScans() async {
    Database db = await database;

    List<Map> maps = await db.query(tableScans);

    if (maps.length > 0) {
      List<Scan> scans = [];
      maps.forEach((map) => scans.add(Scan.fromMap(map)));
      return scans;
    }
    return null;
  }
}
`
```
What could be the issue? Engaged [community](https://stackoverflow.com/questions/61798919/flutter-sqflite-error-flutterengine-getplugins-addnew-com-tekartik-sqflite-s) with no help so far.

**Comment by Muniru0** [comment]
i think i ran into a similar problem problem, but mine is 

> ```
> C:\Users\Maatla\Downloads\Code\flutter_backend\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:18: error: cannot find symbol
>     flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
>                                                            ^
>   symbol:   class SqflitePlugin
>   location: package com.tekartik.sqflite
> 1 error
> 
> FAILURE: Build failed with an exception.
> ```
> 
> Added latest 1.3.0+1 to pubsec.yaml and plugin fails to registered by GeneratedPluginRegistrant.java
> 
> ```
> `package io.flutter.plugins;
> 
> import androidx.annotation.Keep;
> import androidx.annotation.NonNull;
> 
> import io.flutter.embedding.engine.FlutterEngine;
> 
> /**
>  * Generated file. Do not edit.
>  * This file is generated by the Flutter tool based on the
>  * plugins that support the Android platform.
>  */
> @Keep
> public final class GeneratedPluginRegistrant {
>   public static void registerWith(@NonNull FlutterEngine flutterEngine) {
>     flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
>     flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
>     flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
>   }
> }
> ```
> 
> * re-installed flutter sdk, switched to stable flutter channel, created new project and still facing same issue.
> * flutter doctor -v output is all green ticks
> * failing to build sqflite usage examples
> * Cannot seem to find any problems with code; database helper class followed from @suragch below:
> 
> ```
> `import 'dart:io';
> import 'package:path/path.dart';
> import 'package:path_provider/path_provider.dart';
> import 'package:sqflite/sqflite.dart';
> 
> // database table and column names
> final String tableScans = 'scans';
> final String columnId = '_id';
> final String columnFirstName = 'firstName';
> final String columnLastName = 'lastName';
> final String columnPersonalNumber = 'personalNumber'; 
> 
> // data model class
> class Scan {
>   int id;
>   String firstName;
>   String lastName;
>   String personalNumber;
> 
>   Scan();
> 
>   // convenience constructor to create a Word object
>   Scan.fromMap(Map<String, dynamic> map) {
>     id = map[columnId];
>     firstName = map[columnFirstName];
>     lastName = map[columnLastName];
>     personalNumber = map[columnPersonalNumber];
>   }
> 
>   // convenience method to create a Map from this Word object
>   Map<String, dynamic> toMap() {
>     var map = <String, dynamic>{
>       columnFirstName: firstName,
>       columnLastName: lastName,
>       columnPersonalNumber: personalNumber,
> 
>     };
>     if (id != null) {
>       map[columnId] = id;
>     }
>     return map;
>   }
> }
> 
> // singleton class to manage the database
> class DatabaseHelper {
>   // This is the actual database filename that is saved in the docs directory.
>   static final _databaseName = "ScanDatabase.db";
>   // Increment this version when you need to change the schema.
>   static final _databaseVersion = 1;
> 
>   // Make this a singleton class.
>   DatabaseHelper._privateConstructor();
>   static final DatabaseHelper instance = DatabaseHelper._privateConstructor();
> 
>   // Only allow a single open connection to the database.
>   static Database _database;
> 
>   Future<Database> get database async {
>     if (_database != null) return _database;
>     _database = await _initDatabase();
>     return _database;
>   }
> 
>   // open the database
>   _initDatabase() async {
>     // The path_provider plugin gets the right directory for Android or iOS.
>     Directory documentsDirectory = await getApplicationDocumentsDirectory();
>     String path = join(documentsDirectory.path, _databaseName);
>     // Open the database. Can also add an onUpdate callback parameter.
>     return await openDatabase(path,
>         version: _databaseVersion, onCreate: _onCreate);
>   }
> 
>   // SQL string to create the database
>   Future _onCreate(Database db, int version) async {
>     await db.execute('''
>               CREATE TABLE $tableScans (
>                 $columnId INTEGER PRIMARY KEY AUTOINCREMENT,
>                 $columnFirstName TEXT NOT NULL,
>                 $columnLastName TEXT NOT NULL,
>                 $columnPersonalNumber TEXT NOT NULL,
>               );
>               ''');
>   }
> 
>   // Database helper methods:
> 
>   Future<int> insert(Scan scan) async {
>     Database db = await database;
>     int id = await db.insert(tableScans, scan.toMap());
>     return id;
>   }
> 
>   Future<List<Scan>> queryAllScans() async {
>     Database db = await database;
> 
>     List<Map> maps = await db.query(tableScans);
> 
>     if (maps.length > 0) {
>       List<Scan> scans = [];
>       maps.forEach((map) => scans.add(Scan.fromMap(map)));
>       return scans;
>     }
>     return null;
>   }
> }
> `
> ```
> 
> What could be the issue? Engaged [community](https://stackoverflow.com/questions/61798919/flutter-sqflite-error-flutterengine-getplugins-addnew-com-tekartik-sqflite-s) with no help so far.


I ran into a similar problem last time, but mine was MissingPluginException  think it is caused by using the flutter embedding libraries.....

**Comment by MaatlaBird** [comment]
@Muniru0  you pointed me in the right direction there. I depended on the github sqflite url instead of the pub.dev package and thats when it worked! Thanks you!

**Comment by MaatlaBird** [comment]
![image](https://user-images.githubusercontent.com/40599226/82486433-1e98c600-9add-11ea-82f1-392f35038c15.png)
