### ISSUE TITLE
querying the table will return empty list regardless the data is in the database.

### ISSUE THREAD

**Issue by nelsonalexandrino** [tekartik/sqflite#443]
I have an App that is saving some data locally using Sqflite.

I am able to create the database.
I am able to save the data.

To make sure I even checked if the database exists using databaseExists().

I used this piece of code to count the number of row in my table.

```
return firstIntValue(
      await db.rawQuery('SELECT COUNT(*) FROM $TABLE_ACCOUNTS'),
    );
```

I am sure the data is being saved successfully because I get an ID returned when inserting the data with this method:

```
Future<LowKYCAccount> saveAccountLocaly(LowKYCAccount account) async {
    final db = await getDatabase();
    await db.transaction((transaction) async {
      account.autoId = await transaction.rawInsert(
          'INSERT INTO $TABLE_ACCOUNTS($COLUMN_ACCOUNT_ID, $COLUMN_CUSTOMER_PICTURE, $COLUMN_DOC_FRONT, $COLUMN_DOC_BACK, $COLUMN_SIGNATURE, $COLUMN_GENDER, $COLUMN_FIRST_NAME, $COLUMN_LAST_NAME, $COLUMN_DOC_TYPE, $COLUMN_BIRTHDAY, $COLUMN_DOC_NUMBER, $COLUMN_DOC_EXPIRATION_DATE, $COLUMN_ADDRESS, $COLUMN_ADDRESS2, $COLUMN_COUNTRY, $COLUMN_PROVINCE, $COLUMN_CITY, $COLUMN_HAS_JOB, $COLUMN_SALARY_RANGE, $COLUMN_JOB_DESIGNATION, $COLUMN_COMPANY_NAME, $COLUMN_JOB_TYPE, $COLUMN_COMPANY_TELEPHONE, $COLUMN_COMPANY_MONTHLY_INCOME_RANGE, $COLUMN_COMPANY_OWN_JOB, $COLUMN_COMPANY_BUSINESS_TYPE) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
          account.toList());
    });
    //account.autoId = await db.insert(TABLE_ACCOUNTS, account.toMap());
    return account;
  }
```

this is the code that create the database.

```
 Future<Database> getDatabase() {
    _database ??= _initDatabase();
    return _database;
  }

  Future<Database> _initDatabase() async {
    var databasesPath = await getDatabasesPath();
    print('databasesPath: $databasesPath');
    var dbpath = join(databasesPath, 'paperless.db');
    print('dbpath: $dbpath');

// Make sure the directory exists
    try {
      await Directory(databasesPath).create(recursive: true);
    } catch (_) {}

    return await openDatabase(
      dbpath,
      version: 1,
      onCreate: (Database db, int version) async {
        await db.execute(
          'CREATE TABLE $TABLE_ACCOUNTS ($COLUMN_AUTO_ID INTEGER PRIMARY KEY, '
          '$COLUMN_ACCOUNT_ID TEXT, '
          '$COLUMN_CUSTOMER_PICTURE BLOB, $COLUMN_DOC_FRONT BLOB, '
          '$COLUMN_DOC_BACK BLOB, $COLUMN_SIGNATURE BLOB, '
          '$COLUMN_GENDER INTEGER, $COLUMN_FIRST_NAME TEXT, '
          '$COLUMN_LAST_NAME TEXT, $COLUMN_DOC_TYPE TEXT, '
          '$COLUMN_BIRTHDAY TEXT, $COLUMN_DOC_NUMBER TEXT, '
          '$COLUMN_DOC_EXPIRATION_DATE TEXT, $COLUMN_ADDRESS TEXT, '
          '$COLUMN_ADDRESS2 TEXT, $COLUMN_COUNTRY TEXT, '
          '$COLUMN_PROVINCE TEXT, $COLUMN_CITY TEXT, '
          '$COLUMN_HAS_JOB TEXT, $COLUMN_SALARY_RANGE TEXT, '
          '$COLUMN_JOB_DESIGNATION TEXT, $COLUMN_COMPANY_NAME TEXT, '
          '$COLUMN_JOB_TYPE TEXT, $COLUMN_COMPANY_TELEPHONE TEXT, '
          '$COLUMN_COMPANY_MONTHLY_INCOME_RANGE TEXT, $COLUMN_COMPANY_OWN_JOB TEXT, '
          '$COLUMN_COMPANY_BUSINESS_TYPE TEXT)',
        );
      },
    );
  }
```

But for some reason I am not able to get the data from the database using this method:

```
Future<List<LowKYCAccount>> getLocalLowKYCAccount() async {
    final db = await getDatabase();
    var accounts = await db.query(TABLE_ACCOUNTS);
    print('accounts: $accounts');
    print(await db.query("sqlite_master"));

    var accountsList = List<LowKYCAccount>();
    accounts.forEach((account) {
      LowKYCAccount kycAccount = LowKYCAccount.fromMap(account);
      accountsList.add(kycAccount);
    });
    return accountsList;
  }
```

I also noticed that in the console this is printed

`E/SQLiteCursor(27200): onMove() return false. RequiredPos: 0 WindowStartPos: 0 WindowRowCount: 0(original count of query: 1)`

After debugging in every way I could, I am still facing this issue. I always get an empty list.

can you help me?

**Comment by alextekartik** [comment]
Sometimes print help in seeing what is wrong in your content:
```dart
print(await db.query("sqlite_master"));
print(await db.query(TABLE_ACCOUNTS));
```

If needed, bump the version of the database and re-create the table.

**Comment by nelsonalexandrino** [comment]
I have printed 

**`print('Querying the table: ${await db.query(TABLE_ACCOUNTS)}');**
`
`I/flutter (13217): Querying the table: []
`

**`    print('sqlite_master info: ${await db.query("sqlite_master")}');**
`
`I/flutter (13217): sqlite_master info: [{type: table, name: android_metadata, tbl_name: android_metadata, rootpage: 3, sql: CREATE TABLE android_metadata (locale TEXT)}, {type: table, name: Accounts, tbl_name: Accounts, rootpage: 4, sql: CREATE TABLE Accounts (id INTEGER PRIMARY KEY, accountID TEXT, customerPicture BLOB, docFrontPicture BLOB, docBackPicture BLOB, signature BLOB, gender INTEGER, firstName TEXT, lastName TEXT, docType TEXT, birthday TEXT, docNumber TEXT, docExpirationdate TEXT, address TEXT, address2 TEXT, country TEXT, province TEXT, city TEXT, hasJob TEXT, salaryRange TEXT, jobDesignation TEXT, companyName TEXT, jobType TEXT, telephone TEXT, monthlyIncomeRange TEXT, ownJob TEXT, businessType TEXT)}]`

**Comment by alextekartik** [comment]
Ok you have not data. Maybe you can try before (and display what is the id the object inserted) and after the insert to see if anything goes wrong in your insertion or turn on the basic console logging (https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#turn-on-sql-console-logging) to see your command as they are executed

**Comment by nelsonalexandrino** [comment]
Hi @alextekartik 

I turned on the logging and here is the printed info:

`D/Sqflite (28292): [1,Sqflite(13975)] BEGIN IMMEDIATE
`


`I/zygote  (28292): Background concurrent copying GC freed 11(4MB) AllocSpace objects, 3(27MB) LOS objects, 13% free, 156MB/180MB, paused 844us total 359.661ms`



`D/Sqflite (28292): [1,Sqflite(13975)] INSERT INTO Accounts(accountID, customerPicture, docFrontPicture, docBackPicture, signature, gender, firstName, lastName, docType, birthday, docNumber, docExpirationdate, address, address2, country, province, city, hasJob, salaryRange, jobDesignation, companyName, jobType, telephone, monthlyIncomeRange, ownJob, businessType) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [8aaf95af-a8ac-4a77-a544-fb54fb9a72a5, [-1, -40, -1, -31, -59, 39, 69, 120, 105, 102, 0, 0, 73, 73, 42, 0, 8, 0, 0, 0, 12, 0, 0, 1, 4, 0, 1, 0, 0, 0, 80, 6, 0, 0, 1, 1, 4, 0, 1, 0, 0, 0, -68, 4, 0, 0, 15, 1, 2, 0, 8, 0, 0, 0, -98, 0, 0, 0, 16, 1, 2, 0, 8, 0, 0, 0, -90, 0, 0, 0, 18, 1, 3, 0, 1, 0, 0, 0, 8, 0, 0, 0, 26, 1, 5, 0, 1, 0, 0, 0, -48, 0, 0, 0, 27, 1, 5, 0, 1, 0, 0, 0, -40, 0, 0, 0, 40, 1, 3, 0, 1, 0, 0, 0, 2, 0, 0, 0, 49, 1, 2, 0, 13, 0, 0, 0, -82, 0, 0, 0, 50, 1, 2, 0, 20, 0, 0, 0, -68, 0, 0, 0, 19, 2, 3, 0, 1, 0, 0, 0, 1, 0, 0, 0, 105, -121, 4, 0, 1, 0, 0, 0, -32, 0, 0, 0, -122, 2, 0, 0, 115, 97, 109, 115, 117, 110, 103, 0, 83, 77, 45, 80, 53, 56, 53, 0, 80, 53, 56, 53, 74, 88, 85, 51, 67, 82, 75, 51, 0, 0, 50, 48, 50, 48, 58, 48, 54, 58, 48, 51, 32, 49, 48, 58, 50, 53, 58, 49, 56, 0, 72, 0, 0, 0, 1, 0, 0, 0, 72, 0, 0, 0, 1, 0, 0, 0, 20, 0, -102, -126, 5, 0, 1, 0, 0, 0, 96, 2, 0, 0, -99, -126, 5, 0, 1, 0, 0, 0, 104, 2, 0, 0, 34, -120, 3, 0, 1, 0, 0, 0, 2, 0, 0, 0, 39, -120, 3, 0, 1, 0, 0, 0, -112, 1, 0, 0, 0, -112, 7, 0, 4, 0, 0, 0, 48, 50, 50, 48, 3, -112, 2, 0, 20, 0, 0, 0, 56, 2, 0, 0, 4, -112, 2, 0, 20, 0, 0, 0, 76, 2, 0, 0, 5, -110, 5, 0, 1, 0, 0, 0, 112, 2, 0, 0, 7, -110, 3, 0, 1, 0, 0, 0, 2, 0, 0, 0, 9, -110, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 10, -110, 5, 0, 1, 0, 0, 0, 120, 2, 0, 0, 124, -110, 7, 0, 98, 0, 0, 0, -42, 1, 0, 0, 1, -96, 3, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, -96, 4, 0, 1, 0, 0, 0, 80, 6, 0, 0, 3, -96, 4, 0, 1, 0, 0, 0, -68, 4, 0, 0, 2, -92, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, -92, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 5, -92, 3, 0, 1, 0, 0, 0, 30, 0, 0, 0, 6, -92, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 32, -92, 2, 0, 6, 0, 0, 0, -128, 2, 0, 0, 0, 0, 0, 0, 7, 0, 1, 0, 7, 0, 4, 0, 0, 0, 48, 49, 48, 48, 2, 0, 4, 0, 1, 0, 0, 0, 0, 32, 1, 0, 12, 0, 4, 0, 1, 0, 0, 0, 0, 0, 0, 0, 16, 0, 5, 0, 1, 0, 0, 0, 90, 0, 0, 0, 64, 0, 4, 0, 1, 0, 0, 0, 0, 0, 0, 0, 80, 0, 4, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 48, 50, 48, 58, 48, 54, 58, 48, 51, 32, 49, 48, 58, 50, 53, 58, 49, 56, 0, 50, 48, 50, 48, 58, 48, 54, 58, 48, 51, 32, 49, 48, 58, 50, 53, 58, 49, 56, 0, 1, 0, 0, 0, 9, 0, 0, 0, 22, 0, 0, 0, 10, 0, 0, 0, -29, 0, 0, 0, 100, 0, 0, 0, -12, 0, 0, 0, 100, 0, 0, 0, 83, 82, 50, 53, 57, 0, 8, 0, 0, 1, 4, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 1, 4, 0, 1, 0, 0, 0, -128, 1, 0, 0, 3, 1, 3, 0, 1, 0, 0, 0, 6, 0, 0, 0, 26, 1, 5, 0, 1, 0, 0, 0, -20, 2, 0, 0, 27, 1, 5, 0, 1, 0, 0, 0, -12, 2, 0, 0, 40, 1, 3, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 2, 4, 0, 1, 0, 0, 0, -4, 2, 0, 0, 2, 2, 4, 0, 1, 0, 0, 0, 35, -62, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 1, 0, 0, 0, 72, 0, 0, 0, 1, 0, 0, 0, -1, -40, -1, -32, 0, 16, 74, 70, 73, 70, 0, 1, 1, 2, 0, 59, 0, 59, 0, 0, -1, -37, 0, 67, 0, 3, 2, 2, 3, 2, 2, 3, 3, 3, 3, 4, 3, 3, 4, 5, 8, 5, 5, 4, 4, 5, 10, 7, 7, 6, 8, 12, 10, 12, 12, 11, 10, 11, 11, 13, 14, 18, 16, 13, 14, 17, 14, 11, 11, 16, 22, 16, 17, 19, 20, 21, 21, 21, 12, 15, 23, 24, 22, 20, 24, 18, 20, 21, 20, -1, -37, 0, 67, 1, 3, 4, 4, 5, 4, 5, 9, 5, 5, 9, 20, 13, 11, 13, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, -1, -64, 0, 17, 8, 1, -128, 2, 0, 3, 1, 34, 0, 2, 17, 1, 3, 17, 1, -1, -60, 0, 31, 0, 0, 1, 5, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, -1, -60, 0, -75, 16, 0, 2, 1, 3, 3, 2, 4, 3, 5, 5, 4, 4, 0, 0, 1, 125, 1, 2, 3, 0, 4, 17, 5, 18, 33, 49, 65, 6, 19, 81, 97, 7, 34, 113, 20, 50, -127, -111, -95, 8, 35, 66, -79, -63, 21, 82, -47, -16, 36, 51, 98, 114, -1`


```
D/Sqflite (28292): [1,Sqflite(13975)] inserted 3
D/Sqflite (28292): [1,Sqflite(13975)] COMMIT
```

**Comment by alextekartik** [comment]
And your table Account is till empty? (i.e. what does `print(await db.query(TABLE_ACCOUNTS));` gives). I don't recommend using blob for big data (it will fail for blob above 1MB). Maybe that's the issue. Can you try without blob?

**Comment by nelsonalexandrino** [comment]
@alextekartik also after trying to insert data on the database I executed this piece of code

```
firstIntValue(
      await db.rawQuery('SELECT COUNT(*) FROM $TABLE_ACCOUNTS'),
    );
```

and the response is 3.
Meaning were found 3 rows.

**Comment by nelsonalexandrino** [comment]
OK! let me try without blob.

**Comment by nelsonalexandrino** [comment]
Hi @alextekartik I have tried to save and read data without blob successfully.
It seams the problem was with the size of the blob I was trying to save.

Thank you for your help to understand what was happening.

**Now, it there any workout around to save a blob above 1MB ?**

**Comment by alextekartik** [comment]
> Now, is there any workout around to save a blob above 1MB ?

The workaround is to save the blob in an external file and save the reference in sqlite

> Is there a limit for the TEXT type?

Not that I am aware of. Likely 1MB (due to cursor size limit when reading)

**Comment by nelsonalexandrino** [comment]
Thank you! I am closing this issue.
