### ISSUE TITLE
Build for release architecture error   

### ISSUE THREAD

**Issue by luisEnriqueR** [tekartik/sqflite#444]
Running _flutter build ios_ gives the next error.
I am able to run the project in xcode and flutter run, its completely useful  the db part, but cant build the app for release

Xcode's output:
↳
    Building AOT snapshot in release mode (ios-release)...
    Building App.framework for arm64...

    Building App.framework for armv7...
    Building AOT snapshot in release mode (ios-release)...             29.4s
    Built to build/aot/.
    warning: parsing line table prologue at offset 0x6f697463 found unsupported version 0x00
    warning: line table parameters mismatch. Cannot emit.
    note: while processing /Users/luis/Documents/freelance/destruye-el-enarm/mobile/build/aot/armv7/snapshot_assembly.o
    Project /Users/luis/Documents/freelance/destruye-el-enarm/mobile built and packaged successfully.
    Non-fat binary /Users/luis/Documents/freelance/destruye-el-enarm/mobile/build/ios/Release-iphoneos/Runner.app/Frameworks/sqflite.framework/sqflite is not armv7. Running lipo -info:
    Non-fat file: /Users/luis/Documents/freelance/destruye-el-enarm/mobile/build/ios/Release-iphoneos/Runner.app/Frameworks/sqflite.framework/sqflite is architecture: arm64
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Encountered error while building for device.

**Comment by alextekartik** [comment]
I think arm7 is no longer supported (but I could be wrong). I'm not an expert in iOS build but there are several similar issues in Flutter and sometimes the best is just the recreate the iOS project (`flutter create .`)

**Comment by alextekartik** [comment]
@luisEnriqueR  Are you still getting the issue? If you solve it, can you share what you have done?

**Comment by luisEnriqueR** [comment]
@alextekartik sorry for the late response...
Yeah, i resolved remouving the armv7 architecture... You're right is deprecated.
I give this sc with the change i made. 
![image](https://user-images.githubusercontent.com/25944810/86875068-494bd780-c0a7-11ea-918e-24308b336407.png)
