### ISSUE TITLE
Provide possibility to replace the database factory instance

### ISSUE THREAD

**Issue by devjeff** [tekartik/sqflite#445]
At the moment, sqflite uses a database factory instance from the "factory_impl.dart" file for many internal operations. I would like to be able to replace the used instance at runtime for instance by the factory implementation provided in [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi) 

Unfortunately, there is only a deprecated setter method called "sqlfliteDatabaseFactory" that can be used to achieve this. Am I missing something? If not, it would be great to provide a possibility to replace the database factory instance with a different implementation.

**Comment by alextekartik** [comment]
Modifying the default factory used has an impact on all existing components using sqflite which can lead to unexpected results. The setter is deprecated on purpose.

in `sqflite_dev.dart`, there is setMockDatabaseFactory (also deprecated/visibleForTesting) which can be used. https://pub.dev/documentation/sqflite/latest/sqflite_dev/setMockDatabaseFactory.html

Best is to use the factory as a parameter/global in your code that can be changed.

**Comment by devjeff** [comment]
Thanks for the quick reply. I understand you suggestion, still I think it's not feasible in several cases:

1. If I want to use some present methods in sqflite.dart like "getDatabasesPath" or "openDatabase" I can not do that without overriding the default factory. If the calls are within my own code, it would be possible. Still, there's a risk that some developers of the project would use the default methods from sqflite.dart by accident, which might be recognized too late.
2. If I use 3rd party libraries like [jaguar_query_sqflie](https://pub.dev/packages/jaguar_query_sqflite), there is some code like the "SqfliteAdapter" class, which calls the main "openDatabase" method and is out of my control. Of course, I could override the class and the problematic method, but this would mean that I need to investigate the internal code of the 3rd party library to find all the problematic code parts.

That's why I think, there should be an officially supported way to override the default factory. You said, this has an impact on all existing components and could lead to unexpected results. Could you give some examples? I'm wondering, if there's a reasonable use case, where somebody would want to use a custom database factory for some part of the code and the default factory for the rest.

**Comment by alextekartik** [comment]
setMockDatabaseFactory is currently the "official" way and should work if you call it before any other sqflite methods. We could decide to add a new official setter (without mock in in its name). Does it solve your issue?

>  I'm wondering, if there's a reasonable use case, where somebody would want to use a custom database factory for some part of the code and the default factory for the rest.

One scenario I could think of is using a sqflite version that encrypts data in your app while using a cache manager based on sqflite where you don't want encryption (and that uses the default factory).

**Comment by devjeff** [comment]
Yes, this solves my issue. The setMockDatabaseFactory method internally calls the "sqlfliteDatabaseFactory" setter method that I mentioned in my initial description. Still, it seems to be kind of a hack to use a deprecated method that was supposed to be used for testing purposes. 

I think, it would be a good idea to add a new official setter method that can be used to replace the database factory.

**Comment by alextekartik** [comment]
I was about to export sqfliteDatabaseFactory setter. However it needs to export some internal definition (SqfliteDatabaseFactory) that i don't want to expose at this point.

I also just notice the typo in sqlfliteDatabaseFactory, stupid me.

So I simpler added a setter to databaseFactory. It will only work for compatible database factory (and implementing such requires access to some internals). It should only be called once before any other call to sqflite and will print a warning otherwise.

I published sqflite 1.3.1-dev.1 with the exported databaseFactory. Le me know if that works for you

**Comment by alextekartik** [comment]
@devjeff  does it fix you issue?

**Comment by devjeff** [comment]
Hey, sorry, I wasn't able to test it till now. I will try it out today and let you know.

**Comment by devjeff** [comment]
It works with the new setter method. The only thing that is not very clean is the fact that I need to import the "package:sqflite/src/factory_impl.dart", which leads to the 'implementation_imports' warning. Would it be bad to include the setter in the sqflite.dart file (or at least export it from here)?

**Comment by alextekartik** [comment]
Humm weird, it is in sqflite.dart. `databaseFactory` setter should be exported without private imports. Are you using sqflite 1.3.1-dev.1?

**Comment by devjeff** [comment]
Yes, you're right. I somehow missed the export statement. It works. You can can close the issue if there are no more open tasks.

**Comment by alextekartik** [comment]
Published 1.3.1
