### ISSUE TITLE
FCM OnBackGroundMessage -  MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

### ISSUE THREAD

**Issue by renenucci** [tekartik/sqflite#446]
Hi,

I'm trying to use FCM onBackGroundMessage with sqflite and I'm facing this exception `MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)`

Only if app is in background, I suspect that is similar to #169 but I'm not sure.

My flutter project is using kotlin version and I have an Application.kt with this code:

```
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
    }
}
````

as far I know, this 'register' fcm to run in background. But I'm newbie with native code and how this 'bridge' works.

Anyone knows how to make both work together? (firebase_messagind and sqflite)

**Comment by alextekartik** [comment]
Although I have not tried this scenario, maybe you should also register the Sqflite plugin here (the registration code to copy is available in the generated GeneratedPluginRegistrant)
```
SqflitePlugin.registerWith(registry.registrarFor("com.tekartik.sqflite.SqflitePlugin"));
```

**Comment by renenucci** [comment]
> Although I have not tried this scenario, maybe you should also register the Sqflite plugin here (the registration code to copy is available in the generated GeneratedPluginRegistrant)
> 
> ```
> SqflitePlugin.registerWith(registry.registrarFor("com.tekartik.sqflite.SqflitePlugin"));
> ```

NICEEEEEEEEEEEEEEEEEEE this works!
THANK YOU VERY MUCH!

**Comment by TheUnriashol** [comment]
I seem to be having this same issue. Only difference is that I am using background_fetch. Everything works fine while the app is open but as soon as I close the app completely and it runs a headless task I get this error:

```
06-10 03:13:43.695 9848-9848/com.example.example D/TSBackgroundFetch: - Background Fetch event received
06-10 03:13:43.695 9848-9848/com.example.example D/TSBackgroundFetch: �� [HeadlessTask flutter_background_fetch]
06-10 03:13:43.695 9848-9865/com.example.example I/flutter: [BackgroundFetch] Headless event received: flutter_background_fetch
06-10 03:13:43.695 9848-9865/com.example.example  E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #2      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
    #3      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:82:7)
    #4      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
    #5      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
    #6      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
    #7      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
    #8      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
    #9      getDatabasesPath (package:sqflite/sqflite.dart:168:54)
    #10     DatabaseHelper.initDb (package:example/services/DatabaseHelper.dart:25:47)
    #11     DatabaseHelper.db (package:example/services/DatabaseHelper.dart:18:17)
    #12     DatabaseHelper.getIn (package:example/services/DatabaseHelper.dart:73:26)
    #13     backgroundFetchHeadlessTask (package:example/main.dart:18:18)
    #14     _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:619:15)
    #15     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
    #16     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
    #17     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
    #18     _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
    #19     _rootRun (dart:async/zone.dart:1184:13)
    #20     _CustomZone.run (dart:async/zone.dart:1077:19)
    #21     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #22     _invoke3 (dart:ui/hooks.dart:289:10)
    #23     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
```
I have created the Application.kt file which looks like this for me:

```
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import com.tekartik.sqflite.SqflitePlugin

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
    }

    override fun registerWith(registry: PluginRegistry?) {
        SqflitePlugin.registerWith(registry?.registrarFor("com.tekartik.sqflite.SqflitePlugin"));
    }
}
```

And I have added the Application.kt file to my manifest like this:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.example">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:name=".Application"
        android:label="Example"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">

...
```

I have also run:

```
flutter packages get

flutter pub get

flutter clean
```

But nothing has helped.

Any idea why I am still having this issue. Is it just simply impossible to run sqflite in a headless background task?

**Comment by emouawad** [comment]
@TheUnriashol did u find a solution for this?

@alextekartik can you please refer some documentation about this?

Trying to use it from background isolate (pub workmanager)
Flutter 1.20.4
sqflite 1.3.1+1

**Comment by alextekartik** [comment]
sqflite (like most plugins) cannot be used from a background isolate.

**Comment by emouawad** [comment]
> sqflite (like most plugins) cannot be used from a background isolate.

Thanks for the fast reply - sorry i am no flutter expert (not sure about the terminology i.e isolate) but are you saying there is no way to use sqflite in a background service? not sure if it's possible to run background code on main isolate or it has to be in a seperate isolate.

Any workarounds to use sql lite from background?

**Comment by alextekartik** [comment]
sqflite transaction mechanism is not safe across multiple isolates (dart mechanism for having multiple threads) and so far flutter plugin service support for background isolate is not clear for me. sqflite already runs in the background so you can call from the main isolate and do cpu extensive operation in background function (using `compute`) to have somehow a background task running that won't jank the UI

**Comment by TheUnriashol** [comment]
@emouawad I did not find a solution sadly. In the end I just have it running in the background while the app is running. It still does not work to have it run with the app closed and I also don't really have any leads on how to do it either.

@alextekartik Is there a way to execute the `compute` function while the app is closed, like a background task to do some syncing?

**Comment by TheUnriashol** [comment]
#https://github.com/flutter/flutter/issues/62006

**Comment by alextekartik** [comment]
>  Is there a way to execute the compute function while the app is closed, like a background task to do some syncing?

I'm not aware of any cross-platform solution.

**Comment by emouawad** [comment]
> sqflite transaction mechanism is not safe across multiple isolates (dart mechanism for having multiple threads) and so far flutter plugin service support for background isolate is not clear for me. sqflite already runs in the background so you can call from the main isolate and do cpu extensive operation in background function (using `compute`) to have somehow a background task running that won't jank the UI

Sadly I need to use a background service because the app has to pull data periodically from a remote api server - The confusing thing is that i already have other plugins working in the same function like: flutter_local_notifications

**Comment by AlecDr** [comment]
Hey @TheUnriashol, did you found a solution for this?

**Comment by TheUnriashol** [comment]
@AlecDr I actually stopped looking for a solution since I also stopped working on the project I needed this for. But I am monitoring these issues for posible solutions. Seems like Flutter 2 seems to have solved it for some people. But I have not had time to try it out.
