### ISSUE TITLE
Modify an existing db with a new Table

### ISSUE THREAD

**Issue by francescovallone** [tekartik/sqflite#447]
Hello,
I would like to add a new table to my database without deleting the whole database.
The database already exists, so it means that there are already some entries and I want to keep them.
There is a way to do that?

**Comment by davidmartos96** [comment]
@francescovallone  The openDatabase method provides a callback called onUpgrade to handle these use cases.
Take a look at the docs: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/migration_example.md

You would have to change the version of the database from 1 to 2 and modify the onUpgrade callback accordingly.

**Comment by francescovallone** [comment]
Thanks, I will read the docs more carefully the next time.
