### ISSUE TITLE
deleteDatabase() not delete the .db file

### ISSUE THREAD

**Issue by louia** [tekartik/sqflite#460]
Hi,
After logout of user, I delete the Database of user. First i rawdelete every table of my database and then i want to delete the .db file.

But when I look at /data/data/com....../app_flutter, i always see .db file and when i export it and open it with DBrowerser for SQLite i always see my database schema.

My code to delete : 
```flutter
   await ((await openDatabase(path)).close());
    try{
      await deleteDatabase(path);
    }catch( e){
      print(e.toString());
    }
    _database = null;
```
It's beacause i am in debug ?
Thanks for the response @tekartik

**Comment by alextekartik** [comment]
Thanks for the report. This case is well tested in unit test so to be sure, can you confirm that the database is not re-opened somewhere else?

Or can you try to reproduce the issue in a unit test or a small app?

Or can you add `Sqflite.devSetDebugModeOn(true);` temporarily in your main before any database calls and show the logs confirming that the database is deleted and not re-opened?

thanks
