### ISSUE TITLE
Does sqflite support windows desktop application?

### ISSUE THREAD

**Issue by jims57** [tekartik/sqflite#468]
I tried to write sqflite to support Windows application, but failed. Do you have plan to make sqflite to support Windows application in the future?

By the way, it will be better, if web app is supported.

**Comment by alextekartik** [comment]
[`sqflite_common_ffi`](https://pub.dev/packages/sqflite_common_ffi) works on windows. Currently there is no reliable persistent web support.

**Comment by alextekartik** [comment]
I added some notes on how to supports Windows and Linux here: https://github.com/tekartik/sqflite/blob/develop/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md
