### ISSUE TITLE
how to save a list of int into one table?

### ISSUE THREAD

**Issue by jinfagang** [tekartik/sqflite#469]
table can save string, integer, etc. How to save a list of ints then?

**Comment by alextekartik** [comment]
One solution is to simply convert the list to string (json encoded string, comma separated list of ints).

Some info here with a similar issue (how to store an inner map): https://github.com/tekartik/sqflite/blob/master/sqflite/doc/supported_types.md

**Comment by jinfagang** [comment]
@alextekartik  thanks
