### ISSUE TITLE
UNIQUE COLLATE NOCASE with non-Latin symbol

### ISSUE THREAD

**Issue by RomanKapshuk** [tekartik/sqflite#473]
How to make work UNIQUE COLLATE NOCASE in the case when column can contain both English and non-English symbols?

Example 

```
CREATE TABLE IF NOT EXISTS testTable (
id text PRIMARY KEY,
queryColumn text,
UNIQUE (queryColumn COLLATE NOCASE)
);

```

With English word – all just ok 

```
INSERT testtable (id, queryColumn) VALUES ('id1', 'ABC'); // Inserted (OK)
INSERT testtable (id, queryColumn) VALUES ('id2', 'Abc'); // Not-Inserted (OK)
INSERT testtable (id, queryColumn) VALUES ('id3', 'AbC');// Not-Inserted (OK)
```

With Cyrillic  – not ok

```
INSERT testtable (id, queryColumn) VALUES ('id4, 'АБВ'); // Inserted (OK)
INSERT testtable (id, queryColumn) VALUES ('id5', 'Абв'); // Inserted (NOT OK)
INSERT testtable (id, queryColumn) VALUES ('id6', 'АбВ');// Inserted (NOT OK)
```

**Comment by alextekartik** [comment]
Unfortunately it does not seem consistent on the various implementation and sqflite uses whatever the platform provides. One safe solution I see is to add another column where you manually convert the string (lowercase, removing diacritics). see https://github.com/tekartik/sqflite/issues/231 for a similar bug and proposed solution

**Comment by RomanKapshuk** [comment]
Ok, I close the issue. Thanks
