### ISSUE TITLE
Query returns empty results with not primary key condition

### ISSUE THREAD

**Issue by salvakexx** [tekartik/sqflite#48]
i'm trying to execute next query in my flutter application: 
`
return await _db.query("npa", columns: ["id", "title" ,"identifier"], where: '"identifier" = ?', whereArgs: ["0008120150514"]);
`
but the results is always - empty QueryResultSet[].

If i'm trying to do the same with the id field and integer value like 
`
return await _db.query("npa", columns: ["id", "title" ,"identifier"], where: '"id" = ?', whereArgs: [215]);
`

- works fine.

I've got the npa.identifier = "0008120150514" (id : 215) in database, so the trouble not in data existense.

**Comment by alextekartik** [comment]
Hi, thanks for the report. I tried to reproduce your issue but could not manage. See my test here: https://github.com/tekartik/sqflite/commit/06e393aed98670e392dde661c9f70f71d3523e52

Do you have a sample code I could try to reproduce

**Comment by salvakexx** [comment]
Sorry that disturbed you. issue was in my application. it downloads a database from url, so that was little file version issue... 

Thanks a lot for your quick reply!!!
