### ISSUE TITLE
Slow insert Value into the Table

### ISSUE THREAD

**Issue by DipakSkywave** [tekartik/sqflite#486]
If I can insert 31,000 values into the table then it can be taken at least 5 to 7 minutes.

  sqflite: ^1.3.0+1
  path_provider: ^1.6.8

await db.saveUser(user);

 Future<SqliteUser> saveUser(
      SqliteUser sqliteUser) async {
    var dbClient = await db;
    sqliteUser.id = await dbClient.insert(
        "User", sqliteUser.toMap(),
        conflictAlgorithm: ConflictAlgorithm.replace);
    return sqliteUser;
  }

Map<String, dynamic> toMap() {
    var map = new Map<String, dynamic>();

    map["id"] = id;
    map["name"] = name;

    return map;
  }

**Comment by davidmartos96** [comment]
Make sure to use transactions + batches when doing many write operations at once. It can improve performance by a lot.

**Comment by DipakSkywave** [comment]
Can you tell me how to use a Transactions + Batch?

**Comment by davidmartos96** [comment]
You would have to change a bit your implementation, but this is the idea.

```dart
    await db.transaction((txn) async {
      final batch = txn.Batch();
      for (var user in users) {
        batch.insert(...);
      }
      await batch.commit();
    });
```

**Comment by DipakSkywave** [comment]
> You would have to change a bit your implementation, but this is the idea.
> 
> ```dart
>     await db.transaction((txn) async {
>       final batch = txn.batch();
>       for (var user in users) {
>         batch.insert(...);
>       }
>       await batch.commit();
>     });
> ```

Not working the same result
