### ISSUE TITLE
MissingPluginException when testing with sqflite

### ISSUE THREAD

**Issue by VinceERS** [tekartik/sqflite#49]
Hi, I'm wondering if there is a way to workaround this problem when running flutter test with sqflite.  I know that there is also a similar problem with path_provider when testing because getting a directory for use with tests is different (https://flutter.io/cookbook/persistence/reading-writing-files/).

After following the testing steps on that page I was able to get past the first problem with path_provider, but then get the following:

```
MissingPluginException(No implementation found for method openDatabase on channel com.tekartik.sqflite)
package:flutter/src/services/platform_channel.dart 153:7   MethodChannel.invokeMethod
  ===== asynchronous gap ===========================
  dart:async                                                 _Completer.completeError
  package:flutter/src/services/platform_channel.dart         MethodChannel.invokeMethod
  ===== asynchronous gap ===========================
  dart:async                                                 _asyncThenWrapperHelper
  package:flutter/src/services/platform_channel.dart 146:74  MethodChannel.invokeMethod
  package:sqflite/src/sqflite_impl.dart 17:28                invokeMethod
  ===== asynchronous gap ===========================
  dart:async                                                 new Future.microtask
  package:sqflite/src/sqflite_impl.dart 16:69                invokeMethod
  package:sqflite/src/database.dart 197:7                    SqfliteDatabase.invokeMethod
  package:sqflite/src/database.dart 459:14                   SqfliteDatabase._openDatabase.<fn>
  package:sqflite/src/exception.dart 78:28                   wrapDatabaseException
  ===== asynchronous gap ===========================
  dart:async                                                 new Future.microtask
  package:sqflite/src/exception.dart 76:62                   wrapDatabaseException
  package:sqflite/src/database.dart 458:12                   SqfliteDatabase._openDatabase
  package:sqflite/src/database.dart 506:28                   SqfliteDatabase.open
  ===== asynchronous gap ===========================
  dart:async                                                 new Future.microtask
  package:sqflite/src/database.dart 487:39                   SqfliteDatabase.open
  package:sqflite/src/database.dart 610:19                   openDatabase
  package:sqflite/sqflite.dart 280:5                         openDatabase
  package:flutter_app/services/data.service.dart 28:28       DataService.initDb
```

This is what I have tried and it doesn't seem to have worked, the tests run forever:

```
final Directory directory = await Directory.systemTemp.createTemp();
final String path = join(directory.path, "main.db");

const MethodChannel('com.tekartik.sqflite')
        .setMockMethodCallHandler((MethodCall methodCall) async {
      if (methodCall.method == 'openDatabase') {
        SqfliteDatabase db = new SqfliteDatabase(path);
        return db.open(version: 1, onCreate: _onCreate);
      }
      return null;
});
```

**Comment by alextekartik** [comment]
I don't think we can run test with plugins as the tests don't run on the device. As a TDD fan, I miss this feature too. At least I did not find a way to do it. None of the "official" flutter plugins have any as far as I can tell and according to https://stackoverflow.com/questions/46382789/how-to-run-tests-with-code-that-depends-on-plugins there is no solution. I remember seeing an example of native code and flutter driver somewhere but I could not make it work.

If you can leave with mocking the API, you could take a look at what I did here (it uses some private source so might break): https://github.com/tekartik/sqflite/blob/master/test/src_database_test.dart if that could help (but it might be a pain to mock return values from the plugin)

**Comment by newlix** [comment]
hi, can you provide some suggestion to do testing with sqflite?  Do I have to run `flutter drive`?  
Thank you

**Comment by alextekartik** [comment]
I'm not aware of any way of doing dart unit-testing with plugins. flutter drive could be a (currently painful) solution. Even plugins in https://github.com/flutter/plugins/ don't have these kinds of test. I'm still waiting for a solution

**Comment by nathansamson** [comment]
Can we not provide a native backend as well where it handles sqlite calls to https://pub.dartlang.org/packages/sqlite?

I understand this might basically triple the work needed for implementation, but I think it might be worth it...

**Comment by alextekartik** [comment]
I have not tried this package yet, have you? Your are talking about testing right (I'm not aware of native backend without objc/java yet). For testing I guess it should have to work on the workstation used (mac, linux, win) so I guess a dart2 compatible native sqlite package should work (if you know any)
An alternative for testing would be to have sqlite server and mock native calls to it. If you know any flutter package with native calls and complete unit tests, that would be great.

**Comment by nathansamson** [comment]
I did not try the package yet, it seems it just wraps the native C/C++ library so it  should work on mac, linux and win so should in general work for unit testing purposes

It seems the package is a bit unmainaintaned though. Not sure what its test coverage though

**Comment by alextekartik** [comment]
I could not manage to make it work...

**Comment by jlcool** [comment]
现在还是没办法写测试吗
Is it still impossible to write tests now?

**Comment by alextekartik** [comment]
There is still no simple/managed ways to run unit test on the device. In this thread <https://github.com/tekartik/sqflite/issues/83>, there is a solution though

    # run the test
    flutter run test/sqlite_test.dart

with some caveats...

**Comment by rolurq** [comment]
@alextekartik how about if you provide the mocks you used in https://github.com/tekartik/sqflite/blob/master/test/src_database_test.dart in an extra package to ease with testing?

**Comment by alextekartik** [comment]
@rolurq The mocks here are here for testing that the correct calls are made to the plugins. You might want a simpler mock just by implementing `DatabaseFactory`:

```dart
import 'dart:async';

import 'package:sqflite/sqflite.dart';

class DatabaseFactoryMock implements DatabaseFactory {
  @override
  Future<bool> databaseExists(String path) async {
    return false;
  }

  @override
  Future<void> deleteDatabase(String path) async {}

  @override
  Future<String> getDatabasesPath() async {
    return null;
  }

  @override
  Future<Database> openDatabase(String path, {OpenDatabaseOptions options}) {
    return null;
  }
}

final databaseFactoryMock = DatabaseFactoryMock();
```

and use `databaseFactoryMock` instead of `databaseFactory` in your test code.

Then you might say that you need a real Database object so you will need to mock Database then but here it will depends on your need so it is hard to make something that everybody will agree on...

**Comment by NerditLtd** [comment]
I can run sqflite tests using flutter run "test file path" but I need to include test in coverage report. How should I do that. any code samples appreciated

**Comment by nobimac** [comment]
i also getting this error while testing..

**Comment by alextekartik** [comment]
I started a doc about testing here:
https://github.com/tekartik/sqflite/issues/49

If anyone has already tried e2e testing or find a good way to test code with sqflite, I'd be happy to complete the documentation.

**Comment by maxisme** [comment]
```dart
import 'package:sqflite/sqflite.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

  const MethodChannel('com.tekartik.sqflite')
      .setMockMethodCallHandler((MethodCall methodCall) async {
    if (methodCall.method == 'openDatabase') {
      return await databaseFactoryFfi.openDatabase(inMemoryDatabasePath);
    }
  });
  ```
  Worked for me.

**Comment by alextekartik** [comment]
I think setMockMethodCallHandler is deprecated in the next flutter release. A solution is available here:
https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/testing.md

Example:

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';
import 'package:sqflite/sqflite.dart';

Future main() async {
  // Setup sqflite_common_ffi for flutter test
  setUpAll(() {
    // Initialize FFI
    sqfliteFfiInit();
    // Change the default factory
    databaseFactory = databaseFactoryFfi;
  });
  test('Simple test', () async {
    var db = await openDatabase(inMemoryDatabasePath, version: 1,
        onCreate: (db, version) async {
      await db
          .execute('CREATE TABLE Test (id INTEGER PRIMARY KEY, value TEXT)');
    });
    // Insert some data
    await db.insert('Test', {'value': 'my_value'});
    // Check content
    expect(await db.query('Test'), [
      {'id': 1, 'value': 'my_value'}
    ]);

    await db.close();
  });
}
```
