### ISSUE TITLE
In ORDER BY column_name [DESC] - column_name [DESC] cannot be passed as parameter to rawQuery

### ISSUE THREAD

**Issue by hicnar** [tekartik/sqflite#490]
I am not sure if this is by design, but it appears not possible to do the following:

`database.rawQuery('SELECT d.id,d.external_id,d.archived,d.created_at AS created_at,pd.sorting_index AS sorting_index FROM DOCUMENTS d, PLAYLIST_TO_DOCUMENT pd WHERE d.id = pd.document_id AND pd.playlist_id = ?1 ORDER BY ?2', [123, 'created_at DESC'])`

And not that there is an error, the query returns results but they are not ordered as desired.

And this:

`database.rawQuery('SELECT d.id,d.external_id,d.archived,d.created_at AS created_at,pd.sorting_index AS sorting_index FROM DOCUMENTS d, PLAYLIST_TO_DOCUMENT pd WHERE d.id = pd.document_id AND pd.playlist_id = ?1 ORDER BY created_at DESC, [123])`
works perfectly fine.

Is there something I am doing wrong?

I am on sqflite 1.3.1

**Comment by alextekartik** [comment]
I think the behavior is correct. Parameters should not allow inner sql injection. `create_at DESC` should not be a parameter.
