### ISSUE TITLE
iOS DatabaseException(Error Domain=FMDatabase Code6922 "disk i/o error"

### ISSUE THREAD

**Issue by maerlynflagg** [tekartik/sqflite#492]
i logout my app. in my logout i clear all table rows. after logout is done,  i initialize the app. 

so there is a sql statement to create a table if not exists. after logout and clearing all data of tables, i get the error on iOS Simulator and iOS 13.3.1 device.

i'm using flutter 1.20.2.

**Comment by alextekartik** [comment]
Thanks for the report. Hard to tell what goes wrong without being able to reproduce. Typically this happen during open which is not your case. Are you getting the error consistently with a scenario/code I can try?  Can you confirm that you are not closing/deleting the database once open even on logout?

You could turn on some logging https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#turn-on-sql-console-logging to make sure you are not closing/deleting the database.

**Comment by alextekartik** [comment]
Can you try to avoid closing/opening the database? Best/simplest is to keep the database open.

**Comment by maerlynflagg** [comment]
> Can you try to avoid closing/opening the database? Best/simplest is to keep the database open.

i only use openDatabase. the documentation say, isSingleinstance is default true. so i get always the same db?
i never using the close function, so the db is always open.

or reopen _openDatabase()_ the database?

**Comment by alextekartik** [comment]
I recommend opening the database only once and perform table setup (`CREATE TABLE ...`) during `onCreate`. See an example of a database setup and migration process here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/migration_example.md

Can you display more information about the exception you are seeing (there are likely some relevant information) in your logs. Maybe you can try changing the name of the column named `key` (a reserved [SQLite keyword](https://sqlite.org/lang_keywords.html)) to something else.

**Comment by maerlynflagg** [comment]
i do it like the example in the documentation, i get always the _no such table_ exception.

example: 
```
// open the database
Database database = await openDatabase(path, version: 1,
    onCreate: (Database db, int version) async {
  // When creating the db, create the table
  await db.execute(
      'CREATE TABLE Test (id INTEGER PRIMARY KEY, name TEXT, value INTEGER, num REAL)');
});
```
because this exception i started for long time with my way to create the tables and it worked fine on Android. it works fine on iOS, if no one using log out.



i'm not sure, why i'm always open the database. in the documentation of this method:
```

/// When [singleInstance] is true (the default), a single database instance is
/// returned for a given path. Subsequent calls to [openDatabase] with the
/// same path will return the same instance, and will discard all other
/// parameters such as callbacks for that invocation.
```
so on my example, the default value is selected and i get always the same instance and the other parameters are not important.

but to be sure, i changed the code to write one time the database in a variable, also call openDatabase only once. 

the issue is not solved. there is no effect, same exception Code 6922.

**Comment by alextekartik** [comment]
The `no such table` exception you are facing was not in your original report. What might happen here is that you database is already at version 1. Try to bump version to 2 to force creating the table (you can even use IF NOT EXISTS). Look at migration example here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/migration_example.md

**Comment by maerlynflagg** [comment]
i found a solution for me for 
_iOS DatabaseException(Error Domain=FMDatabase Code6922 "disk i/o error"_.

i simply had to close database after deleting all rows tables.

```
      await database.transaction((txn) async {
        await txn.execute('DELETE FROM ' + userTable);
        await txn.execute('DELETE FROM ' + generalTable);
        await txn.execute('DELETE FROM ' + encryptionTable);
        await txn.execute('DELETE FROM ' + imageTable);
        await txn.execute('DELETE FROM ' + photoTable);
        await txn.execute('DELETE FROM ' + requestStore);
        await txn.execute('DELETE FROM ' + staticDataStore);
        await txn.execute('DELETE FROM ' + adviceRefStore);
        await txn.execute('DELETE FROM ' + adviceStore);
        await txn.execute('DELETE FROM ' + forumStore);
        await txn.execute('DELETE FROM ' + reportStore);
        await txn.execute('DELETE FROM ' + buildingPartStore);
        await txn.execute('DELETE FROM ' + roomStore);
        await txn.execute('DELETE FROM ' + absenceStore);
        await txn.execute('DELETE FROM ' + workingTimeProfileStore);
        await txn.execute('DELETE FROM ' + messageStore);
        await txn.execute('DELETE FROM ' + adviceOffersStore);
      });

    **await database.close();**
```

now the Code 6922 exception is gone.

Thanks for help!

**Comment by luckv** [comment]
I experienced the same error in crashlytics from release app
`DatabaseException(Error Domain=FMDatabase Code=6922 "disk I/O error" UserInfo={NSLocalizedDescription=disk I/O error}) sql 'DELETE FROM cacheObject WHERE _id IN ()' args []}. Error thrown null.`

I don't directly use this library, but is used in another package that I use, [flutter_cache_manager](https://github.com/Baseflow/flutter_cache_manager)
I will open an issue on that library soon

### Output of `flutter --version`
- Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
- Framework • revision f4abaa0735 (3 months ago) • 2021-07-01 12:46:11 -0700
- Engine • revision 241c87ad80
- Tools • Dart 2.13.4

### Version of sqflite used
2.0.0+3

**Comment by alextekartik** [comment]
Indeed the SQL generated does not look correct. If there is no "ids" to delete in a `WHERE IN` clause, there should not any SQLite command to execute.
