### ISSUE TITLE
UpToDate database

### ISSUE THREAD

**Issue by HeikkiK** [tekartik/sqflite#499]
Hi, I have a minor problem to get uptodate database when using from callback:
If I open database in main app and modify database values, after that when location plugins callback triggers and gets new position, I have to first open database again and everything works ok otherwise but I cannot see last db modifications which I made in main app... 
It's updated after app is closed and reopened.
So how I should work to get updated db in callback?

**Comment by alextekartik** [comment]
Thanks for the report. Weird indeed. Maybe you can share the way you open the database (singleInstance should not be false). I'm assuming you never close the database and that your open section is safe regarding multiple calls.

**Comment by HeikkiK** [comment]
I opened it like it's told in examples and it works ok, only problem is that it's not uptodate. I am using background_locator plugin and it's callback. And yes I don't close db and singleinstance is default = true. What do you mean by "your open section is safe regarding multiple calls"?

**Comment by HeikkiK** [comment]
Hey...I found bug in my code. There was flag which verified that it doesn't load db unnecessarily if there's no changes and it worked in app but when it loaded new (changed) values (into list) in main app which I verified, it didn't load new values in callback again as it should. Stupid mistake and I don't know why I didn't notice that reason was that flag... sorry.
