### ISSUE TITLE
Linux: Not Working on snapcraft release

### ISSUE THREAD

**Issue by mjafartp** [tekartik/sqflite#502]
app working good on debug but on release to snapcraft database not creating

Getting Exception:
 _SqfliteFfiException(error, Invalid argument(s): Failed to load dynamic library (libsqlite3.so: cannot open shared object file: No such file or directory)} DatabaseException(Invalid argument(s): Failed to load dynamic library (libsqlite3.so: cannot open shared object file: No such file or directory))_

installed `sudo apt-get -y install sqlite3 libsqlite3-dev`

but not working

**Comment by alextekartik** [comment]
This part is handled by [sqlite3 package](https://pub.dev/packages/sqlite3). In the README there is a snipped that shows how to bundle libsqlite3.so with your app that you could try.

**Comment by omidraha** [comment]
For Linux  desktop I got this error:

```
Unhandled Exception: 
MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
```

Info:

```yaml
  sqflite: ^2.0.0+3
  sqlite3_flutter_libs: ^0.4.1
  sqflite_common_ffi: ^2.0.0
```

```
apt-get install sqlite3 libsqlite3-dev
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio
[✓] Connected device (2 available)

• No issues found!
```

**Comment by alextekartik** [comment]
@omidraha `DatabaseFactory.openDatabase` has an options parameter where you can specify the onCreate/onConfigure callbacks: https://pub.dev/documentation/sqflite_common/latest/sqlite_api/OpenDatabaseOptions-class.html

**Comment by omidraha** [comment]
Thanks, fixed as:
```dart
  if (Platform.isWindows || Platform.isLinux) {
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  }
  final Future<Database> database = databaseFactory.openDatabase(
      join(await getDatabasesPath(), 'database.db'),
      options: OpenDatabaseOptions(
        onConfigure: onConfigure,
        onCreate: (db, version) async {
          Batch batch = db.batch();
          createTables(batch);
          createIndexes(batch);
          await batch.commit(continueOnError: false);
        },
        version: 1,
      ));
```

**Comment by mjafartp** [comment]
> Thanks, fixed as:
> 
> ```dart
>   if (Platform.isWindows || Platform.isLinux) {
>     sqfliteFfiInit();
>     databaseFactory = databaseFactoryFfi;
>   }
>   final Future<Database> database = databaseFactory.openDatabase(
>       join(await getDatabasesPath(), 'database.db'),
>       options: OpenDatabaseOptions(
>         onConfigure: onConfigure,
>         onCreate: (db, version) async {
>           Batch batch = db.batch();
>           createTables(batch);
>           createIndexes(batch);
>           await batch.commit(continueOnError: false);
>         },
>         version: 1,
>       ));
> ```

This solution only for local running,

releasing to snap not supported.

**Comment by alextekartik** [comment]
I'm not familiar with the snap build process but you need to add [libsqlite3 dependency somehow](https://snapcraft.io/docs/build-and-staging-dependencies), maybe in the snapcraft.yaml with something like:
```yaml
 stage-packages:
      - libsqlite3-0
```

**Comment by jmsilvadev** [comment]
In `snapcraft.yaml` use `libsqlite3-dev` instead of `libsqlite3-0`. Like this:
```parts:
  bots4coins:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    stage-packages:
    - libsqlite3-dev

**Comment by mjafartp** [comment]
@jmsilvadev It's working
