### ISSUE TITLE
onCreate Method(while openDatabase) not getting called in android 9

### ISSUE THREAD

**Issue by Jaldips** [tekartik/sqflite#503]
While creating Database using below code:
`database = await openDatabase(
      path,
    onCreate: _onCreate,
    onConfigure: _onConfigure,
    version: 1,
  );`
_onCreate method is not getting called (resulting in no table creation) in android 9(Mi A1),
Recently upgraded flutter and this issue has started,

Though same code works in other version, say Android 6.0.1, And was working in Android 9 as well but before flutter upgrade,

Below are the Framework Details:
Lib Version:  

> sqflite: ^1.3.1+1,

Flutter Doctor Result:

> C:\Users\jaldip.katre>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-IN)

>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Android Studio (version 3.6)
[!] VS Code (version 1.48.2)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

>! Doctor found issues in 1 category.

Please suggest.

**Comment by Jaldips** [comment]
@alextekartik Please specify the info you need.
FYI tutorial followed is [https://flutter.dev/docs/cookbook/persistence/sqlite](url)

**Comment by alextekartik** [comment]
@Jaldips I meant how can i reproduce the issue. Maybe show some code, [some logs](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#debugging-sql-commands). This is a pretty well tested feature so maybe your database was already existing.

**Comment by Jaldips** [comment]
@alextekartik I tried downgrading flutter to the earlier version, still was facing same problem. Ended up calling onCreate method from my code only. Reason of onCreate not getting called automatically from library in still unknown, no error was shown.
Closing the issue (Solved with above workaround).

**Comment by imssurya** [comment]
same issue for me and like @alextekartik said my database is already exists thanks dude, and anyone pls tell me how we can solve this issue i need use existing db or else i need to create one already im checking db is null or not but its not working

**Comment by naimurhasan** [comment]
I came here for the same problem, but later found there are to different methods, onCreate and onUpgrade So yes, onUpgrade solves my problem.

**Comment by naimurhasan** [comment]
I came here for the same problem, but later found there are to different methods, onCreate and **`onUpgrade`** So yes, onUpgrade solves my problem.
