### ISSUE TITLE
"IN" operators with String as argument

### ISSUE THREAD

**Issue by ghprod** [tekartik/sqflite#509]
Hi,

Example

```dart
await db.update(
  'my_table',
  data,
  where: 'uuid IN (?)',
  whereArgs = [['xx', 'zz']],
);
```

And got error

> Unhandled Exception: DatabaseException(java.lang.String cannot be cast to java.lang.Integer

Is `IN` support String? or just Integer?

Thanks

**Comment by ghprod** [comment]
Found a solution

```dart
await db.update(
  'my_table',
  data,
  where: 'uuid IN (${uuids.map((e) => '?').join(', ')})',
  whereArgs: [...uuids],
);
```

Is it the right way? or maybe there's a simpler syntax?

Thanks

**Comment by alextekartik** [comment]
That is (unfortunately) the right way!

**Comment by ghprod** [comment]
Thanks for confirmed. Closed it.
