### ISSUE TITLE
License stated "Copyright 2017 Your Company"

### ISSUE THREAD

**Issue by miriambusch** [tekartik/sqflite#51]
Hi,

we are using your plugin in our app and would like to properly credit you on the credits / licenses page but your license file only states the placeholder "Copyright 2017 Your Company"

Do you want to fix this or let us know how to properly attribute you?

Thanks a lot either way.

**Comment by alextekartik** [comment]
I have updated the license (MIT). I must say that I'm not certain of the license to use (BSD2, MIT?)...your recommendation on what the other license you use are to be inline with them would be welcome. I used MIT like the google flutter plugins

**Comment by miriambusch** [comment]
MIT, BSD, Apache2... all fine. And now we can credit you with your name too. Thanks you!
