### ISSUE TITLE
batch insert ,can not select data

### ISSUE THREAD

**Issue by leetomlee123** [tekartik/sqflite#512]
`  /// 添加章节
  Future<Null> addChapters(List<Chapter> cps, String bookId) async {
    var dbClient = await db;
    var batch = dbClient.batch();
    for (var i = 0; i < cps.length; i++) {
      Chapter chapter = cps[i];
      batch.rawInsert(
          'insert into $_tableName (chapter_id,name,content,book_id,hasContent) values(?,?,?,?,?)',
          [chapter.id, chapter.name, "", bookId, chapter.hasContent]);
    }

    batch.commit(noResult: true, continueOnError: true);
    print("save cps success");
  }

  Future<List<Chapter>> getChapters(String bookId) async {
    var dbClient = await db;

    var list = await dbClient
        .rawQuery("select * from $_tableName where book_id=?", [bookId]);
    List<Chapter> cps = [];
    for (var i in list) {
      cps.add(Chapter(i['hasContent'], i['chapter_id'], i['name']));
    }
    return cps;
  }`

**Comment by leetomlee123** [comment]
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.3)
[√] Connected device (1 available)

• No issues found!
`

**Comment by alextekartik** [comment]
I'm not sure what the question is:
- Please try to format your code properly (adding the proper \`\`\` before and after the code)
- Make sure to use `pedandic`. You are missing some `await` calls (before batch.commit() which should be `await batch.commit()`) which should appear as warning (and fix all the warnings).

I don't know what hasContent type is but if it is a boolean it is not supported.

If you can, can you try to write a unit test showing the issue (see example here: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi#unit-test-code)

Thanks!

**Comment by leetomlee123** [comment]
```  Future<Null> addChapters(List<Chapter> cps, String bookId) async {
    var dbClient = await db;
    print('add dbclient hashcode ${dbClient.hashCode}');
    var batch = dbClient.batch();
    for (var i = 0; i < cps.length; i++) {
      Chapter chapter = cps[i];
      batch.rawInsert(
          'insert into $_tableName (chapter_id,name,content,book_id,hasContent) values(?,?,?,?,?)',
          [chapter.id, chapter.name, "", bookId, chapter.hasContent]);
    }

    await batch.commit(noResult: true, continueOnError: true);

    print("save cps success");
  }

  Future<List<Chapter>> getChapters(String bookId) async {
    var dbClient = await db;
    print('get dbclient hashcode ${dbClient.hashCode}');
    var list = await dbClient
        .rawQuery("select * from $_tableName where book_id=?", [bookId]);
    List<Chapter> cps = [];
    for (var i in list) {
      cps.add(Chapter(i['hasContent'], i['chapter_id'], i['name']));
    }
    return cps;
  }```

**Comment by leetomlee123** [comment]
`  Future<Null> addChapters(List<Chapter> cps, String bookId) async {
    var dbClient = await db;
    print('add dbclient hashcode ${dbClient.hashCode}');
    var batch = dbClient.batch();
    for (var i = 0; i < cps.length; i++) {
      Chapter chapter = cps[i];
      batch.rawInsert(
          'insert into $_tableName (chapter_id,name,content,book_id,hasContent) values(?,?,?,?,?)',
          [chapter.id, chapter.name, "", bookId, chapter.hasContent]);
    }

    await batch.commit(noResult: true, continueOnError: true);

    print("save cps success");
  }

  Future<List<Chapter>> getChapters(String bookId) async {
    var dbClient = await db;
    print('get dbclient hashcode ${dbClient.hashCode}');
    var list = await dbClient
        .rawQuery("select * from $_tableName where book_id=?", [bookId]);
    List<Chapter> cps = [];
    for (var i in list) {
      cps.add(Chapter(i['hasContent'], i['chapter_id'], i['name']));
    }
    return cps;
  }`

**Comment by leetomlee123** [comment]
```  Future<Null> addChapters(List<Chapter> cps, String bookId) async {
    var dbClient = await db;
    print('add dbclient hashcode ${dbClient.hashCode}');
    var batch = dbClient.batch();
    for (var i = 0; i < cps.length; i++) {
      Chapter chapter = cps[i];
      batch.rawInsert(
          'insert into $_tableName (chapter_id,name,content,book_id,hasContent) values(?,?,?,?,?)',
          [chapter.id, chapter.name, "", bookId, chapter.hasContent]);
    }

    await batch.commit(noResult: true, continueOnError: true);

    print("save cps success");
    //can query data ,when i insert
    var list = await dbClient.rawQuery('select * from $_tableName');
    print('after insert all $list');
  }

  Future<List<Chapter>> getChapters(String bookId) async {
    var dbClient = await db;
    //can not query any data
    var all = await dbClient.rawQuery('select * from $_tableName');
    print('before select $all');
    print('get dbclient hashcode ${dbClient.hashCode}');
    var list = await dbClient
        .rawQuery("select * from $_tableName where book_id=?", [bookId]);
    List<Chapter> cps = [];
    for (var i in list) {
      cps.add(Chapter(i['hasContent'], i['chapter_id'], i['name']));
    }
    return cps;
  }```

**Comment by leetomlee123** [comment]
hadContent is int type

**Comment by leetomlee123** [comment]
hasContent is int type

**Comment by leetomlee123** [comment]
Whether it is not closed, causing the data to be not flushed
