### ISSUE TITLE
warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated

### ISSUE THREAD

**Issue by lowmanav** [tekartik/sqflite#518]
Using software rendering with device Android SDK built for x86. You may get better performance with hardware mode by configuring hardware rendering for your device.
Launching lib/main.dart on Android SDK built for x86 in debug mode...
/Users/as/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/android/src/main/java/com/tekartik/sqflite/SqflitePlugin.java:34: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;               
                               ^                                        
/Users/as/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/android/src/main/java/com/tekartik/sqflite/SqflitePlugin.java:34: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;               
                               ^                                        
2 warnings

**Comment by alextekartik** [comment]
Thanks for the report. Although deprecated, this is still needed to support V1 embedding (which will be likely removed soon). I fixed the deprecation warning in sqflite 1.3.1+2

**Comment by lowmanav** [comment]
Thanks for your quick response. Warnings disappeared.
