### ISSUE TITLE
Escaping Strings

### ISSUE THREAD

**Issue by Norbert515** [tekartik/sqflite#52]
I'm getting a SQL syntax error when trying to insert a text which contains ' " '. Is this something I should manually escape or could the library do that work?

**Comment by alextekartik** [comment]
Thanks for the report. I tried inserting, testing text with quote here:

https://github.com/tekartik/sqflite/blob/093615490ef216737dcb28e158ce9bc7e6cbe4df/example/lib/exp_test_page.dart#L289-L305

It seems to work. When a text contains a '"' you have to use it as an argument (i.e. not in the sql itself). Maybe you have a failing test that you could share

**Comment by Norbert515** [comment]
I'm using "rawQuery", well should have expected that, haha. Thanks I'll change my code to the other method.

**Comment by alextekartik** [comment]
Even using rawQuery, you have to use arguments
```
await db.rawQuery('SELECT * FROM test WHERE value = ?', ['with " quote'])
```

**Comment by Norbert515** [comment]
Future updateBook(Book book) async {
    var db = await _getDb();
    await db.inTransaction(() async {
      await db.rawInsert(
          'INSERT OR REPLACE INTO '
              '$tableName(${Book.db_id}, ${Book.db_title}, ${Book.db_url}, ${Book.db_star}, ${Book.db_notes}, ${Book.db_author}, ${Book.db_description}, ${Book.db_subtitle})'
              ' VALUES("${book.id}", "${book.title}", "${book.url}", ${book.starred? 1:0}, "${book.notes}", "${book.author}", "${book.description}", "${book.subtitle}")');
    });
  }
This is my current code

**Comment by alextekartik** [comment]
That's not good. String might not be escaped properly. It should be something like that instead
```
await db.rawInsert(
'INSERT OR REPLACE INTO '
'$tableName(${Book.db_id}, ${Book.db_title}, ${Book.db_url}, ${Book.db_star}, ${Book.db_notes}, ${Book.db_author}, ${Book.db_description}, ${Book.db_subtitle})'
' VALUES(?, ?; ?; ?; ?, ?, ?, ?)',
[book.id, book.title, book.url, book.starred? 1:0, book.notes, book.author, book.description, book.subtitle])');
```

**Comment by Norbert515** [comment]
Oh, sorry for the formatting. Thanks, I will try it out once I get home.
