### ISSUE TITLE
batch insert is very slow in android devices

### ISSUE THREAD

**Issue by sushantburla** [tekartik/sqflite#522]
I am trying to insert a list of records in batch. In iOS devices, its blazing fast but the same code in android is super slow. here is the code 
final db = await getDBInstance();
Batch batch = db.batch();
    for (T t in ts) {
      batch.insert('todos', t.toMap(),
          conflictAlgorithm: ConflictAlgorithm.replace);
    }
 await batch.commit(noResult: true);

I am running the enclosing method asynchronously but it still freezes the UI. I believe the main thread/isolate is too busy in batch commit. I also tried running it in a separate isolate but it throws below error while opening the db.
Error caught Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
Normally it takes 200-300 milliseconds to run in iOS but in android it takes 50-60 seconds.

**Comment by alextekartik** [comment]
Hi and thanks for the report. This should not be the case. Sqflite already ran native code in a separate thread. Don't use a separate isolate. How did you make the measurement? Do you start a stop watch before the code above and stopping it after the commit showing indeed that this is this code freezing the UI ? If you have such log can you also print the number of item inserted? (if you don't have can you add it or can you try to have a sample code I could use to reproduce the issue).

 You mention an error above. There is a typically a log telling you to call `WidgetsFlutterBinding.ensureInitialized();` before any sqflite code.

Personally, I limit batch to about 100 instructions but there is nothing that should prevent doing more.

**Comment by sushantburla** [comment]
thanks @alextekartik for your prompt response. 
I measured the performance using stopwatch. The number of items inserted are around 250 which is not so high. I will try to create a sample app to reproduce the issue. and share with you.

**Comment by sushantburla** [comment]
HI @alextekartik , I figured out the issue and fortunately/unfortunately its not due to sqflite. Its because of local notification scheduling which is taking way more time in android than in iOS. The logs always stuck before the batch commit which made me believe that it was due to commit. Anyway, I am closing the issue.
