### ISSUE TITLE
Minimum supported Gradle version is 6.5

### ISSUE THREAD

**Issue by zwz1192511822** [tekartik/sqflite#526]
* Where:
           Build file '/usr/local/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite-1.3.1+2/android/build.gradle' line: 30

           * What went wrong:
           A problem occurred evaluating root project 'sqflite'.
           > Failed to apply plugin [id 'com.android.internal.version-check']
              > Minimum supported Gradle version is 6.5. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in /usr/local/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite-1.3.1+2/android/gradle/wrapper/gradle-wrapper.properties to gradle-6.5-all.zip

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

[?] Flutter (Channel stable, 1.22.1, on Linux, locale en_US.UTF-8)
    ? Flutter version 1.22.1 at /usr/local/flutter
    ? Framework revision f30b7f4db9 (12 days ago), 2020-10-08 10:06:30 -0700
    ? Engine revision 75bef9f6c8
    ? Dart version 2.10.1
    ? Pub download mirror https://pub.flutter-io.cn
    ? Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    ? Android SDK at /usr/local/android-sdk
    ? Platform android-30, build-tools 30.0.1
    ? ANDROID_HOME = /usr/local/android-sdk
    ? Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    ? Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (not installed)
    ? Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by alextekartik** [comment]
Thanks for the report. That did not seem to be a file in the source code so far. I have added and publish v1.3.2-dev.1 (so you must specify 'sqflite: '>= 1.3.2-dev.1' to get it.
Let me if that works.

If not can you tell me the steps you did to get such issue. Thanks!

**Comment by zwz1192511822** [comment]
This problem occurs in Linux, and I don’t know how to reproduce it

**Comment by alextekartik** [comment]
So if this cannot be reproduced, is it an issue?

**Comment by zwz1192511822** [comment]
> So if this cannot be reproduced, is it an issue?

The gradle version does not match, isn’t it a problem?

**Comment by alextekartik** [comment]
It should match now with the update I have published. Does it fix your issue?
