### ISSUE TITLE
Query not await?

### ISSUE THREAD

**Issue by buuth** [tekartik/sqflite#537]
Tried 
await db.query(tableName);
However it does not wait until rows fetched.
Is there anything wrong?

**Comment by daybson** [comment]
The method from where you are calling "await db.query(tableName);" is market to return a **Future** and **async**?
If not, can be the cause.

```
Future<Myobj> get(int id) async {
    Database db = await DatabaseHelper.instance.database;

    var result = await db.query(
      'MyTable',
      where: 'ID = ?',
      whereArgs: [id],
    );

    return Myobj.fromMap(result.first);
  }
```
