### ISSUE TITLE
How can I Get database Version ? 

### ISSUE THREAD

**Issue by JAICHANGPARK** [tekartik/sqflite#538]
I'd like to get current database version 

How can I get db version?

**Comment by alextekartik** [comment]
`Database.getVersion()`: https://pub.dev/documentation/sqflite_common/latest/sqlite_api/Database/getVersion.html

**Comment by JAICHANGPARK** [comment]
Thanks @alextekartik

**Comment by alextekartik** [comment]
(well I was super slow though...)
