### ISSUE TITLE
Transaction exceptions handling

### ISSUE THREAD

**Issue by GRouslan** [tekartik/sqflite#54]
I did not notice any "beginTransaction" methods in android java code. How are exceptions while in a transaction handled? What will happen if an app terminates in a middle of a transaction?

**Comment by alextekartik** [comment]
The transaction is dealt at the sqlite level. beginTransaction in Android is sugar code around "BEGIN TRANSACTION" which is managed by the dart code in sqlifte here
.
Regarding your question. An uncommited transaction is discarded. See the example here: https://github.com/tekartik/sqflite/blob/eb3737a242ef47dfe8873a7d18fea671266ac91a/example/lib/exception_test_page.dart#L13-L42

So if an app terminates in a middle of a transaction it will be discarded.

**Comment by GRouslan** [comment]
Oh, my sorry! I was searching beginTransaction in android code, then "BEGIN TRANSACTION" and missed that "TRANSACTION" in "BEGIN TRANSACTION" can be omitted. Now I see it in [database.dart](https://github.com/tekartik/sqflite/blob/master/lib/src/database.dart)
