### ISSUE TITLE
Lock contention during database opens

### ISSUE THREAD

**Issue by jinglim** [tekartik/sqflite#542]
Hi,

(@mehmetf)

I'm wondering why there's a global lock at openDatabase()?

 Future<Database> openDatabase(String path, {OpenDatabaseOptions options}) {
    // Global factory lock during open
    return lock.synchronized(() async {
...

We are opening 5 databases on startup; each database requiring some configuration steps. This causes a bottleneck here, all contending for the lock. If a local lock is used, all the dbs can be opened in parallel and would result in faster app startup.

Thanks!
Jing Lim

**Comment by alextekartik** [comment]
Good point. I think it was in place to handle a but if a database was opened multiple times but indeed it locks other database which is not needed.
I will look into it as it can be solved (I might have a lock based on a database path instead)

**Comment by alextekartik** [comment]
I have fix this issue by locking by database full path (still needed to handle concurrent open of the same single instance database). Pushed as a dev package you have to add the following dependency (which will not hurt even in the future) to try it before I released for good:
```
dependencies:
  sqflite_common: '>=1.0.3-dev.1
```
