### ISSUE TITLE
Dealing with foreign keys in SQFlite Flutter

### ISSUE THREAD

**Issue by mado-bohsali** [tekartik/sqflite#544]
To whom it may concern,
I need assistance in SQFlite because I am not knowing how to manage it when there are multiple tables linked together. The parent table works but the child tables aren't. How should I insert the foreign key?

I am using SQL queries normally and they are working fine in Localhost. Should I also delete the app in the simulator everytime I make changes to the queries?

**Comment by daybson** [comment]
Did you create your database with foreign keys enabled?

`PRAGMA foreign_keys;`

read more: https://www.sqlitetutorial.net/sqlite-foreign-key/

**Comment by alextekartik** [comment]
A good place to enable foreign keys is in onConfigure:
```dart
_onConfigure(Database db) async {
  // Add support for cascade delete
  await db.execute("PRAGMA foreign_keys = ON");
}

var db = await openDatabase(path, onConfigure: _onConfigure);
```

**Comment by SimpleSoft-Desenvolvimento** [comment]
Thank you Alex!
