### ISSUE TITLE
sqflite_common_ffi windows release error.

### ISSUE THREAD

**Issue by yangyxd** [tekartik/sqflite#547]
sqflite_ common_ After FFI is packaged under Windows platform, it will report an error after moving the packed program.
as a result of:
var location = findPackagePath( Directory.current.path );
When the error is null, the result is returned as follows:
![image](https://user-images.githubusercontent.com/14143779/99660457-63f27c00-2a9d-11eb-97d0-1d663083ce63.png)

error position:

![image](https://user-images.githubusercontent.com/14143779/99660587-871d2b80-2a9d-11eb-8af9-3f7967980283.png)

**Comment by nabil6391** [comment]
the windowsInit() function is actually there as a means to test sqliteffi. If we want to ship sqlite3.dll with our release build then we have to place the sqlite3.dll into the root of our released app folder, meaning alongside our primary *.exe 

Then instead of using their windowsInit(), use this:


`  void windowsInit() {
    String path;
    if (kReleaseMode) {
      var location = Directory.current.path;
      path = normalize(join(location, 'sqlite3.dll'));
    } else {
      var location = findPackagePath(Directory.current.path);
      path = normalize(join(location, 'src', 'windows', 'sqlite3.dll'));
    }

    open.overrideFor(OperatingSystem.windows, () {
      print('loading $path');
      try {
        return DynamicLibrary.open(path);
      } catch (e) {
        stderr.writeln('Failed to load sqlite3.dll at $path');
        rethrow;
      }
    });

    // Force an open in the main isolate
    // Loading from an isolate seems to break on windows
    sqlite3.sqlite3.openInMemory().dispose();
  }
`

**Comment by yangyxd** [comment]
Yes, when publishing mode, you can directly find sqlite3.dll in the current directory. You don't even need to take any path.

``dart
String path;
if (kReleaseMode) {
path = 'sqlite3.dll';
} else {
var location = findPackagePath( Directory.current.path );
path = normalize(join(location, 'src', 'windows', 'sqlite3.dll'));
}
··

**Comment by yangyxd** [comment]
I hope the author can change it so that the plug-in can be used normally on the windows platform, thanks!

**Comment by alextekartik** [comment]
Yes the `windowsInit` helper is here as a reference and to work in a normal development cycle. Hard to assume where the dll will be in release mode as it depends on how the developer will release the application. Maybe windowsInit could be improved to look for the dll in the directory of the executable in release mode like you propose (not the current directory though as it depends from where you launch your application) to cover a very common scenario. I won't likely tackle this before nnbd migration (in progress) is fully done

**Comment by alextekartik** [comment]
I published a new version that should work if the sqlite3.dll is the same folder than the executable in release mode

**Comment by alextekartik** [comment]
Latest: 1.1.1+2 / Prerelease: 2.0.0-nullsafety.6

**Comment by yangyxd** [comment]
thanks!!

**Comment by Invincible1996** [comment]
Flutter desktop on windows load database from aseets error on release model(debug model is ok)
![](/img/bVcRZAe)
example:

```dart
  Database _db;

  /// 初始化
  initialDatabase() async {
    sqfliteFfiInit();
    var databaseFactory = databaseFactoryFfi;
    var databasesPath = await databaseFactory.getDatabasesPath();

    var path = join(databasesPath, "unit_price.db");

    print(path);
    var exists = await databaseFactory.databaseExists(path);

    if (!exists) {
      // Should happen only the first time you launch your application
      print("Creating new copy from asset");

      try {
        await Directory(dirname(path)).create(recursive: true);
      } catch (_) {}
      // Copy from asset
      ByteData data = await rootBundle.load('assets/unit_price.db');
      print(join('assets','unit_price.db'));
      // ByteData data = await rootBundle.load(join('assets','unit_price.db'));
      List<int> bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);

      // Write and flush the bytes written
      await File(path).writeAsBytes(bytes, flush: true);
    } else {
      print("Opening existing database");
    }
    // open the database
    this._db = await databaseFactory.openDatabase(path);

    print(databasesPath);
}
  Future<List<UnitPrice>> queryAllPrice() async {
    List<UnitPrice> priceList = [];
    var result = await _db.query(
      'unit_price',
      limit: 20,
      offset: 0,
    );
    for (var item in result) {
      priceList.add(UnitPrice.fromJson(item));
    }
    print(priceList.length);
    priceList.insert(0, UnitPrice());
    return priceList;
  }
}
```
**Screen Shots:**
![](/img/bVcRZBT)
**Flutter Version:**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
[!] Android Studio (not installed)
[√] Connected device (2 available)
```

**sqflite_common_ffi Version:**
sqflite_common_ffi: ^2.0.0

**Comment by alextekartik** [comment]
@Invincible1996 as stated above, you should copy `sqlite3.dll` to your directory.

**Comment by Invincible1996** [comment]
@alextekartik Thanks! I got it.

**Comment by jampzx** [comment]
It works perfectly fine in debug mode but in release mode this sqflite_common_ffi: ^2.2.5 is not working, am i doing this right?

Screenshots
![1](https://github.com/tekartik/sqflite/assets/72666307/de47c7c0-7bea-4ef7-863d-084dd802fcdf)
![2](https://github.com/tekartik/sqflite/assets/72666307/700a7e85-45a6-4a0e-b083-57c82c492ece)

**Comment by himanshuchaurasiya24** [comment]
> It works perfectly fine in debug mode but in release mode this sqflite_common_ffi: ^2.2.5 is not working, am i doing this right?
> 
> Screenshots ![1](https://private-user-images.githubusercontent.com/72666307/254155609-de47c7c0-7bea-4ef7-863d-084dd802fcdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTI5NjgsIm5iZiI6MTcwNjcxMjY2OCwicGF0aCI6Ii83MjY2NjMwNy8yNTQxNTU2MDktZGU0N2M3YzAtN2JlYS00ZWY3LTg2M2QtMDg0ZGQ4MDJmY2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE0NTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNjFjZjE5OWU0ZWNlMTBhZDFkZWI0YjhiNWE2NmM2NmE5MWEwY2I2NWU4NzliZDc2ZjM4MTEyNzA2MmI0ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pXD8GRqgB1MRBxu0_wHkhaE3sUQjWD3Diaj0G_1-7IQ) ![2](https://private-user-images.githubusercontent.com/72666307/254155665-700a7e85-45a6-4a0e-b083-57c82c492ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTI5NjgsIm5iZiI6MTcwNjcxMjY2OCwicGF0aCI6Ii83MjY2NjMwNy8yNTQxNTU2NjUtNzAwYTdlODUtNDVhNi00YTBlLWIwODMtNTdjODJjNDkyZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE0NTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2M2ZiZDU2M2M3ZjIxMmMyYzg2MWI3ZjIxMTk1YzQ3NTAwNTViOWFlZGI1MjY0ZWU4YmU3YWM0NDk5OGNhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TokdL6KC0zLFZ4MPZ8UPhPhW_3JYfr7leA2Uv7Bpmf8)

Well I have also the same issue brother if anyone can help by making video on releasing desktop app which is using sqflite.
Please

**Comment by satyamsingh2001** [comment]
> It works perfectly fine in debug mode but in release mode this sqflite_common_ffi: ^2.2.5 is not working, am i doing this right?
> 
> Screenshots ![1](https://private-user-images.githubusercontent.com/72666307/254155609-de47c7c0-7bea-4ef7-863d-084dd802fcdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzIwMTMsIm5iZiI6MTcwNjc3MTcxMywicGF0aCI6Ii83MjY2NjMwNy8yNTQxNTU2MDktZGU0N2M3YzAtN2JlYS00ZWY3LTg2M2QtMDg0ZGQ4MDJmY2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNzhlZmZhZDBhNDAxMzNlZWI2M2RiNDdmMDlmYjE5MTIwYWVjZTc5YmUyMmQyYmU5MGI2MTU3MTEyNzhkMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IYFySJkMDSpdbYnQFLioSeNk7wf1NVPiL2cJdg7jZJs) ![2](https://private-user-images.githubusercontent.com/72666307/254155665-700a7e85-45a6-4a0e-b083-57c82c492ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzIwMTMsIm5iZiI6MTcwNjc3MTcxMywicGF0aCI6Ii83MjY2NjMwNy8yNTQxNTU2NjUtNzAwYTdlODUtNDVhNi00YTBlLWIwODMtNTdjODJjNDkyZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YWRlMzgzNTI4ODMyMjJiMjFlMGQzNDQ2NDg3NWQzYjI4OWRlN2YyMWY0ZDg5NmZhMjk4MWVhY2Q4MmI4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7CsKijwpHBgrIlyKysnm4Oti_L-MFVo76UzWYwQk8pg)

I'm also facing the same issues if any have solutions then pls
