### ISSUE TITLE
FFI library opener overrides not working

### ISSUE THREAD

**Issue by davidmartos96** [tekartik/sqflite#551]
There seems to be a bug in `sqflite_common_ffi` when overriding the library opener from `sqlite3`. Because a separate isolate is being used, changes to the `open` variable from the main isolate are not visible in the separate isolate because memory is not shared. ¿Is this a bug? 
Overriding the lookup of the native libraries is useful when one has an specific path to provide or event for an SQLCipher setup, where the name of the library changes. 
More info in this issue: https://github.com/davidmartos96/sqflite_sqlcipher/issues/28

**Comment by alextekartik** [comment]
I'm not sure this is related but I think sqflite3 must be used the first time from the main isolate (at least on windows). That is why I added in windowsInit (provided only as a reference) the following dummy code to call once from the main isolate:

```
// Force an open in the main isolate
// Loading from an isolate seems to break on windows
sqlite3.openInMemory().dispose();
```

**Comment by davidmartos96** [comment]
I tried that on Linux, but the overrides to the library opener are empty when they get run in the FFI isolate.
If you put a breakpoint in the following function from `sqlite3` it will be called twice (main isolate and sqflite isolate). The call from the main isolate has the correct overrides, but the other doesn't.
https://github.com/simolus3/sqlite3.dart/blob/e66702c5bec7faec2bf71d374c008d5273ef2b3b/sqlite3/lib/src/load_library.dart#L89

**Comment by alextekartik** [comment]
Ok I see. In my case (using regular sqlite shared lib), this is fine since I only need to load the library once so it loads fine in the main isolate. I guess it is because you are trying to load a different library.

sqflite_common_ffi does not do much, it only runs sqlite3 in a separate isolate (just a pain to package data accross isolate)

I think the simplest, assuming we override correctly in the main isolate, would be to `overrideForAll` in the background isolate to simply do nothing and return DynamicLibrary that we loaded from the main isolate (that we need to pass as an argument somehow).

**Comment by davidmartos96** [comment]
> I guess it is because you are trying to load a different library.

Yes, this would be the use case of loading a different library like sqlcipher, or even a bundled sqlite version.

> We need to pass as an argument somehow.

What I first tried is to pass as an extra argument the `open.openSqlite` function to the isolate, but that doesn't work because the function is not top level nor static.
Then I tried with a holder class with a static function that can be initialized from the main isolate. The function would return the overrides so that they can be used in the isolate.
I'm not sure if there are better solutions.
The result is something like the sample code in the related issue.

**Comment by davidmartos96** [comment]
@alextekartik I came up with what I think is a cleaner approach from the static method in the holder class.
Provide a method for creating the FFI database factory but that optionally receives a callback for initializing the bindings however you like. The callback should be either toplevel or static and it will be called in the isolate.

The implementation is no more than passing a new argument to the isolate:
```dart
// main isolate
await Isolate.spawn(_isolate, [ourFirstReceivePort.sendPort, ffiInit]);

// isolate
Future _isolate(List<dynamic> args) async {
  // open our receive port. this is like turning on
  // our cellphone.
  var ourReceivePort = ReceivePort();

  final sendPort = args[0] as SendPort;
  final ffiInit = (args[1] as void Function());

  // Initialize with the FFI callback if provided
  ffiInit?.call();
  ...
}
```

And the end result is something like the following:

```dart
Future<void> main() {
  final myFactory = createDatabaseFactoryFfi(ffiInit: ffiInit);
  var db = await myFactory.openDatabase(inMemoryDatabasePath);
  final rows = await db.rawQuery("PRAGMA cipher_version");
  print(rows); // Outputs: [{cipher_version: 4.3.0 community}]
  await db.close();
}

void ffiInit() {
  // Alternatively here we could have the `sqfliteFfiInit()` call
  open.overrideForAll(sqlcipherOpen);
}

DynamicLibrary sqlcipherOpen() {
   ...
}
```

Would you be interested in a PR?

**Comment by alextekartik** [comment]
Maybe what I did (calling overrideFor in the main isolate) is a mistake and we should have something along the line of what you propose. sqlite3 has this nice override feature that I'm not sure how to deal with yet with background isolate:
* should we load the library in the main isolate?
* should we send our init (calling overrideFor) function to the background isolate like you propose?
* What happen if sqlite3 is used by another component (such as moor) in the same application (but in the main isolate)?
* Does sqlite3 supports having multiple sqlite shared lib loaded by different isolate?

I have also a big nnbd migration in progress that might postponed me diving deeper into this (at least not before next week). If you can manage a PR on the null safety branch that would be better, if it can wait and maybe get advices from @simolus3  that would be great too. My main concern is about compatibility with the existing. The current setup is very conservative (you can use both sqflite and moor). But yes we have we'll make this work somehow!

**Comment by simolus3** [comment]
> should we load the library in the main isolate?

Based on the experience David had, it looks like that doesn't necessarily help. @davidmartos96 Did you use something not named `libsqlite3.so` in the end? I assume that, if we call `dlopen("/path/to/libsqlite3.so")` on one thread, later calling `dlopen("libsqlite3.so")` will get us the same shared library. It might not work if you're using the override behavior to open `libsqlcipher.so` instead, for instance.

Considering that it doesn't always work, I think it does more harm than good (since we end up with an unused shared library in memory).

> should we send our init (calling overrideFor) function to the background isolate like you propose?

That sounds more reliable, yes.

> What happen if sqlite3 is used by another component (such as moor) in the same application (but in the main isolate)?

A user would be responsible to ensure their opening override is set on all isolates before using sqlite3 apis, either directly or indirectly through moor.

> Does sqlite3 supports having multiple sqlite shared lib loaded by different isolate?

I don't know much about this unfortunately, it might be OS-specific depending what the loader does. If we end up with multiple copies of sqlite3 in memory, I assume they have independent globals and essentially act like different processes.

**Comment by davidmartos96** [comment]
@alextekartik I've just created a PR with my solution #552 .

> Did you use something not named libsqlite3.so in the end?

Yes, I've been using the override utility for loading `libsqlcipher.so` on Linux and the dll on Windows. With moor + isolate it can be worked around because we have the opener callback, so the override call can be made there because it will get run in the isolate.
https://github.com/simolus3/moor/blob/1cca22bc56e74772b8bccdc4aa6401904b725d6c/moor/lib/src/runtime/isolate/moor_isolate.dart#L78

Maybe this behavior only happens when overriding with names different than `libsqlite3`. The only use case I have in mind then is for getting SQLCipher to work without extra dependencies, which I think is a nice thing to have.

**Comment by alextekartik** [comment]
Thanks for the feedback @simolus3 and for the PR @davidmartos96 (minor comments on it)!

**Comment by davidmartos96** [comment]
@alextekartik Do you want to keep this open or should we close it?

**Comment by alextekartik** [comment]
@davidmartos96 If you consider it fixed (and honestly I have not tried many scenarios personally), let's close it!

**Comment by davidmartos96** [comment]
@alextekartik I think it does its job perfectly fine. I've tried with the native SQLCipher binaries on Linux and Windows just depending on `sqflite_common_ffi`. On Android/iPhone it would work by adding as an extra dependency either `sqflite_sqlcipher` or `sqlcipher_flutter_libs` from @simolus3 , although I think the latter is not on pub.dev. The extra dependency on mobile is just so that the SQLCipher library is available for FFI loading. The only one I couldn't test is on macos, but in the end is a matter of passing the correct `DynamicLibrary` .
On desktop platforms the developer is responsible of providing the SQLCipher binaries by other means, like compiling it from their repo and placing them where the executable is / PATH.
