### ISSUE TITLE
Date functions not supported by SQFlite

### ISSUE THREAD

**Issue by mado-bohsali** [tekartik/sqflite#554]
What functions built-in SQL **not** supported by SQFlite? I will rely on:

CREATE EVENT query
DAYNAME() function
and etc..

**Comment by alextekartik** [comment]
sqflite does not do much. It uses sqlite. You should look at the sqlite documentation for more information on what is supported (personally I avoid TIMESTAMP/DATE utilities):
https://sqlite.org/
