### ISSUE TITLE
Sharing/Exposing database with other Android app.

### ISSUE THREAD

**Issue by tirth-stasis** [tekartik/sqflite#555]
I'll be using this plugin in my Flutter app to create a database. Is it possible to share this database with another android app, which can also read/write from the same database?

**Comment by alextekartik** [comment]
There is no easy way I am aware of. The safest solution being writing a native content provider so not using sqflite at all.

**Comment by tirth-stasis** [comment]
I created a content provider to expose the database. The database was created using sqflite flutter plugin. So flutter app uses sqlite to do database things and the Android app (second app) uses content provider to access the same database.

You're right I don't need sqflite if I use content provider but sqflite makes it easy for flutter app do database things.
