### ISSUE TITLE
Unable to handle incoming background message

### ISSUE THREAD

**Issue by MaheshPeri19** [tekartik/sqflite#556]
I am getting below error when i am trying save push notification message in sqflite in background mode.

```
Unable to handle incoming background message
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'
```

Any suggestions to solve this ?

**Comment by tirth-stasis** [comment]
Try this to convert `_InternalLinkedHashMap` to `Map`.

```dart
final myMapData = Map.from(_InternalLinkedHashMapStoredInVariable);
```

**Comment by MaheshPeri19** [comment]
@tirth-stasis 
Thank you. I will check with this.
