### ISSUE TITLE
flutter run -d chrome, issue is no implement getDatabasePath

### ISSUE THREAD

**Issue by ptrnov** [tekartik/sqflite#562]
Error: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

**Comment by daniilshumkoidt** [comment]
Maybe that is because SQflite does not support web?

**Comment by alextekartik** [comment]
Indeed SQFlite is not supported on the web as there is no decent platform support. You can check https://github.com/deakjahn/sqflite_web for an initial web support but it lacks real persistency.

**Comment by alextekartik** [comment]
See https://github.com/tekartik/sqflite/issues/212
