### ISSUE TITLE
Missing databaseExists implementation in sqflite_common_ffi 

### ISSUE THREAD

**Issue by imReker** [tekartik/sqflite#563]
There is no implementation of `databaseExists` in
https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/lib/src/sqflite_ffi_impl.dart

**Comment by alextekartik** [comment]
Good catch! Will fix ASAP

**Comment by alextekartik** [comment]
Thanks again for the report, I cannot believe this was not tested. Fixed in `sqflite_common_ffi` 1.1.1+1 just published

**Comment by imReker** [comment]
Amazing speed, thank you very much!
