### ISSUE TITLE
Flutter file picker error: Warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated

### ISSUE THREAD

**Issue by User253T** [tekartik/sqflite#564]
I've been using the file_picker plugin to upload files from a mobile device. When running the app in debug, when it first launches, it throws this warning:
**D:\d\src\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.4\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:248: warning: [deprecation] Registrar in PluginRegistry has been deprecated final PluginRegistry.Registrar registrar**

The app still starts up fine and it still works perfect, no errors are thrown. The file_picker plugin works perfect - I can upload files and can view the files uploaded.

But as soon as I build the app in release, the app crashes on startup. When the app is opened, a white screen appears for a split second and the app closes. When I removed the file_picker plugin and built the app in release, the app opens and works perfectly fine without any errors.

I have made sure that the plugin is the latest version which is currently ^2.1.4. I've googled this error and none of the solutions have helped. The only thing that has helped was removing the plugin. Problem with removing the plugin is, I need this for file uploads. Other plugins do not work as nice as this (well in debug).

I've read through many articles on this plugin online and have not come across anyone with this issue, so I'm guessing maybe there's something wrong with my project rather than the plugin itself? Can someone please help me find out why this plugin does not work with my app? I am currently using VS Code.

**Comment by User253T** [comment]
I've also tried a different plugin - documents_picker and that throws the same warning as the file_picker.

**Comment by alextekartik** [comment]
This repository is about sqflite. I think can safely ignore this warning (which supports plugin v1). You should report this issue to the FilePicker repository.
