### ISSUE TITLE
Failed to find Build Tools revision 26.0.3

### ISSUE THREAD

**Issue by ghost** [tekartik/sqflite#57]
here is the log while compiling in android device:

--------------------------
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':sqflite'.
> Failed to find Build Tools revision 26.0.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

------------------------

then I remove "buildToolsVersion '26.0.3' " in build.gradle , fixed.

**Comment by alextekartik** [comment]
Thanks for the report. It seems the android build system does not automatically download the proper build-tools.I took the opportunity to upgrade to sdk 27 and remove any build-tools reference, following what is done in the flutter plugins repo. let me know if that works for you (version published 0.8.9)

**Comment by liutaooliver** [comment]
@alextekartik Thanks so much

**Comment by Mufaddal1125** [comment]
The solution is to update gradle version in android/build.gradle file to 8.x.x. This is because namespace attribute support was adding in this library which is part of gradle 8.0 release.
