### ISSUE TITLE
Flutter web support

### ISSUE THREAD

**Issue by ivofernandes** [tekartik/sqflite#570]
I'm using sqlflite on an android and iphone project and is working well,

but what would be a good way of putting it working on flutter web?

We have a native implementation described in:
https://www.w3.org/TR/webdatabase/

But I'm struggling on understanding why moor uses some sql.js to solve the same problem?

I will leave the the moor web folder here so maybe we can discuss the best way to go:
https://github.com/simolus3/moor/tree/master/moor/lib/src/web

**Comment by alextekartik** [comment]
WebSQL is deprecated and not supported in all browsers (for example not in firefox).

So far there is no decent web solution for that (sql.js is lacking convenient persitency). There are several other issues discussing this you can look at: https://github.com/tekartik/sqflite/issues/212

I personally recommend using other solutions (indexed_db, hive, sembast...)

**Comment by QuentinCG** [comment]
What would be for you the best option to migrate an app using sqfile to a web-compatible app ? (with least time cost)

**Comment by alextekartik** [comment]
I don't see easy solutions. Building a SQL engine (compatible with SQLite) on top of indexed_db (the only real database on the web) is not an easy task.

> Is there a way to help you improve this lib to make it compatible with web ?

if you read https://github.com/tekartik/sqflite/issues/212, you will see a first attempt using sql.js: https://github.com/deakjahn/sqflite_web

Maybe other solutions can be tried (using alasql or jsstore). The flutter plugin architecture allow having this as a separate component. Even having a non flutter solution (basically you just need to have the proper databaseFactory) could be tried.

Personally, I don't believe much in this. SQLite is super fast so any simulation would be likely too slow to be usable when using tons of record. My recommendation is to start abstracting your database as much as possible to allow having a separate implementation for the web. At some point I was interested in lovefield (https://github.com/google/lovefield) but it does not seem to get much 'love' (ha ha) and I'm not sure whether it is fully cross tab safe. I have a personal project similar to this that works on both SQLite and indexed_db but nothing to be shared at this point nor in the near future.

**Comment by QuentinCG** [comment]
Nice, thanks ;)

I'll follow and give my feedback on https://github.com/deakjahn/sqflite_web/issues/1 discussion of this sqflite_web project :)

**Comment by QuentinCG** [comment]
I helped a bit on sqflite_web which is now working quite well even if persistency is not possible due to web limitation.
It is now possible to use it to allow projects using sqflite to also support web (without persistency).

I suggest to integrate sqflite_web to main sqflite repo.
Indeed there will most likely not have better implementation than this one for web.
Moreover, maintainer is thinking of putting the project to null safety but will clearly need to synchronize with your project... And best way would be to be part of main sqflite repo.

**Comment by dream10can** [comment]
also, I am struggling with my project,  I built a library management system is responsive to all screens but it is not support the web is there any solution I am  using sqlflite

**Comment by ivofernandes** [comment]
If you need SQL maybe you need to use moor

import 'package:flutter/foundation.dart';

if(kIsWeb) {

And then use another lib, maybe
https://github.com/rodydavis/moor_shared
