### ISSUE TITLE
Flutter Error: Type 'SqfliteDatabaseFactoryMixin' not found

### ISSUE THREAD

**Issue by bouraine** [tekartik/sqflite#571]
i encounter this issue when i build for ios release mode.

../../../../.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/factory_impl.dart:75:39: Error: Type 'SqfliteDatabaseFactoryMixin' not found.
    class SqfliteDatabaseFactoryImpl with SqfliteDatabaseFactoryMixin {
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Same error when i build using xcode for physical device.

[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

analyzer: ^0.41.1
  flutter:
    sdk: flutter

  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1

  redux_thunk: ^0.3.0
  redux_persist_flutter: ^0.8.3
  redux_logging: ^0.4.0
  redux_epics: ^0.14.0
  flutter_redux: ^0.7.0

  flutter_easyrefresh: ^2.1.7
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.2+1
  flutter_signin_button: ^1.1.0
  flutter_search_bar: ^2.1.0
  jin_widget_helper: ^1.6.0
  webview_flutter: ^1.0.7
  url_launcher: ^6.0.0-nullsafety.1
  cached_network_image: ^2.5.0

  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^4.0.5755

  logging: ^0.11.4
  path_provider: ^1.6.24
  dio: 3.0.10
  quiver: ^2.1.5
  get: ^3.23.1
  intl: ^0.16.1
  favicon: ^1.0.13

dev_dependencies:
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  json_annotation: ^3.1.1
  pedantic: ^1.10.0-nullsafety.3
  integration_test: ^1.0.1
  test: any
  flutter_test:
    sdk: flutter

**Comment by bouraine** [comment]
![image](https://user-images.githubusercontent.com/15714371/103421203-6c110180-4b9b-11eb-99fb-3877abf276ba.png)

**Comment by alextekartik** [comment]
Sorry, I could not reproduce. I don't know what is your min sdk in your pubspec but it seems you are using some null safety package. You might want to try to explictely depend on sqflite null safety version too...

**Comment by bouraine** [comment]
thank for you help. i figure it out. it was because of a pub cache.
fixed simply by this command `pub cache repair`
