### ISSUE TITLE
Error running project

### ISSUE THREAD

**Issue by rubenteste** [tekartik/sqflite#578]
hi,
I download the project, and run after, i didn't change anything 
and just give me this error :

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Script '/opt/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 325

* What went wrong:
A problem occurred configuring project ':sqflite'.
> Could not get unknown property 'android' for project ':sqflite' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 457ms
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by alextekartik** [comment]
Can you tell which project you are trying to run (the example in sqflite?) and which flutter channel you are using. Thanks!

**Comment by rubenteste** [comment]
hey @alextekartik 
already try to run sqflite_test_app and sqflite but always give me errors
![Captura de ecrã de 2021-01-25 10-28-29](https://user-images.githubusercontent.com/75133022/105694588-08a79480-5ef9-11eb-80dd-ab4018905e8b.png)
![Captura de ecrã de 2021-01-25 10-34-43](https://user-images.githubusercontent.com/75133022/105694593-09402b00-5ef9-11eb-985c-08d9a69e9364.png)

**Comment by alextekartik** [comment]
This project does not contain any project file (android, ios,....), as specified in the README.md in the same folder you should do:
```
flutter create  .
flutter run
```

In case of error, you can try to delete the android folder first.

Which flutter channel (stable/beta/dev) are you using? You can also try to run the project in the sqflite/example which should contain the android project files already (but it is always a pain to maintain).

**Comment by rubenteste** [comment]
i'm using flutter stable
just try to run the project in the sqflite/example and give me error:
![Captura de ecrã de 2021-01-25 15-20-51](https://user-images.githubusercontent.com/75133022/105725579-08bb8a80-5f21-11eb-8755-b643b7b4d421.png)

**Comment by alextekartik** [comment]
I'm sorry I cannot reproduce the issue. I'm assuming `flutter doctor` does not return any error and that you are able to create and run a flutter project without issue. Can you confirm?

**Comment by rubenteste** [comment]
I ended up managing to solve the problem
one last thing
everytime i close the app, the database is destroyed right?
if i close the app and then open the app i need to create the BD again? i cant access to the data that i have created before close the app right?

**Comment by alextekartik** [comment]
> I ended up managing to solve the problem

Great. It would be good for everybody to know what you did to solve the problem.

> if i close the app and then open the app i need to create the BD again? i cant access to the data that i have created before close the app right?

No, the data should persist (that's the purpose of this plugin!). Hard to say what is going wrong without seeing any context/code.

**Comment by rubenteste** [comment]
on the pc where I got this error I couldn't solve it, what I did was test it on my desktop I did everything the same, but on the laptop I couldn't solve it ... 
After all I already have the data persistent, the only way to delete the BD is to delete the data related to the APP
thanks for your help :)

**Comment by rubenteste** [comment]
@alextekartik it's normal that in my app making a select without internet doesn't work?

**Comment by alextekartik** [comment]
This sounds like a separate issue. That should not happen. I am able to run the example app without internet connection. If you can have an example that show the issue, good if you can fill a separate issue (If I understand your latest question is about your app while the initial issue is about running the example app) with a way to reproduce.

**Comment by Mufaddal1125** [comment]
The solution is to update gradle version in android/build.gradle file to 8.x.x. This is because namespace attribute support was adding in this library which is part of gradle 8.0 release.
