### ISSUE TITLE
Databases path

### ISSUE THREAD

**Issue by 538Michael** [tekartik/sqflite#579]
Hello, I do like to know the path directory of databases, so I can open it with DB Browser for example.

**Comment by alextekartik** [comment]
It depends on the platform:
- On Android, it is typically data/data/
- On iOS, it is the Documents directory

You can call [`getDatabasesPath()`](https://pub.dev/documentation/sqflite/latest/sqflite/getDatabasesPath.html) and print the directory

**Comment by Invincible1996** [comment]
How about on macos?

**Comment by alextekartik** [comment]
On macos, it also uses the documents directory. On windows using ffi it is a placeholder relative location which does not make much sense but for testing. 

In facts besides Android, you'd better use `path_provider` to find the best location for your database.
