### ISSUE TITLE
linux plugin support?

### ISSUE THREAD

**Issue by jinfagang** [tekartik/sqflite#583]
Sqflite is so good to use, the only drawback is that not official flutter linux plugin.

Does anyone knows how to make it can use on linux?

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method openDatabase on channel com.tekartik.sqflite)

```

**Comment by alextekartik** [comment]
On Linux, you can use https://pub.dev/packages/sqflite_common_ffi
It is not implemented as a flutter plugin as it also runs on the dartvm outside of any flutter context, but the usage is similar.

https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md

**Comment by jinfagang** [comment]
@alextekartik  thanks. How should I using it without changing my current code?

I am using `flutter build linux` to generate linux app, it can runs, but tell me no such plugin of sqflite. How do I using sqflite_common to fix this gap?

**Comment by alextekartik** [comment]
> How should I using it without changing my current code?

That is what the link explained: https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md#initialization


Simply doing `databaseFactory = databaseFactoryFFi;` before any other database call should bring Linux and Windows support.

```dart
import 'package:sqflite_common_ffi/sqflite_ffi.dart';
import 'package:sqflite/sqflite.dart';

Future main() async {
  if (Platform.isWindows || Platform.isLinux) {
    // Initialize FFI
    sqfliteFfiInit();
    // Change the default factory
    databaseFactory = databaseFactoryFfi;
  }
  runApp(MyApp());
}
```


You might also have to change the path of the database, maybe using path_provider to find a good location.

**Comment by jinfagang** [comment]
@alextekartik Yes, thank u. I think this is very good.

**Comment by imanpr** [comment]
i am used it in windows debug mode and works correctly. but when i get release version of windows app in flutter. its dont working good. any one have solution for this?

**Comment by bbrto21** [comment]
Hi I am trying to try this on Tizen(a kind of Linux distribution) using [flutter-tizen](https://github.com/flutter-tizen/flutter-tizen)
I've tried using sqflite_common_ffi but I faced two problems.
The first problem was the path, Tizen has an app model similar to other mobile platforms., so I need to get a writable path for the running app. 
Second, plugin instances created from the main isolate were not shared with the spawned isolate, so I couldn't override the library loading path. 

I want your cool plugins to work on Tizen too, can you help me? 
I'll share my temporary solution [here](https://github.com/bbrto21/sqflite/commit/28d45148c03aee0fdd9a30c07301c5bfdfcb8fb7),
