### ISSUE TITLE
Sqflite.devSetDebugModeOn(true) stops db being filled with data on iOS simulator

### ISSUE THREAD

**Issue by saward** [tekartik/sqflite#585]
On my local machine (m1 mac), iOS simulator, when I use:

`Sqflite.devSetDebugModeOn(true);`

Any attempts to create tables or insert rows seem to fail silently (the sqlite db file stays at 0 bytes size).  As a result, querying returns no results:

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=1 "no such table: Project" UserInfo={NSLocalizedDescription=no such table: Project}) sql 'SELECT
```

As soon as I stop trying to devSetDebugModeOn or setDebugModeOn, it appears to work again.

A brief test with Android studio running on Linux, I did not have the same issue.

**Comment by alextekartik** [comment]
Thanks for catching this.
Indeed activating logs on iOS and MacOS was preventing execute request to execute...
Fixed in 1.3.2+3 just published

**Comment by saward** [comment]
Nice quick fix, thanks!  I haven't tested yet, but will likely return to my project in a few days.

**Comment by saward** [comment]
Initial quick test indicates that it is fixed.
