### ISSUE TITLE
#question - How sqlflite works?

### ISSUE THREAD

**Issue by vimalmistry** [tekartik/sqflite#586]
I want to know. How sqflite works.

For example. When I open my app and its open database.
- On that time all data will be loaded on memory?
- Or it fetch data according query from disk to memory?

**Comment by alextekartik** [comment]
sqflite does not do much besides giving a dart API and some threading mechanism. All the credits go to SQLite.

No the data is not loaded in memory on start but I don't know the deep details. You will find information here: https://sqlite.org/index.html
