### ISSUE TITLE
Named int variables don't work correctly on Android

### ISSUE THREAD

**Issue by simolus3** [tekartik/sqflite#589]
This is essentially a follow-up to #272 and #64. A moor user reported that the following query didn't work as expected:

```sql
select 
  LST_PAY_MODE.LSCB_ID,
  LST_PAY_MODE.LSCB_PAY_MODE,
  LST_PAY_MODE.LSCB_TTL_MONTH,
  LST_PAY_MODE.LSCB_KALI
from LST_PAY_MODE 
where case 
  when :payModeList = 1 then LSCB_ID in (0) 
  when :payModeList = 2 then LSCB_ID in (6,1,2,3) 
  when :payModeList = 3 then LSCB_ID in (3)
  when :payModeList = 4 then LSCB_ID in (6)
end
```

This query has a single variable (`:payModeList`) at index 1, which is bound to an integer. The moor issue is https://github.com/simolus3/moor/issues/1049 (cc @rrifafauzikomara), but I don't think it's a moor bug since we're using a custom query that's directly passed to sqflite.

I know that the root cause of all this is that we can't properly bind ints on Android, so we're inlining int variables by replacing the `?` in the query string. I'm wondering if you've considered using [androidx.sqlite](https://developer.android.com/jetpack/androidx/releases/sqlite) instead of the raw apis? It provides [this class](https://developer.android.com/reference/androidx/sqlite/db/SupportSQLiteProgram) which has typed methods to bind parameters.

**Comment by alextekartik** [comment]
Thanks @simolus3 for pointing me to androidx.sqlite that I was not aware of. Indeed it seems to support binding non string argument that is worth taking a look at.
