### ISSUE TITLE
Insert or update

### ISSUE THREAD

**Issue by dankop123** [tekartik/sqflite#59]
Is there an easy and efficient way to insert multiple objects to a database if not existing, or update if already exist? Do you predicted this eventuality? Some SQL helper maybe, or do I need to manually check each object for existence in the database?

**Comment by alextekartik** [comment]
SQLite has this built-in. I personnally use 2 solutions

* During `CREATE TABLE` you can add a constraint such as

```
CREATE TABLE xxx (..., UNIQUE name ON CONFLICT REPLACE)"
```

* For primary key conflict, during `INSERT` you can do

```
INSERT OR REPLACE INTO xxx 
```

There is no helper for `CREATE TABLE` (it could be very complex to handle all the possible SQL features here). For insert/update helper however, there is `ConflictAlgorithm` parameter that you can try. I have not tested it much myself as I tend to write raw SQL.

Unfortunately it requires diving into SQLite documentation. Best for your case is to look at the `UPSERT`documentation here: https://www.sqlite.org/draft/lang_UPSERT.html

**Comment by dankop123** [comment]
@alextekartik Thank you, that helped me a lot

**Comment by ostertagi** [comment]
The method i use is more direct :

  Future<void> insertOrUpdate(MyClass obj) async {
    var id = await update(obj);
    if (id == 0) insert(obj);
  }
i've tested it and it seems to work. i started with the update method because the conflict (exception) is more resource consuming since i'm working with large amount of data.
Hope this help

**Comment by omidraha** [comment]
@ostertagi 
Thanks.

**Comment by develop-sell** [comment]
this may help if you use sqlfite (flutter version)

await db.execute('''CREATE TABLE IF NOT EXISTS ChatMemberInfo(
          rowId integer primary key autoincrement,
          loginId text not null unique,   // this line.
          nickname text not null,
          imageUrl text not null
          )''');
