### ISSUE TITLE
Licenses of pub.dev and this repository differ

### ISSUE THREAD

**Issue by trin94** [tekartik/sqflite#597]
https://pub.dev/packages/sqflite **MIT**  
https://github.com/tekartik/sqflite **BSD 2-Clause "Simplified"**

I assume that this software is licensed under the BSD 2-Clause "Simplified", as it is 'closer to the code'? :smile:

**Comment by alextekartik** [comment]
I'm not sure I get the difference, sorry!. Basically I want the license to be as permissive as possible. Should it be BSD 2 or MIT? Can I just change without problem. I think then I just need to copy the proper license file in the various dir.
