### ISSUE TITLE
Fails silently on iOS if logging is disabled

### ISSUE THREAD

**Issue by BoaNeo** [tekartik/sqflite#6]
There's a bug around line 320 in SqflitePlugin.m that causes the execution queue to only be created if logging is enabled (NSOperationQueue is created inside the check for _log when it should have been outside) - this is the correct code:

**   if (_databaseOpenCount++ == 0) {
            if (_log) {
                NSLog(@"Creating operation queue");
            }
          self.operationQueue = [NSOperationQueue new];
        } **

**Comment by alextekartik** [comment]
oups indeed. I guess I enabled logging too much. thanks, fixing it right now

**Comment by BoaNeo** [comment]
Great, thanks. And thanks for providing this library - saved me a good chunk of time :)

**Comment by alextekartik** [comment]
fixed in v0.2.1 published
