### ISSUE TITLE
FMDB error

### ISSUE THREAD

**Issue by Naveenkumar3506** [tekartik/sqflite#603]
<img width="1440" alt="Screenshot 2021-03-05 at 10 21 48 AM" src="https://user-images.githubusercontent.com/6657950/110068916-b6318180-7d9c-11eb-9076-432e44a1ece8.png">

Hi, I am getting the above error. can please help me to fix this. i have to updated flutter 2.0. I tried clear derived data also but no use.

**Comment by alextekartik** [comment]
I think you need to remote the arm7 architecture from Xcode for existing project. I'm not sure about the proper steps, sorry, but you can create a new flutter project and compare the settings in XCode.

**Comment by mithunmqb** [comment]
I am facing the same error. I do not have sqflite in my pubspec.yaml. The only places I can see the usage is in some files within the Flutter SDK. I tried adding armv7 to excluded architectures in Xcode and I could run on the device. But that flag gets reset when I run flutter build iOS from Android Studio.

**Comment by bestkid1234** [comment]
Same issue here...

**Comment by alextekartik** [comment]
@mithunmqb @bestkid1234 The arm7 architecture must be **removed** from the project (not excluded). If you have a project (since I'm assuming this happens when migrating an old project) to share, I can try to find the steps. Sometimes the best solution is to completely recreate the Xcode project (deleting the ios folder and calling `flutter create .`) although I know that is not a convenient solution for old project where you have other settings (icons, splash) in place.

**Comment by bestkid1234** [comment]
> @mithunmqb @bestkid1234 The arm7 architecture must be **removed** from the project (not excluded). If you have a project (since I'm assuming this happens when migrating an old project) to share, I can try to find the steps. Sometimes the best solution is to completely recreate the Xcode project (deleting the ios folder and calling `flutter create .`) although I know that is not a convenient solution for old project where you have other settings (icons, splash) in place.

I tried to recreate the project by `flutter create .` but no luck 😢

**Comment by alextekartik** [comment]
Did you delete the ios folder before? by 'no luck', can you tell which error you get?

**Comment by alextekartik** [comment]
Great. Thanks for pointing to the link as it can help others.
