### ISSUE TITLE
What is the difference between a batch and a transaction?

### ISSUE THREAD

**Issue by magnuswikhog** [tekartik/sqflite#604]
I understand that transactions are an SQL feature, and a batch operation is something SQFlite uses to minimize the "ping ping" between Dart and native code. That's the underlying difference,  but it's not entirely clear what the practical differences are, and when one should prefer one or the other. For example, they are both able to either commit or abort the entire operation. 

Some clarification on this would be appreciated!

**Comment by alextekartik** [comment]
That's a good question and the documentation is poor.  A batch is just a list of queries/sql commands. When you commit a batch, it actually creates a transaction, then run all the commands from the list and return. The batch semantic comes from Android content provider which has about the same feature (https://developer.android.com/guide/topics/providers/content-provider-basics#Batch)

If a sql command does not depend on a previous result, you can use a batch. If however your command depends on the result of the previous one, use a transaction.

To clarify with an example, if you want to check that a record exists before adding another record, you cannot use a batch, you have to create a transaction, perform a query, read the result and depending on the result, perform an insert or not. A batch won't work here.

If you need to insert 100 records and you don't care about the result, a batch is a good solution.

Practically, I personally use a batch when I can, typically during onCreate where I setup a lot of tables and most of the time, I'm fine with just using transactions.

**Comment by Somtobro** [comment]
Hey, having said this i think I found a bug or unusual behavior.
I'm running a modify table query in a transaction.
If I skip adding apostrophe's to indicate it's a string like I did with bbbb below in the first line, this emptys my table when it's done, it doesn't show an error or rollback or anything (recall I'm using a transaction) 


ALTER TABLE "person_organization_member_association" ADD COLUMN "COLUMN_NAME" REAL DEFAULT bbbb; CREATE TABLE "new_person_organization_member_association" ("person_id" INTEGER,"organization_id" TEXT,"COLUMN_NAME" REAL DEFAULT bbbb);INSERT INTO "new_person_organization_member_association" ("person_id","organization_id") SELECT "person_id","organization_id" FROM "person_organization_member_association";DROP TABLE "person_organization_member_association";ALTER TABLE "new_person_organization_member_association" RENAME TO "person_organization_member_association";



On the other hand if run this exact code with a single modification i.e putting bbbb into apostrophe's like 'bbbb', it works perfectly


Still note if I run just the alter query without creating and the others(just the first single query).it also works perfectly

**Comment by alextekartik** [comment]
@Somtobro can you create a separate issue (it does not seem to be related to the original question regarding batch and transaction) and enclose your code using triple ticks? Thanks!

**Comment by Somtobro** [comment]
Done
