### ISSUE TITLE
Are SQL Triggers possible

### ISSUE THREAD

**Issue by EzzatOmar** [tekartik/sqflite#613]
I'm just getting into sqlite and sqflite.
Is it possible to use sql triggers.
I'm looking for a way to issue dart function on database changes.

Thank you

**Comment by alextekartik** [comment]
There is no way currently to call a dart function from database triggers.

**Comment by AshweenMankash** [comment]
Any plans to add it?

**Comment by russelljahn** [comment]
I'm also interested in trigger functionality to dynamically subscribe to database changes in Dart code.

**Comment by alextekartik** [comment]
Sorry, there is no way currently to call a dart function from database triggers. (for example Android does not support that).
