### ISSUE TITLE
getDatabasesPath return non nullable return

### ISSUE THREAD

**Issue by bohdan1krokhmaliuk** [tekartik/sqflite#615]
`Future<String?> getDatabasesPath() => databaseFactory.getDatabasesPath();` this method has a return type of Future with nullable string, otherwise `databaseFactory.getDatabasesPath` has a return type of `Future<String>`. Looks like no reason to use nullable string over here

**Comment by alextekartik** [comment]
Good catch, thanks, I guess I missed this during `dart migrate`. Fixed in sqflite 2.0.0+3
