### ISSUE TITLE
Preload a SQLite DB or from SQL file

### ISSUE THREAD

**Issue by samuelmukoti** [tekartik/sqflite#62]
Hi,

Any tips on how one can preload/pre-seed a database using flutter?

**Comment by alextekartik** [comment]
Yeap. I added a section here: https://github.com/tekartik/sqflite/blob/master/doc/opening_db.md#preloading-data

Basically you can either:
* Import an existing SQLite file
* Populate data during onCreate

**Comment by anhhh11** [comment]
I have a little big sql file (~4Mb). Can I just read file as string and execute  one time with `db.execute`? Is there any problem here?
I've seen the preloading data section:
https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_db.md#preloading-data

**Comment by alextekartik** [comment]
Unfortunately the native implementation only allows executing commands one by one. If you have one command per line, you simply do something like this:

```dart
var batch = db.batch();
const LineSplitter().convert(sql).forEach((cmd) {
  batch.execute(cmd);
});
await batch.commit();
```
If you have commands that span over multiple lines, it will require some pre-parsing to extract each command and this plugin does not have utilities to parse sql.

**Comment by Dinosane2** [comment]
Well, I was searching for better soluctions than my current one, but looks that it could help someone:

I'm working with 27MB files and my user start the app without any database file at all and once I detect it is missing, I just download it as a sqlite file already created at server and zipped ! (7.5MB zip file).

Once uncompressed, I open it, let my user edit what he wants and then syncronize back only what was done (using REST).
