### ISSUE TITLE
Failed to run Unit test on Linux: SqfliteIsolate.handle - libsqlite3.so: cannot open shared object file

### ISSUE THREAD

**Issue by akadatsky** [tekartik/sqflite#620]
I want to write a unit test using sqflite_common_ffi for my flutter app, and it works ok on Mac but failed on Linux pc with error:

```
package:sqflite_common_ffi/src/isolate.dart 39:9  SqfliteIsolate.handle

SqfliteFfiException(error, Invalid argument(s): Failed to load dynamic library (libsqlite3.so: cannot open shared object file: No such file or directory)} DatabaseException(Invalid argument(s): Failed to load dynamic library (libsqlite3.so: cannot open shared object file: No such file or directory)) {}
```

I believe it failed because could not found  `libsqlite3.so` library on my PC.
I tried to install sqlite3 on my Linux PC but it does not help. 
I found that `libsqlite3.so` library located in `~/android-sdk/emulator/lib64/qt/lib`

Any way to make it works?

**Comment by alextekartik** [comment]
There is a small step on linux: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi#linux

which on debian (ubuntu) should be:
```
sudo apt-get -y install sqlite3 libsqlite3-dev
```

**Comment by akadatsky** [comment]
Thanks for a fast response, it works
