### ISSUE TITLE
Disable PRAGMA foreign_keys only during migrations

### ISSUE THREAD

**Issue by aleripe** [tekartik/sqflite#624]
I need to issue two commands to the database before executing my migrations:

```
await db.execute('PRAGMA foreign_keys = OFF');
await db.execute('PRAGMA legacy_alter_table = ON');
```

Unfortunately during `onUpgrade` a transaction has already been created and Sqlite documentation states that:

```
PRAGMA foreign_keys;
PRAGMA foreign_keys = boolean;

Query, set, or clear the enforcement of foreign key constraints.

This pragma is a no-op within a transaction; foreign key constraint enforcement may only be enabled or disabled when there is no pending BEGIN or SAVEPOINT.
```

So I solved by editing Sqflite's source code like that:

```
if (options.version != null) {
        // Check the version outside of the transaction
        // And only create the transaction if needed (https://github.com/tekartik/sqflite/issues/459)
        final oldVersion = await getVersion();
        if (oldVersion != options.version) {
          await db.execute('PRAGMA foreign_keys = OFF');
          await db.execute('PRAGMA legacy_alter_table = ON');
          await transaction((Transaction txn) async {
```

Is there a way of doing that without altering the source code? I can't use `onConfigure` since `PRAGMA foreign_keys` must be `ON` always except while doing upgrades.

**Comment by alextekartik** [comment]
Indeed I don't see easy solutions. I can think of questions:
- you say that you don't want foreign_keys to on during upgrade, is there a reason or a way to make your upgrade mode with foreign keys on?
- what about configuring foreign_keys during onOpen (basically the order is onConfigure(no transaction), onCreate/onUpgrade, onOpen(no transaction).

**Comment by aleripe** [comment]
I can't leave foreign keys on as I have a lot of ALTER TABLE hacks with DROP TABLEs that would result in data loss for foreign key constraints.

I need to do it before onUpgrade. What I was thinking is to add two new callbacks: onBeforeUpgrade and onAfterUpgrade ... do you think it could be possible?

**Comment by alextekartik** [comment]
I cannot easily add callbacks without breaking some dependencies (ffi, cipher) but I guess that could be a solution.

What about, in you case, turning on foreign keys during onOpen instead? (maybe you don't need foreign keys neither during onCreate).

**Comment by aleripe** [comment]
Yes, it could be an option for my case... I try and then let you know. Thanks!

**Comment by aleripe** [comment]
The onOpen trick worked (I didn't know that hook). So for my case the problem is solved, but those additional callbacks could still be useful for other cases.

Again, thanks for your help!

**Comment by alextekartik** [comment]
Alternatively, during onConfigure you could check the version to know if you are going to upgrade and perform the proper initialization. So we'll see if additional callbacks are needed (as a side android database open helper has similar callbacks than sqflite has).

**Comment by aleripe** [comment]
Yes, you're right. But the problem when a transaction is automatically started before calling the callbacks. It seems some ORMs like Android's Room disable foreign keys before opening the transaction so the problem doesn't appear.
