### ISSUE TITLE
About method getDatabasesPath

### ISSUE THREAD

**Issue by onlylikews** [tekartik/sqflite#626]
Why do getDatabasesPath methods not be used in the Library directory on the ios platform? Can you provide a api that can specify the path？

**Comment by alextekartik** [comment]
Not sure what you mean by "not be used in the Library". The API came from Android. On iOS it currently returns the default document folder and for compatibility reason that cannot safely be changed. 

However you can ignore this method and use path_provider to find a better location to build an absolute path to use in openDatabase.
