### ISSUE TITLE
Let getDatabasesPath return an injectable path for Android

### ISSUE THREAD

**Issue by xster** [tekartik/sqflite#628]
By default, getDatabasesPath (and the path used for openDatabase etc) are based on [Context.getDatabasePath](https://github.com/tekartik/sqflite/blob/master/sqflite/android/src/main/java/com/tekartik/sqflite/SqflitePlugin.java#L1035). This is ok for most cases. Though sometimes, users may want to customize this path (such as putting it in /data/username/ rather than /data/data etc). It would be nice to make this path injectable (such as via the SqflitePlugin java class constructor for advanced users).

**Comment by alextekartik** [comment]
You can use https://pub.dev/documentation/sqflite_common/latest/sqlite_api/DatabaseFactory/setDatabasesPath.html:

```dart
await databaseFactory.setDatabasesPath('my_new_path');
```

**Comment by xster** [comment]
LG thanks!
