### ISSUE TITLE
Possible usage improvement

### ISSUE THREAD

**Issue by tkreuder** [tekartik/sqflite#630]
Hey,
thanks a lot for this awesome plugin :) We are using it extensively, without any issues.
For me it was not clear, that:
`onCreate/onUpgrade/onDowngrade` are wrapped into a transaction [https://github.com/tekartik/sqflite/](https://github.com/tekartik/sqflite/blob/0973f29d5338f4fa53695a78b016b61bb1e762c7/sqflite_common/lib/src/database_mixin.dart#L712) and inside those callbacks I wrapped the statements into transactions, which is unnecessary.
If you agree, I would open a PR to rename these arguments to: 
`onCreateTransaction/onUpgradeTransaction/onDowngradeTransaction`

**Comment by alextekartik** [comment]
Renaming would unfortunately break all existing packages/apps so sometimes we have to live with history and I would likely not accept your PR...

As a side note:
* the API matches partially Android [SQLiteOpenHelper api](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper) which has the exact same names (and transaction mechanism)
* Transaction inside those callbacks are indeed useless but it should be handled gracefully and it does not hurt

**Comment by alextekartik** [comment]
But I would gladly accept a PR on clarifying this in the doc ha ha ;)
