### ISSUE TITLE
Accesing database on Terminal

### ISSUE THREAD

**Issue by pr4nshul** [tekartik/sqflite#631]
I want to use terminal to see my database on my emulator. But when I use `sqlite database_name` or s`qlite3 database_name` . It throws error that sqlite not found. Is there a way we can access the database in shell using terminal.

**Comment by alextekartik** [comment]
Try `sqflite3 <full_database_path>` (lowercase s and not just the database base but its full path). But it is sometimes more convenient to 'pull' the file (using Android studio file manager)

**Comment by TarasMazepa** [comment]
Hi @pr4nshul @alextekartik , can you give some step-by-step instructions for doing this? Is there some kind of dar/flutter terminal where I can call `sqflite3` ?

**Comment by TarasMazepa** [comment]
What I did for android emulator to access database was:
`adb shell` - open emulator shell
`su` - enter superuser mode
`sqlite3 /data/user/0/<app package name>/databases/<db name>`
