### ISSUE TITLE
Create table with autoincrement documented incorrectly

### ISSUE THREAD

**Issue by SoftMaster19** [tekartik/sqflite#633]
The documentation has this:
await db.execute('CREATE TABLE my_table (id INTEGER PRIMARY KEY AUTO INCREMENT, name TEXT, type TEXT)');

I think it should be this (at least on the Android simulator I am using for testing).
await db.execute('CREATE TABLE my_table (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, type TEXT)');

**Comment by alextekartik** [comment]
Thanks for the report!
