### ISSUE TITLE
batch not support on windows?

### ISSUE THREAD

**Issue by jinfagang** [tekartik/sqflite#636]
```
handler for method 'batch' on channel 'com.tekartik.sqflite' returned an error: invalid args
```
I am building on windows using hover `go-flutter`, I am not sure it's official vendor lib or not, but I don't know why this happen, any help please?

**Comment by alextekartik** [comment]
Windows is supported not as a regular plugin since it uses ffi and works also on DartVM (i.e. not only flutter). See https://pub.dev/packages/sqflite_common_ffi for more information
