### ISSUE TITLE
Local db migration problem

### ISSUE THREAD

**Issue by JMApps** [tekartik/sqflite#637]
I have a local database that the user can make changes to. If I supplement the database and start a new version, how can I leave the data changed by the user and add new ones?

**Comment by alextekartik** [comment]
There is no global solution for that. One solution is to 'tag' data (could be adding a version field to the the records) added by the user so that you know what has changed since the previous migration.

**Comment by JMApps** [comment]
It would be very nice if you could study the database room migration on android and implement something similar.

**Comment by alextekartik** [comment]
If you want a higher level API you might look at the `moor` package which has some migration helpers: https://moor.simonbinder.eu/docs/advanced-features/migrations/

sqflite provides only a low level SQLite API with only a basic migration mechanism - [example here](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/migration_example.md) - but by incrementing the version you can do almost anything

**Comment by JMApps** [comment]
Thank you very much

сб, 15 мая 2021 г. в 22:26, Alexandre Roux ***@***.***>:
