### ISSUE TITLE
sqflite query needs to support List type items within whereArgs

### ISSUE THREAD

**Issue by Tahaan** [tekartik/sqflite#641]
Specifically to allow queries with the IN operator, eg

SELECT * FROM item WHERE name IN ('chair', 'table', 'cup');

From something like
```dart
List<String> valueList = ['chair', 'table', 'cup'];
final r = await db.query('item', where: 'column IN ?', whereArgs: [valueList]);
```

Specifically the following workaround does not sufficiently safeguard against SQL injection.

```dart
List<String> valueList = ['chair', 'table', 'cup')];
String valuesCompiled = '"' + valueList.join('","') + '"';
final r = await db.query('item', where: 'column IN (?)', whereArgs: [valuesCompiled]);
```

**Comment by alextekartik** [comment]
Unfortunately sqflite does not do any SQL parsing so since what you asked for is not supported in SQLite, it cannot work.
See https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#parameters

The proper way for you example is
```dart
List<String> valueList = ['chair', 'table', 'cup'];
final r = await db.query('item', where: 'column IN (?,?,?)', whereArgs: valueList);
```

Notice that all parameters must be specified and the whereArgs is a flat list (not a list of list).

**Comment by Tahaan** [comment]
The number of items may not be fixed.

`db.query('items', where: 'column IN ? AND date > ? AND otherColumn NOT IN ?', whereArgs: [values, startDate, otherList]);`

The implementations of DB support packages in other programming languages does support array / List type values as where arguments, hence my question.

Example:Python: https://www.psycopg.org/docs/usage.html#adapt-list

**Comment by alextekartik** [comment]
If the number of args is not fixed, you can generate ?,?,?... using trick like this:
```dart
var inArgs = ['cat', 'dog', 'fish'];
var list = await db.query('my_table',
  where: 'name IN (${List.filled(inArgs.length, '?').join(',')})',
  whereArgs: inArgs);
```

As I said, doing what your example does would requires changing ? to ?,?,? at some point and sqlite does not manipulate nor parse sql queries.
