### ISSUE TITLE
macos release open error

### ISSUE THREAD

**Issue by Invincible1996** [tekartik/sqflite#644]
When I use xcode to archive the application and then copy it out, I got this error when I opened the app, even though I copied .dart_tools  to the root directory.
![image](https://user-images.githubusercontent.com/22675676/118238500-2bbb7b80-b4cb-11eb-8145-2d2f59e00b80.png)
![image](https://user-images.githubusercontent.com/22675676/118238977-ccaa3680-b4cb-11eb-978d-07cb09b99c1f.png)

**Comment by alextekartik** [comment]
Notice that that path you are using is absolute not relative. You might better handle the location yourself (instead of using getDatabasesPath or relative path which makes mainly sense on Android) by use `path_provider` or other custom location

**Comment by Invincible1996** [comment]
@alextekartik Thanks! use path_provider works for me.
