### ISSUE TITLE
Supporting 3.35 version

### ISSUE THREAD

**Issue by guid-empty** [tekartik/sqflite#645]
HI! 
And A olt of thanks for this Flutter package 👍 

But one question - Is it possible to support 3.35 version of SQLite?
https://sqlite.org/changes.html

As you can see there is support added for ALTER TABLE DROP COLUMN feature.
But right now in Sqflite is not possible to use this feature. 
Using the dropping the column is very importing when we need to get some migrations to create new columns and delete old columns without recreating whole tables.

Thank you.

**Comment by alextekartik** [comment]
sqflite uses whatever version the platform provides so likely not 3.35. You might want to try `sqflite_common_ffi` for using a custom flutter libs using https://pub.dev/packages/sqlite3_flutter_libs package but I have not tested that much (and I don't know which version of SQLite it uses)

More information here: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi#readme

**Comment by tomshen66** [comment]
Hi,
I have the same requirement to use a more update-to-date SQLite version for several advanced sql queries. According to https://developer.android.com/reference/android/database/sqlite/package-summary, Android API 28 uses SQLite 3.22 (release in 2018), Android API 30 uses SQLite 3.28 (released in 2019), both are rather outdated. The SQLite version release dates are listed at https://www.sqlite.org/chronology.html.

My question is: is it possible to ship a latest SQLite database (e.g. version 3.35.0) at APPLICATION level, packaged with the Flutter APP itself? Or else is there any workaround e.g. to upgrade the phone's OS SQLite version? 

Thanks!

**Comment by alextekartik** [comment]
>  is it possible to ship a latest SQLite database (e.g. version 3.35.0) at APPLICATION level,

Yes using https://pub.dev/packages/sqlite3_flutter_libs package and using sqflite_common_ffi.
More information here: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi#readme

>  is there any workaround e.g. to upgrade the phone's OS SQLite version?

I am not aware of such trick

**Comment by tomshen66** [comment]
Hi alextekartik, thanks for the info. https://www.sqlite.org/changes.html this page lists detailed features added from version to version. I think for compatibility it might be better to leave the system sqlite installation intact and use walkaround sql queries to achieve the same effect. One example is the "FILTER clause on aggregate functions", which was only added on 3.30.0 release. The same effect can be achieved by using CASE statement.
