### ISSUE TITLE
Need to open an sqlite3 database with password word protected? 

### ISSUE THREAD

**Issue by iampopal** [tekartik/sqflite#648]
sqflite does not support password protection so I was using https://pub.dev/packages/sqflite_sqlcipher, now i am using sqflite_common_ffi for windows and need password protection.

when will we support password-protected SQLite opening?

**Comment by davidmartos96** [comment]
@iampopal Posting again here the solution for visibility. https://github.com/davidmartos96/sqflite_sqlcipher/issues/42#issuecomment-843770864

@alextekartik Do you think the docs for sqflite_commom_ffi could be updated to indicate the possibility of using Sqlcipher on desktop?
