### ISSUE TITLE
] Unhandled Exception: SqfliteFfiException(error, Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory} DatabaseException(Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory) {}

### ISSUE THREAD

**Issue by jinfagang** [tekartik/sqflite#652]
flutter snap error:

```
] Unhandled Exception: SqfliteFfiException(error, Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory} DatabaseException(Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory) {}

```

I run `flutter run` is OK, but when run `snapcraft` or `flutter build release`, it got this error.

But I have sqlite3.so installed already,

**Comment by jinfagang** [comment]
Look closely at error message, I think it is related to sqflite way to load this dynamic lib:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(206)] Unhandled Exception: SqfliteFfiException(error, Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory} DatabaseException(Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory) {}

```

For Ubunut, it should locate at: 

```
/usr/lib/x86_64-linux-gnu/libsqlite3.so
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6

```

**Comment by jinfagang** [comment]
@alextekartik Sorry I tried `sudo apt-get -y install sqlite3 libsqlite3-dev ` but didn't work.

**Comment by alextekartik** [comment]
I'm not familiar with the snap build process but you need to add [libsqlite3 dependency somehow](https://snapcraft.io/docs/build-and-staging-dependencies), maybe in the snapcraft.yaml with something like:
```yaml
 stage-packages:
      - libsqlite3-0
```

I'm also on ubuntu where it should find it properly.

You can try:

```
sudo apt-get -y install libsqlite3-0 libsqlite3-dev
```

Otherwise you can manually configure the location as described in https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3#manually-providing-sqlite3-libraries

To note that I'm interested if you find a solution as I cannot reproduce the issue.

**Comment by jinfagang** [comment]
@alextekartik thanks for your suggestion as always.

Indeed, I using `flutter build linux`, sqflite works normal.

However, I added:

```
parts:
  colibri:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    stage-packages:
      - libsqlite3-0
```

to snap.yml, didn't work though. Don't know how to resolve this

**Comment by jmsilvadev** [comment]
Hi @jinfagang , for me using stage-packages works, but I use `libsqlite3-dev` instead of `libsqlite3-0`. See:
```parts:
  bots4coins:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    stage-packages:
    - sqlite3
    - libsqlite3-dev```

**Comment by jinfagang** [comment]
＠jmsilvadev Seems it doesn't raise sqlite.so not found error, But I got another exception:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(206)] Unhandled Exception: SqfliteFfiException(sqlite_error: 14, , open_failed: SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)} DatabaseException(open_failed: SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)) {}

```

**Comment by jinfagang** [comment]
I changed the ffi:

![image](https://user-images.githubusercontent.com/21303438/122716139-784d6000-d29c-11eb-854b-1db048759bd2.png)

**Comment by jmsilvadev** [comment]
The ffi is correct (see code below), this error maybe is related to the DB path or permissions to the DB path
```
if (Platform.isWindows || Platform.isLinux || Platform.isMacOS) {
      sqfliteFfiInit();
      databaseFactory = databaseFactoryFfi;
    }

**Comment by davidmartos96** [comment]
@jmsilvadev I remember having a similar error code with Sqlite FFI and the problem was that the directory didn't exist. Make sure that you create the target directory before opening the db.
You could use `Directory(somePath).create(recursive: true)`

**Comment by jmsilvadev** [comment]
@davidmartos96 this is exactly I said to @jinfagang :smile:
