### ISSUE TITLE
How can I open an exists databse in assets?

### ISSUE THREAD

**Issue by zhanlijia** [tekartik/sqflite#654]
Hi ,
I want to open the database in "asserts" dir , but it create an new databse in files/databases/......db
How can I open the exists databse in asserts?

project dir:
![image](https://user-images.githubusercontent.com/17610041/120188198-67cf3a00-c248-11eb-9647-37134d59c562.png)

pubspec.yaml:
![image](https://user-images.githubusercontent.com/17610041/120188261-79b0dd00-c248-11eb-8d4e-8fc8cf7a0732.png)

**Comment by alextekartik** [comment]
You cannot open an asset file directly (on some device it might not be a file). You have to copy it first, then open it. Look at the document for [opening an asset database](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_asset_db.md)

**Comment by zhanlijia** [comment]
It works , Thank you!
