### ISSUE TITLE
Is there any way to check DB file is valid or not before open it?

### ISSUE THREAD

**Issue by aiaia** [tekartik/sqflite#656]
openDatabase is not good for checking the validity, because it creates new DB and overwrite if invalid.
databaseExists returns true when the file exists, it doesn't care the file is DB or not.
Is there any way?

**Comment by alextekartik** [comment]
I think one solution is to open it in read-only mode and call getVersion on it.

**Comment by aiaia** [comment]
@alextekartik
your solution works fine on android!
but on iOS, getVersion returns 0 even though it's not a db file.
so, i added to check the result of rawQuery(SELECT name FROM sqlite_master), which works fine so far. thank you!
(by the way, your icon looks like David Bowie. cool!)

**Comment by alextekartik** [comment]
Thanks. That is indeed good to know.

The blurry picture is like 10 years old...I wish I could look like Bowie
