### ISSUE TITLE
the bind value at index is null

### ISSUE THREAD

**Issue by iulian0512** [tekartik/sqflite#657]
On android i cannot do a query like` db.rawQuery("update foo set col1=?",[null]) `it crashes with the bind value at index 1 is null.
i searched the docs there is no mention that null is not supported. 
how can i update col1 with null withoud explicitly puttin col1=null in the query string?

**Comment by alextekartik** [comment]
That is weird indeed. However you are using `rawQuery` to perform an update which can cause some issue on some platforms (android being one). Can you try using `rawUpdate` instead?

**Comment by iulian0512** [comment]
works ok with rawUpdate , thanks for the quick response.
