### ISSUE TITLE
can't launch the app in release mode after using sqflite_sqlcipher 2.0.0 

### ISSUE THREAD

**Issue by ahzmie** [tekartik/sqflite#658]
After I used sqflite_sqlcipher 2.0.0  the app started to crash when in release mode throwing the following crash message: 

PS: The app works well in debug mode

> `
No pending exception expected: java.lang.NoSuchFieldError: no "J" field
"mNativeHandle" in class "Lnet/sqlcipher/database/SQLiteDatabase;" or its superclasses
F/Mobile.roshett(20635): runtime.cc:582]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, jav
a.lang.ClassLoader) (Runtime.java:-2)
F/Mobile.roshett(20635): runtime.cc:582]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lan
g.String) (Runtime.java:1014)
F/Mobile.roshett(20635): runtime.cc:582]   at void io.flutter.plugins.GeneratedPluginRegistrant.registerWith(io.f
lutter.embedding.engine.a) (:-1)
F/Mobile.roshett(20635): runtime.cc:582]   at void android.app.Activity.performCreate(android.os.Bundle, android.
os.PersistableBundle) (Activity.java:7327)
F/Mobile.roshett(20635): runtime.cc:582]   at void android.app.Instrumentation.callActivityOnCreate(android.app.A
ctivity, android.os.Bundle) (Instrumentation.java:1271)
F/Mobile.roshett(20635): runtime.cc:582]   at android.app.Activity android.app.ActivityThread.performLaunchActivi
ty(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:3096)
F/Mobile.roshett(20635): runtime.cc:582]   at void android.app.ActivityThread$H.handleMessage(android.os.Message)
 (ActivityThread.java:1950)
`

I added 
`
-keep class net.sqlcipher.** { *; }
`
`
-keep class net.sqlcipher.database.**{*;}`

in proguard-rules but I still get the app crashing in release mode only.

**Comment by davidmartos96** [comment]
@ahzmie That error is most likely due to the minification and shrinking on release mode. Double check the Proguard configuration, you may have a typo or it's in the wrong folder.

**Comment by ahzmie** [comment]
> @ahzmie That error is most likely due to the minification and shrinking on release mode. Double check the Proguard configuration, you may have a typo or it's in the wrong folder.

Thank you so much. I stopped the minification and shrinking on release mode. I also connected the Proguard rules to Proguard Android and it worked.
