### ISSUE TITLE
how to get sqlite db file?

### ISSUE THREAD

**Issue by zinwalin** [tekartik/sqflite#66]
Since failed to access sqlite with Stetho and sqflite, is it possible to dump sqlite db file to computer for access?

**Comment by alextekartik** [comment]
In Android Studio (> 3.0.1)
* Open `Device File Explorer via View > Tool Windows > Device File Explorer`
* Go to `data/data/[PACKAGE_NAME]/app_flutter`, where PACKAGE_NAME is the name of your package.
  Location might depends how the path was specified (assuming here that are using path_provider to get its direction)
* Right click on the database and select Save As.... Save it anywhere you want on your PC.

Don't know about iOS but I'm pretty sure it might be accessible somehow too

**Comment by zinwalin** [comment]
@alextekartik thank u so much.

**Comment by 6heads** [comment]
I'm trying to access a virtual device this way but it doesn't seem to work. I already tried this: https://stackoverflow.com/questions/49340436/error-initializing-adb-unable-to-create-debug-bridge-unable-to-start-adb-serve

And then I read this: https://stackoverflow.com/questions/51460920/error-initializing-adb-android-debug-bridge-not-found?noredirect=1&lq=1
It seems to me, that this works only with a physical device, right?

How would I obtain the database from a virtual device?

**Comment by fadhlisulaimi** [comment]
@6heads try this

var db = await openDatabase('pathyouset/yourdbname.db');
import sqflite package to any of your dart file then use the code above. Then put a debug point after this code and analyze 'db'. There will be 'path' property which shows the full path. 

I have copied it successfully to my desktop but when i open the file with sqlitebrowser, it's empty. What's weird is, if I get the count for one of the tables programatically, there's data.
