### ISSUE TITLE
windows release cannot find the database path

### ISSUE THREAD

**Issue by zhibaiwei** [tekartik/sqflite#664]
Everything is OK in debug state. The release version is also normal. But move the file location and run exe again. Error, database not found

**Comment by alextekartik** [comment]
I guess it depends what is the location of your database. I suggest using path_provider to set the proper location of the database on Windows.

I'm not sure what you mean by "move the file location". Do you mean the executable only? (I guess you need to move the required dll with it)

**Comment by zhibaiwei** [comment]
@alextekartik  Thank you very much for your reply. The problem has been solved! Thank you
