### ISSUE TITLE
Not support M1 mac while run on ios simulator

### ISSUE THREAD

**Issue by sunjianan9900** [tekartik/sqflite#670]
```
Ld /Volumes/Jianan/M1PRO/Library/Developer/DerivedData/Runner-fctjuspyeptjeehbapjjnwszpdli/Build/Products/Debug-iphonesimulator/sqflite/sqflite.framework/sqflite normal (in target 'sqflite' from project 'Pods')
    cd /Volumes/Jianan/Work\ Project/Work/myios/2021/untitled2/ios/Pods
    /Volumes/Jianan/M1PRO/APPS/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios10.0-simulator -dynamiclib -isysroot /Volumes/Jianan/M1PRO/APPS/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -L/Volumes/Jianan/M1PRO/Library/Developer/DerivedData/Runner-fctjuspyeptjeehbapjjnwszpdli/Build/Products/Debug-iphonesimulator/sqflite -F/Volumes/Jianan/M1PRO/Library/Developer/DerivedData/Runner-fctjuspyeptjeehbapjjnwszpdli/Build/Products/Debug-iphonesimulator/sqflite -F/Volumes/Jianan/SDK/BETA/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-x86_64-simulator -F/Volumes/Jianan/M1PRO/Library/Developer/DerivedData/Runner-fctjuspyeptjeehbapjjnwszpdli/Build/Products/Debug-iphonesimulator/FMDB -filelist /Volumes/Jianan/M1PRO/Library/Developer/DerivedData/Runner-fctjuspyeptjeehbapjjnwszpdli/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite.build/Objects-normal/x86_64/sqflite.LinkFileList -install_name @rpath/sqflite.framework/sqflite -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Volumes/Jianan/M1PRO/Library/Developer/DerivedData/Runner-fctjuspyeptjeehbapjjnwszpdli/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite.build/Objects-normal/x86_64/sqflite_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -framework Flutter -framework FMDB -framework Foundation -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Volumes/Jianan/M1PRO/Library/Developer/DerivedData/Runner-fctjuspyeptjeehbapjjnwszpdli/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite.build/Objects-normal/x86_64/sqflite_dependency_info.dat -o /Volumes/Jianan/M1PRO/Library/Developer/DerivedData/Runner-fctjuspyeptjeehbapjjnwszpdli/Build/Products/Debug-iphonesimulator/sqflite/sqflite.framework/sqflite

ld: warning: ignoring file /Volumes/Jianan/M1PRO/Library/Developer/DerivedData/Runner-fctjuspyeptjeehbapjjnwszpdli/Build/Products/Debug-iphonesimulator/FMDB/FMDB.framework/FMDB, building for iOS Simulator-x86_64 but attempting to link with file built for iOS Simulator-arm64
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FMDatabaseQueue", referenced from:
      objc-class-ref in SqflitePlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (3 available)

**Comment by alextekartik** [comment]
Thanks for the report. Unfortunately I don't have a Mac M1 to investigate the issue. The iOS/MacOS implementation uses FMDB and I cannot tell whether it supports M1 or whether any update is needed at this point. Any clue is welcome...

**Comment by sunjianan9900** [comment]
> Thanks for the report. Unfortunately I don't have a Mac M1 to investigate the issue. The iOS/MacOS implementation uses FMDB and I cannot tell whether it supports M1 or whether any update is needed at this point. Any clue is welcome...

I found that set target to ios 11+ can fix this
because there's no armv7 after ios11

**Comment by xx-li** [comment]
same for me， but set target to ios 11+ not fix this。 this error is because of x86_64，not armv7

**Comment by xx-li** [comment]
at `sqflite/ios/sqflite.podspec` file,  contains line:
`s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }`
why set simulator archticture to x86_64?

**Comment by ForgetAll** [comment]
> 

any solution?

**Comment by ForgetAll** [comment]
> at `sqflite/ios/sqflite.podspec` file, contains line: `s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }` why set simulator archticture to x86_64? @alextekartik

Any solution?

**Comment by alextekartik** [comment]
Unfortunately I still don't have a M1 to test this.

**Comment by xx-li** [comment]
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
    end
  end
end
```
add this at podfile can fix it，if not work，check project setting  options `EXCLUDED_ARCHS` same of pod setting。

[M1设备的Xcode编译问题深究](https://juejin.cn/post/7037037120158269448) Its principle is introduced

**Comment by ForgetAll** [comment]
> ```ruby
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
>     end
>   end
> end
> ```
> 
> add this at podfile can fix it，if not work，check project setting options `EXCLUDED_ARCHS` same of pod setting。
> 
> [M1设备的Xcode编译问题深究](https://juejin.cn/post/7037037120158269448) Its principle is introduced

Finally I set alias for pod install => arch -x86_64 pod install, then project can run. I think the best soultion is to build arm64 lib for iOS simulator which run on M1 cpu.I'm an Android and Golang developer, not know iOS project how to build it's lib well.
