### ISSUE TITLE
get tables list

### ISSUE THREAD

**Issue by Leeeeerich** [tekartik/sqflite#672]
Hey! I don't understand, how I can get all tables list? Because "execute" does not return values.

**Comment by alextekartik** [comment]
You should use `query` if you expect a result. SQLite has a `sqlite_master` table that can be queried: https://www.sqlite.org/schematab.html

See https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#list-existing-tables

### List existing tables

This will print all existing tables, views, index, trigger and their schema (`CREATE` statement).
You might see some system table (`sqlite_sequence` as well as `android_metadata` on Android)


````dart
print(await db.query("sqlite_master"));
````
