### ISSUE TITLE
Will onUpgrade called multiple times if version in-between is skipped?

### ISSUE THREAD

**Issue by sukhcha-in** [tekartik/sqflite#674]
User installs app with DB version 1

We provide an update with version 2 and user **doesn't** update to version 2

We provide another update with version 3 and user with version 1 updates the app with db version 3.

Will onUpgrade method call for 2 times?

```
if (oldVersion == 1) {
//Add column updatedAt
} else if(oldVersion == 2) {
//Add column description
}
```

In above example my version 2 adds `updatedAt` column to DB. Then version 3 adds `description` column.

Skipping from version 1 to 3 will still create `updatedAt` column or I do have to define that again in `oldVersion == 2`?

**Comment by sukhcha-in** [comment]
@alextekartik Please answer this whenever you get some time.

**Comment by alextekartik** [comment]
Indeed you have to handle the case where the user might have skipped some of your published version.
`onUpgrade` will be called once with `oldVersion = 1` and `newVersion = 3` in your scenario. Possible solution for your algorithm to handle all cases:

```
if (oldVersion == 1) {
  // Add column updatedAt
} 
// No else here!
if (oldVersion <= 2) {
  // Add column description
}
```

**Comment by sukhcha-in** [comment]
Thank you for your clarification.
