### ISSUE TITLE
 unimplementederror:  sqfliteFfiInit only for io application

### ISSUE THREAD

**Issue by bksubhuti** [tekartik/sqflite#679]
The library says it supports web, but it fails on  
sqfliteFfiInit();

Using the mydbtest app repo, I hardcoded "true" to run the  sqfliteFfiInit(); segment.
**unimplementederror: sqfliteFfiInit only for io application**

without running the desktop code for sqfliteffiinit,  it runs the mobile code and I get the this error:
**Error: Unsupported operation: Platform._operatingSystem**

**Comment by alextekartik** [comment]
Unfortunately there is no good way (that I am aware of) to advertise which platforms are supported or not supported. See https://github.com/dart-lang/pub/issues/2353

Web is [not supported](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/web_support.md)

**Comment by bksubhuti** [comment]
Sorry to open this again. I think it is possible to know what is supported and what is not supported. The only platforms that should be listed are the ones that have been tested on.
I think that we can say good things about android, ios, mac , linux, & windows.
I think it is known.. or known now.. that web is not supported and there are reasons for multiuser support and record locking and loading db on the client side over the net versus, the server side. So there are reasons why it is not supported.

**Comment by alextekartik** [comment]
> The only platforms that should be listed are the ones that have been tested on.

Currently there is no way to control the platform listed on pub.dev. See https://github.com/dart-lang/pub/issues/2353

**Comment by bksubhuti** [comment]
Yes.. i see the issue you listed this time.   I did not fully understand your response.  The reason I thought this was possible is because sqflite does not list everything.  See pic below.
Perhaps there is only a mobile/desktop checkbox for devs to specify.

In either case.. the pub.dev description should be able to say whatever one wants.

![image](https://user-images.githubusercontent.com/18184280/129003473-ce42bee9-209d-4a3a-b9d1-751246f51550.png)

**Comment by alextekartik** [comment]
sqflite itself only supports Android, iOS and MacOS as stated. Windows/Linux supports is provided by [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi) as specified in the beginning of the description - but if you look at the supported platforms for sqflite_common_ffi, it incorrectly says that web is supported. I know it is kind of weird but Desktop support works on flutter and also on DartVM so unlike sqflite it is not a regular flutter plugin and I don't want to add a dependency on sqfite_common_ffi for people that only wants mobile support. I understand you specific needs but some people also want SQLcipher supports or use [specific flutter libs](https://pub.dev/packages/sqlite3_flutter_libs) so i don't want to make choice that will satisfy some users and block other users.

**Comment by bksubhuti** [comment]
I trust you know these issues way better than me.  Perhaps put it on the first line of the sqflite_ffi description as a heads up ...  I will not instigate this further.  I appreciate your support for this very important plugin .  I agree  and understand that we support shoild be implemented differently.  Maybe one day a myfsql plugin will be made.
