### ISSUE TITLE
TRUNCATE TABLE

### ISSUE THREAD

**Issue by aravindhkumar23** [tekartik/sqflite#69]
is it possible to truncate the table? instead of deleting a single row.

**Comment by alextekartik** [comment]
Actually the `DELETE` statement can be used without a `WHERE` clause to act as a `TRUNCATE`on SQLite, see here:
https://www.sqlite.org/lang_delete.html

> The Truncate Optimization
> When the WHERE is omitted from a DELETE statement and the table being deleted has no triggers, SQLite uses an optimization to erase the entire table content without having to visit each row of the table individually. This "truncate" optimization makes the delete run much faster.

**Comment by aravindhkumar23** [comment]
Thanks @alextekartik 
I will use the Delete statement to delete all rows.
and how to use `singleInstance = false` can i have a example to implement it? 
I upgraded the package today and got struck with this single instance. any help pls?

**Comment by alextekartik** [comment]
Yes sorry for the singleInstance breaking change (but that's what most users want..). I've added an example to use the old behavior here:
https://github.com/tekartik/sqflite/blob/237d3af1afe5bacf1c1b66d4f5102aa79c5ee63c/example/lib/open_test_page.dart#L511-L538

basically:

```dart
openDatabase(singleInstance: false);
```

**Comment by aravindhkumar23** [comment]
Thanks, @alextekartik  for the sample code. I have opened the database and performed the operation with the single instance 
```
final Database insertdb = await databaseFactory.openDatabase(await getDatabasePath(),options:new OpenDatabaseOptions(singleInstance: true));
await insertdb.transaction((Transaction txn) async {
        await txn.rawDelete('DELETE FROM mytablename');
})
```
