### ISSUE TITLE
Error message printed is too long when a BLOB is involved

### ISSUE THREAD

**Issue by Zarainia** [tekartik/sqflite#690]
When an error is encountered while doing a database operation involving a BLOB, the entire contents are printed in list format in the error message, overloading normal terminal history limits and making it difficult to see what the original error was. I would suggest not printing the entirety of BLOB arguments.

**Comment by alextekartik** [comment]
Thanks for the report. I'll look into it

**Comment by alextekartik** [comment]
This should be fixed in `sqflite_common` (used by sqflite, just do a flutter pub upgrage). Blob data will be replaced by `Blob(<length>)` in the exception message.

**Comment by Zarainia** [comment]
Works great, thanks!
