### ISSUE TITLE
getDatabasesPath() returns incorrect Directory on iOS

### ISSUE THREAD

**Issue by guymclean** [tekartik/sqflite#695]
Database files should be persistent, backed up, and not visible to the user. The most appropriate location therefore on iOS would be the Library directory. This thinking is confirmed in the documentation for the getLibraryDirectory() function in the path_provider package https://pub.dev/documentation/path_provider/latest/path_provider/getLibraryDirectory.html.

getDatabasesPath (https://pub.dev/documentation/sqflite/latest/sqflite/getDatabasesPath.html) however returns the Documents directory, which is not the most appropriate location for storing database files as regular users of the app can see them in their phone's file explorer. Please consider changing this behaviour, or explain why this decision was made.

**Comment by alexinventhys** [comment]
Thanks for the report.

Unfortunately this decision (I could not find specific recommendations when starting the project) was made at the beginning as a placeholder location. We cannot safely change the behavior as it would break all existing apps so we will have to live with the behavior. Indeed using `path_provider` to find the best location is the way to go, then you can change it for you entire apps with something like:
```dart
await databaseFactory.setDatabasesPath(<your_location>);
```
Or you can use on absolute path in `openDatabase()`.

In fact `getDatabasesPath()` only makes sense on Android as the API is largely inspired by the Android Database API. Maybe adding some recommendation in the docs for iOS to use `path_provider` would help. PR are welcome if I don't tackle this soon.

**Comment by alextekartik** [comment]
Thanks for the report.

Unfortunately this decision (I could not find specific recommendations when starting the project) was made at the beginning as a placeholder location. We cannot safely change the behavior as it would break all existing apps so we will have to live with the behavior. Indeed using `path_provider` to find the best location is the way to go, then you can change it for you entire apps with something like:
```dart
await databaseFactory.setDatabasesPath(<your_location>);
```
Or you can use on absolute path in `openDatabase()`.

In fact `getDatabasesPath()` only makes sense on Android as the API is largely inspired by the Android Database API. Maybe adding some recommendation in the docs for iOS to use `path_provider` would help. PR are welcome if I don't tackle this soon.

**Comment by guymclean** [comment]
Okay, understood. Yes it would probably be worth adding something to the documentation explaining this, cheers.
