### ISSUE TITLE
Support for cursors

### ISSUE THREAD

**Issue by ryanheise** [tekartik/sqflite#698]
I'd like to iterate over a result set with millions of rows, which is not feasible with the current API which loads the entire result set into memory before iteration can begin.

A cursor-based API could potentially be made with [BidirectionalIterator](https://api.dart.dev/stable/2.14.2/dart-core/BidirectionalIterator-class.html).

**Comment by alextekartik** [comment]
With the way flutter plugins are designed, that is not easily feasible as it requires asynchronous remote calls to the native side while you might expect synchronous cursor calls. Performance might be bad too.

However cursor might be possible using sqlite3 package that uses ffi and synchronous calls to the native layer.

**Comment by ryanheise** [comment]
Platform communication has been made more efficient in Flutter 2.5, and you could implement a look-ahead buffer to make it more efficient.

**Comment by alextekartik** [comment]
Even with a more efficient communication, we cannot have a synchronous API to transfer data from native to dart land. remote procedure calls remains asynchronous. So we still have to fetch some page of results (transferring rows one at a time will definitely be very slow).

I could imagine an API like that (yes that is not what you might expect) assuming the native side implements at least `moveNext`
```dart
/// Select API
abstract class PageCursorDatabase {
  /// Executes a raw SQL SELECT query and returns a cursor.
  ///
  /// [pageSize] specified the size of the first page of result, if null, all rows
  /// are fetched.
  ///
  /// Cursor must be closed.
  Future<PageSelectCursor> rawSelectPage(String sql, List<Object?>? arguments,
      {int? pageSize});
}

/// Select Cursor.
abstract class PageSelectCursor {
  /// The data of the current page.
  /// If empty, the end of the cursor is reached.
  List<Map<String, Object?>> get rows;

  /// Move next, skipping [skipCount] if specified, up to [pageSize] rows.
  Future<PageSelectCursor> moveNext({int? skipCount, int? pageSize});

  /// Close a cursor, not closing it will result in memory leaks on the
  /// native side.
  Future<void> close();
}
```

On android, where you can navigate in a cursor, the user could fetch page of results from a cursor (instead of doing moveNext):
```dart
/// Select API
abstract class CursorDatabase {
  /// Executes a raw SQL SELECT query and returns a cursor.
  ///
  /// Cursor must be closed.
  Future<SelectCursor> rawSelect(String sql, [List<Object?>? arguments]);
}

/// Select Cursor.
abstract class SelectCursor {
  /// Cursor total row count
  int get count;

  /// Fetch cursor data at the give offset and limit.
  Future<List<Map<String, Object?>>> fetch({int? offset, int? limit});

  /// Close a cursor, not closing it will result in memory leaks on the
  /// native side.
  Future<void> close();
}
```

Both solution would not work on iOS yet as FMDB does not expose a cursor API, so we'll have access sqlite directly with some weird workaround (some iOS implementation are not thread safe). For sqflite_ffi implementation, sqlite3 does not export cursor yet but I guess that could be added.

**Comment by ryanheise** [comment]
I don't think a synchronous API is required and this shouldn't be an obstacle to providing a look-ahead buffer over asynchronous platform channels under the hood. A look-ahead buffer fetches the next N rows when the client only requested the next row, then for the next N-1 rows it reads from the internal look-ahead buffer. So a batch of N rows can be sent over the platform channels at once for efficiency. A look-ahead buffer can be completely internal and doesn't need to be exposed in the API (aside from perhaps configuring the size of the look-ahead buffer). For the thread safety issue, you could document that cursors are not thread safe. It's the app's choice whether it decides to. deal with that limitation to avoid an even worse memory limitation that would happen without a cursor.

Regarding sqlite3, I did make a feature request yesterday and it was already implemented in the latest git commit, so I'll use that, but still think a traditional cursor API could be implemented for sqflite with a look-ahead buffer.

**Comment by alextekartik** [comment]
Yes I understand, but it means that `moveNext` must be asynchronous (i.e. not a traditional cursor API as you said) as it might either use the value from memory, either fetch from the native land. Could you share the API you have in mind for this? (i.e. the user should be able to specify the row cache count)?

**Comment by ryanheise** [comment]
If it's asynchronous, then I guess the API could be represented by a stream (which is the case for file I/O).

**Comment by alextekartik** [comment]
Ok I see but I thought you wanted to control (through an iterable or moveNext) the cursor. The stream gives you no control of that (besides cancelling). The only benefit I see is that you will get the first row slightly faster but then you will get everything so unless you cache in memory or cancel soon enough (likely too late, sqflite runs in a separate thread so even a cancel might be received once all the data has been loaded), data will be transmitted anyway. This does not provide cursor support as you ask for. This is a big work (especially a full rewrite on iOS, FMDB - popular on iOS - has a similar API to sqflite without cursor support) so precise suggestion (event better a full API interface) are welcome before I tackle this issue since nobody asked for it so far.

**Comment by ryanheise** [comment]
> Ok I see but I thought you wanted to control (through an iterable or moveNext) the cursor.

Since you pointed out correctly that it needs to be async, an iterable won't work. You could create an async version of `Iterable` (using a look-ahead buffer internally):

```dart
class SqfliteCursor {
  Future<bool> moveNext() { ... }
  Row get current { ... }
}
```

But you could also implement this same functionality with a stream by having the stream internally keep a look-ahead buffer of the next N rows, and then to fetch the next batch of N after the last row in the current batch is consumed. Then you could iterate over it like this:

```dart
await for (var row in result) {
  ...
}
```

That's all I meant to suggest in my previous comment, although doing something like `SqfliteCursor` is probably more recognisable as a cursor.

**Comment by alextekartik** [comment]
Ok I see the stream usage. II think the N variable (i.e. the cache size) should be a parameter. You might not want the same N if you query table with big records vs small records. a bigger N giving better overall performance but bigger memory usage and it is hard to make a good default guess. It is likely that we will always have N*2 rows in memory.

What could be the name of this N parameter. I propose `pageSize` but it could but `rowCacheCount`.

So we could have an API like that:
```dart
  /// Executes a raw SQL SELECT query and stream the result rows.
  ///
  /// [pageSize] specified the size of the cache, if null, all rows
  /// are fetched and cached.
  Stream<Map<String, Object?>> rawSelect(String sql, List<Object?>? arguments,
      {int? pageSize});
```

The good thing is that if the native side does not implement it (android, ios, linux, mac, windows, sqflite_cipher too) have to be supported), we could create the whole stream in memory using the existing implementation, which could allow for an incremental implementation for the various platforms.

**Comment by hotlittlewhitedog** [comment]
@ryanheise Why do you want to iterate millions of rows?  
I had a similar question (not millions but thousands) and came to the same conclusion: use a cursor.  
But it's a wrong question because you probably don't want to display all of them :)
If you use execute() you should be able to manage them.  
Finally I used 'Attach db' cmd and it seems it works great.

**Comment by ryanheise** [comment]
My purpose is just to do processing on a large number of rows by iterating over them, not to display any of them.

**Comment by linsvensson** [comment]
Any updates on this?

**Comment by alextekartik** [comment]
Not yet sorry. Generic cursor will likely not be supported. And i did not get a response whether having something like:

```dart
  /// Executes a raw SQL SELECT query and stream the result rows.
  ///
  /// [pageSize] specified the size of the cache (row count), if null, all rows
  /// are fetched and cached.
  Stream<Map<String, Object?>> rawSelectStream(String sql, List<Object?>? arguments,
      {int? pageSize});
```

is a possible solution of the original problem and whether it could be useful for others.

**Comment by alextekartik** [comment]
Ok so I made a solution for the original issue:

> I'd like to iterate over a result set with millions of rows

The solution is a new api badly named `Database.rawQueryByPage()`. The implementation is not that obvious as it requires maintaining a cursor (with the risk of not closing it that I don't want to take). The results are sent in a callback until you return false.

It is only implemented on ffi for now, for others the API works but no cursor is used and the whole query is loaded in memory so you won't get any benefit.

Below is a usage example:
```dart
await db.rawQueryByPage(
  // The query
  'SELECT * FROM Product',
  // The arguments
  null,
  QueryByPageOptions(
    // Read from the cursor 10 by 10
    pageSize: 10,
    resultCallback: (page) {
      // Read the list of results by page
      // Don't spend too much time here and don't call another sqflite function
      // The function can be asynchronous though.
      for (var item in page) {
        // ...
      }
      // return true to continue, false for cancel
      return true;
    }));
```
Publish in sqflite_common_ffi: 2.2.0-dev.2

@ryanheise let me know if that answer your needs.

**Comment by ryanheise** [comment]
I am in no rush to have a published solution so I would also be interested in the other participants' feedback.

I think for me the API looks like it should work, although as you say the API naming/etc. could possibly undergo revisions based on the feedback.

I wonder if it could be more convenient to just make `rawQueryByPage` return an object that allows the client to move through the pages (rather than having a callback). That would probably be an easier API to work with.

**Comment by alextekartik** [comment]
The main goal here was to allow fetching millions of rows without having memory issues.
However it is not convenient and the database will remain locked until fetching everything so if http calls are needed or other lengthy operation that is not good indeed...

> I wonder if it could be more convenient to just make rawQueryByPage return an object that allows the client to move through the pages (rather than having a callback). That would probably be an easier API to work with.

You are definitely right so I ended up adding basic cursor support (moveNext/current/close). The main advantages is that you can have multiple cursor opened and could perform long operation without locking the database.

The only drawback is that you have to close the cursor (or reach the end with moveNext) which could lead to memory leaks...but well, we are developers.

Then even worst named API `Database.rawQueryByPageCursor()` - maybe should I name it `selectCursor` to match ffi name - to be used like this:

```dart
// Query cursor
var cursor = await db.rawQueryByPageCursor(
  'SELECT * FROM Product',
  null,
  pageSize: 10,
);
try {
  while (await cursor.moveNext()) {
    var row = cursor.current;
    // ...
  }
} finally {
  // Important don't forget to close the cursor in case any exception is thrown before
  await cursor.close();
}
```

Published in sqflite_common_ffi: 2.2.0-dev.3.

**Comment by ryanheise** [comment]
Looks good to me. I don't mind too much about the name, although I think that the word "page" may make less sense now that the API iterates over rows rather than pages. That includes the method name and the parameter name. Also, maybe the word "page" has a different meaning in SQLite so it could be best to avoid confusion:

https://www.sqlite.org/fileformat.html (Section 1.2)

@linsvensson , @hotlittlewhitedog , please feel free to comment on this new feature also.

My suggestions for names are:

- method name: `queryCursor` and `rawQueryCursor`
- parameter name: `bufferSize`

**Comment by alextekartik** [comment]
Thanks @ryanheise I like your suggestion. For bufferSize, I'd like to make it optional and use a default value to 100 (completely arbitrary but definitely needed).
I will keep the previous APIs described above but will deprecate them and remove them soon

**Comment by alextekartik** [comment]
@ryanheise I renamed as you proposed and implemented it in sqflite (Android/iOS/MacOS) and sqflite_ffi (Desktop, Mobile and Web). Still published as dev for now (I'm a poor iOS developer)

Let me know if that works for you.

**Comment by alextekartik** [comment]
Published as stable
