### ISSUE TITLE
What version of Sqlite is this plugin built upon? Does this support JSON1 extension of Sqlite?

### ISSUE THREAD

**Issue by jagan999** [tekartik/sqflite#70]

**Comment by alextekartik** [comment]
Sqflite does not include SQLite itself, it uses whatever the platform (Android, iOS) provides. I could not find the details of what each built-in version includes (for example the version os SQLite for each Android OS version here https://developer.android.com/reference/android/database/sqlite/package-summary) but I doubt any of them include the json1 extension. The solution here would be to embed the sqlite library for each platform and architecture which is not the goal of sqflite at this point.
