### ISSUE TITLE
No pending exception expected: java.lang.NoSuchFieldError: no "J" field "mNativeHandle" in class "Lnet/sqlcipher/database/SQLiteDatabase;" or its superclasses

### ISSUE THREAD

**Issue by dbirkheuer** [tekartik/sqflite#704]
I'm getting the following error below when opening the release application. Any idea what it might be and how I can fix it?

```
2021-09-29 17:29:46.133 12654-12654/br.com.retta.castilho.ccdc A/a.castilho.ccd: thread.cc:2365] No pending exception expected: java.lang.NoSuchFieldError: no "J" field "mNativeHandle" in class "Lnet/sqlcipher/database/SQLiteDatabase;" or its superclasses
    thread.cc:2365]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.Class) (Runtime.java:-2)
    thread.cc:2365]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:1121)
    thread.cc:2365]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1075)
    thread.cc:2365]   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:998)
    thread.cc:2365]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1656)
    thread.cc:2365]   at void net.sqlcipher.database.SQLiteDatabase$a.a(java.lang.String[]) (SQLiteDatabase.java:2)
    thread.cc:2365]   at void net.sqlcipher.database.SQLiteDatabase.y(android.content.Context, java.io.File, net.sqlcipher.database.SQLiteDatabase$e) (SQLiteDatabase.java:1)
```

**Comment by davidmartos96** [comment]
@dbirkheuer 
You are missing the Proguard config for SQLCipher. You can follow the readme of the sqflite_sqlcipher package on pub.dev

**Comment by dbirkheuer** [comment]
Hi, yes, this solved my problem. I ended up adding this package due to another package needing it and I ended up not even looking at the README. Thank you very much.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/33560861/135446058-e8f6e82e-7d12-48f1-a023-638e87487ede.png">

**Comment by pedropastor** [comment]
Hi , I added the proguard rule and still got the problem. Any other situations this may happen??

pro-guard:
`...

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer
-keep class net.sqlcipher.** { *; }

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
...`

Exception:

> No pending exception expected: java.lang.NoSuchFieldError: no "J" field "mNativeHandle" in class "Lnet/sqlcipher/database/SQLiteDatabase;" or its superclasses
    thread.cc:2468]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.Class) (Runtime.java:-2)
    thread.cc:2468]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:1121)
    thread.cc:2468]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1075)
    thread.cc:2468]   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:998)
    thread.cc:2468]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1661)
    thread.cc:2468]   at void net.sqlcipher.database.SQLiteDatabase$a.a(java.lang.String[]) (:-1)
    thread.cc:2468]   at void net.sqlcipher.database.SQLiteDatabase.b0(android.content.Context, java.io.File, net.sqlcipher.database.SQLiteDatabase$e) (:-1)
    thread.cc:2468]   at void net.sqlcipher.database.SQLiteDatabase.a0(android.content.Context, java.io.File) (:-1)
    thread.cc:2468]   at void net.sqlcipher.database.SQLiteDatabase.Z(android.content.Context) (:-1)
    thread.cc:2468]   at void k0.c.z(android.content.Context, s4.b) (:-1)
    thread.cc:2468]   at void k0.c.onAttachedToEngine(j4.a$b) (:-1)
    thread.cc:2468]   at void io.flutter.embedding.engine.c.e(j4.a) (:-1)
    thread.cc:2468]   at void io.flutter.plugins.GeneratedPluginRegistrant.registerWith(io.flutter.embedding.engine.a) (:-1)
    thread.cc:2468]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
    thread.cc:2468]   at void p4.a.a(io.flutter.embedding.engine.a) (:-1)
    thread.cc:2468]   at void io.flutter.embedding.android.d.C(io.flutter.embedding.engine.a) (:-1)
    thread.cc:2468]   at void cl.homachile.homa2c.MainActivity.C(io.flutter.embedding.engine.a) (:-1)
    thread.cc:2468]   at void io.flutter.embedding.android.e.p(android.content.Context) (:-1)
    thread.cc:2468]   at void io.flutter.embedding.android.d.onCreate(android.os.Bundle) (:-1)
    thread.cc:2468]   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:8163)
    thread.cc:2468]   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:8130)
    thread.cc:2468]   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1330)
    thread.cc:2468]   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:3744)
    thread.cc:2468]   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3938)
    thread.cc:2468]   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:103)
    thread.cc:2468]   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:135)
    thread.cc:2468]   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:95)
    thread.cc:2468]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2291)
    thread.cc:2468]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
    thread.cc:2468]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:210)
    thread.cc:2468]   at void android.os.Looper.loop() (Looper.java:299)
    thread.cc:2468]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8319)
2022-10-21 12:15:43.319 24107-24107/? A/omachile.homa2: thread.cc:2468]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
    thread.cc:2468]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:556)
    thread.cc:2468]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1038)
    thread.cc:2468] 
2022-10-21 12:15:43.402 24196-24196/? E/.xiaomi.mipick: Not starting debugger since process cannot load the jdwp agent.
2022-10-21 12:15:43.453 24107-24107/? A/omachile.homa2: runtime.cc:675] Runtime aborting...
    runtime.cc:675] All threads:
    runtime.cc:675] DALVIK THREADS (35):
    runtime.cc:675] "main" prio=10 tid=1 Runnable
    runtime.cc:675]   | group="" sCount=0 ucsCount=0 flags=2 obj=0x71f1cab8 self=0xb400007ae0fb9800
    runtime.cc:675]   | sysTid=24107 nice=-10 cgrp=default sched=0/0 handle=0x7ae26164f8
    runtime.cc:675]   | state=R schedstat=( 120548858 38944111 287 ) utm=6 stm=5 core=6 HZ=100
    runtime.cc:675]   | stack=0x7fcd67c000-0x7fcd67e000 stackSize=8188KB
