### ISSUE TITLE
can we use file extension .sqlite instead of .db

### ISSUE THREAD

**Issue by NIkos77-cloud** [tekartik/sqflite#714]
I want to access downloaded .sqlite file directly as database file

**Comment by alextekartik** [comment]
The extension of the file can be whatever you want when using SQLite api. `.db` is just a convention I guess for desktop association between the file and an app such as sqlite browser. Since a database is just a file, you can access it like a regular file (though I recommend closing it first).

**Comment by NIkos77-cloud** [comment]
@alextekartik  Thanks for your response
