### ISSUE TITLE
Not working on Windows when run from a Windows installer

### ISSUE THREAD

**Issue by whiplashoo** [tekartik/sqflite#718]
Trying to get this to work in release mode for Windows with no luck, even after following the advice [here](https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md). 

In my init database process, I have the following, with a special case handler for the Windows platform:

```dart
import 'dart:ffi';
import 'dart:io';

import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';
import 'package:sqflite_common_ffi/src/windows/setup_impl.dart';
import 'package:sqlite3/open.dart';
import 'package:sqlite3/sqlite3.dart' as s3;

Future<Database> init() async {
    if (Platform.isWindows) {
      var location = findPackagePath(Directory.current.path);
      if (location != null) {
        var path = normalize(join(location, 'src', 'windows', 'sqlite3.dll'));
        open.overrideFor(OperatingSystem.windows, () {
          try {
            return DynamicLibrary.open(path);
          } catch (e) {
            stderr.writeln('Failed to load sqlite3.dll at $path');
            rethrow;
          }
        });
      }
      s3.sqlite3.openInMemory().dispose();
      databaseFactory = databaseFactoryFfi;
    }
    final dbPath = await getDatabasesPath();
    return await openDatabase(
      join(dbPath, 'shortcuts.db'),
      onCreate: (db, version) {
        final stmt = '''CREATE TABLE IF NOT EXISTS $tableName (
            id INTEGER PRIMARY KEY,
            ...
        )'''
            .trim();
        return db.execute(stmt);
      },
      version: 1,
    );
  }
```

I also have:

- Copied the `sqlite3.dll` file to in `build/windows/runner/Release`.
- Used the [msix](https://github.com/YehudaKremer/msix) package to create the MSIX installer, setting a config option to also include `sqlite3.dll` in the final product.
- Verified that the `sqlite3.dll` is included if I extract all the files from the installer.

The app works and the database is properly connected when I run it in debug, or in release mode, or by using the .exe file from the Release folder, or by using the .exe file from the extracted installer files.

However, it doesn't work when installed with the MSIX installer (the database hangs in loading state), which means I can't submit the app to the Windows Store (where an MSIX installer is expected).

Is there anything I am not doing right, regarding the use of `sqflite_common_ffi` and its Windows implementation? Could this be an issue with the database path?

**Comment by whiplashoo** [comment]
The issue was caused by the database path selection function, which didn't work properly for Windows. The solution was to use path_provider and get the path manually:

```dart
Future<String> getDatabasePath() async {
    if (Platform.isWindows) {
      var ref = await path.getApplicationSupportDirectory();
      return ref.path;
    } else {
      var dbPath = await getDatabasesPath();
      return dbPath;
    }
  } 
```

**Comment by SteveCruise** [comment]
Let me try your solution
