### ISSUE TITLE
unable to load sqflite package

### ISSUE THREAD

**Issue by pgfepale** [tekartik/sqflite#72]
Hi, 
I added dependencies in pubspec.yaml and also run flutter package get, import packages in my dart file.
everything fine till this.

but when I try to run the app it fails with below error.

`    FAILURE: Build failed with an exception.
    * What went wrong:
     Execution failed for task ':sqflite:platformAttrExtractor'.
    > A failure occurred while executing com.android.build.gradle.internal.actions.AttrExtractor
    > error in opening zip file`

**Comment by alextekartik** [comment]
I'm not sure which version of Flutter you are using. Do you have the same issue if you try another plugin (such as path_provider)? Have you checked the troubleshooting section here: https://github.com/tekartik/sqflite/blob/master/doc/troubleshooting.md?
