### ISSUE TITLE
insert operation not flushed to the DB?

### ISSUE THREAD

**Issue by pognibene** [tekartik/sqflite#725]
Hello,
In my flutter app, I use sqlflite.
I have a sequence like:
 ```
int rowid = await database.insert(
      'my_table',
      map,
    );
```
Immediately followed by a :
```
final List<Map<String, dynamic>> maps = await globals.database.query(
      'my_table',
      where: 'room_id = ? AND timestamp < ?',
      whereArgs: [roomId, dateString],
      orderBy: 'timestamp DESC',
      limit: pageSize);
```
This does not work as expected (most of the time). Even though a rowId is returned by the insert operation, when querying the table right after the new row is not part of the list.
If I delay the query operation by about 500ms (sometimes more), then the inserted row appears. It looks like the insert operation is asynchronous, and returns even though the new row is not written in the database?

is this the expected behavior? Any workaround I could apply so that I can immediately read back the inserted value?

Thank you!

**Comment by alextekartik** [comment]
> is this the expected behavior? 

This is definitely not an expected behavior unless:
- the query was started before the insert
- the dateString is dependent on the current time in your query and if it could not satisfy the inserted row. Maybe print the inserted map and dateString before the query to make sure the query will work for the newly added item (and work a little bit later if dateString has changed).

**Comment by pognibene** [comment]
Hi,
You are absolutely right : my problem was actually caused by slightly different clock time on different devices. As a consequence, the second request could not fetch the last row in the db, which had a timestamp in the future.
Sometimes all we need is a rubber duck to see what's right under your nose :-)

Thank you for your help, closing this issue.
