### ISSUE TITLE
Why you can't support bool?

### ISSUE THREAD

**Issue by tremp-m** [tekartik/sqflite#727]
This would be convenient, for example, when we can read data from a json file or from a database and get from this dto in one way - json_seriazable...

**Comment by UCetinkaya94** [comment]
sqlite is written in C and C does not have a built-in bool type

**Comment by alextekartik** [comment]
Per the SQLite doc: https://www.sqlite.org/datatype3.html

> SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).
