### ISSUE TITLE
Read from External Database (another app)

### ISSUE THREAD

**Issue by riccardocescon** [tekartik/sqflite#729]
Is it possible to read a database from a different app path?
For example my app path for the database is : `/data/user/0/com.myCompany.myAppName/databases/myDatabase`
and i want to copy some tables from my other app : `/data/user/0/com.myCompany.anotherMyApp/databases/anotherDatabase`

Is it possible? If not, is there a workaround for doing this?

**Comment by riccardocescon** [comment]
@alextekartik any update?

**Comment by alextekartik** [comment]
You cannot access other applications files. One solution on Android, non-Flutter, is to use a ContentProvider (i.e. not sqflite)

**Comment by riccardocescon** [comment]
Thanks, closing this issue
