### ISSUE TITLE
Renamig The Column name  in _onupgrade()  function

### ISSUE THREAD

**Issue by Shabeebcp** [tekartik/sqflite#743]
SqfliteDatabaseException (DatabaseException(near "COLUMN": syntax error (code 1): , while compiling: ALTER TABLE InvTransMaster RENAME COLUMN EmpID TO EmpPD) sql 'ALTER TABLE InvTransMaster RENAME COLUMN EmpID TO EmpPD' args [])

**Comment by alextekartik** [comment]
rename column is only supported in recent version of sqlite which might not be the case on your device.
