### ISSUE TITLE
add support for windows and linux, to work with flutter for desktop

### ISSUE THREAD

**Issue by insinfo** [tekartik/sqflite#746]
add support for windows and linux, to work with flutter for desktop
This will make development for android and ios much easier, so I can test the application by compiling directly to my machine without needing an emulator to test the application

**Comment by alextekartik** [comment]
Windows and linux are supported using `sqflite_common_ffi` (which is not flutter only, its works on desktop and dart VM too and supports unit tests). See explanation/setup here: https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md

**Comment by insinfo** [comment]
the ffi version has this inconvenience, having to worry about the dll is pretty bad, I thought that sqflite was pure dart, I didn't know it was directly dependent on the sqlite dynamic library, the ideal would be to have a solution that already embeds this

> Windows: You need to manually ship sqlite3 with your app

**Comment by alextekartik** [comment]
Many people have different requirement. Some want cipher support, some want to build their own sqlite library so it is hard to satisfy every need. I know it is not convenient. sqflite is not pure dart at all. On iOS, MacOS and Android it depends on the system implementation, Windows and Linux and DartVM use sqlite3 package. Currently windows should work as is during development when using ffi as a bundled sqlite3.dll is used during debug mode. Yes you need to copy manually the dll when building in release mode...

**Comment by clragon** [comment]
I am not really bothered by the dll file, but other packages I want to use, 
like `dio_http_cache` use this package so I cannot test on windows if I want to use them, which is a big deal for me.
(even worse with the _incredibly_ slow release cycle of `dio_http_cache`)

Is it not possible to combine the sqflite package and the `ffi` package into a single one?
to be perfectly hoenst I didnt quite understand the explanation you sent.

**Comment by alextekartik** [comment]
I'm not familiar dio_http_cache so cannot tell much about it and whether it could work (it is not advertised to work on Windows). Have you tried the steps I sent here? (copied below for convenience): https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md#setup

## Setup

First add the dependency:

```
dependencies:
  sqflite_common_ffi:
```

## Initialization

Then initialize ffi before running your app:

```dart
import 'package:sqflite_common_ffi/sqflite_ffi.dart';
import 'package:sqflite/sqflite.dart';

Future main() async {
  if (Platform.isWindows || Platform.isLinux) {
    // Initialize FFI
    sqfliteFfiInit();
    // Change the default factory
    databaseFactory = databaseFactoryFfi;
  }
  runApp(MyApp());
}
```

> Is it not possible to combine the sqflite package and the ffi package into a single one?

It will add more dependency that not everybody wants. Maybe another package could be created but I have not plan to create that at this point.

**Comment by clragon** [comment]
I am quite confident that `dio_http_cache` is only not tagged as working on windows because of its dependency on `sqflite`.

but I think I just realized that by adding the ffi package and changing the global database factory, 
its possible to basically add windows support from the outside.

Well this is awesome.
Ignore my request for a single package then, I think after understanding the structure here,
I do think that is unecessary.

Thank you for your help.

**Comment by alextekartik** [comment]
> its possible to basically add windows support from the outside.

That is my hope, however I'm interested in whether that works for you. You might also want to specify the database path (`databaseFactory.setDatabasesPath()`) on windows as by default it is some non-standard local path. You are pointing at a recurring issue so if I could specify the proper steps for this kind of issue, that would help for the next developer!

**Comment by clragon** [comment]
excuse my extremely late reply;

Works perfectly for me.
Setting the global database factory is definitely super helpful and makes it possible to test on windows.

However, I could neither locate the database by myself nor set the database path, as that seems to throw a Platform Exception error on windows, meaning that function is not implemented (?).

**Comment by alextekartik** [comment]
> However, I could neither locate the database by myself nor set the database path

Thanks for the report. I'll check that. `getDatabasesPath()` only makes sense on Android. I recommend using the `path_provider` package to find the best absolute location for other platform according to the platform recommendations (but setDatabasesPath has to work too...).

**Comment by alextekartik** [comment]
@clragon Does the following example fails for you too?

```dart
import 'dart:async';

import 'package:path/path.dart';
import 'package:sqflite_common/sqlite_api.dart';
import 'package:sqflite_common/utils/utils.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

Future main() async {
  sqfliteFfiInit();
  var factory = databaseFactoryFfi;
  var localDbPath = join('.dart_tool', 'sqflite_exp', 'test', 'databases');
  var dbName = 'simple.db';
  await factory.setDatabasesPath(localDbPath);
  print('Databases path: ${await factory.getDatabasesPath()}');
  // await factory.debugSetLogLevel(sqfliteLogLevelVerbose);
  int? newValue;

  var db = await factory.openDatabase(dbName,
      options: OpenDatabaseOptions(
          version: 1,
          onCreate: (db, version) async {
            await db.execute(
                'CREATE TABLE IF NOT EXISTS my_table (id INTEGER PRIMARY KEY, value INTEGER)');
          }));

  await db.transaction((txn) async {
    var existing = firstIntValue(
            await txn.query('my_table', columns: ['value'], where: 'id = 1')) ??
        0;
    newValue = existing + 1;
    var updated = await txn.update('my_table', {'value': newValue});
    if (updated == 0) {
      await txn.insert('my_table', {'value': newValue, 'id': 1});
    }
  });

  print(
      'updated to $newValue (re-run and it should increment again - $dbName)');
  await db.close();
}
```

**Comment by clragon** [comment]
That code works fine for me.
I actually also managed to print the database path on windows this time, inside my app, 
which is just inside the dart tools folder. you're definitely right, thats a strange location.

I guess if the database was to be put inside the application directory, this package would have to import path_provider, I see.
