### ISSUE TITLE
openDatabase(inMemoryDatabasePath) should  return a new instance

### ISSUE THREAD

**Issue by newlix** [tekartik/sqflite#75]
`openDatabase(inMemoryDatabasePath)`  returns the same instance currently. It only returns a new instance after `close` is called on the old instance, but you can only use one in-memory db at a time.

**Comment by alextekartik** [comment]
You can use the option `singleInstance: false` when calling `openDatabase` in the latest version to get new instance each time

**Comment by newlix** [comment]
thanks
