### ISSUE TITLE
where IN statement method

### ISSUE THREAD

**Issue by GourabPaul007** [tekartik/sqflite#752]
It would be good to have a `whereIn:` method like `where:` built into package. The current way of doing is to raw execution of sql with string interpolation which is quite unwieldy.

**Comment by alextekartik** [comment]
What would whereIn do? (i.e. it just takes a field name?). SQL is so complex that it is hard to provide a way to build a complex query with simple parameters to satisfy every needs. Maybe a separate package could help build complex queries.
