### ISSUE TITLE
How to dump SQL queries?

### ISSUE THREAD

**Issue by bambinoua** [tekartik/sqflite#753]
I need to print generated SQL queries. How can I do this? I didn't anything in documentation and stackoverflow.

**Comment by alextekartik** [comment]
Yes it is completely undocumented but there is some way to activate some native logging:

````dart
import 'package:sqflite_common/sqflite_dev.dart';
import 'package:sqflite/sqflite.dart';

Future<void> main() async {
  // Turn logging on
  await databaseFactory.setLogLevel(sqfliteLogLevelVerbose);
}
````
