### ISSUE TITLE
Shared Memory Files and Write Ahead Logs are not Committed on Termination or End of Transaction

### ISSUE THREAD

**Issue by erayerdin** [tekartik/sqflite#756]
I have an app. I have a kind of problem where I can insert into a table but it returns nothing when I select from it.

Since it's almost impossible to test sqflite, I tried to do some debugging. First things first, though, I am sure my SQL expressions are valid since I test them on [here](https://sqliteonline.com/) beforehand.

During troubleshooting, I have thought it's a good idea to check my app's data directory. It is, as you probably know, `/data/data/com.myname.myapp`. I've got my db file under `databases` subdirectory in there. (A note: I have root on my phone.)

During the application runtime, I see three files:

```
app.db
app.db-shm
app.db-wal
```

I was not sure about those `shm` and `wal` files but I have had an idea after [reading this in SQLite's official docs](https://www.sqlite.org/tempfiles.html). The presence of these files is to be expected on runtime. (A note: I am not really experienced with SQLite.)

The problem, however, is that these files should be persisted to main `app.db` file under one of these circumstances:

i. Either the application is terminated,
ii. or the app reaches the end of [transaction](https://pub.dev/documentation/sqflite_common/latest/sqlite_api/Database/transaction.html) without any problem.

As far as I understand, this is how it goes.

However, these `shm` and `wal` files persist in either in these conditions. I terminated the debug session on VSCode, fired up my app manually and tested it out, then terminated, the files are still there.

This is how I have database:

```dart
import 'package:sqflite/sqflite.dart';

Future<Database> getDatabase() async {
  return openDatabase(
    'app.db',
    version: 1,
    onCreate: _onCreate,
    onConfigure: _onConfigure,
  );
}

void _onCreate(Database db, int version) async {
  await db.execute('''
  CREATE TABLE resource (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    last_opened_at INTEGER NOT NULL,
    last_data_path TEXT NOT NULL,
    type INTEGER NOT NULL
  )
  ''');

  await db.execute('''
  CREATE TABLE resource_file (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_path TEXT UNIQUE,
    resource_id INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (resource_id) REFERENCES resource(id) ON DELETE CASCADE
  )
  ''');
}

void _onConfigure(Database db) async {
  await db.execute('PRAGMA foreign_keys = ON');
}
```

I use `get_it` and `registerLazySingletonAsync` in order to get a lazy and singleton instance to the database.

This below is an example SELECT transaction:

```dart
    List<Map<String, dynamic>> data = await db.transaction((txn) {
      return txn.rawQuery(
        '''
      SELECT * FROM resource
      ORDER BY last_opened_at DESC
      LIMIT ?
      ''',
        [limit],
      );
    });
```

And here below you see an example INSERT (or rather, REPLACE):

```dart
          int resId = await txn.rawInsert(
            '''
            REPLACE INTO resource(last_opened_at, last_data_path, type)
            VALUES (?, ?, ?)
            ''',
            [
              file.lastOpenedAt.millisecondsSinceEpoch,
              _jsonEncoder.convert(file.lastDataPath),
              resource.type.sqlId,
            ],
          );

          await txn.rawInsert(
            '''
            REPLACE INTO resource_file(file_path, resource_id)
            VALUES (?, ?)
            ''',
            [file.filePath, resId],
          );
```

My only guess is that `REPLACE INTO` is from a newer version of SQLite (I guess) and this causes unexpected behavior without any hard errors when used with `rawInsert`.

***

# Environment

`flutter --version`

```plain
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (3 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

 - sqflite 2.0.1
 - Android aosp_shamrock-userdebug 9 PQ3A.190605.003 eng.tnhnsh.20190610.211402 test-keys

**Comment by alextekartik** [comment]
> Since it's almost impossible to test sqflite, I tried to do some debugging.

You can do unit testing using sqflite_common_ffi: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/testing.md#using-sqflite_common_ffi

> REPLACE INTO

I have not used this command but as far as I know, REPLACE INTO is just an alias for INSERT OR REPLACE (https://www.sqlite.org/lang_replace.html)

So you should be able to do it this way to: `await db.insert(table, map, conflictAlgorithm: ConflictAlgorithm.replace);`

I"m unusure of the behavior though and why you use this instead of a regular insert command for the table `resource`. Maybe some print will help or try to reproduce in a unit test.

> However, these shm and wal files persist in either in these conditions

sqflite don't control that, it depends on the platform implementation and should not be a pb. I think the file should properly deleted when you close the database. If by terminated, you mean kill, yes those files should remain.

**Comment by erayerdin** [comment]
Just as a reply to googlers, my issue was my confusion about how futures work. I awaited at some point and my problem is solved.
