### ISSUE TITLE
Publish to pub.dev

### ISSUE THREAD

**Issue by gquarles** [tekartik/sqflite#757]
@alextekartik 
Can this package be published to pub.dev so that https://github.com/tekartik/sqflite/pull/749 is live?

Currently jcenter is returning a 502 error and any app that uses sqflite will fail when trying to build

https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml

**Comment by alextekartik** [comment]
Sorry, since I did not encounter any issue so far (even now, I just tried) I did not see what the problem was. Published as sqflite 2.0.2

**Comment by gquarles** [comment]
Thanks! 
That fixed my build
