### ISSUE TITLE
How does flutter use sqflite in multiple flutter engines?

### ISSUE THREAD

**Issue by ddxl123** [tekartik/sqflite#763]
Can a  'await openDatabase(path)' be created in each engine?
So if there are 10 engines, I have to create 'await openDatabase(path)' 10 times?

**Comment by alextekartik** [comment]
I'm not sure how multiple engine differs from isolate or processes, maybe some insights would help. Currently sqflite is cross process safe but not cross-isolate safe (regarding transactions). And yes you have to open the database in each isolate.
