### ISSUE TITLE
sqflite package not working in release mode

### ISSUE THREAD

**Issue by maryanlouis** [tekartik/sqflite#770]
I'm using sqflite package in a flutter app, It works well in debug mode, but the package is not working when building an apk, can you help me please?

**Comment by alextekartik** [comment]
More information would help to understand the issue your are facing (some logs, platform, setup, some code showing where it fails, the exception you are seeing and how it differs from debug mode).

**Comment by maryanlouis** [comment]
no error is shown. It just neither show any data nor create the database in release mode, but it does it in debug mode

**Comment by alextekartik** [comment]
Hard to know what is going on and I still don't know whether you are on Android or Windows or iOS or Linux or MacOS. My only suggestion is to add more print statement to see where it is failing (there could be tons of reason). I am not aware of such issue though. If you can reproduce the issue with a smaller example.
Or maybe you can try the simple example here: https://github.com/alextekartik/flutter_app_example/tree/master/notepad_sqflite and see whether if fails on release.
(Please use triple ticks to enclose you code)

**Comment by maryanlouis** [comment]
Thanks for responding, I'm using android
I'll try the example and see
