### ISSUE TITLE
SUBSTR with different behaviour on iOS and Android

### ISSUE THREAD

**Issue by tuxskar** [tekartik/sqflite#771]
I'm using the filter on a string with SUBSTR and depending on where it is executed it returns a different values.

When having a string like "2021-01-02" and running:
```
List<Map> ret = await db.rawQuery("""select substr('2022-01-02', 0, 4) year, 
substr('2022-01-02', 0, 7) ym, 
substr('2022-01-02', 6, 2) month, 
substr('2022-01-02', -10, 4) myear, 
substr('2022-01-02', -10, 7) mym""");
```

I get the next results:
On iOS: 
`[{year: 2022, ym: 2022-01, month: 01, myear: 2022, mym: 2022-01}]`

On Android:
`[{year: 202, ym: 2022-0, month: 01, myear: 2022, mym: 2022-01}]`

So seems that the sqlite version are treating the substr function internally different when using 0 for the start parameter.

Summarizing:
When using android with `substr('2022-01-02', 0, 4) => "202"`
When using iOS `substr('2022-01-02', 0, 4) => "2022"`

I'll use the negative start because align the 2 platforms but seems an good issue to track

**Comment by alextekartik** [comment]
Thanks for the report. Indeed, that's puzzling. I think a negative start means starting from end so that should not be a solution neither. I will try to reproduce using raw android sqlite.

**Comment by alextekartik** [comment]
After reading more about it:
https://www.sqlitetutorial.net/sqlite-functions/sqlite-substr/

In fact you should not use 0 but 1 for the starting character.
```
select substr('2022-01-02', 1, 4); // => 2022
```
