### ISSUE TITLE
Group by Date Not working.... on Android.

### ISSUE THREAD

**Issue by ashokavarthanan** [tekartik/sqflite#773]
/* Create a table called NAMES */

	  CREATE TABLE c_price (
		c_id INTEGER PRIMARY KEY,
		c_date INTEGER NOT NULL,
		c_name TEXT NOT NULL,
		c_veraity TEXT NOT NULL,
		c_price INTEGER NOT NULL,
		UNIQUE(c_date,c_name,c_veraity)
	  );
	/* Create few records in this table */
	INSERT INTO c_price VALUES(1,20220210,'AAAA',"XX",50);
	INSERT INTO c_price VALUES(2,20220210,'AAAA',"YY",60);
	INSERT INTO c_price VALUES(3,20220210,'AAAA',"ZZ",70);

	INSERT INTO c_price VALUES(4,20220211,'AAAA',"XX",55);
	INSERT INTO c_price VALUES(5,20220212,'AAAA',"YY",65);
	INSERT INTO c_price VALUES(6,20220213,'AAAA',"ZZ",75);
	COMMIT;

This Code is Problem.

	SELECT t.c_id, t.c_name,  t.c_veraity,t.c_price,r.MaxTime
	FROM (
		  SELECT c_veraity, MAX(c_date) as MaxTime
		  FROM c_price
	WHERE c_date <= 20220213
		  GROUP BY c_veraity
	) r
	INNER JOIN c_price t
	ON t.c_veraity = r.c_veraity AND t.c_date = r.MaxTime
	AND t.c_name = 'AAAA'

This Code works on **Online** Sqlite v3.0
But Not working **sqflite**
Result is Showing only data date **"20220213"**.

**Comment by alextekartik** [comment]
Hard to know without seeing some dart code and an easy way to reproduce (what is expected, what is returned). sqlite does not do any SQL parsing so maybe that is the behavior on android (you might try the same in java for confirmation).

**Comment by ashokavarthanan** [comment]
something wrong with me..
WHERE  c_date <= 20220213 **AND c_name = 'AAAA'**
works fine.
Sorry.. by mistake.

**Comment by ashokavarthanan** [comment]
something wrong with me.. 
(but still  I don't know why I get result only on date "20220213" when I used **"<="**)
now works fine.
thanks for replay.
