### ISSUE TITLE
Can't catch exception on linux

### ISSUE THREAD

**Issue by CodinKitchen** [tekartik/sqflite#775]
Hi,

I'm building a flutter desktop app using sqflite_common_ffi package. I'm working and testing on linux. Haven't tested on macos or Windows yet.

I'm trying to catch an exception when deleting a row referenced in another table but it's like my try/catch does nothing. Here is my code :

```dart
try {
      database.delete(
        Account.table,
        where: 'id = ?',
        whereArgs: [account.id],
      );
} catch (e) {
      print('test');
}
```

I'm pretty new to flutter and dart so maybe I missed somthing ?

**Comment by alextekartik** [comment]
delete in an asynchronous method so you need to add `await` to catch any exception that might occur during the deletion:
```dart
try {
  await database.delete(...);
} catch (e) {
}
```

More info [here](https://dart.dev/codelabs/async-await#handling-errors)

**Comment by CodinKitchen** [comment]
Oh ok that was a stupid mistake. Thanks @alextekartik !!
