### ISSUE TITLE
Window is full

### ISSUE THREAD

**Issue by sagarstackapp** [tekartik/sqflite#779]
`W/CursorWindow(15261): Window is full: requested allocation 1310926 bytes, free space 904042 bytes, window size 2097152 bytes`
`E/SQLiteQuery(15261): exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT * FROM my_package
`

I'm getting this warning and not getting sql data from table in **Android flutter**. but for **IOS** it working fine.

Please, Help me to find solution.!

**Comment by alextekartik** [comment]
It seems that Android default record size is limited to about 1MB. My recommendation would be to keep record much smaller and store big binary data as files.

**Comment by sagarstackapp** [comment]
but my data is not type of image, it's json type response. And as you mentioned android default size is 1MB. Can we increase that size? That would be great for me and many more devs. Because as i check many devs had this issue.

**Comment by alextekartik** [comment]
Unfortunately I'm not sure we can change this in the default android implementation. One solution is to use a custom sqlite implementation. This is possible using [sqflite_common_ffi](https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md). In some tests I was able to read a 150 MB record without issue. The API usage remain the same, there is a little bit of setup as described in the sqflite3 package.

**Comment by sagarstackapp** [comment]
Thank it may works for me.!
