### ISSUE TITLE
Export query results as .csv

### ISSUE THREAD

**Issue by 0x3C** [tekartik/sqflite#78]
Are there any plans to allow exporting the results of a query to a .csv file? 

I want to allow users in my app to export the contents of their database to a .csv file for either back ups, or for taking the data and using it for another application/service.

**Comment by alextekartik** [comment]
There is no plan at this time to support exporting in various format. This is a raw package around sqlite. However exporting List<Map> to csv should not take more than a few lines of code (except escaping the separator)

**Comment by dalmat36** [comment]
@0x3C This may be helpful to you: https://dzone.com/articles/java-8-convert-list-to-string-comma-separated

**Comment by manfye** [comment]
any way to export the data out?

**Comment by alextekartik** [comment]
There is no sql export/import part for sqflite as sqlite does not provider this. I have a side project in progress to import/export as sql here:
https://github.com/tekartik/sqflite_more/tree/master/sqflite_porter

Back to the subject (csv) I added an example using the csv package to convert a query result to csv using a [mapListToCsv](https://github.com/tekartik/sqflite_more/blob/de853083cdbb977f8417970c4ea012de47a9cbcc/sqflite_porter/lib/utils/csv_utils.dart) utility method. Exporting a table is then as simple as doing:
```dart
var result = await db.query('MyTable');
var csv = mapListToCsv(result);
```

You can definitely export/import easily into your own format by querying the master_table for the schema and exporting data from queries and importing using insert. The existing de facto SQL export format is a pain (especially with trigger and line feed) but I don't want to invent/impose any new format.

**Comment by qlssk8737** [comment]
@alextekartik How can I get the path of csv file? After using `mapListToCsv` code, I can not find the csv file and it returned null.

**Comment by alextekartik** [comment]
mapListToCsv return a string which is the content (you have to write the file with this content). It should not return null. Can I reproduce the issue?. See simple unit test here: https://github.com/tekartik/sqflite_more/blob/b7ddcd2362cf3b58e5b0aa7f1c7a3d5b2992f257/sqflite_porter/test/csv_utils_test.dart#L41-L55

(if needed we might follow this issue in the [repo where it belong](https://github.com/tekartik/sqflite_more/tree/master/sqflite_porter)

**Comment by qlssk8737** [comment]
@alextekartik Thanks for your comment! Thanks to you, I solved the export issue. By the way, when import csv file to Sqlite, I want to replace an existing table with a new one. For this, I tried to use `FilePicker` and `CSV` but it doesn't work at all and looks like I'm missing something. Could you take a look at code below or tell me the way to import sqlite from csv using `sqflite_porter`? Thanks in advance.

```
Future importVoca() async {
    File file = await FilePicker.getFile(
        type: FileType.custom, allowedExtensions: ['csv']);
    final data = file.openRead();
    final fields = await data
        .transform(utf8.decoder)
        .transform(new CsvToListConverter())
        .toList();

    Database _db = await openDatabase(
        join(await getDatabasesPath(), 'vocas.db'),
        version: 1, onCreate: (Database db, int version) async {
      await db.execute("DROP TABLE IF EXISTS vocas");
      await db.execute(
          "CREATE TABLE vocas(id TEXT PRIMARY KEY, word TEXT, meaning TEXT, createTime TEXT)");
      await db.execute(
          "INSERT OF REPLACE INTO vocas (id, word, meaning, createTime) VALUES(fields.id, fieldw.word, fields.meaning, fields.createTime)");
    });
    return _db;
  }
```

**Comment by alextekartik** [comment]
sqflite_porter provider a dbImportSql/dbExportSql to export/import the data as a list of statements. In your case you need as you do to write the insert statement. fields is a list in your case so guess you need to iterate in it (for (var field in fields) and extract the list of keys and columns. It will have several issues, for example null values will be treated as string "null". I don't recommend importing from csv unless you know the format used and the tricks needed for null, blobs...

**Comment by rubana28** [comment]
> @alextekartik Thanks for your comment! Thanks to you, I solved the export issue. By the way, when import csv file to Sqlite, I want to replace an existing table with a new one. For this, I tried to use `FilePicker` and `CSV` but it doesn't work at all and looks like I'm missing something. Could you take a look at code below or tell me the way to import sqlite from csv using `sqflite_porter`? Thanks in advance.
> 
> ```
> Future importVoca() async {
>     File file = await FilePicker.getFile(
>         type: FileType.custom, allowedExtensions: ['csv']);
>     final data = file.openRead();
>     final fields = await data
>         .transform(utf8.decoder)
>         .transform(new CsvToListConverter())
>         .toList();
> 
>     Database _db = await openDatabase(
>         join(await getDatabasesPath(), 'vocas.db'),
>         version: 1, onCreate: (Database db, int version) async {
>       await db.execute("DROP TABLE IF EXISTS vocas");
>       await db.execute(
>           "CREATE TABLE vocas(id TEXT PRIMARY KEY, word TEXT, meaning TEXT, createTime TEXT)");
>       await db.execute(
>           "INSERT OF REPLACE INTO vocas (id, word, meaning, createTime) VALUES(fields.id, fieldw.word, fields.meaning, fields.createTime)");
>     });
>     return _db;
>   }
> ```

here, are you trying to export the values of database table into a csv file?
