### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type 'Future<int>' exception in flutter database creation

### ISSUE THREAD

**Issue by mobile-stunntech** [tekartik/sqflite#79]
I create a database using path provider plugin and SQFLite. But it is not working, it shows an exception message type Future<dynamic> is not a subtype of type Future<int>. the exception is shown in the line 

` var ourDb = await openDatabase(path, version: 1, onCreate: _onCreate);`

my full code is here.
`static final DatabaseHelper _instance = new DatabaseHelper.internal();
  factory DatabaseHelper() => _instance;

  static Database _db;

  Future<Database> get db async {
    if (_db != null) {
      return _db;
    }
    _db = await initDb();
    return _db;
  }

  DatabaseHelper.internal();

  initDb() async {
    Directory documentDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentDirectory.path, "tododatabase.db");
    var ourDb = await openDatabase(path, version: 1, onCreate: _onCreate);
    return ourDb;
  }

  Future _onCreate(Database db, int version) async {
    await db.execute(
        "CREATE TABLE TodoList(id INTEGER PRIMARY KEY, todoText TEXT)");
    // print("Table is created");
  }

//insertion
  Future<int> saveTodo(Todo todo) async {
    var dbClient = await db;
    int res = await dbClient.insert(" TodoList", todo.toMap());
    return res;
  }`

**Comment by alextekartik** [comment]
Hi and thanks for your note. Which sqflite and flutter versions are you using and are you using iOS or Android. Have you checked the [troubleshooting](https://github.com/tekartik/sqflite/blob/master/doc/troubleshooting.md) section?

(I copied some part of your code in a blank projet and it worked)
