### ISSUE TITLE
Request Support sqflite package for Windows

### ISSUE THREAD

**Issue by astudilloalex** [tekartik/sqflite#793]
Please add support for Windows in sqflite package, because is very difficult change sqflite to sqflite_common_ffi package.

Use only one package for all platforms

**Comment by alextekartik** [comment]
I understand but there are some many combination for desktop and mobile (ffi or not, bundled version, cipher...) that it is hard to make strong choices. Even for me depending on the project, I don't use the same solutions. For example using sqlite3_flutter_libs on mobile add several megabites that not everybody want.

Also a single package will bring aditional dependencies even if not needed. 

Someone could decide to wrap sqflite, sqflite_common_ffi, sqlite3_flutter_libs into a single package but at this point, this is not planned for this package yet (I'd rather create a sqflite_ffi package).
