### ISSUE TITLE
Windows: Why does ./path/to/test.exe only work from root of project?

### ISSUE THREAD

**Issue by pamtbaau** [tekartik/sqflite#795]
Depending whether library sqlite3.dll is available in same folder as test.exe, there is some inconsistency when running the app from different locations.
- If sqlite3.dll is available, all goes well.
- If sqlite3.dll is not available, only running from root of project app will work.

Some tests:

**Without sqlite3.dll in same folder as test.exe**
- `$ cd /root/of/project`
  - `$ ./build/windows/runner/Release/test.exe` is working fine
- `$ cd /root/of/project/build/windows/runner/Release`
  - `$ ./test.exe` shows blank screen.
- `$ cd /anywhere`
-    `$ /path/to/project/build/windows/runner/Release/test.exe` shows blank screen.

**With sqlite3.dll in same folder as test.exe**
- `$ cd /root/of/project`
  - `$ ./build/windows/runner/Release/test.exe` is working fine
- `$ cd /root/of/project/build/windows/runner/Release`
  - `$ ./test.exe` is working fine
- `$ cd /anywhere`
-    `$ /path/to/project/build/windows/runner/Release/test.exe` is working fine.

Apparently, when starting the app from inside the root of the project (first test), flutter finds something needed to find the sqlite3.dll library. There are a few sqlite3.dll libraries on the system, but nowhere in the tree of the project.

Any explanation for this behaviour?

**Comment by alextekartik** [comment]
Thanks for detailed report. sqlite3.dll loading is managed by the [sqlite3](https://pub.dev/packages/sqlite3) which by default load whatever sqlite3.dll available in the path. My guess is that you can include `sqlite3_flutter_libs` and it should work but I have not tried yet.

If you are calling sqfliteFfiInit which basically on windows debug mode will look into loading the bundled dll (that I'll need to update at some point). As mentioned, this is only a reference implementation that you can copy and tweak for you needs. For example you could find the executable absolute path and look for the dll there.

That is said, I think I could implement this default behavior so that it works.

**Comment by alextekartik** [comment]
After more testing the behavior is as expected. Copying the dll along the exe in release mode is handled by sqfliteFfiInit. Not doing so, the behavior could depend on whether such a dll exists in the system. Running from the root of the project is a special case during development (it tries to resolve the path to the dll from the package.json file).

**Comment by pamtbaau** [comment]
I'm new to flutter so please excuse my ignorance...

> a special case during development

Is running de Release/test.exe still considered "during development"?

> it tries to resolve the path to the dll from the package.json file

But there is no sqlite3.dll anywhere inside the tree of the project... Does it perhaps search the %APPDATA%\Pub\Cache folder? Does sqflite also contain a sqlie3.dll.

**Comment by alextekartik** [comment]
> Is running de Release/test.exe still considered "during development"?

Running from the project root is considered during development here (pure personal opinionated decision for debug mode but also active in release mode). basically it manages to find the package_config.json file locally so assume you are in a flutter development mode. So it tries to resolve the package sqflite_common_ffi to find the dll

> But there is no sqlite3.dll anywhere inside the tree of the project

It tries to find sqlite3.dll in the following dir:
https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi/lib/src/windows

The location will likely by in the pubcache folder. Look at `.dart_tool/package_config.json` to find the location on your computer.
