### ISSUE TITLE
Enable read only access to a database directly from the app bundle. 

### ISSUE THREAD

**Issue by nicolasjon** [tekartik/sqflite#81]
When using large read only databases it would be great to avoid copying them to another directory before use. Less device memory used, faster setup, simpler, less blocking operations to go wrong etc.
I have hacked the iOS code as a test in SqflitePlugin.m  

```
NSString* key;

+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
    FlutterMethodChannel* channel = [FlutterMethodChannel
                                     methodChannelWithName:_channelName
                                     binaryMessenger:[registrar messenger]];
    SqflitePlugin* instance = [[SqflitePlugin alloc] init];
    [registrar addMethodCallDelegate:instance channel:channel];
    // NJP
    key = [registrar lookupKeyForAsset:@"assets/database.db"];
}
```
and

```
- (void)handleOpenDatabaseCall:(FlutterMethodCall*)call result:(FlutterResult)result {
    NSString* path = call.arguments[_paramPath];
    NSNumber* readOnlyValue = call.arguments[_paramReadOnly];
    bool readOnly = [readOnlyValue boolValue];
    
    // NJP
    if ([path isEqualToString:@"/asset"])
    {
    readOnly = true;
    path = [[NSBundle mainBundle] pathForResource:key ofType:nil];
    }
```
Called from Flutter with

```
      // For iOS open the database in read-only mode directly from the bundle
      return await openDatabase("asset");
```

I have not yet figured out how to save a reference to `registrar`, which would save the `NSString* key;` hack. Then perhaps another parameter to indicate the name is from the bundle and read only.
These are just some ideas. But it works on iOS, and I think a similar pattern could be used for Android, just not sure if the underlying SQL engine would allow it.

References

Flutter Assets (https://flutter.io/assets-and-images/)

Video Player (https://pub.dartlang.org/packages/video_player) 

Any thoughts?

**Comment by alextekartik** [comment]
Thanks for finding a way to do that in iOS. Ineeded we could support specifying a uri in the path to open asset databases. On Android I'm not sure yet how to do it (we can read an asset but i don't see yet whether we can get a file path - needed). In the worst case the native implementation could handle the conversion to a file if needed

**Comment by nicolasjon** [comment]
I have looked into this further and as you say, on Android there is no official way for SQLite to access  a database in the bundle directly.

**Comment by alextekartik** [comment]
Yeap. one half-baked solution would be to retrieve a file path from an asset on iOS only but such extension is not sqflite specific so maybe should deserve its own package
