### ISSUE TITLE
on flutter windows the app works well on debug but on released mode packaged with installer it doesnt work

### ISSUE THREAD

**Issue by Galzysoft** [tekartik/sqflite#816]
the windows software I build with it is working very well on flutter  debug mode or on released mode using the distribution folder method but I currently noticed that when I packaged the app with an installer (inno setup.exe and msix package ) I noticed that the database cant connect i also downloaded the sqlite3.dll file as you suggested in the documentation

**Comment by humam-alBasha** [comment]
add this in  pubspec.yaml
  sqlite3_flutter_libs:

  _initDatabase() async {
    DatabaseFactory _databaseFactory;
    String path = '';
    if (!kIsWeb && Platform.isWindows) {
      sqfliteFfiInit();
      _databaseFactory = databaseFactoryFfi;
      final Directory _directory = await getApplicationSupportDirectory();
      await _databaseFactory.setDatabasesPath(_directory.path);
      path = join(await _databaseFactory.getDatabasesPath(), "name.db");
    } else {
      _databaseFactory = databaseFactory;
      path = join(await _databaseFactory.getDatabasesPath(), "name.db");
    }
    _database = await _databaseFactory.openDatabase(path,
        options: OpenDatabaseOptions(
            onCreate: (Database db, int _) => _createDb(db), version: 1));

    return _database;
  }

**Comment by Galzysoft** [comment]
Thanks this solve my problem thanks

**Comment by himanshuchaurasiya24** [comment]
> add this in pubspec.yaml sqlite3_flutter_libs:
> 
> databaseHelper.dart ==> use
> 
> ```
> _initDatabase() async {
>   DatabaseFactory _databaseFactory;
>   String path = '';
>   if (!kIsWeb && Platform.isWindows) {
>     sqfliteFfiInit();
>     _databaseFactory = databaseFactoryFfi;
>     final Directory _directory = await getApplicationSupportDirectory();
>     await _databaseFactory.setDatabasesPath(_directory.path);
>     path = join(await _databaseFactory.getDatabasesPath(), "name.db");
>   } else {
>     _databaseFactory = databaseFactory;
>     path = join(await _databaseFactory.getDatabasesPath(), "name.db");
>   }
>   _database = await _databaseFactory.openDatabase(path,
>       options: OpenDatabaseOptions(
>           onCreate: (Database db, int _) => _createDb(db), version: 1));
> 
>   return _database;
> }
> ```

can you provide your full code
