### ISSUE TITLE
Foreign Key not working

### ISSUE THREAD

**Issue by FDhunterz** [tekartik/sqflite#835]
how i can add foreignkey error ?

**Comment by alextekartik** [comment]
Can you elaborate what you mean by "not working"  and maybe show some code to reproduce the issue your are seeing. Typically I set up foreign key during onConfigure: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_db.md#configuration

**Comment by FDhunterz** [comment]
@alextekartik i try to make restrict configuration like this, but always no error
```
I/flutter (19326): CREATE TABLE m_product (p_id  INTEGER PRIMARY KEY AUTOINCREMENT, p_nama  TEXT, p_satuan  INTEGER ,  FOREIGN KEY(p_satuan) REFERENCES m_satuan(s_id)  ON DELETE RESTRICT  ON UPDATE RESTRICT )
I/flutter (19326): CREATE TABLE m_satuan (s_id  INTEGER PRIMARY KEY AUTOINCREMENT, s_nama  TEXT)
```
```
I/flutter (19326): [{s_id: 1, s_nama: nice}]
I/flutter (19326): [{p_id: 1, p_nama: nice, p_satuan: 1}]
```
