### ISSUE TITLE
[iOS] Get Databases Path from Shared Container

### ISSUE THREAD

**Issue by tuan08t2** [tekartik/sqflite#84]
Thank you to create an awesome package for Flutter!
As the title, I expect a way to get database path from share container in case the ios app have a share extension and we need to share data between them.
I can use method channel to get a path. But I expect a better way from the package.
Example create a shared container path:
```
let fileManager = FileManager.default
        guard let groupURL = fileManager
            .containerURL(forSecurityApplicationGroupIdentifier: "group.com.example") else {
                return 
        }
        
        let storagePathUrl = groupURL.appendingPathComponent("db_folder_name")
        let storagePath = storagePathUrl.path
        
        // 2: Create a folder in the shared container location with name"db_folder_name"
        if !fileManager.fileExists(atPath: storagePath) {
            do {
                try fileManager.createDirectory(atPath: storagePath,
                                                withIntermediateDirectories: false,
                                                attributes: nil)
            } catch let error {
                print("error creating filepath: \(error)")
                return
            }
        }
        print(storagePath)
        if sqlite3_open(storagePathUrl.appendingPathComponent("db_file_name.sqlite").path, &db) != SQLITE_OK {
            print("error opening database")
            return
        }
```
Source: https://blog.couchbase.com/couchbase-lite-with-ios-app-extensions/

Thanks!

**Comment by alextekartik** [comment]
Thanks for the note, I was not aware of such feature (that is iOS only). It sounds like getting such shared container path could be used by any app that needs some file system so I'm not sure sqflite is the best host for it. Maybe that could be part of another existing plugin (`path_provider`?) or maybe it could deserve its own plugin. I agree that there is already a `getDatabasesPath` that was made to provide a basic strategy for database location but my first thought would be to not provide such feature yet (unless there is really an sqlite shared container location)
