### ISSUE TITLE
How to save data when the app is closed

### ISSUE THREAD

**Issue by burhanaksendir** [tekartik/sqflite#844]
What should I do to save sqflite data when the application closes?

I tried didChangeAppLifecycleState "detached" but it didn't work.

**Comment by alextekartik** [comment]
I don't think you can rely on any API to be called when the application is closed, most of the time, the application process will simply be killed.

**Comment by burhanaksendir** [comment]
Thanks.  Is there another chance to Write/Save before the application terminates?

**Comment by alextekartik** [comment]
I don't think so.
