### ISSUE TITLE
Is it possible to check/validate a database has the correct schema?

### ISSUE THREAD

**Issue by asmith26** [tekartik/sqflite#849]
Hi there,

I'm hoping to allow users to restore/upload a sqflite database file to my app. Of course my app requires a specific database format/schema, hence I was wondering if it is possible to check/validate an uploaded file has the correct schema for my app?

My only thought so far is to compare an uploaded file to the required schema using something like `print(await db.query("sqlite_master"));`

Many thanks for any help, and for this amazing lib! :)

[Sorry I've just realized there is a discussions tab for this repo, so I have also asked this question [there](https://github.com/tekartik/sqflite/discussions/850) if preferable?]

**Comment by alextekartik** [comment]
Answered here: https://github.com/tekartik/sqflite/discussions/850
