### ISSUE TITLE
Not Working on Real iOS Device 

### ISSUE THREAD

**Issue by dynamitechetan** [tekartik/sqflite#85]
Not able to open db on real iOS Device. Works fine on iOS Simulators and Android Devices.
Am I missing something here?
```
2018-08-06 15:15:37.962898+0530 Runner[6380:2156049] [logging-persist] cannot open file at line 42154 of [95fbac39ba]
2018-08-06 15:15:37.962927+0530 Runner[6380:2156049] [logging-persist] os_unix.c:42154: (0) open(/var/mobile/Containers/Data/Application/EE6AB869-4A66-4B77-88A1-9A01A153E59B/Documentsbooks.db) - Undefined error: 0
2018-08-06 15:15:37.962982+0530 Runner[6380:2156049] error opening!: 14
2018-08-06 15:15:37.962999+0530 Runner[6380:2156049] Could not create database queue for path /var/mobile/Containers/Data/Application/EE6AB869-4A66-4B77-88A1-9A01A153E59B/Documentsbooks.db
2018-08-06 15:15:37.963044+0530 Runner[6380:2156049] Could not open db.
2018-08-06 15:15:37.978424+0530 Runner[6380:2156167] [VERBOSE-2:dart_error.cc(16)] Unhandled exception:
DatabaseException(open_failed /var/mobile/Containers/Data/Application/EE6AB869-4A66-4B77-88A1-9A01A153E59B/Documentsbooks.db)
#0      wrapDatabaseException (package:sqflite/src/exception.dart:125)
<asynchronous suspension>
#1      SqfliteDatabase._openDatabase (package:sqflite/src/database.dart:469)
#2      SqfliteDatabase.doOpen (package:sqflite/src/database.dart:502)
<asynchronous suspension>
#3      SqfliteDatabaseOpenHelper.openDatabase.<anonymous closure> (package:sqflite/src/database.dart:167)
<asynchronous suspension>
#4      Lock._runTask (package:synchronized/src/synchronized_impl.dart:147)
#5      LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:62)
#6      LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:72)
#7      Lock.synchronized (package:synchronized/src/synchronized_impl.dart:140)
```

**Comment by dynamitechetan** [comment]
Sorry, I fixed it by
```    var documentDirectory = await getApplicationDocumentsDirectory(); ```
previously I was doing 
```     var databasesPath = await getDatabasesPath(); ```

**Comment by deliaslan** [comment]
iOS 14.01 i have the same problem. Sqflite works on iOS emulator but does not work on the real iOS device. Program installing and opening and navigations work but can not insert new data. 
I tried on Code and Xcode Ides.
Xcode warn me about build settings then I fixed but nothing changed.

**Comment by alextekartik** [comment]
@deliaslan Do you have more information to share on where it fails (logs, database location, making sure that the database folder exists) in sqflite. You could do some basic print before and after opening the database and [turn on logging](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#turn-on-sql-console-logging)

**Comment by deliaslan** [comment]
> @deliaslan Do you have more information to share on where it fails (logs, database location, making sure that the database folder exists) in sqflite. You could do some basic print before and after opening the database and [turn on logging](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#turn-on-sql-console-logging)

thanks for your helping @alextekartik  I opened debug mode and watch the problem. my database name does not split by the / so do not see the path on the phone. now I added it to the path and it works!

**Comment by didierboka** [comment]
> > @deliaslan Do you have more information to share on where it fails (logs, database location, making sure that the database folder exists) in sqflite. You could do some basic print before and after opening the database and [turn on logging](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#turn-on-sql-console-logging)
> 
> thanks for your helping @alextekartik I opened debug mode and watch the problem. my database name does not split by the / so do not see the path on the phone. now I added it to the path and it works!

Hi all ! But why it work on Emulator and Android real device ? By adding this '/' will not disavantaged other device ? @deliaslan
