### ISSUE TITLE
[windows] crashes on devices running Windows build 22000

### ISSUE THREAD

**Issue by daydreary** [tekartik/sqflite#851]
##### the issue is:
SqfliteFfiException
SqfliteFfiException(sqlite_error: 14, , open_failed: SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)}) 
DatabaseException(open_failed: SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21))

I already added [sqlite3.dll](https://github.com/tekartik/sqflite/raw/master/sqflite_common_ffi/lib/src/windows/sqlite3.dll) in same folder as the executable. On some devices, it works well. But tested on Microsoft Surface Laptop, Win 10 S. Dell Latitude 5520, Win 11, it crashed.
The issue was observed on multiple devices running Windows build 22000.

I found it may run flawless on some devices when open Windows compatibility mode.

<details>
<summary>Expand error logs</summary>
<pre><code>
isolate.dart in SqfliteIsolate.handle at line 41 within sqflite_common_ffi
Called from: <asynchronous suspension>
database_factory_ffi.dart in FfiMethodCallHandler._isolateHandle at line 96 within sqflite_common_ffi
Called from: <asynchronous suspension>
database_factory_ffi.dart in FfiMethodCallHandler.handleInIsolate at line 52 within sqflite_common_ffi
Called from: <asynchronous suspension>
factory.dart in _SqfliteDatabaseFactoryImpl.invokeMethod at line 22 within sqflite_common
Called from: <asynchronous suspension>
database_mixin.dart in SqfliteDatabaseMixin.openDatabase at line 556 within sqflite_common
Called from: <asynchronous suspension>
database_mixin.dart in SqfliteDatabaseMixin.doOpen at line 649 within sqflite_common
Called from: <asynchronous suspension>
database.dart in SqfliteDatabaseOpenHelper.openDatabase at line 44 within sqflite_common
Called from: <asynchronous suspension>
factory_mixin.dart in SqfliteDatabaseFactoryMixin.openDatabase.<fn> at line 110 within sqflite_common
Called from: <asynchronous suspension>
reentrant_lock.dart in ReentrantLock.synchronized.<fn> at line 37 within synchronized
Called from: <asynchronous suspension>
basic_lock.dart in BasicLock.synchronized at line 33 within synchronized
Called from: <asynchronous suspension>
</code></pre>
</details>

**Comment by alextekartik** [comment]
Do you have the path of your database? On windows `getDatabasesPath()` returns some dummy location. Can you try:
- Use path_provider to find the best location for you database
- Ensure that the parent directory exists and is writable (i.e. you can create file at this location)

**Comment by daydreary** [comment]
> Do you have the path of your database? On windows `getDatabasesPath()` returns some dummy location. Can you try:
> 
> * Use path_provider to find the best location for you database
> * Ensure that the parent directory exists and is writable (i.e. you can create file at this location)

Thanks for your reply, I'll try this.
