### ISSUE TITLE
wrapDatabaseException when put Long String into table database 

### ISSUE THREAD

**Issue by nawzhin95** [tekartik/sqflite#854]
Hello Guys 
i have a sqflite database and a table inside it connected with my flutter app
i can insert  regular String size text and query text ( get text ) from my database 

i know sqflite text data type accept long string but i think my problem with long string that longer that dart string data type when i want to put my string into database sqflite through wrapDatabaseException  Exception into terminal 

so there is any wat to deal with long string in dart (flutter) or any way to insert long string into sqflite database ?

**Comment by alextekartik** [comment]
Not sure what you mean by long string (1Kb, 10Kb, 1Mb, 1Gb?). There is a hard limit of 1Mb on Android. Can you specify the length of the string and some code you have tried?

**Comment by nawzhin95** [comment]
> Not sure what you mean by long string (1Kb, 10Kb, 1Mb, 1Gb?). There is a hard limit of 1Mb on Android. Can you specify the length of the string and some code you have tried?

Thanks @alextekartik  i mean string length for example string with long data 10000 characters
