### ISSUE TITLE
Change of Copyright notice

### ISSUE THREAD

**Issue by julia410m** [tekartik/sqflite#859]
Hello! Can you change Copyright notice in your BSD License (software sqflite and sqflite_common) and add the author's name and surname, bacause the author's nickname "tekartik" can be changed in the future and this can make it difficult to identify the copyright owner of your software. Thank you in advance

**Comment by alextekartik** [comment]
Thanks for spotting that. I'm still at lost whether to use MIT, BSD-2 or BSD-3 and whether this can still be changed and what the copyright holder name should be. I have changed to "Alexandre Roux Tekartik" although maybe it should only be "Alexandre Roux". You recommendation is welcome.

**Comment by julia410m** [comment]
@alextekartik as I know, it is better to indicate your full name than your username regardless of what license you use because it allows easy to identify you as a copyrht owner of this software. 

As I know, the copyright notice may contain both your full name and your username. Thank you for your quick answer for my request

**Comment by alextekartik** [comment]
Fixed
