### ISSUE TITLE
How to use IN condition with query() ?

### ISSUE THREAD

**Issue by Nik99** [tekartik/sqflite#86]
Hi everyone, i'm trying to get a specific number of rows by ID. I'm trying to use the IN condition for this task, but i don't know how to implement it.

List<int> rowIDS = [3, 7, 9];

db.query("Table", where: "id IN (?)", rowIDS);

This is my current code.
Thanks everyone!

**Comment by microdog** [comment]
https://github.com/tekartik/sqflite/issues/15

**Comment by alextekartik** [comment]
Indeed bug (which is not really but more a usage query) https://github.com/tekartik/sqflite/issues/15 has a detailed answer, the number of `?` must match the number of values
