### ISSUE TITLE
Support specifying journal mode in openDatabase calls

### ISSUE THREAD

**Issue by Haozhe123** [tekartik/sqflite#861]
Currently sqflite plugin only supports `CREATE_IF_NECESSARY` when [opening database](https://github.com/tekartik/sqflite/blob/ab9a8bb82fcf68b268e0efe8d0e5b333e59cdb19/sqflite/android/src/main/java/com/tekartik/sqflite/Database.java#L29). 
The [openDatabse android API](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase#openDatabase(java.lang.String,%20android.database.sqlite.SQLiteDatabase.CursorFactory,%20int)) allows specifying other flags such as ENABLE_WRITE_AHEAD_LOGGING. This would be very useful for applications that want to enable WAL. Currently the only way to do that is through a statement like `PRAGMA journal_mode=WAL`. 

If ENABLE_WRITE_AHEAD_LOGGING is not set, SQLite sets the default journal mode (which from what we observe is TRUNCATE for most devices). 
and then `PRAGMA journal_mode=WAL` will force SQLite to change the journal mode to WAL.

For subsequent usages of openDatabase, SQLite will again reset the journal mode back to the default one with [resolveJournalMode](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/database/sqlite/SQLiteDatabaseConfiguration.java;l=250;drc=a6af06cb700f0b2bd17ae36cbc8835aa3e2c8eac). The PRAGMA statement will then set the journal mode to WAL.

By opening up the API to specify journal mode in the dart side plugin, we could cut down on the number of operations here (i.e. we dont have to issue `PRAGMA journal_mode=WAL` which saves a lot of latency if a large number of DB is opened during app start).

A related question is: does WAL benefit sqflite plugin? IIUC this plugin executes messages in a serial manner (since it only uses one thread) and WAL is beneficial for [improving performance of parallel read/write](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase#JOURNAL_MODE_WAL).

**Comment by alextekartik** [comment]
One issue is to find the proper dart API to expose and make this working for all platforms. Most apps have one database so the latency should not be much an issue in most scenario.

Also, as you noticed, is `singleInstance` is true (which is the default), all calls happens in a single thread so I'm not sure you'll get much benefit. Using multiple instances should work better for WAL but it has tons of other issues (hotreload/restart will often fail, and you have a risk of locked database in some scenario).

The main bottleneck of performance is (I think) sending data between the plugin and the dart land. I'm curious if you make any performance measurement to see the benefit of WAL here. I know the implementation is not the most optimized one. Personally, I assume that database access can be slow at the application level. If you need the fastest access, you might try to use `sqlite3` directly.

>  we dont have to issue PRAGMA journal_mode=WAL which saves a lot of latency if a large number of DB is opened during app start

I'm assuming you call this during `onConfigure`. Do you have some numbers to see what you mean by "lot of latency".

Sorry if I sound a little bit reluctant but it is not a simple change and we have to think about mac, ios, android, linux and windows at the same time.

Looking at the SQLite wal doc: https://sqlite.org/wal.html

> Unlike the other journaling modes, [PRAGMA journal_mode=WAL](https://sqlite.org/pragma.html#pragma_journal_mode) is persistent.

So maybe you only need to call this during onCreate?

**Comment by Haozhe123** [comment]
We have about ~10 databases in our app. Removing all the `PRAGMA journal_mode=WAL` yield a 2%  (27ms) decrease in app start latency (from application creation to home page loaded) on a high end device benchmark, which is quite significant. Another possibility of this latency reduction could be attributed to not using WAL at all, which is my next question.

Does the single instance nature of the plugin mean that we wouldn't benefit from WAL mode, even if we do somehow do enable it once during the creation of the database? 

Regarding the persistent nature of  `PRAGMA journal_mode=WAL`, it is persistent but [Android SQLite will check that it is != to the default journaling mode](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/database/sqlite/SQLiteConnection.java;l=419;drc=0bde67ab00d3ab196772abed4deaefeae5e39425), so it will [revert the journal mode](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/database/sqlite/SQLiteConnection.java;l=422;drc=0bde67ab00d3ab196772abed4deaefeae5e39425) to the default again. (The setJournalMode function in SQLiteConnection is called [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/database/sqlite/SQLiteConnection.java;l=339;drc=1d08a53a6abafb77d499f5b7750221fe4fd680b3;bpv=1;bpt=1), which takes the result returned from SQLitDatabaseConfiguration.resolveJournalMode(). Inside resolveJournalMode(), it will not return WAL since WAL is not a flag being passed in).

**Comment by alextekartik** [comment]
The nature of the issue (globally a 3 ms extra time if i understand correctly) is significant for you but might not be significant for most of the users (and some might say that you could always open the databases after showing the home page or open less databases which would be far more significant)

That does not mean that I should not fix it!

> Does the single instance nature of the plugin mean that we wouldn't benefit from WAL mode

I don't know WAL benefits enough. One is better concurrency which you won't get here. If it is faster in general, il will be faster.

> Android...will revert the journal mode

Ok sorry I did not know that. I think of two solutions (1. is my preferred solution):

1. one would be to globally enable WAL on Android (i.e. all openDatabase will always open in WAL mode) using a setOptions method on the factory
2. one would be to create a `AndroidOpenDatabaseOptions` to specify the open mode for Android only (`factory.openDatabase`)

as I said, it is hard to change `openDatabase` API at this point (a lot of packages implement it) and I don't want to make a breaking change for this feature which is not compatible for all platforms.

**Comment by Haozhe123** [comment]
I'm guessing solution 1) is something like:
```
// In Database.java
public void open() {
        sqliteDatabase = SQLiteDatabase.openDatabase(path, null,
                SQLiteDatabase.CREATE_IF_NECESSARY | SQLiteDatabase.ENABLE_WRITE_AHEAD_LOGGING);
    }
```

We tried that and saw improvement as well (~1.5%), compared to our existing way of setting WAL through PRAGMA. 

The Android docs says that there's a [compatibility WAL](https://source.android.com/docs/core/perf/compatibility-wal) which is turned on by default since Android 9, but in the [code](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/database/sqlite/SQLiteDatabaseConfiguration.java;l=226-229;drc=5860970a8606bb48059aa31ee506328286b9bf92) I traced through it seems like it still depends on the flag being passed in, as `(openFlags & SQLiteDatabase.ENABLE_LEGACY_COMPATIBILITY_WAL) != 0` will evaluate to `False` (in the case of sqflite plugin, openFlags is [0x10000000](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase#CREATE_IF_NECESSARY) and ENABLE_LEGACY_COMPATIBILITY_WAL is [0x80000000](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/database/sqlite/SQLiteDatabase.java;drc=5860970a8606bb48059aa31ee506328286b9bf92;l=282)).  

If there's no harm in enabling WAL globally on Android, it seems like that's what Android would recommend doing.

**Comment by alextekartik** [comment]
I would be tempted to turn it on globally like you suggest (i.e. not compatibility WAL but full WAL support, whatever that means). I don't know how much testing should be made and whether there is any risk. I could also allow disabling WAL by using a custom meta data in manifest so that applications that don't want WAL or has any compatibility issue could turn it off. I will make a dev version first.

Thanks for pointing that out and for making some tests around that.

If someone reading this issue has some advices against that, you're welcome!

**Comment by alextekartik** [comment]
I have tried to turn it on and it causes several issue when the database does not exists just by using the example application. I have tried multiple things (using `ENABLE_WRITE_AHEAD_LOGGING` flag and calling  `enableWriteAheadLogging()`) so the change is not that safe and I'm reluctant to change this for now.

Failed test when SUPPORTS_WAL is true
![image](https://user-images.githubusercontent.com/1721046/190167355-0b631b1a-b070-4c7d-8179-a42666f6e977.png)

```java
E/SQLiteLog( 9819): (26) file is not a database in "PRAGMA journal_mode"
E/SQLiteDatabase( 9819): Database corruption detected in open()
E/SQLiteDatabase( 9819): android.database.sqlite.SQLiteDatabaseCorruptException: file is not a database (code 26 SQLITE_NOTADB): , while compiling: PRAGMA journal_mode
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1047)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:790)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:407)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:337)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:260)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
E/SQLiteDatabase( 9819): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:737)
E/SQLiteDatabase( 9819): 	at com.tekartik.sqflite.Database.open(Database.java:79)
E/SQLiteDatabase( 9819): 	at com.tekartik.sqflite.SqflitePlugin$6.run(SqflitePlugin.java:797)
```

Such test does not fail with WAL turned off.

I have published a dev version (you have to explicitely specify `>2.1.0-dev.1` in your dependency.

Since sqflite v2.0.4-dev.1 You can turn it on by declaring the 
following in you app manifest (in the application object):

```xml
<application>
  ...
  <!-- Enable WAL -->
  <meta-data
    android:name="com.tekartik.sqflite.wal_enabled"
    android:value="true" />
  ...
</application>
```

**Comment by Haozhe123** [comment]
Thanks for trying it out nevertheless! :)
