### ISSUE TITLE
Undefined variable `factory` in doc/migration_example.md

### ISSUE THREAD

**Issue by vporton** [tekartik/sqflite#863]
In `doc/migration_example.md` there is used variable `factory` that is not defined nor explained what it is.

**Comment by alextekartik** [comment]
Yes sorry. I added a note:

> In the examples below, `factory` can be replaced by `sqfliteDatabaseFactory` when using sqflite.

Basically this allows using a different implementation (such as sqflite_common_ffi) on desktop. The API for `DatabaseFactory.openDatabase` is slightly different from `openDatabase` - all options being in a single `options` parameter)
