### ISSUE TITLE
Insertion return value for a model with string primary key and without ROWID

### ISSUE THREAD

**Issue by Amir-P** [tekartik/sqflite#871]
Based on what documentation says about `insert` method and my experiments looks like the sqflite returns ROWID for models with ROWID. My question is what it returns for models with string primary key and without ROWID? Cause the return type is integer and in my experiments it returns some random numbers and sometimes 0 and indicates there's been a conflict and data is not inserted which isn't the case and I can validate that the data is inserted correctly.

**Comment by alextekartik** [comment]
Indeed the return type cannot be the primary key in this case.

I have a small example/test of table without ROWID in the example app here:
https://github.com/tekartik/sqflite/blob/master/sqflite/example/lib/raw_test_page.dart#L507-L542

As you can see, the result is different between Android and iOS. I don't think you'll get 0 for conflict as you should get an exception in this case. I just tried on Android and indeed, I did get a `(code 1555 SQLITE_CONSTRAINT_PRIMARYKEY))`

So in theory, I would say that you should ignore the result and simply try/catch any conflict in an exception. As a side note, a table can have a primary key as a string and a rowid (that is the default, you have to explicitely say that you don't want ROWID). I don't know the reason why we should not have a rowid (performance? size?), personally I never tried this option (besides in tests)

**Comment by Amir-P** [comment]
Thanks for your response.
If `insert` will always throw an exception in case of conflict, I think the method document should be updated to remove this line: "0 could be returned for some specific conflict algorithms if not inserted.". Since it can't return something and throw exception at the same time, right? @alextekartik
