### ISSUE TITLE
Gradle Tests fail for version 2.1.0

### ISSUE THREAD

**Issue by methompson** [tekartik/sqflite#876]
Gradle Tests fail for sqflite version 2.1.0, where they used to pass in earlier versions.

Steps to reproduce:

1. Create a new flutter project 
   - `flutter create my_app`
2. cd into the project
   - `cd my_app`
3. Add sqflite using the command line
   - `flutter pub add sqflite`
4. Build for Android
   - `flutter build apk`
5. cd into the android folder
   - `cd android`
6. Run gradle test
   - `./gradlew test`

This results in the sqflite unit tests throwing the following errors:
```
> Task :sqflite:compileDebugUnitTestJavaWithJavac FAILED
/Users/username/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.1.0/android/src/test/java/com/tekartik/sqflite/SqlCommandTest.java:73: error: cannot find symbol
        assertEquals(new SqlCommand("1", null), command.sanitizeForQuery());
                                                       ^
  symbol:   method sanitizeForQuery()
  location: variable command of type SqlCommand
/Users/username/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.1.0/android/src/test/java/com/tekartik/sqflite/SqlCommandTest.java:75: error: cannot find symbol
        assertEquals(command, command.sanitizeForQuery());
                                     ^
  symbol:   method sanitizeForQuery()
  location: variable command of type SqlCommand
/Users/username/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.1.0/android/src/test/java/com/tekartik/sqflite/SqlCommandTest.java:77: error: cannot find symbol
        assertEquals(command, command.sanitizeForQuery());
                                     ^
  symbol:   method sanitizeForQuery()
  location: variable command of type SqlCommand
/Users/username/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.1.0/android/src/test/java/com/tekartik/sqflite/SqlCommandTest.java:79: error: cannot find symbol
        assertEquals(command, command.sanitizeForQuery());
                                     ^
  symbol:   method sanitizeForQuery()
  location: variable command of type SqlCommand
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sqflite:compileDebugUnitTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I encountered these issues on both a MacBook Pro M1 and an Ubuntu based CI/CD pipeline.

**Comment by alextekartik** [comment]
Thanks for the report and sorry. I guess this started to happen after the following pull request: https://github.com/tekartik/sqflite/pull/868

I'll be interested in trying to run some native tests in my github CI, for now it is only dart stuff (on win/mac/linux), no integration test If you have some config file you can share I can try, I'll be happy to get them. I could simply start by running android unit test on the example as this would have shown this issue.

Fixed in 2.1.0+1 published just now.
