### ISSUE TITLE
COLLATE NOCASE

### ISSUE THREAD

**Issue by alex9153** [tekartik/sqflite#880]
```
CREATE TABLE IF NOT EXISTS users
	(
		name TEXT DEFAULT '',  
		UNIQUE (name COLLATE NOCASE)
	)
```

COLLATE NOCASE working only for english characters 
For example "эскьюлайт" and "эскьюлайТ" are equal. This is wrong

**Comment by alextekartik** [comment]
Unfortunately it does not seem consistent on the various implementation and sqflite uses whatever the platform provides. One safe solution I see is to add another column where you manually convert the string (lowercase, removing diacritics). see https://github.com/tekartik/sqflite/issues/231 for a similar bug and proposed solution
