### ISSUE TITLE
Asset Database resets to default on app restart

### ISSUE THREAD

**Issue by dev-horacebg** [tekartik/sqflite#89]
Hi,

I'm using this library to load an asset database using the instructions provided [here](https://github.com/tekartik/sqflite/blob/master/doc/opening_asset_db.md)

This works great and I'm able to add and remove data as I'd expect.

The issue is, that when the app is restarted, all of the newly saved data is completely gone and I'm left with the default database.

I've inspected the database before any new values have been added, after new values added and after restarting the app to see that the data is present during use and gone on restart.

Is there anything I'm either missing from the docs or some condition around using an asset database that I'm unaware of here or is there a genuine bug?

My code:

```
class DatabaseClient {
  static final DatabaseClient _instance =
  DatabaseClient.internal();

  static const DB_NAME = "my_database.db";

  factory DatabaseClient() => _instance;

  static DatabaseClient get() => _instance;

  DatabaseClient.internal();

  static Database _db;

  Future<Database> get db async {
    if (_db != null) return _db;
    File file = await initDeleteDb();
    _db = await openDatabase(file.path);
    return _db;
  }

  Future<File> initDeleteDb() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, DB_NAME);

    // delete existing if any
    await deleteDatabase(path);

    // Copy from asset
    ByteData data = await rootBundle.load(join("assets", DB_NAME));
    List<int> bytes =
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    return await File(path).writeAsBytes(bytes);
  }

}
``` 

Thanks

**Comment by alextekartik** [comment]
I've updated the documentation here: https://github.com/tekartik/sqflite/blob/master/doc/opening_asset_db.md

In your example indeed you are deleting the database each time so you get a fresh copy from the assets each time. You should copy it only once (the first time the user starts the app) and then directly use the the copied file.

**Comment by dev-horacebg** [comment]
Thanks for getting back to me though now I'm now even more confused!

When I follow the new instructions a copy of the database is made, but it seems I'm only able to do this successfully if I choose to make the database a read-only one. I'd like to be able to write to the database but setting `readOnly: false` when calling `openDatabase() `ensures that the database copy made includes _none_ of the tables from the source database. 
Is there any particular reason for this? 
Is there another step I need to take to be able to write values to the database once I've made the copy?

```
class SqfliteDatabaseClient implements DatabaseClient {
  static final SqfliteDatabaseClient _instance = SqfliteDatabaseClient.internal();
  static const DB_NAME = "my_database.db";

  factory SqfliteDatabaseClient() => _instance;

  static SqfliteDatabaseClient get() => _instance;

  SqfliteDatabaseClient.internal();

  Future<Database> get db async {
    var databasesPath = await getDatabasesPath();
    var path = join(databasesPath, DB_NAME);

// try opening (will work if it exists)
    Database db;
    try {
      db = await openDatabase(path, readOnly: false);
    } catch (e) {
      print("Error $e");
    }

    if (db == null) {
      // Should happen only the first time you launch your application
      print("Creating new copy from asset");

      // Copy from asset
      ByteData data = await rootBundle.load(join("assets", DB_NAME));
      List<int> bytes =
      data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      await new File(path).writeAsBytes(bytes);

      // open the database
      db = await openDatabase(path, readOnly: false);
    }
    return db;
  }
}
```
For additional context, I'm still very new to Dart and Flutter, please excuse if I've missed something really obvious here.

Thanks.

**Comment by alextekartik** [comment]
Indeed trying to open in normal (not read-only) would work even if the database does not exist. In your case, you should check whether the file exists before copying or opening it, something like that:

```dart
  var lock = Lock();
  Database _db;
  
  Future<Database> get db async {
    if (_db == null) {
      await lock.synchronized(() async {
        if (_db == null) {
          var databasesPath = await getDatabasesPath();
          var path = join(databasesPath, DB_NAME);
          var file = new File(path);

          // check if file exists
          if (!await file.exists()) {
            // Copy from asset
            ByteData data = await rootBundle.load(join("assets", DB_NAME));
            List<int> bytes =
                data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
            await new File(path).writeAsBytes(bytes);
          }
          // open the database
          _db = await openDatabase(path);
        }
      });
    }

    return _db;
  }
```
