### ISSUE TITLE
Error please use -source 8 or higher to enable lambda expressions on latest 2.2.0+1 version

### ISSUE THREAD

**Issue by ehangwork** [tekartik/sqflite#891]
version： sqflite-2.2.0+1

/Users/ehang/.pub-cache/hosted/pub.flutter-io.cn/sqflite-2.2.0+1/android/src/main/java/com/tekartik/sqflite/Database.java:232: 错误: -source 7 中不支持 方法引用
                handler.post(this::runQueuedOperations);
                                   ^
  (请使用 -source 8 或更高版本以启用 方法引用)
/Users/ehang/.pub-cache/hosted/pub.flutter-io.cn/sqflite-2.2.0+1/android/src/main/java/com/tekartik/sqflite/Database.java:243: 错误: -source 7 中不支持 lambda 表达式
        wrapSqlOperationHandler(operation, () -> doQuery(operation));
                                              ^
  (请使用 -source 8 或更高版本以启用 lambda 表达式)
/Users/ehang/.pub-cache/hosted/pub.flutter-io.cn/sqflite-2.2.0+1/android/src/main/java/com/tekartik/sqflite/SqflitePlugin.java:197: 错误: -source 7 中不支持 lambda 表达式
        handler.post(() -> {
                        ^
  (请使用 -source 8 或更高版本以启用 lambda 表达式)
3 个错误

FAILURE: Build failed with an exception.

**Comment by alextekartik** [comment]
You need to add to your `build.gradle` file:

```
android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by trygvis** [comment]
I just hit the same issue, I think this [patch](https://github.com/mogol/flutter_secure_storage/pull/331/files) is required here: [sqflite/android/build.gradle#L33](https://github.com/tekartik/sqflite/blob/master/sqflite/android/build.gradle#L33)

**Comment by ehangwork** [comment]
Yes! I already have VERSION_1_8 in my build.gradle, but I still get the same issue.

**Comment by saighost** [comment]
just update and done with sqflite 2.2.0+2

**Comment by alextekartik** [comment]
@saighost You meant that it solved your issue?

**Comment by trygvis** [comment]
Upgrading to `2.2.0+2` fixed it for me, thanks!

**Comment by alextekartik** [comment]
Thanks for the confirmation @trygvis and sorry for error in the previous published version
