### ISSUE TITLE
How to access an already made database?

### ISSUE THREAD

**Issue by TitikshaDaga** [tekartik/sqflite#9]
I have a folder named assets which contains my database. How do i copy it to the app folder? When I declare that as an asset in pubspec.yaml I get the following  exception. How do I access it?

Oops; flutter has exited unexpectedly.
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.

FAILURE: Build failed with an exception.

* Where:
Script '/home/power/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 320

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command '/home/power/flutter/bin/flutter'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Finished with error: Gradle build failed: 1

**Comment by alextekartik** [comment]
I have not played with Asset yet so cannot really help for now. I will try to make an example next week and will keep you posted

**Comment by alextekartik** [comment]
The example now includes opening an asset database (copying it to the file system first). Check documentation here:
https://github.com/tekartik/sqflite/blob/master/doc/opening_asset_db.md

**Comment by TitikshaDaga** [comment]
Hey thanks a lot. Your solution worked!!!
