### ISSUE TITLE
Flutter Sqflite "IN" operator in query is  not working 

### ISSUE THREAD

**Issue by ravipatel147** [tekartik/sqflite#90]
I have following query

`employee_id in ( ? )`   i pass in argument like `"value1,value2"`

In database same value record is present but i receive null result

I create on helper class name `sql` in app my code is as below

```
 e = await sql.sqlquery(employee_attendance,where: "employee_id in ( ? )",arg: ["5b544246476eda5dcb055044,5b545084476eda98206914f2"]);
    logger(e);
```

**Comment by Mohammed90** [comment]
Please refer to:

https://github.com/tekartik/sqflite/issues/15

**Comment by ravipatel147** [comment]
Okay but you late i done through this

```
serverEmpAtten.forEach((f) {
        id += "'" + f["employee_id"] + "',";
      });

      id = id.substring(0, id.length - 1);
```

**Comment by Mohammed90** [comment]
Totally unclean attempt and probably needs more tweaking to work, but you can try:

`IN (${ids.map((_)=> '?').join(', ')})`

And provide the array in whereArg
