### ISSUE TITLE
How to do a query to get an attribute in a TEXT object ?

### ISSUE THREAD

**Issue by kauzige** [tekartik/sqflite#906]
Is there any way to make a query in the database that obtains an attribute of a TEXT object ?

What happens is that in my DB I have an object that was converted and coded in String to save it in the DB, however inside that object there is an id that I want to select.

For example :

```json
"profile" : {
  "surname" : "kauz",
  "user" : {
     "name" : "Daniel",
     "id" : 1 // i want this
  },
  "userId" : 1
}
```

In my Profile model, to save it in the DB i use :

```dart
  Map<String, dynamic> toMap() {
    return {
      'surname': surname,
      'user': (user as UserModel).toJson(),
    };
  }

  String toJson() => json.encode(toMap()); /// With this i encode the Map
```

Now, in the query, i want to get the **Profile** by the id from the **UserModel** like this :

```sqlite
  var res = await database!.query(
    _profileTable,
    where: "user.id = ?", // or user['id'] ??
    whereArgs: [0],
  );
```

But in the Profile doesn't exist the id, its attribute "user" has the id, i want to know if there is any way to obtain the id or to be able to condition it.

Also i see here one solution and it's okey to save it in the DB, but for select i didn't find anything

https://github.com/tekartik/sqflite/blob/master/sqflite/doc/supported_types.md

**Comment by alextekartik** [comment]
Unfortunately that is not possible. You can save your user as json in a `user` field, however if you want to lookup for `user.id` you have to create a dedicated field such as `userId` at the root of your profile map

**Comment by alextekartik** [comment]
You can user whatever SQLite supports, sqflite being just a wrapper on the native implementation (which we don't control and depend on the OS and devices) ! See https://github.com/tekartik/sqflite/blob/e2eb6e2546e829f23304a1da7dc675a1e4fde0b1/sqflite/doc/sql.md#using-like
for `LIKE` examples.

Look for items with `name` starting with 'Ta':

```dart
var list = await db.query('my_table', columns: ['name'], where: 'name LIKE ?', whereArgs: ['Ta%']);
```

Look for items with `name` containing with 'free':

```dart
var list = await db.query('my_table', columns: ['name'], where: 'name LIKE ?', whereArgs: ['%free%']);
```

%idValue% should be a parameter though and I guess it will be less performant that a direct query on a userId field. I use SQLite in a very basic way so I'm not even an expert to give you the best practices.

`MATCH` might require FTS support which might not be available on all devices. The ffi version along with sqlite3_flutter_libs might give a more consistent SQLite version and features. See more information here: https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md

**Comment by kauzige** [comment]
Perfect, I have a better understanding, thank you very much ! 😁
