### ISSUE TITLE
Supported SQLite types - link in doc not working

### ISSUE THREAD

**Issue by nicolasjon** [tekartik/sqflite#92]
From the doc.

Supported SQLite types

No validity check is done on values yet so please avoid non supported types. DateTime is not a supported SQL type (https://www.sqlite.org/datatype3.html). Personally I store them as int (millisSinceEpoch) or string (iso8601)

The link has gained an extra ) so does not work.

Very useful package. Thanks

**Comment by alextekartik** [comment]
Thanks for the note. I don't get an extra ) when I click on the link. Which browser are you using?

**Comment by alextekartik** [comment]
Ah ok sorry indeed it happens on pub.dartlang.org indeed (but not on github). I'll fix that

**Comment by alextekartik** [comment]
Fixed in 0.11.2+2. Thanks again for the report
