### ISSUE TITLE
Split sqflite_common_ffi_web into runtime dependency and tooling

### ISSUE THREAD

**Issue by ruicraveiro** [tekartik/sqflite#926]
Hi,

Currently sqflite_common_ffi_web has a double life as a dependency, which I can add to a package and as a tool, which I can run. The problem with this approach is that it depends on dev_test, which has out of date dependencies, and are conflicting with all my other generation tools.

One option would be to update dev_test with more recent dependencies, namely analyzer ^5.2.0. Another, less brittle option, would be to create a new package containing:
- bin/setup.dart
- lib/src/setup/*

By doing so, you could remove dev_test as a dependency (or move it to dev_dependency if needed) from sqflite_common_ffi_web, and add it exclusively to the new package which would act as the tool.

Thank you for sqflite!

Kind Regards,

Rui

**Comment by alextekartik** [comment]
Indeed the dependency is unfortunate and that - splitting -  should be the long term solution. It means publishing/maintaining yet another package which I'm not sure I'd like to do. I think I might leave the setup manual (or using a git dependency) in the future. web support remains experimental for now.

> One option would be to update dev_test with more recent dependencies, namely analyzer ^5.2.0

I'm not sure dev_test prevent this though. I have published a new version. Do you think it is the one causing the issue as I have analyzer 5.4.0 in my project right now?

**Comment by ruicraveiro** [comment]
It still didn't work. The only way I got it to work was by adding a dependency override:
```yaml
dependency_overrides:
  analyzer: ^5.2.0
```
BTW, ^5.4.0 is premature as it depends on collection 1.17, "and every version of flutter_test from sdk depends on collection 1.16.0". I am using Flutter's latest release, but I am on the main channel.

Finally, I am aware of it being experimental, but I've doing tests and, except for this issue, it seems to be working really well. I still haven't been able to break it, and performance is truly amazing.

**Comment by ekuleshov** [comment]
Wondering if issue with `dev_test` dependency could be addressed in the released web package. 

Also, isn't having `dev_test` in the `dependencies` section is bringing all its transitive dependencies into the app code?

**Comment by alextekartik** [comment]
> Wondering if issue with dev_test dependency could be addressed in the released web package

Sorry I still have not addressed that yet.

For my information, besides relying on too many packages is there any sub dependency that is causing the issue (i.e. maybe `test` or `analyze`). As an experiment if encounter depencencies issues, can you try - if there is no issue when removing `sqflite_common_ffie_web` - adding the `test` lib as a depencency to see if it causing a similar issue ?

> Also, isn't having dev_test in the dependencies section is bringing all its transitive dependencies into the app code?

Fortunately no. When you use `path_provider` it will import `win32` even on linux. When compiled unused code is removed.

# Solutions

I might remove dependency on `dev_test` but might still want to keep some tooling to download sqlite3 wasm and build the js worker file.

## Option 1 

I guess the dependency on `test` could be problematic in flutter (although for me so far it is ok). It mights remains dependencies on [args](https://pub.dev/packages/args), [collection](https://pub.dev/packages/collection), [meta](https://pub.dev/packages/meta), [path](https://pub.dev/packages/path), [pool](https://pub.dev/packages/pool), [process_run](https://pub.dev/packages/process_run), [pub_semver](https://pub.dev/packages/pub_semver), [stack_trace](https://pub.dev/packages/stack_trace), [test](https://pub.dev/packages/test), [yaml](https://pub.dev/packages/yaml)
Removing deps [matcher](https://pub.dev/packages/matcher) and  [test](https://pub.dev/packages/test) dependency. 

## Option 2

Create and publish a seperate dart package for the tooling and keeping `sqflite_common_ffi_web` web only. I know that this is the preferred solution but what a burden having to create/publish/maintain that.

## Option 3

Create a seperate dart package on github that requires a weird installation global install.

## Option 4

Make the setup manual. Building the js worker file could be painful

## Option 5

Leave as is. As a I ask above can you help finding which sub-dependency is causing an issue when you add `sqflite_common_ffi_web` ?

**Comment by alextekartik** [comment]
And I don't use `build_runner` !

**Comment by alextekartik** [comment]
I published v0.4.1 that removes the dependency on `test` (`dev_build` replaces `dev_test` but `test` is no longer a dependency.

As of now I don't plan to publish the sqflite web tooling into a separate package unless it becomes really necessary !

**Comment by ekuleshov** [comment]
Nice reduction in dependencies. Thank you!

Though I'm curious why not to use the `build_runner`? Also if you only need these to build/package some assets when publishing plugin, perhaps the tooling doesn't need to be posted as a public packages and you could instead have a relative module dev dependency.

```
- coverage 1.7.1
- dev_test 0.16.3
- frontend_server_client 3.2.0
- http_multi_server 3.2.1
- node_preamble 2.0.2
- shelf 1.4.1
- shelf_packages_handler 3.0.2
- shelf_static 1.1.2
- shelf_web_socket 1.0.4
- source_map_stack_trace 2.1.1
- source_maps 0.10.12
- test 1.24.9
- test_core 0.5.9
- vm_service 13.0.0
- web_socket_channel 2.4.0
- webkit_inspection_protocol 1.2.1
```

**Comment by alextekartik** [comment]
> Though I'm curious why not to use the build_runner? 

In the past, I mostly had issues when including dependencies with build_runner so I guess I did not take the time to go through its complete behavior but don't take anything for granted here but I think the build step here does not really fit into build_runner (and is optional if you include the generated wasm and worker js file). Here the setup is a one time big step (unless you want to upgrade) that can take a lot of time.

> perhaps the tooling doesn't need to be posted as a public packages and you could instead have a relative module dev dependency.

I'm not sure I understand how you get your "relative module dev dependency". Another pub package? a git package (might break)? What would be the easy setup here you're thinking about?
I tried to provide a one line setup tools that I am lazy to publish as a separate package sorry since they are really dependent on each other.

Or maybe you were thinking of another solution that I might be missing. 

Do you still encounter dependencies issue?
