### ISSUE TITLE
possible error in documentation regarding pragma journal_mode = WAL

### ISSUE THREAD

**Issue by StephenWithPH** [tekartik/sqflite#929]
First, thank you for your hard work on a great product.

If indeed this happens to other users, a small documentation update could help save some bother.

https://github.com/tekartik/sqflite/blob/251c40a57b7ba1e3f987ab1c514f44b0833f5914/sqflite/doc/dev_tips.md#enable-wal-on-android states:

>Alternatively a more conservative (multiplatform) way is to call during onConfigure:
>
> ```db
>    await db.execute('PRAGMA journal_mode=WAL')
>  ```

When using that in `onConfigure`, I get the following error:

```text
error DatabaseException(unknown error (code 0 SQLITE_OK): Queries can be performed using SQLiteDatabase query or rawQuery methods only.) sql 'PRAGMA journal_mode = WAL' args [] during open, closing...
```

I changed that to:
```db
await db.rawQuery('PRAGMA journal_mode = WAL');
```

... and SQLite was happy:

```text
D/Sqflite (10406): [1,Sqflite(4648)] opened 1 /data/user/0/<redacted>/databases/demo.db
D/Sqflite (10406): [1,Sqflite(4648)] PRAGMA journal_mode = WAL
D/Sqflite (10406): [1,Sqflite(4648)] PRAGMA user_version
```

Interestingly, I could not get similar behavior with `PRAGMA pragma_list` or `PRAGMA auto_vacuum = FULL`, so this seems somewhat specific to `PRAGMA journal_mode = WAL`.

**Comment by alextekartik** [comment]
Thanks for the report. I need to add some test on this.

**Comment by alextekartik** [comment]
Indeed I reproduced the issue on Android. Not on iOS and nor using ffi, that is weird...I have update the doc here to mention your finding: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#enable-wal-on-android

Thanks!

**Comment by StephenWithPH** [comment]
Great! Hopefully that saves future developers from a bit of frustration.

Thanks again for your work on sqflite.
