### ISSUE TITLE
Expose isOpen on Database class

### ISSUE THREAD

**Issue by long1eu** [tekartik/sqflite#93]

**Comment by alextekartik** [comment]
Added in 0.11.2 (published). Let me know if that works for you

**Comment by jaydeedub** [comment]
My pubspec.yaml has sqflite: ^2.0.0+3
I have a check `if (db.isOpen)` and it returns true, BUT, if I pause program (in Android Studio Arctic Fox). and Evaluate Expression db shows a property isClosed = true.  But I can also inspect the **property** db.isClosed and it also shows true.  However, I can't access the property isClosed from code.
In my code, the isOpen property returns true, but a db.update() call gets an exception `DatabaseException(error database_closed)`
![db_object_isclosed_true](https://user-images.githubusercontent.com/65282494/133933677-22227fa8-0c97-409a-8679-a65295ca8085.png)
![db_property_isclosed_true](https://user-images.githubusercontent.com/65282494/133933679-ef6d8216-02d7-41eb-b77a-246376706616.png)
![db_propery_isopen_true](https://user-images.githubusercontent.com/65282494/133933680-76327fe9-7278-4842-b7ca-56cab1fb2b61.png)

**Comment by alextekartik** [comment]
isClosed is used internally. In general I don't recommend closing databases. There might be race conditions between when test if the db isOpen and when you actually call a db function. isOpen is set to false after the db is actually closed.

https://github.com/tekartik/sqflite/blob/768fa189576e7b00b9ea1e65be9ff32e11c65dd8/sqflite_common_test/lib/open_test.dart#L189-L198
