### ISSUE TITLE
[Question] When i should close db 

### ISSUE THREAD

**Issue by mazen930** [tekartik/sqflite#941]
If i leave the db without close it , next time when i open the app it throws error , so what are the best practices here ?

**Comment by alextekartik** [comment]
In a regular one database per app application, personally I never close the db.

>  next time when i open the app it throws error 

That is not normal, can you elaborate what is throws (which platform, some code, some logs) ?

**Comment by Shabeebcp** [comment]
Its Better Not Close The Database

**Comment by mazen930** [comment]
It was my bad, I was doing something wrong, and yes never close the db
