### ISSUE TITLE
Direct transaction access in onUpgrade

### ISSUE THREAD

**Issue by ivan-semkin-gismart** [tekartik/sqflite#944]
The issue I'm facing is that the transaction that happens in `onUpgrade` is not exposed to the callback `OnDatabaseVersionChangeFn`. I need access to the transaction to make a small query (count the amount of items in a table) to make a map of ids for migration to a new format (int ids to text uuids)

As I understood, `query` and `rawQuery` directly on the `Database` object should not be used when inside a transaction. I've tried using query inside `onUpgrade`, and while it works half of the time, the other half of the time it doesn't - probably due to a race condition (and a possible lock?).

I was wondering, maybe exposing the Transaction directly to the onUpgrade callback might solve my problem?

**Comment by alextekartik** [comment]
Indeed during onUpgrade your are already in a transaction so calling query/rawQuery on the db runs in the transaction. You could event start a transaction (db.transaction) during onUpgrade which also has a specific behavior in onUpgrade/onCreate as it will give you the transaction object you want.

**Comment by ivan-semkin-gismart** [comment]
@alextekartik is it okay to do async/await in onUpgrade? can it cause issues?

**Comment by ivan-semkin-gismart** [comment]
I currently run a `rawQuery` (count) on the database object in `onUpgrade`, but on some rare occasions users report **"table not found"** in crashalytics logs. It appears that the table was already dropped by the migration, which supposedly should only happen after `batch.commit()` and after the query was done.

**Comment by alextekartik** [comment]
> is it okay to do async/await in onUpgrade?

You HAVE to await any asynchronous operation during onUpgrade (execute, query, batch.commit). See some example here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/migration_example.md

or another direct example (where you see await is used!

```dart
_onCreate(Database db, int version) async {
  // Database is created, create the table
  await db.execute(
    "CREATE TABLE Test (id INTEGER PRIMARY KEY, value TEXT)");
}

_onUpgrade(Database db, int oldVersion, int newVersion) async {
  // Database version is updated, alter the table
  await db.execute("ALTER TABLE Test ADD name TEXT");
}

// Special callback used for onDowngrade here to recreate the database
var db = await openDatabase(path,
  version: 1,
  onCreate: _onCreate,
  onUpgrade: _onUpgrade,
  onDowngrade: onDatabaseDowngradeDelete);
```

>  It appears that the table was already dropped by the migration,

Hard to analyse much without seeing what you are doing code. Are you properly using await for all database operations?

**Comment by ivan-semkin-gismart** [comment]
here is a short snippet of what i'm trying to do. it seems that this issue only occurs on iOS judging by the logs

```
  // exampleTableName exists and filled with content prior to the migration
  // in onUpgrade:
  final String exampleTableName = 'example_table_name';
  final Batch batch = db.batch();
  final int itemsCount = await database.getCount(exampleTableName).outputOrZero; // some users report an error here: table does not exist
  batch.dropTable(exampleTableName);
  await batch.commit(noResult: true);
```

**Comment by ivan-semkin-gismart** [comment]
is it possible that `await rawQuery('SELECT COUNT(*)` could be executed after `batch.commit` in some cases? (potential race condition or something). because i'm honestly out of ideas

**Comment by ivan-semkin-gismart** [comment]
could you also please elaborate on how does this relate to our direct usage of `database` in `onUpgrade` while inside a transaction? (taken from `sqflite` docs)

![image](https://user-images.githubusercontent.com/103565136/217316347-1c9b33ad-71b3-4b7d-98c4-ccf50353c9d4.png)

**Comment by alextekartik** [comment]
In onUpgrade/onCreate/onDowngrade you should just not bother to know whether you are in a transaction, it is managed for you. just use the regular db.

> is it possible that await rawQuery('SELECT COUNT(*) could be executed after batch.commit in some cases? 

Looking at your code, no. All SQL code are serialized and the order you use is maintained. However I cannot tell whether the table exists before the call query (which would trigger the same error). You can try the new experimental logger (https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#try-the-experimental-logger) to view the SQL commands and results.
