### ISSUE TITLE
DELETE NOT IN(?) deletes all selected rows

### ISSUE THREAD

**Issue by ced1check** [tekartik/sqflite#946]
This will delete all table rows:
    where: "id not in (?)", whereArgs: [list.join(",")]

This will behave as expected, deleting only rows not in id's list:
    where: "id not in (${list.join(",")})"

Not sure if the way I setup the where in the first instance is correct though. list is a List<String> and I expected the ? to be replace by the first and only argument, being a string itself.

**Comment by alextekartik** [comment]
Unfortunately you have to specify each argument of a list, i.e. `?,?,?.....` and your list must be flatten in whereArgs so that each element is an argument not a list of element.

One solution:
```dart
extension SqlHelperExt on List {
  /// Converts [a, b, c] to '?,?,?'
  String asArgs() => map((e) => '?').join(',');
}

await db.delete(table, where: 'id NOT IN (${list.asArgs()})', whereArgs: list);
```

More information here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#parameters

**Comment by ced1check** [comment]
Thanks for your feedback. Sorry I didn't find/see the documentation before posting.

I find it much simpler to write a simple where without arguments like this:

`
where: "id not in (${list.join(",")})"
`

Is there a rationnal to not do so? Are whereArgs more secure compared to code injection?

**Comment by alextekartik** [comment]
> Is there a rationnal to not do so? Are whereArgs more secure compared to code injection?

For integer it might not change much but whereArgs are definitely needed for string. I tend to stick with args as much as possible but that's personal.
