### ISSUE TITLE
Unit testing with copied database does not work

### ISSUE THREAD

**Issue by maBarabas** [tekartik/sqflite#947]
I have set up a unit test that tries to load data from various different database files written by older versions of our app.

The files are stored in the assets folder of the flutter app, then copied to `tmp/database-name`. When trying to open this path using `openDatabase`, the following error is thrown:

``` SqfliteFfiException(sqlite_error: 14, , SqliteException(14): unable to open database file, unable to open database file (code 14)
  Causing statement: SELECT * FROM 'some_table' }) DatabaseException(SqliteException(14): unable to open database file, unable to open database file (code 14)
  Causing statement: SELECT * FROM 'some_table' ) sql 'SELECT * FROM 'some_table' ' {details: {database: {path: /tmp/database-name, id: 1, readOnly: true, singleInstance: true}}}
  ```

The same setup was working OK as an integration test on Android, but I want to convert  it to dart VM based test to speed it up.

I get a different error when `/tmp/database-name` does not exist, so it seems to be able to see that the file is there.

If I create the database using `openDatabase` at the same path, then everything works as expected, but this does not allow me to inject the old data.

I'm running on MacOS, so this could be related to entitlements. Maybe files written by the Dart VM can not be read by the sqlite library?

**Comment by alextekartik** [comment]
Sorry for the delay as I don't have much knowledge about MacOS and folder access.
Have you tried to copy it to a different folder than `tmp` such as a folder retrieved by path_provider ?
