### ISSUE TITLE
when i  run on android 8.1.0  

### ISSUE THREAD

**Issue by zhaiqc** [tekartik/sqflite#95]
DatabaseException   
![image](https://user-images.githubusercontent.com/21993390/44708201-1c0c6680-aad9-11e8-9ffe-116d441ff871.png)    why  can not open the db     ?

**Comment by alextekartik** [comment]
Not sure what happened here. the most common reason is when the directory does not exist. Can you confirm it exists (or otherwise) create it. You can check some other points here:
https://github.com/tekartik/sqflite/blob/master/doc/opening_db.md#solving-exceptions

**Comment by mohamed6996** [comment]
Did you use this code to find a location path for the database?
```
var databasesPath = await getDatabasesPath();
var path = join(databasesPath, dbName);

// Make sure the directory exists
try {
  await Directory(databasesPath).create(recursive: true);
} catch (_) {}
```

**Comment by dvdghe** [comment]
> Did you use this code to find a location path for the database?
> 
> ```
> var databasesPath = await getDatabasesPath();
> var path = join(databasesPath, dbName);
> 
> // Make sure the directory exists
> try {
>   await Directory(databasesPath).create(recursive: true);
> } catch (_) {}
> ```

how can find the directory is exist ?

**Comment by alextekartik** [comment]
To find if a directory exits is not part of sqflite, you can do this with `dart:io`
```dart
bool directoryExists = await Directory(databasesPath).exists();
```
