### ISSUE TITLE
Does it support "ALTER TABLE DROP COLUMN"?

### ISSUE THREAD

**Issue by phuocbitmark** [tekartik/sqflite#956]

**Comment by alextekartik** [comment]
I think support for `DROP COLUMN` has been added in SQLite 3.35.0 so it depends on the implementation on the platform for `sqflite` (using whatever the platform provides), which should work with `sqflite_common_ffi` (bundled with sqlite3 libs).

See https://github.com/tekartik/sqflite/blob/master/sqflite/doc/version.md to get the versions.
