### ISSUE TITLE
raw insert fails while DB helper works on tables with  boolean column

### ISSUE THREAD

**Issue by acorn371** [tekartik/sqflite#959]
Hi,
my flutter app runs on a real device with Android 9.
A raw insert `insert into users (username,password,enabled) values ('acorn371','my password',true);` having a boolean column value (true) fails in the following table while a DB Helper insert works well.

```
CREATE TABLE IF NOT EXISTS users (
	id                   integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	username             text  NOT NULL,
	password             text,
	enabled              boolean  NOT NULL
 );
```
The error is: 
`_Connection : ABORT Transaction: DatabaseException(no such column: true (code 1 SQLITE_ERROR): , while compiling: insert into users (username, password,enabled) values('acorn371','10cbd305e87caa0d6b984f6616dfcd1fa82832b38ee7525f5499d1802d5069a9',true);) sql 'insert into users (username, password,enabled) values('acorn371','10cbd305e87caa0d6b984f6616dfcd1fa82832b38ee7525f5499d1802d5069a9',true);' args []`

**Comment by alextekartik** [comment]
boolean [are not supported](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/supported_types.md#supported-sqlite-types). You should use use an INTEGER column type and 0 and 1 values. Also make sure the variables are used as [parameters](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#parameters).
