### ISSUE TITLE
Origin database opens rather than updated database

### ISSUE THREAD

**Issue by engr-zeeshan** [tekartik/sqflite#96]
i am  "always getting a fresh copy from the asset" of database NOT in readonly mode because I have to perform update query. After I update, results are reflected within the app. Opening the app again after closing, the app gets the original database rather than opening updated one.

### Database Initialization

```
Future<Database> get db async {
    if (_db != null) return _db;
    _db = await initDb();
    return _db;
  }

  //Creating a database with name test.dn in your directory
  initDb() async {
    var databasesPath = await getDatabasesPath();
    var path = join(databasesPath, "store.db");

// delete existing if any
    await deleteDatabase(path);

// Copy from asset
    ByteData data = await rootBundle.load(join("assets", "store.db"));
    List<int> bytes =
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    await new File(path).writeAsBytes(bytes);

// open the database
    var db = await openDatabase(path, version: 1);
    return db;
  }
```

### Update query
```
Future<int> makeFavorite(int id) async {
    print("$id i am From Database");
    var dbClient = await db;

    int count = await dbClient
        .rawUpdate('UPDATE quotes SET is_favourite = 1 WHERE _id = $id');

    print("count $count");
    
    return count;
  }
```

**Comment by alextekartik** [comment]
Indeed in `initDb` you are deleting the updated file and copying a new copy from the asset each time. You could for example check if the file exists before doing the copy and if the file exists open it directly

**Comment by alextekartik** [comment]
Actually the issue https://github.com/tekartik/sqflite/issues/89 expose the same pb and the solutions. Closed as duplicated
