### ISSUE TITLE
SQFLite Delete is not removing a record in the table

### ISSUE THREAD

**Issue by DktPhl2019** [tekartik/sqflite#960]
Hello

In the UI, when I do delete, the item is removed visually.
But, in the database table, the record is not removed.
Could you please take a look. Thank You

I have code example:

```
Future<int> delete(int id) async {
 final db = await instance.dataBase;
 return await db.delete(myTable,where: '${Fields.id} = ?',whereArgs: [id]);
 }
```

**Comment by alextekartik** [comment]
I'm not sure what I should take a look since that is a fairly simple scenario that has been well tested. so I might be enclined to say "are you sure ?". Hard to know what goes wrong without some logs of what you think should happen (what does delete returns) and what indeed happens. You might also ask stackoverflow.

**Comment by DktPhl2019** [comment]
Hello! I have two demo projects (these are not my projects). I tested the issue in both projects. 
I checked Stackoverflow, and what I have in these projects is correct. Could you please tell me exactly what information you need. I could provide the code. Thank You

**Comment by alextekartik** [comment]
It is hard to give personal support as I don't know how much investigation you have done and what tells you that an issue occurs, i.e. can you print the content of the table (`print(db.query('my_table');`) before and after your statement (i.e. does the id exists before the delete statement and does it still exist after the delete statement).  You can also try the [experimental logger](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/dev_tips.md#try-the-experimental-logger):
```dart
databaseFactory = databaseFactory.debugQuickLoggerWrapper();
```
to get the logs of the sql you are running.

> Could you please tell me exactly what information you need. I could provide the code. Thank You

Any information that you think maybe useful for me to investigate. This package assume a good knowledge of SQLite and flutter and I don't even know what platform (iOS, Android, others?) you are using, why you say there is an issue (i.e. how do you say the record is not removed, do you read it, do you look at the raw sqlite content...). I'm not sure what you mean 'removed in the UI' neither as I guess that it is your flutter code.

**Comment by DktPhl2019** [comment]
Hello Alex!

The url of the project(not my project): github.com/ambjn/Notely?ref=flutterawesome.com

I cannot add a screenshot here for some reason.

Please follow the steps to reproduce - hopefully, I answered all your questions:

1. On Windows 11, install: https://sqlitebrowser.org/ 
2. Run Android Studio preferably the latest version (Eel)
3. Download the app code from the above URL
4. Paste the unzipped project into the folder: C:\Users\Home\AndroidStudioProjects
5. On pubspec.yaml, run pub get or upgrade
6. Open Device Manager, under Phone tab, select Pixel XL, click Next, select Tiramisu API 33, and click Finish
7. Run the app
8. Add a new note(heading: my test and text: some Text or anything you like)
9. Close the app
10. In Android Studio, open Device File Explorer, and select folder: data/data/com.example.notely/databases
11. Using a mouse on windows pc, select the notes.db file, right click, select Save As, and click Ok
12. Open DB Browser for SQLite (from step 1 above)
13. Select File / Open Database/ and browse to a folder on pc: C:\Users\Home\AppData\Local\Google\AndroidStudio2022.1\device-explorer\Pixel_XL_API_33 [emulator-5554]\data\data\com.example.notely\databases
Note:  I am assuming you have Android Studio2022.1 version and Pixel XL API 33 installed
14. Using DB Browser for SQLite, open the file: notes.db, and select Browse Data tab
15. In the Table dropdown, select notes, and you will see the new row added.
16. Close the DB Browser for SQLite
17. Restart the app from Step 9
18. Tap the note saved in step 8.
19. Click red X to delete the note
20. Now, in the UI, there are no notes or it is empty
21. Close the app and reopen the DB Browser for SQLite
22. Select the Browse Data tab, select notes from the Table dropdown, and click refresh
23. Issue: The record is not removed. We removed the note in step 19, but the raw sql file shows the record is still there.    

Please let me know if you have questions. 

Thank You

**Comment by alextekartik** [comment]
I tried the app and the record was correctly deleted: for step 21, are you opening the same file that you copied at step 11 ? Or you performing the step 11 again to download the updated database from Android ?

**Comment by DktPhl2019** [comment]
Hello! The answer is Yes. In step 21, I am opening the same file as in step 11. In Step 21, I am not doing step 11 again.

**Comment by DktPhl2019** [comment]
This issue is now closed.
