### ISSUE TITLE
How to change the name of the database file?

### ISSUE THREAD

**Issue by Wolfaks** [tekartik/sqflite#966]
Hello.
How i can to change the name of the database file?
Thanks

**Comment by alextekartik** [comment]
Since the implementation is just a single file. The safest is to rename the file (before opening the database or after closing it). If you have a relative database file path, you can use getDatabasesPath to find the absolute path.

**Comment by Wolfaks** [comment]
Thank you. I wrote this logic:
` String dbPath = DB.connection.path;
          String newPath = ..
          await DB.connection.close();

          final fileDb = File(dbPath);
          final newFileDb = File(newPath);

          bool fileDbExists = await fileDb.exists();
          bool newFileDbExists = await newFileDb.exists();

          if(fileDbExists && !newFileDbExists) {
            await fileDb.rename(newPath);
          }
`
