### ISSUE TITLE
sqflite_common_ffi_web: warn if binaries are missing

### ISSUE THREAD

**Issue by cachapa** [tekartik/sqflite#967]
It seems that if you try to open a database without installing the binaries, the method simply blocks forever.

It would be nice if it could either fail, or at least warn the user, ideally with the instructions to run `dart run sqflite_common_ffi_web:setup`.

I just spent a couple hours wondering why the database was opening fine in one project but not the other 🤦‍♂️

**Comment by alextekartik** [comment]
Thanks for the report. Indeed error handling is very poor and I was not even sure how to capture that. worker error are now reported on the first message (i.e. opening the database) so an error message should now be displayed properly in the console. Published in v0.3.3+3

**Comment by cachapa** [comment]
Thanks for the quick turnaround. Just tested and it's working perfectly.
