### ISSUE TITLE
rawQuery hangs with no error.

### ISSUE THREAD

**Issue by hobleyd** [tekartik/sqflite#969]
Hello,

Thanks for all your work on this library, it is greatly appreciated.

I have used SQLite a lot over the years and have just discovered Flutter. I have a basic app running well and retrieving data. I have just built  a second route, using the same ChangeNotifier and I found that I am getting a weird issue with rawQuery hanging on call.

Literally, the call:

`await db.rawQuery('select * from books order by addedDate desc;');`

will hang and never return. I tried changing it to:

`db.rawQuery('select * from books order by addedDate desc;').then((map) => _processResults(map));`

which started working; but when I changed all the db.query(...) calls I am using to use the .then syntax, the rawQuery hung again.

Given there is no indication of what is going wrong, any idea where I could start looking, please?

I am running this on a Mac (M2 silicon with the latest MacOS).

Cheers,
David

**Comment by alextekartik** [comment]
It is hard for me to guess and sorry to ask how you say that it hangs (are you able to get a stack trace where it hangs?) and "are you sure it is executed?". Have a you tried a simple print before and after?:

```dart
try {
  print('Does it hang?');
  await db.rawQuery('select * from books order by addedDate desc;');
} finally {
  print('No it does not hang');
}
```

**Comment by hobleyd** [comment]
No need to apologies; I should have mentioned that initially.

I had put print statements on both sides of the rawQuery, but hadn't tried wrapping in a try/finally block. I just did that and got:

```
flutter: Does it hang?
```

So definitely something happening in the rawQuery.

**Comment by hobleyd** [comment]
Actually, your comment inspired me to look more closely, at how I have been debugging; I think the problem might be that Flutter is hanging, not that rawQuery is hanging. 

I am truly sorry to have taken up your time. I am continuing to investigate, but I am pretty sure the rawQuery hang was correlation and not causation.
