### ISSUE TITLE
[Bug] unsupported result null

### ISSUE THREAD

**Issue by CodeDoctorDE** [tekartik/sqflite#974]
After upgrading to the latest `sqflite_common_ffi_web`, I get this error while loading the web app:
```
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 567:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 640:7                                     <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1398:13                                          _rootRun
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1300:19                                          run
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1232:23                                          callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
```

**Comment by alextekartik** [comment]
Arg. Indeed sqlite3.wasm had some updates that might not compatible. You might have to re-run the setup steps (--force option):

```bash
dart run sqflite_common_ffi_web:setup --force
```

Let me know if it fixes the issue and I'll add some notes in the doc.
The sqlite3 version and the wasm version have to match and I don't know a smart way to control that (but I'm looking for a solution to handle this)

**Comment by CodeDoctorDE** [comment]
Oh yeah that worked thanks.
I didn't know you can use `--force` in this comment.

**Comment by alextekartik** [comment]
Ok good to know, lack of documentation sorry, I try to follow what sqlite3 is doing (steps are described in https://pub.dev/packages/sqlite3#wasm-web-support). The tool is in progress...

**Comment by alextekartik** [comment]
Since it depends about sqlite3 and its associated binary, it might required a manuel update until I find a better way...
Until then I have started to write some note about that here: https://github.com/tekartik/sqflite/blob/master/packages_web/sqflite_common_ffi_web/README.md#setup-binaries
