### ISSUE TITLE
Sqflite configuration issue

### ISSUE THREAD

**Issue by GamexStudio** [tekartik/sqflite#98]
Hi All,

I am integration sqflite plugin in my flutter project . But for some reasons it is not working for iOS and give sme floowing error. 
`/Users/user/Documents/DEVELOPMENT/Flutter_Dev/Flutter_project/local_db/ios/Runner/AppDelegate.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
/Users/user/Documents/DEVELOPMENT/Flutter_Dev/Flutter_project/local_db/ios/Runner/main.m:1:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
In file included from /Users/user/Documents/DEVELOPMENT/Flutter_Dev/Flutter_project/local_db/ios/Runner/GeneratedPluginRegistrant.m:5:
/Users/user/Documents/DEVELOPMENT/Flutter_Dev/Flutter_project/local_db/ios/Runner/GeneratedPluginRegistrant.h:8:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
ld: file not found: /Users/user/Library/Developer/Xcode/DerivedData/Runner-eqhuhphzvosrgvdilnpudqzvakju/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the application for the simulator.
Error launching application on iPhone 8 Plus.`

I have already tried flutter upgrade and already reinstalled the flutter but could not able to resolve it. Could you please help me with this? 
Thanks in advance

**Comment by GamexStudio** [comment]
@alextekartik , Thanks for the prompt reply. And yes, It worked fine without installing plugin. Moreover, as soon as I added this plugin and removed it, my normal projects also stops working. Here is the result of `flutter doctor` command. 
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.14 18A384a, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.27.2)
[✓] Connected devices (2 available)

! Doctor found issues in 2 categories.`
I have also tried with `pod install` command. Still receiving the same error. I am in beta version.
`Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (3 weeks ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282`

**Comment by alextekartik** [comment]
`flutter doctor` seems to show a warning on your iOS setup. Can you try to update XCode to 9.4.1 (it seems that you have only 9.3 installed)?

**Comment by GamexStudio** [comment]
@alextekartik, Yes sure. will update it and let you know the result.

**Comment by Rassell** [comment]
Having the same issue: 

`[✓] Flutter (Channel master, v0.11.13-pre.1, on Mac OS X 10.14.1 18B75, locale en-ES)
    • Flutter version 0.11.13-pre.1 at /Users/Gonzalo/Documents/flutter
    • Framework revision c80244d1ca (12 hours ago), 2018-11-28 16:19:28 -0800
    • Engine revision 72c7a75672
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/gonzalo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/gonzalo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • iPhone 8 • 7DACA6B1-EA0D-42E1-9F4C-27784E1DABE0 • ios • iOS 12.1 (simulator)

• No issues found!`

**Comment by Rassell** [comment]
I just got an strange issue:

Follow the steps, worked fine (not the build because of the signature) but yes the "run", moved to my project, run correctly, tried to build, get the same error again, also trying to run the example code after:
```

Launching lib/main.dart on iPhone 8 in debug mode...
Starting Xcode build...
Xcode build done.                                            1.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET sqflite OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/usr/Documents/invest/sqflite/ios/Classes/SqfliteOperation.m:9:
    /Users/usr/Documents/invest/sqflite/ios/Classes/SqfliteOperation.h:7:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone 8.
```

**Comment by alextekartik** [comment]
Damn it. It seems that other users have similar issues on other plugins:
- https://github.com/flutter/flutter/issues/16036
- https://github.com/spritewidget/spaceblast/pull/3
- https://github.com/luanpotter/audioplayer/issues/48
- https://github.com/flutter/flutter/issues/21592
- https://github.com/flutter/flutter/issues/17899

Some suggestion are to remove the Podfile.lock, update CocoaPods, updating the Podfile, building again...Maybe you can try the suggestions. If one of them work, let me know. Can you also confirm that if you try the example in shared_preferences (<https://github.com/flutter/plugins/tree/master/packages/shared_preferences>) it works? (i.e. to know if you have this issue with any plugin of just sqflite)

**Comment by GamexStudio** [comment]
@alextekartik , I have resolved this issue. It was my silly mistake. I have saved the flutter sdk in a folder named "DEVELOPMENT" which is in capital letters and in flutter it was searching the file in the smalll lettered "development" folder.

**Comment by Rassell** [comment]
> Damn it. It seems that other users have similar issues on other plugins:
> 
>     * [flutter/flutter#16036](https://github.com/flutter/flutter/issues/16036)
> 
>     * [spritewidget/spaceblast#3](https://github.com/spritewidget/spaceblast/pull/3)
> 
>     * [luanpotter/audioplayer#48](https://github.com/luanpotter/audioplayer/issues/48)
> 
>     * [flutter/flutter#21592](https://github.com/flutter/flutter/issues/21592)
> 
>     * [flutter/flutter#17899](https://github.com/flutter/flutter/issues/17899)
> 
> 
> Some suggestion are to remove the Podfile.lock, update CocoaPods, updating the Podfile, building again...Maybe you can try the suggestions. If one of them work, let me know. Can you also confirm that if you try the example in shared_preferences (https://github.com/flutter/plugins/tree/master/packages/shared_preferences) it works? (i.e. to know if you have this issue with any plugin of just sqflite)

Yes with 'shared_preferences' worked fine, was moving to 'shared_preferences' to sqflite when i found this issue

**Comment by Rassell** [comment]
It seems that is a issue related to flutter sdk, on another pc I have 0.11.9 instead of 0.11.13 and working like a charm...

**Comment by alextekartik** [comment]
Ok good to know. Being on the master channel has some risk. Unless you have the needs, you should be on the beta channel which is more stable.
