### ISSUE TITLE
[Web] Download sqlite3.wasm binaries manually

### ISSUE THREAD

**Issue by AliEasy** [tekartik/sqflite#999]
By executing `dart run sqflite_common_ffi_web:setup` I get `Error: Unable to find git in your PATH.`
I an not able to add git at the moment. I can find `sqlite3.wasm` in the link provided in documentation. but not `sqflite_sw.js`

**Comment by alextekartik** [comment]
Hard to know when this happen (at the initial dart pub get ?). The tools itself does not require git though. Unfortunately I don't have a built-in sqflite_sw.js available (maybe I should).
Maybe you can try using the project: https://github.com/tekartik/sqflite/tree/master/packages_web/sqflite_common_ffi_web (running any script called setup in the tool folder should work).

**Comment by AliEasy** [comment]
Is it possible for you to provide a link for easier access to both files?! like in correct version to avoid any future issues and conflicts.

**Comment by alextekartik** [comment]
Does the issue happens when using:

```dart
dart pub global activate sqflite_common_ffi_web
dart pub global run sqflite_common_ffi_web:setup
```

Starting maintaining binaries is not a task I'm willing to endorse (i.e. I will likely forget to update the binaries every time an update is made). I put the binaries generated as of today here:
https://drive.google.com/drive/u/0/folders/1eO7rO1lzbhGz0tZw3B0Z9uqAf2gj5j14

**Comment by AliEasy** [comment]
The issue even happens on `dart pub global activate sqflite_common_ffi_web`.

I agree with you. I would forget too.

**Comment by alextekartik** [comment]
> The issue even happens 

Can you elaborate on when it happens (logs), The script only runs a few executable (dart pub get and dart build). I still don't know when you get "Error: Unable to find git in your PATH."

```bash
dart pub global run sqflite_common_ffi_web:setup --force --verbose
```

**Comment by AliEasy** [comment]
![errr](https://user-images.githubusercontent.com/45623453/235641372-474321c7-559e-4a57-9db7-6bca45b26e66.png)

**Comment by alextekartik** [comment]
Thanks, ok indeed, not much info but this. I tried to remove git (not on windows though) without success. Out of curiosity, does the  following command work in your project ?
```
dart pub upgrade
```

**Comment by M97Chahboun** [comment]
@alextekartik I want ask you about sqlite on web 
Can I use ready sqlite on web (database have data just I will read it)...
Thanks

**Comment by alextekartik** [comment]
I'm not sure I can help, make sure you can indeed run `flutter pub upgrade`. Some solution here: https://stackoverflow.com/questions/51263438/how-to-solve-unable-to-find-git-in-your-path-on-flutter

**Comment by AliEasy** [comment]
Sorry for the late...
Following the link you provided solved it. No issue from sqflite
